### ISSUE TITLE
[Docs] Errant html tags in "releases" page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1019]
**Current State:**
<img width="1737" alt="Screen Shot 2020-05-18 at 8 22 10 AM" src="https://user-images.githubusercontent.com/7570704/82217967-cc8b5100-98e0-11ea-8f76-918f47d3a1ba.png">

**Desired State:**
HTML tags should not be visible.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by nitishvu** [comment]
> **Current State:**
> <img alt="Screen Shot 2020-05-18 at 8 22 10 AM" width="1737" src="https://user-images.githubusercontent.com/7570704/82217967-cc8b5100-98e0-11ea-8f76-918f47d3a1ba.png">
> 
> **Desired State:**
> HTML tags should not be visible.
> 
> **Contributor Resources**
> 
> * [Meshery documentation site](https://meshery.layer5.io/docs/)
> * [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
> * [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

Also, we can include  clickable version.
example:
`
<a href="https://github.com/layer5io/meshery/releases/tag/v0.3.14" target="_blank">0.3.14</a>`
<a href="https://github.com/layer5io/meshery/releases/tag/v0.3.14" target="_blank">0.3.14</a>

**Comment by nitishvu** [comment]
Also, we can include  clickable version.
example:
`
<a href="https://github.com/meshery/meshery/releases/tag/v0.3.14" target="_blank">0.3.14</a>`
<a href="https://github.com/meshery/meshery/releases/tag/v0.3.14" target="_blank">0.3.14</a>

**Comment by leecalcote** [comment]
@nitishvu nice, yes. Eventually, having https://meshery.io/releases will be good. @shivaylamba was working toward this, but has paused the effort currently. Could be an item of interest to you; something to discuss on today's CI working group call.

**Comment by leecalcote** [comment]
Heads-up: @kushthedude may have something in the works in terms of a new Meshery.io/releases page.

**Comment by kushthedude** [comment]
Fixed with new release page.
