### ISSUE TITLE
Unable to connect to GKE

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#102]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by girishranganathan** [comment]
@sakomws I thought you were planning on filling the description of the bug here. Can you please add the info you have?

**Comment by sakomws** [comment]
Hey @girishranganathan, here is fix how we discussed using ServiceAccount:

1. Create cluster-admin role service account
2. Get secret name from  service account
3. Extract CA Certificate and User token from secret
4. Generate new kubeconfig yaml file to input to Meshery

Steps:
1. Run shell script with service account name and namespace arguments:
```
./generate_kubeconfig_gke.sh cluster-admin-sa-gke default
```
2. Input generated file `config-cluster-admin-sa-gke-default.yaml` to meshery.

**Comment by sakomws** [comment]
![Uploading Screen Shot 2019-05-10 at 4.54.44 AM.png…]()

**Comment by leecalcote** [comment]
@sakomws do we have a fix and set of instructions for this now?
