### ISSUE TITLE
Change the indent & spacing of UI files to match golang files

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1029]
**Current Behavior**

We have a different set of indents and spaces for our server code & UI code which we need to eliminate.

**Desired Behavior**

Change the indent & spacing of UI files to match golang files, more context here https://github.com/layer5io/meshery/pull/1020#discussion_r427122097

---
**Resources**

- Change the rule here https://github.com/layer5io/meshery/blob/1a2bba9232f5ef92f530a4905fac23fa6efcfe9b/ui/.eslintrc.js#L42
- See rule details https://eslint.org/docs/rules/indent
- Once you have changed the rule, run `make run-ui-lint` from root of the repository

**Comment by kushthedude** [comment]
Hi @tsingh2k15, This issue may be of interest to you.

**Comment by tsingh2k15** [comment]
thanks @kushthedude , I will take this up.

**Comment by kushthedude** [comment]
Not required now!
