### ISSUE TITLE
[Install] Need windows friendly docker-compose.yml and mesheryctl function

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#1034]
**Description**
Mesheryctl currently use a common docker-compose file for unix/linux , windows machine. 

**Expected Behavior**
Need windows specific docker-compose.yaml 
Use mehseryctl to detect windows and download  windows specific docker-compose to deploy on docker.

**Comment by leecalcote** [comment]
@sixeyed pointed out that he uses overrides - one for Linux and one for Windows as seen for the volume here - https://github.com/sixeyed/diamol/tree/master/ch11/exercises/infrastructure

**Comment by leecalcote** [comment]
@nunix if you free up, this might be one you want to wrangle.

**Comment by nunix** [comment]
@leecalcote yes I will tackle this one, the issue will be the Watchtower and also, with Mesheryctl it should be "context aware", because on Windows, if the backend is WSL2 or Windows, the compose file will also be different (cool right 😅 )
