### ISSUE TITLE
[CI] Introduce golang-ci-lint for our CI Testing.

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1050]
**Current Behavior**

Right now, we are using 4 different actions for similar sort of golang actions. Moreover, adding to it we have 4 different cache jobs for each action which totals to 8 GitHub Actions which not only increases the CI time but also is a waste of resources.

**Desired Behavior**

Replace the current linter & error checker with golang-ci-lint.

---
**Resources**

https://github.com/golangci/golangci-lint

**Alternatives / Additional Context**

Let me know if anyone is interested in implementing it or else I will go forward with this.

**Comment by tharun208** [comment]
Also, better suggestion is to also add a make command to run `golangci-lint` as a developer practice. Before, pushing the changes.

**Comment by leecalcote** [comment]
Great suggestion, @tharun208. 👍

**Comment by tharun208** [comment]
I like to work on this
