### ISSUE TITLE
UI: Clean up provider ui dependencies

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1074]
**Description**

There are a lot of dependencies which have been specified in provider-ui but are useless. Perhaps, while writing the provider-ui the contributor would have copied the package.json of meshery-ui to provider-UI.

**Expected Behavior**

Clean up the package.json & reduce bundle size.

**Comment by tsingh2k15** [comment]
@kushthedude I can take this up

**Comment by kushthedude** [comment]
> @kushthedude I can take this up

Sure, Please go ahead. Let me know if you need any help with this.

**Comment by tsingh2k15** [comment]
> > @kushthedude I can take this up
> 
> Sure, Please go ahead. Let me know if you need any help with this.

Thanks, I have assigned this to myself. Will start working on it actively.

**Comment by kushthedude** [comment]
> > > @kushthedude I can take this up
> > 
> > 
> > Sure, Please go ahead. Let me know if you need any help with this.
> 
> Thanks, I have assigned this to myself. Will start working on it actively.

Hey @tsingh2k15 , meanwhile you were busy with some other stuff. I got my hands dirty and cleaned some of the stuff but still, there are more unused deps in provider-UI.
