### ISSUE TITLE
[Docs] Update Meshery Build & Release Strategy document with ReleaseDrafter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1075]
**Current State:**
ReleaseDrafter has been incorporated into Meshery builds.

**Desired State:**
The [Meshery Build & Release Strategy document](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit) should be updated to reflect this.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by clementkng** [comment]
Hi @kushthedude would this simply be adding details about ReleaseDrafter to the linked google doc?

**Comment by leecalcote** [comment]
@kushthedude given the current set of changes going through. You might tie-off this item at the same time...

**Comment by kushthedude** [comment]
> @kushthedude given the current set of changes going through. You might tie-off this item at the same time...

Done 😄

**Comment by leecalcote** [comment]
🙏
