### ISSUE TITLE
[mesheryctl]: Move hardcoded mesheryctl config defaults to a generated default mesheryctl.yaml file

### ISSUE THREAD

**Issue by nitishm** [layer5io/meshery#1083]
**Current Behavior**
`mesheryctl` uses hardcoded defaults if the user does not specify a `--mesheryctl-config` file location.

**Desired Behavior**
It will be a better UX and more intuitive (in terms of config file syntax) if a default `mesheryctl.yaml` file is generated when meshery is initialized (similar to `meshery.yaml`) with the default values, while getting rid of the hardcoded defaults

---
**Resources**
N/A

**Alternatives / Additional Context**
N/A

**Comment by harsh-not-haarsh** [comment]
@kushthedude can you assign this to me?

**Comment by leecalcote** [comment]
@harsh-not-haarsh fyi - here is the PR that recently brought in this functionality - https://github.com/meshery/meshery/pull/1047

**Comment by leecalcote** [comment]
@nitishm will you double-check that a `mesheryctl.yaml` is autogenerated? I'm missing one in my setup.

**Comment by nitishm** [comment]
> @nitishm will you double-check that a `mesheryctl.yaml` is autogenerated? I'm missing one in my setup.

@leecalcote this hasn't been done yet. Currently it requires a manual creation of the file ifthe user wises to override hardcoded defaults

**Comment by sladyn98** [comment]
This could be a good step just when it is initialized. Should the YAML be populated with default values ? Also it would be nice to let the user know that we are generating such a file and you can edit it before you start. Or you can reload the yaml

**Comment by anirudhjain75** [comment]
Should I pick this one up @sladyn98, @nitishm and @leecalcote  ??

**Comment by anirudhjain75** [comment]
This currently blocks one of my PR which Lee referenced, I need this done to have 2 PRs counted for you who what

**Comment by anirudhjain75** [comment]
This PR creates a new config file (mesheryctlConfig.yaml) based on default values and put's it into .meshery folder

**Comment by leecalcote** [comment]
Way to knock this out, @anirudhjain75! 💪
