### ISSUE TITLE
[UI] Implement toggle to show/hide header fields

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1099]
**Current Behavior**

Right now, all the header fields are visible on the performance page which is not looking good on UI.

**Desired Behavior**

Implement a toggle to show/hide the header fields.

**Screenshot**
<img width="881" alt="Screenshot 2020-06-03 at 4 56 56 AM" src="https://user-images.githubusercontent.com/44091822/83579419-d8207e00-a556-11ea-9a3e-e78695cbbd03.png">

---

**Comment by kushthedude** [comment]
@raghavaggarwal99 Is this issue of any interest to you?

**Comment by dhruv0000** [comment]
I would like to work on this.
