### ISSUE TITLE
[CI] Cache actions are not working for GoLang Jobs

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1101]
**Description**

We have introduced cache actions but none of the cache action is working for golang jobs, & ultimately all dependencies are fetched again.

**Expected Behavior**

Correct the cache actions.

**Screenshots**

<img width="981" alt="Screenshot 2020-06-03 at 6 01 02 AM" src="https://user-images.githubusercontent.com/44091822/83582620-a2cc5e00-a55f-11ea-957b-a96cd0866466.png">

**Comment by Aisuko** [comment]
I will take a look.

**Comment by leecalcote** [comment]
Related to #981

**Comment by leecalcote** [comment]
Is this still an issue?

**Comment by Aisuko** [comment]
We can close this, the script under `.github/workflows/CI.yml` all can work well.
