### ISSUE TITLE
Verify Meshery compatibility with GKE

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#112]
Install Meshery locally. Point to GKE cluster. Update documentation based on experience.

Tasks:

1. Install Meshery locally. (using Meshery cli which runs all the services on `Docker` using `docker-compose`)
2. Open Meshery UI.
3. Configure Meshery to use kubeconfig for GKE deployment. [using the kubeconfig file mostly found in your $HOME/.kube/config (OR) by getting the config from `kubectl config view --raw > config` command]
3. Deploy each supported service mesh & a sample app in that environment using Meshery.
4. Performance test each supported service mesh in the environment using Meshery.
5. Update documentation with changes needed.

**Comment by girishranganathan** [comment]
@sakomws I know we tried this, can you please add our attempts to the docs? Also, did you get a chance to try with a service account?

**Comment by leecalcote** [comment]
#102

**Comment by leecalcote** [comment]
@sakomws any update here?

> @sakomws I know we tried this, can you please add our attempts to the docs? Also, did you get a chance to try with a service account?

**Comment by kdelee** [comment]
@leecalcote FWIW I set up a cluster in GKE and got kubectl configured to talk to it. Many things seemed to work but whenI clicked button on main meshery console page to test connnection with the cluster, I get a red pop up error and this in the logs of the meshery container:

![Screenshot from 2019-10-15 12-35-14](https://user-images.githubusercontent.com/29239279/66851269-6ef8e580-ef48-11e9-8c1f-e5397840ce15.png)


```
time="2019-10-15T16:13:59Z" level=error msg="unable to create client set: No Auth Provider found for name \"gcp\""
```

seems to be related to https://github.com/kubernetes/client-go/issues/242#issuecomment-314642965

**Comment by leecalcote** [comment]
@kdelee thank you! This is very helpful. 😊

@sakomws do you have any time to be able to dig in here? Or @kdelee if you're inclined, we'd love for you to take a further crack at this as well.

**Comment by leecalcote** [comment]
@kdelee do you mind testing the script on this page to generate a GCP-compatible kubeconfig for Meshery? https://meshery.meshery.io/docs/installation/gke 

Your help here would be is appreciated!

**Comment by Ozrlz** [comment]
Hi all.

I just tried that script on my linux desktop and after some modification I was able to succesfully setup the kubeconfig.

According to base64 manpage [1] the -D arg must be changed to -d, which is something I was able to to using the following:

curl -sL https://meshery.meshery.io/docs/pages/installation/generate_kubeconfig_gke.sh | sed -e 's/-D/-d/g' | bash -s -- ${SA} ${NS}

I'm new to meshery, but I've been using GKE for a while. If there's anything I can help with please just let me know.

[1] - https://linux.die.net/man/1/base64

**Comment by leecalcote** [comment]
@Ozrlz thank you for jumping in here! Your help is most welcome. 👍 Your investigation here is very timely as we're updating Meshery's support of EKS, which leverages this same script as well. https://github.com/meshery/meshery/pull/458 and https://github.com/meshery/meshery/pull/459 are updates to the docs for EKS support, but we're still in need of an update to this `generate_kubeconfig_gke.sh` script:

- [ ] rename to `generate_kubeconfig.sh`
- [ ] Provide `sed` or similar solution for lowercasing `-D` for Linux support (as a work-around until the generate_kubeconfig functionality is built into `mesheryctl` here https://github.com/meshery/meshery/issues/146).

**Comment by leecalcote** [comment]
@Ozrlz we'd love to have you join in the community and engage in the project at your leisure. Please join - http://slack.meshery.io.

**Comment by leecalcote** [comment]
Completed. Thank you, @Ozrlz!
