### ISSUE TITLE
Use apps/v1 instead of extensions/v1beta1 for deployments

### ISSUE THREAD

**Issue by AdheipSingh** [layer5io/meshery#1125]
**Description**

**Expected Behavior**

 - In the install folder, deployment yaml i see most of the deployments set to ```extensions/v1beta1```. 
- As per 1.16 k8s extensions is not present. Plus the helm charts are using ```apps/v1```.

**Comment by leecalcote** [comment]
Thank you, @AdheipSingh! Is this item an item that you might consider tackling?

**Comment by AdheipSingh** [comment]
@leecalcote sure, ill raise a PR
