### ISSUE TITLE
[Helm Chart]: Gateway yaml selector should be configurable by user

### ISSUE THREAD

**Issue by AdheipSingh** [layer5io/meshery#1129]
**Description**

- https://github.com/layer5io/meshery/blob/master/install/kubernetes/helm/meshery/templates/gateway.yaml#L8
- Selector is hard coded to default labels.

**Expected Behavior**

- A user can have multiple ingress gateways each having different labels. 
- As a user i should be able to specify which selector to use to point to the gateway of my choice. 
- Values.yaml should support this.

**Comment by Aisuko** [comment]
@AdheipSingh Thanks for mention this issue.  And we may need to confirm the API version of the `apiVersion ` is useful

https://github.com/meshery/meshery/blob/fddf806170a431dc9d182489f0b56d59663d952a/install/kubernetes/helm/meshery/templates/gateway.yaml#L2

**Comment by AdheipSingh** [comment]
@Aisuko i think this is the latest supported ```apiVersion``` though will take a look into it,
