### ISSUE TITLE
Verify Meshery compatibility with EKS

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#113]
Install Meshery locally. Point to EKS cluster. Update documentation based on experience.

Tasks:

1. Install Meshery locally. (using Meshery cli which runs all the services on `Docker` using `docker-compose`)
2. Open Meshery UI.
3. Configure Meshery to use kubeconfig for EKS deployment. [using the kubeconfig file mostly found in your $HOME/.kube/config (OR) by getting the config from `kubectl config view --raw > config` command]
3. Deploy each supported service mesh & a sample app in that environment using Meshery.
4. Performance test each supported service mesh in the environment using Meshery.
5. Update documentation with changes needed.

**Comment by girishranganathan** [comment]
@sakomws any progress here?

**Comment by leecalcote** [comment]
@sakomws do we have anything left to document or improve upon?

**Comment by leecalcote** [comment]
@venkatasankarapu Here's a start - https://github.com/meshery/meshery/tree/feature/leecalcote/eks

Nice work! ;)

**Comment by leecalcote** [comment]
Completed.
