### ISSUE TITLE
Denial of Service vulnerability  in "ui" module

### ISSUE THREAD

**Issue by tsingh2k15** [layer5io/meshery#1130]
**Description**
   
Versions of http-proxy prior to 1.18.1 are vulnerable to Denial of Service.                                                                                                                                         

-   High            Denial of Service                                                                                                                           
-   Package         http-proxy                                                                                                                             
-   Dependency of   http-proxy [dev]                                                                                                                      
-   Path            http-proxy                                                                                                                      
-   More info       https://npmjs.com/advisories/1486   

                      
             
                                                                   
**Expected Behavior**

Upgrade to version 1.18.1 or later for remediation

**Comment by leecalcote** [comment]
Thank you, @tsingh2k15

**Comment by kushthedude** [comment]
I guess why dependabot didn't catch this 😓
