### ISSUE TITLE
[UI] New performance request headers are taking mouse focus

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1145]
**Description**
When the Meshery UI `/performance` page loads, the "Request Body" field automatically receives the mouse's focus.

**Expected Behavior**
No field should receive focus.

**Screenshots**
<img width="782" alt="Screen Shot 2020-06-17 at 3 19 03 PM" src="https://user-images.githubusercontent.com/7570704/84946280-0dc47b80-b0ae-11ea-8c3a-2fcb48f383ce.png">

**Comment by kushthedude** [comment]
#1151 will fix this, right @dhruv0000 ?

**Comment by dhruv0000** [comment]
No. Its a quick fix. Let me include it in #1151.

**Comment by kushthedude** [comment]
Fixed in #1151
