### ISSUE TITLE
[UI] Performance Tests: A drop-down list for the `Duration` field

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1149]
**Current Behavior**
The Duration field is current a text field. While the tooltip provides some reference, it has been noted that users may not be readily aware of the full set of acceptable values for the Duration field are.

See this discussion of the issue: https://www.youtube.com/watch?v=G6wDVdTXwcY&feature=youtu.be&t=2013

**Desired Behavior**
Use of an autocomplete field in combination with the reference information in the tooltip will help guide users to both successfully filling in the field and to understanding the full set of possible acceptable values.

---
**Resources**
Thanks to @MikeBorovik:

- https://material-ui.com/components/autocomplete/ - an autocomplete reference
- https://www.npmjs.com/package/react-autocomplete - a ready-to-use package for react

**Comment by Aisuko** [comment]
@PmcFizz Would you like to look at this?

**Comment by PmcFizz** [comment]
ok I will fix it @Aisuko

**Comment by PmcFizz** [comment]
> @PmcFizz Would you like to look at this?

ok I will fix it

**Comment by PmcFizz** [comment]
@leecalcote  I am use  material-ui's  autocomplete  component to replace text field on  `Duration` field ,  can  you tell me the drop-dwon options  what user can selected ?

**Comment by leecalcote** [comment]
@PmcFizz thank you for picking up this issue! 👍 

Great question. While technically, this field a  is capable of accepting a broad array of values (see definition for [ParseDuration](https://golang.org/pkg/time/#ParseDuration)), we'll want to provide users with a pre-populated list of commonly used selections. Here's what I suggest that we include for the pre-populated list: `15s`, `30s`, `1m`, `3m`, `5m`, `10m`, `30m`, `1h`, `2.5h`, `5h`, `10h`, `1d`.

We will also want for the user to be able to type in a custom value for duration that doesn't exactly match our pre-defined list of selections. In this way, they can enter a value like `20s` and have it accepted. Currently, Meshery only supports whole numbers, so for example, it would not support `20.5s`.

Here is an example of a similar field providing a pre-populated list and allowing a custom entry - 
![Untitled](https://user-images.githubusercontent.com/7570704/86785900-e9165080-c028-11ea-97d7-585e58f70496.gif)

**Comment by PmcFizz** [comment]
OK I get it
