### ISSUE TITLE
Create an Octarine adapter for Meshery

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#115]
- need to create an Octarine adapter for Meshery
- a repo has been created for the Octarine adapter [here](https://github.com/layer5io/meshery-octarine)

**Comment by girishranganathan** [comment]
@thehh1974, this is an issue to track your effort for creating an adapter.
Can you please tell us if the adapter will be ready to demo at kubecon eu in less than 2 weeks from now?

**Comment by thehh1974** [comment]
@girishranganathan, unfortunately it won't by ready. I hope to finish coding by the end of next week, but there won't be time to test it.

**Comment by leecalcote** [comment]
@thehh1974 has delivered a functional adapter for Octarine.
