### ISSUE TITLE
[Docs] Propagate description of MeshMates program.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1154]
**Current State:**
MeshMates is our newcomer onboarding program. It is described in brief here - https://layer5.io/community and in full here - https://docs.google.com/document/d/1vquQMD0TTWREahpx_JXuvIbQ4hM2_4jrVFk8xqZ72ok/edit

**Desired State:**
This program should be included in:

- [x]  the Meshery repo README and in 
- [x] the Newcomer's Welcome Guide.
- [x] Meshery Docs here - https://meshery.layer5.io/docs/project/contributing

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by chandrashritii** [comment]
@leecalcote Can I work on this?

**Comment by leecalcote** [comment]
thank you, @chandrashritii.That would be great.

**Comment by leecalcote** [comment]
@chandrashritii fyi - https://layer5.io/community#meshmates

**Comment by chandrashritii** [comment]
@leecalcote Thanks for the link!
Also, the `balloon` emoji in the [project/contributing](https://meshery.layer5.io/docs/project/contributing) page isn't visible when built with jekyll. 
It can be corrected simply by adding a [jemoji plugin](https://github.com/jekyll/jemoji) in the Gemfile and updating the _config.yml file. Should I add that?

![Screenshot_2020-06-26 Contributing](https://user-images.githubusercontent.com/34476976/85804920-85f30700-b768-11ea-9a04-3b1dd9616f8d.png)

**Comment by leecalcote** [comment]
Good catch. Yes, adding this plugin sounds great.

**Comment by chandrashritii** [comment]
@leecalcote Updated the Newcomer's Welcome Guide with a description of [MeshMates](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit#bookmark=id.b4o1pib29db0).

**Comment by leecalcote** [comment]
@chandrashritii Nice. I toss in a couple minor updates in other areas of the Newcomer's Welcome Guide. We're good to go here. ✔️
