### ISSUE TITLE
Create a consul adapter for Meshery

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#116]

**Comment by girishranganathan** [comment]
An initial bare bones version can be found [here](https://github.com/layer5io/meshery-consul)

**Comment by girishranganathan** [comment]
Hello @venilnoronha, it has been a while we heard from you. Hope you are doing well.
One qq to you: would you be interested to take a stab at this adapter?

**Comment by venilnoronha** [comment]
Hi @girishranganathan! What needs to be changed in the existing one?

**Comment by girishranganathan** [comment]
hey @venilnoronha what exists is just a bare bones one. Doesn't have much functionality.

**Comment by leecalcote** [comment]
@venilnoronha @girishranganathan which is to say that it needs the provisioning flow initially addressed.

**Comment by leecalcote** [comment]
@nicholasjackson and @eveld, it'd be good to get your eyes on this adapter as we go to release a v0.1.

**Comment by leecalcote** [comment]
Consul adapter released.
