### ISSUE TITLE
[Docs] Add `system config` as new `mesheryctl` command

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1168]
**Current State:**
The https://meshery.layer5.io/docs/guides/mesheryctl doc does not include the new `mesheryctl system config` command created in PR https://github.com/layer5io/meshery/pull/1084

**Desired State:**
The docs should include this new command along with example usage.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
cc @chandrashritii

**Comment by chandrashritii** [comment]
@leecalcote I'm working on it

**Comment by chandrashritii** [comment]
@leecalcote Please review #1170
