### ISSUE TITLE
[Docs] Update GKE and EKS Quick Start Instructions with `mesheryctl system config`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1172]
**Current State:**
`mesheryctl system config` is a new feature to assist in the configuration of the kubeconfig file used by Meshery for interacting with remote, managed Kubernetes clusters operated by Cloud providers.

**Desired State:**
Given this new feature, let's:

1. Take much of what is on the [GKE](https://meshery.layer5.io/docs/installation/gke#quick-start-with-google-kubernetes-engine-gke) and [EKS](https://meshery.layer5.io/docs/installation/eks#quick-start-with-google-kubernetes-engine-eks) pages and move these instructions into a "Manual Configuration" section. 
1. Above the "Manual Configuration" section, regurgitate the description of the `mesheryctl system config` function and its use.
1. Do this on both the GKE and EKS pages.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1170#issuecomment-648472944_

**Comment by leecalcote** [comment]
@chandrashritii feel free to grab this one, if you like. 👍

**Comment by chandrashritii** [comment]
@leecalcote I'll start working on it asap. Thanks for asking me :)
