### ISSUE TITLE
[mesheryctl] add `system reset` function to `system update`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1190]
**Current Behavior**
As the "stable" release channel is created, users will not naturally upgrade to this channel. Their ~./meshery/meshery.yaml file will need to be updated. This update is only made when performing a `system reset`. 

**Desired Behavior**
Users upgrading to newer versions of Meshery should be updated to the stable release channel, unless they have otherwise specified the "edge" channel, which we don't have yet. Essentially, all new and existing users should be migrated to the "stable" channel. Adding a call to the `reset` function inside of the `update` command will cause users to upgrade to the stable channel the next time they start Meshery (the `start` command implicitly calls `update`) unless the `--skip-update` flag is present.

**Implementation**
- add a call to the `reset` function from within the `update` command.

**Roadmap**
In the future, additional controls will be provided to allow users to control which version of Meshery they want to run.

**Comment by chetanku** [comment]
@leecalcote I would like to help, where can I find the documentation for initial setup?

**Comment by leecalcote** [comment]
@chetanku, that would be great. Thank you. Yes, there are a number of resources to get into your hands here. If you will jump into http://slack.meshery.io, we'll get you all that you need.

**Comment by crustyy** [comment]
@chetanku are u still working on this?? Or if you want we can work together in this:)

**Comment by PluckyPrecious** [comment]
> @chetanku are u still working on this?? Or if you want we can work together in this:)

Hi @crustyy looks like @chetanku May be hooked with other things. I will be great if you take it up.😊

**Comment by chetanku** [comment]
@crustyy apologize for the delay, please go ahead, I am just wrapped up in a few things, hope to find some time to contribute soon.

**Comment by subhamkrai** [comment]
@leecalcote I can take this if available.
