### ISSUE TITLE
[Docs] Mention about `make run-tests` in contributing.md

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1193]
**Current State:**

We now have ability to test some of the CI checks on local machine using `make run-tests`, there is no mention of this command in our contributing file & respective docs.

**Desired State:**
Mention about `make run-tests` in contributing.md

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Adeola-Adesoba** [comment]
Hi, I will like to work on this. I am just wondering about which sub section will this fall under? Can it go under the **Build and run Meshery Server?**

![image](https://user-images.githubusercontent.com/46505882/87218766-596bed00-c31b-11ea-9ba0-70dfff477215.png)

**Comment by kushthedude** [comment]
Hi @Adeola-Adesoba , Thanks for jumping in! IMO we would want to have another subsection `Tests` under build & run in contributing.md file.

**Comment by Adeola-Adesoba** [comment]
> Hi @Adeola-Adesoba , Thanks for jumping in! IMO we would want to have another subsection `Tests` under build & run in contributing.md file.

Alright, got it!
