### ISSUE TITLE
[Docs] Update Release docs with v0.3.16 and v0.3.17

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1194]
**Current State:**
https://meshery.layer5.io/docs/project/releases is missing these last two releases.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by morrme** [comment]
Not sure if these should be left to other new comers to the project, but either way, I did some digging and here is what is needed to complete this task:

[0.3.16 Release Info](https://github.com/meshery/meshery/releases/tag/v0.3.16)  Released on June 22, 2020
[0.3.17 Release Info](https://github.com/meshery/meshery/releases/tag/v0.3.17) Released on July 1, 2020 (seems like only the most recent release date is included on the releases page?

**Comment by shwegyi198361** [comment]
> Not sure if these should be left to other new comers to the project, but either way, I did some digging and here is what is needed to complete this task:
> 
> [0.3.16 Release Info](https://github.com/meshery/meshery/releases/tag/v0.3.16) Released on June 22, 2020
> [0.3.17 Release Info](https://github.com/meshery/meshery/releases/tag/v0.3.17) Released on July 1, 2020 (seems like only the most recent release date is included on the releases page?

**Comment by morrme** [comment]
@leecalcote in general, what is your project's policy on this? Are those who have previously contributed to "good first issues" eligible to take on others, or are they reserved for newcomers?
Hope the info provided above at least helped  get it done faster :) 

m

**Comment by leecalcote** [comment]
@morrme, I missed your comment above (regarding the research that you did). 

Great question. Simple answer: tear through as many issues as your heart desires irrespective of labels. 😄 More than this, if you see an issue of interest, but notice that it's already assigned to someone, please don't let that stop you from asking if you can collaborate or take over the issue entirely. Often contributors have the best of intentions to take and complete an issue, but either stumble along the way and don't finish or get distracted elsewhere and don't finish. Many issue assignments are stale.

**Comment by leecalcote** [comment]
@morrme and @shwegyi198361, also note that there are open issues and help wanted across many different repos in the community. You're welcomed and encouraged to try your hand at any of them - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+label%3A%22help+wanted%22+.

Slack isn't for everyone, but know that there's much that transpires in the community in the Meshery Slack (http://slack.meshery.io). Jump in at your leisure. I'd love to see you in there, if you aren't already. 👍
