### ISSUE TITLE
[Docs] Upgrade to Jekyll 4.0.1

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1197]
**Current State:**
The docs site is running Jekyll 4.0.0.

**Desired State:**
The docs site needs to be updated to Jekyll 4.0.1.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by chandrashritii** [comment]
@leecalcote Meshery Docs use github pages. The github pages gem doesn't support Jekyll v4 yet. Reference ~ https://github.com/github/pages-gem/issues/651

**Solution:**

If we really want to upgrade to Jekyll v4.0.1, we could opt to use Github Actions. Reference ~ https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by leecalcote** [comment]
@chandrashritii we're already running Jekyll v4.0 in our gem today.
