### ISSUE TITLE
[mesheryctl] Create global constant to reference Meshery docs site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1200]
**Current Behavior**
`mesheryctl` has the URL to the Meshery documentation site hard-coded in some areas. Example:

```
$ mesheryctl perf
Error: please enter a test URL
See https://meshery.layer5.io/docs/guides/mesheryctl#performance-management for usage details
```

**Desired Behavior**
- [ ] A `DOCS_BASEURL` should be created as a global reference in `mesheryctl`.
- [ ] Each of the hard-coded references to Meshery documentation should be updated with this global constant.

**Comment by morrme** [comment]
So maybe around here: 
https://github.com/layer5io/meshery/blob/6b573d4c8cb1c55e3538601eb5c112cda3bf5cc3/mesheryctl/pkg/utils/helpers.go#L31

Then update the lines there with just their relative tags (along with [this line?])(https://github.com/layer5io/meshery/blob/6b573d4c8cb1c55e3538601eb5c112cda3bf5cc3/handlers/load_test_handler.go#L75) 
then leave [the link at the bottom here](https://github.com/layer5io/meshery/blob/master/docs/pages/service-meshes/adapters.md) hardcoded (once it is fixed--seems to be 404 right now 😬  )

**Comment by Sylfrena** [comment]
Hi @leecalcote ,

Can I try to solve this issue?

**Comment by leecalcote** [comment]
Hi @Sylfrena, that would be wonderful, yes.

**Comment by Sylfrena** [comment]
Hi,

My [PR](https://github.com/layer5io/meshery/pull/1496) seems to be failing due to a linting error. I think it has something to do with my local setup but I can't be sure. :(

Is it okay if I get back to this in a few days after resetting my entire system? If not, then I am okay with giving up my claim on the issue.
