### ISSUE TITLE
[Docs] List network ports in Adapters table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1204]
**Current State:**
The adapters table (https://meshery.layer5.io/docs/service-meshes/adapters) should have a third column for network port.

**Desired State:**
Should include the port number for each adapter just like this table - https://meshery.layer5.io/docs/architecture#network-ports. The same logic can be used.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@morrme feeling up to this task?

**Comment by chandrashritii** [comment]
@leecalcote can I work on this?

**Comment by morrme** [comment]
@leecalcote I was still testing my solution, and I guess someone beat me to it! Thanks for thinking of me anyway!

**Comment by leecalcote** [comment]
Thank you, @chandrashritii. ✔️ 

@morrme, no sweat. There's more where this came from. 😉
