### ISSUE TITLE
[mesheryctl] Improve `version` error message when server is unreachable

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1206]
**Description**
When the Meshery server API is unreachable, the following error is shown to the user when executing `meshery version`:

```
➜  ~ mesheryctl version
Client Version: 0.3.18 	  GitSHA: 26173973db79fe92523754d8301d1421186b9cc3
Server Version: Unavailable 	  GitSHA: Unavailable

Could not communicate with Meshery at http://localhost:9081/api
Ensure that Meshery is available. See (https://docs.meshery.io)
```

**Expected Behavior**
A couple minor wording updates will improve this error message:

- [ ] Provide actual /api/server/version endpoint in message.
- [ ] Change from "Ensure that Meshery is available." to
     ```  
     Ensure that Meshery is available. 
     See Meshery Documentation (https://docs.meshery.io) for help.
     ```

**Comment by rshivam08** [comment]
@leecalcote, I want to take up this issue.

**Comment by leecalcote** [comment]
Sounds great, @rshivam08. ✔️
