### ISSUE TITLE
Implement `meshery` CLI in Go

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#121]
Currently, users can use the `meshery` bash script as a CLI to interact with Meshery. The CLI experience will be more robust and responsive if it is implemented in Go. 

**Feature Request**
1. Convert [`meshery` bash script](https://github.com/layer5io/meshery/blob/master/meshery) from shell to golang, leveraging the Cobra framework - https://github.com/spf13/cobra
1. Name the new golang-based CLI, `mesheryctl`.
1. Use a Golang Docker client to control Meshery's containers.

**Comment by sakows** [comment]
Initial working version implemented @leecalcote @girishranganathan : https://github.com/meshery/meshery/tree/sakows/mesheryctl/mesheryctl

**Comment by leecalcote** [comment]
@anandrkskd The initial version of `mesheryctl` that @sakomws created needs a bit of finishing up. This is the initial version - https://github.com/meshery/meshery/tree/master/mesheryctl.

In order to be rid of the [`meshery` bash script](https://github.com/meshery/meshery/blob/master/meshery), needs to account for each of the requisites outlined in [preflight_check()](https://github.com/meshery/meshery/blob/master/meshery#L38-L69).

**Comment by sakomws** [comment]
1. 'wget' and 'curl' we dont use, instead use "net/http" library to for HTTP operations including download file.
2. For missing docker-compose binary, it throughs standard error:
a) In Mesheryctl:
```
go run main.go  start
Starting Meshery . . .
2019/06/24 07:11:38 exec: "docker-compose": executable file not found in $PATH
exit status 1
```
b) In Mac OS:
```
mesheryctl $docker-compose
bash: /usr/local/bin/docker-compose: No such file or directory
```

**Comment by sakomws** [comment]
@leecalcote should we add custom logging for docker-compose?

**Comment by leecalcote** [comment]
@sakomws @anandrkskd 
1. That's perfect. One less prerequisite to be concerned with.
2. Meshery's adoption and usefulness will in many cases rely on its user experience. With UX and shortening time-to-value as the goal, I propose that when docker-compose is missing, that Meshery takes action run to run docker-compose in a container, and in doing so, self-fulfilling its prerequisites. 

Benefit to this approach:

 1. avoids bundling docker-compose (python) in the Meshery binary
 1. facilitates getting to running Meshery faster

Behavior to implement:

1. check for `docker-compose` 
 1. if available, use it.
 1. if not, mesheryctl uses docker go client to run docker-compose in a container, like so - `docker run --rm -it -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock docker/compose:1.24.0 up`
 1. if mesheryctl is blocked based on security policy (production systems may not allow bind mounting the docker socket) or for any other reason, exit the install routine with a message to the user: "Prerequisite Docker Compose not available. Please install Docker Compose on this system and retry the installation."

**Comment by leecalcote** [comment]
Expanded design doc - https://docs.google.com/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit

**Comment by sakomws** [comment]
Thanks for details @leecalcote , will proceed accordingly.

**Comment by leecalcote** [comment]
@sakomws some fine work here. `mesheryctl` has landed.

**Comment by Milon210534** [comment]
Why i could not log in my gp apps. Please help
![Screenshot_2020-06-01-18-58-23](https://user-images.githubusercontent.com/66259075/83414080-b3d17e00-a43e-11ea-874b-cfbfaed1c811.png)

**Comment by Milon210534** [comment]
Why I could not log in my gp apps??
Please help urgently.
01766692608
![Screenshot_2020-06-01-18-58-23](https://user-images.githubusercontent.com/66259075/83414388-3ce8b500-a43f-11ea-9f2b-9831f45d62c7.png)

**Comment by ripon516** [comment]
আমার সিমে আমি কোন মেসেজ কিনি নি my Gp থেকে,, তার পরে ও মেসেজ দিয়ে আমার কয়েন কেটে নিছে
