### ISSUE TITLE
[Docs] Update "Create doc issue" hyperlink to use new GitHub issue label

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1212]
**Current State:**
The "Create doc issue" hyperlink on the Meshery Docs site is out of date. It refers to a GitHub issue label `docs` that this project no longer uses. This project now uses the `area/docs` label instead.

<img width="1256" alt="Screen Shot 2020-07-05 at 12 28 09 PM" src="https://user-images.githubusercontent.com/7570704/86540022-219e1900-bec7-11ea-99fe-0077b48e8ac5.png">

**Desired State:**
Update [editable.html](https://github.com/layer5io/meshery/blob/master/docs/_includes/editable.html) to refer to the label `area/docs` not the old label `docs`.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Adeola-Adesoba** [comment]
Hi Lee,
I will like to help work on this.

**Comment by leecalcote** [comment]
Hi @Adeola-Adesoba, that would be fantastic. Yes, please. 👍
