### ISSUE TITLE
[Docs] Add login page screenshot to "Providers" section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1213]
**Current State:**
There are no screenshots of the Meshery UI showing readers what it looks like to select a Provider and login.

**Desired State:**
Incorporate the screenshot below into the [Providers section](https://meshery.layer5.io/docs/extensibility#providers) of the Meshery Docs.

**Screenshot**
<img width="977" alt="Meshery - Providers" src="https://user-images.githubusercontent.com/7570704/86538587-78522580-bebc-11ea-94d9-30bc08f1b675.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Adeola-Adesoba** [comment]
Hi Lee, 
Where should the screenshot go? I was thinking I should place it under this header: https://meshery.layer5.io/docs/extensibility#types-of-providers

What do you think?

**Comment by leecalcote** [comment]
@Adeola-Adesoba sounds real good. Alternatively, a couple sections higher, right here - https://meshery.layer5.io/docs/extensibility#providers, would do the trick as well.

**Comment by morrme** [comment]
@leecalcote Adeola is just working in the browser right now so I did #1216 to help her get this done in one commit :)

**Comment by leecalcote** [comment]
Oh, awesome. A coordinated effort. 😄 Teamwork, baby, teamwork.
