### ISSUE TITLE
[mesheryctl] Fails to initialize app folder (`~/.meshery`) and `meshery.yaml` file

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1241]
**Description**
`mesheryctl system start` fails to create a `~/.meshery` folder, download and rename the `docker-compose.yaml` as `meshery.yaml`.

[This code](https://github.com/layer5io/meshery/blob/master/mesheryctl/internal/cli/root/system/start.go#L50-L53) is not being invoked. Users running fresh installations are unable to start Meshery.

**Environment:**
 - OS: Linux

**To Reproduce**
This issue was seen on a Linux server while installing `mesheryctl` as the root user. I don't believe the bug is constrained to just this environment specifically, however.

1. Run `curl -L https://git.io/meshery | bash -` as `root` on a Linux server.

**Comment by leecalcote** [comment]
@nitishm do you mind looking at this? It seems that one or more sections of the logic between the utils/helper.go and start.go are not being invoked.

**Comment by leecalcote** [comment]
See @tingkai-zhang for assistance in reproducing this issue.

**Comment by nitishm** [comment]
@leecalcote is this confined to linux servers or can I reproduce it on osx ?

**Comment by leecalcote** [comment]
My bet is that this behavior will be seen on MacOS as well, yes.

**Comment by nitishm** [comment]
> My bet is that this behavior will be seen on MacOS as well, yes.

Yup I see it. Let me clone master and see if happens from the build.

```
~ sudo curl -L https://git.io/meshery | bash -
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2964  100  2964    0     0  15437      0 --:--:-- --:--:-- --:--:-- 15437

Downloading mesheryctl-v0.4.0-beta.1 for Darwin...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   654  100   654    0     0   6606      0 --:--:-- --:--:-- --:--:--  6606
100 4120k  100 4120k    0     0  5450k      0 --:--:-- --:--:-- --:--:-- 15.4M

Extracting mesheryctl-v0.4.0-beta.1...
Archive:  /Users/nitish_malhotra/meshery.zip
  inflating: LICENSE
  inflating: README.md
  inflating: mesheryctl

Installing mesheryctl in /usr/local/bin.
mesheryctl installed.
permissions moved to nitish_malhotra
Removing installation files and opening Meshery...open /Users/nitish_malhotra/.meshery/meshery.yaml: no such file or directory
```
