### ISSUE TITLE
[Docs] README - change "Layer5 Contributors Welcome Guide" to "Layer5 Community Welcome Guide" 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1248]
**Description:**

Each of the readme's across each of the repos in the [layer5io org](https://github.com/layer5io) are in need having this reference updated. The guide isn't constrained to contributing, but is a general welcome for newcomers in the community.

**Comment by rshivam08** [comment]
@leecalcote, I want to take up this issue.

**Comment by leecalcote** [comment]
Thank you, @rshivam08. Please do.

**Comment by rshivam08** [comment]
@leecalcote, Do I need to make changes in all repos available at [meshery.org](https://github.com/meshery) or in [meshery](https://github.com/meshery/meshery) alone?

**Comment by leecalcote** [comment]
@rshivam08 across all repos available in meshery org. 👍

**Comment by neha-saggam** [comment]
I'm a first timer :D. Looking to start open source contribution. Can I take up this issue if @rshivam08 you haven't already started working ?

**Comment by leecalcote** [comment]
@neha-saggam yes, please do. There are many repositories in the [meshery org](https://github.com/meshery) need of receiving this update.

**Comment by neha-saggam** [comment]
Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,

<img width="886" alt="Screen Shot 2020-07-13 at 4 02 16 PM" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">

**Comment by rshivam08** [comment]
@neha-saggam, you are trying to access the wrong remote. Please try to push your changes to https://github.com/meshery/meshery.git

**Comment by ashiscs** [comment]
> Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> 
> <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">

@neha-saggam https://github.com/meshery/meshery/blob/master/CONTRIBUTING-gitflow.md (handy resource to get you started) !

**Comment by ashiscs** [comment]
> Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> 
> <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">

@neha-saggam  if you are trying to do changes in this repo so as @rshivam08 suggested it should point to https://github.com/meshery/meshery.git instead of https://github.com/meshery/meshery.io.git

**Comment by neha-saggam** [comment]
> > Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> > <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">
> 
> @neha-saggam if you are trying to do changes in this repo so as @rshivam08 suggested it should point to https://github.com/meshery/meshery.git instead of https://github.com/meshery/meshery.io.git

As @leecalcote mentioned [here](https://github.com/meshery/meshery/issues/1248#issue-654206591) this change is for each of the repos in org, I started of with https://github.com/meshery/meshery.io.git instead of https://github.com/meshery/meshery.git. Should I not do that ?

**Comment by neha-saggam** [comment]
> > Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> > <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">
> 
> @neha-saggam https://github.com/meshery/meshery/blob/master/CONTRIBUTING-gitflow.md (handy resource to get you started) !

@ashiscs Thanks!

**Comment by ashiscs** [comment]
> > > Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> > > <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">
> > 
> > 
> > @neha-saggam if you are trying to do changes in this repo so as @rshivam08 suggested it should point to https://github.com/meshery/meshery.git instead of https://github.com/meshery/meshery.io.git
> 
> As @leecalcote mentioned [here](https://github.com/meshery/meshery/issues/1248#issue-654206591) this change is for each of the repos in org, I started of with https://github.com/meshery/meshery.io.git instead of https://github.com/meshery/meshery.git. Should I not do that ?

Ok, then you are doing it correctly

**Comment by ashiscs** [comment]
> > > Hey @leecalcote, when I try to push changes to a new branch it says permission denied. Am I missing something here ? Please help,
> > > <img alt="Screen Shot 2020-07-13 at 4 02 16 PM" width="886" src="https://user-images.githubusercontent.com/25531156/87295066-45dea300-c522-11ea-9d64-f8fd8aece24e.png">
> > 
> > 
> > @neha-saggam https://github.com/meshery/meshery/blob/master/CONTRIBUTING-gitflow.md (handy resource to get you started) !
> 
> @ashiscs Thanks!

This would definitely help you, but if you still face any problem do reach out !
@neha-saggam feel free to join the community Slack (http://slack.meshery.io/) , to know more about the project !

**Comment by neha-saggam** [comment]
I am still getting permission denied for this repository as well. Am I missing something here ?

<img width="598" alt="Screen Shot 2020-07-15 at 8 15 35 PM" src="https://user-images.githubusercontent.com/25531156/87559549-12457980-c6d8-11ea-8fe8-97a88d934683.png">

**Comment by rshivam08** [comment]
@neha-saggam, Can you please run "git remote -v" command and show the output here? Also show the command that you are using to push your changes with the above error screenshot.

**Comment by morrme** [comment]
@neha-saggam Can you visit this link ? 
https://github.com/meshery/meshery/compare/master...neha-saggam:patch-1

You have already made the change, and you should be able to initiate the pull request there. 

You may need to amend your commit to sign off, but let's just get a proper PR for your work set up first.... cc @leecalcote

**Comment by morrme** [comment]
**Here is my suggestion for everyone:**
@leecalcote provided a convenient link to the org.  There are 31 repos that would need this change.  

**For anyone that wants to submit a change**, put a comment in here this thread with the name of the repo you're working on. That way, nobody has to overcommit to doing all of them, and more people can pitch in. 
**Focus on doing one at a time** and it is a quick and non-overwhelming task that can be completed in minutes.
Doing it this way, this whole task could be completed within a week. 

**For newcomers:** 
This is a very easy task to help you get started with the contribution process. If you're out there lurking and don't know where to start, **THIS IS YOUR ISSUE!** Come in and help! 

Leave a comment if you want to help but you don't know what to do.  Someone will come and help you get that first PR!

**Comment by leecalcote** [comment]
// @crustyy

**Comment by morrme** [comment]
And just to follow my own unauthorized rules :smirk:  I have already done:
learn-layer5 
service-mesh-performance-specification
@neha-saggam has meshery in progress 

Carry on....

**Comment by morrme** [comment]
@Adeola-Adesoba  @zaycodes  @Kolokodess @OdunayoOkebunmi This is a great one for the challenge.

**Comment by crustyy** [comment]
@morrme ya I'll do it!!

**Comment by zaycodes** [comment]
> @Adeola-Adesoba @zaycodes @Kolokodess @OdunayoOkebunmi @samswag This is a great one for the challenge.

Thanks for the heads up @morrme, I can see that there are also a good number of other beginner-friendly issues. I'll be sure to add this project to the list of projects for the challenge and make a shout out. Cheers.

**Comment by Ruth-ikegah** [comment]
Hello, I'm a newcomer. I want to help, please I'd need some help on what to do. Thanks 😊

**Comment by ashiscs** [comment]
@Ruth-ikegah https://github.com/meshery/meshery/blob/master/CONTRIBUTING-gitflow.md ( wonderful resource to get you started) and feel free to ask any questions or doubts you have !
Feel free to join the community Slack (http://slack.meshery.io/) , to know more about the project !

**Comment by leecalcote** [comment]
Here's a great resource to help get you oriented as well - https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit

**Comment by Ruth-ikegah** [comment]
Thanks. I went through them. I made a pull request for meshery/meshery but it did not pass one of the checks. Please can someone help me check it?

**Comment by leecalcote** [comment]
@Ruth-ikegah you bet. The check was most likely one for DCO and whether your commits were signed. Here's an explanation and instructions on the subject - https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by Ruth-ikegah** [comment]
Okay thanks. Noted the mistake now. I'd do it again 😊
