### ISSUE TITLE
[performance] Improve handing of missing protocol in Performance Test form

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1252]
**Current Behavior**
If a user enters a domain name (e.g., `google.com`) without specifying the protocol to be used for the endpoint (e.g., `https://`), the user receives this error message:

<img width="1228" alt="Screen Shot 2020-07-10 at 12 51 52 PM" src="https://user-images.githubusercontent.com/7570704/87207445-85fb1700-c2d1-11ea-8e56-e2c4efa70bcc.png">

This error message is inaccurate. Meshery fails to generate load against the endpoint, because the endpoint string is missing definition of which protocol to use.

**Desired Behavior**
- Client-side form validation should address this issue before the user is allowed to submit the form.

**Comment by kushthedude** [comment]
@rshivam08 Would you like to tackle it?

**Comment by rshivam08** [comment]
@kushthedude, Please assign it to me as similiar issue I was facing yesterday.
