### ISSUE TITLE
[Install] Add support for Meshery Adapter for Consul to Helm Chart

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1253]
**Current Behavior**
The current helm chart for Meshery is missing support for Consul.

**Desired Behavior**
The Meshery Adapter for Consul should be included in the default Helm deployment of Meshery.

**Comment by Ozrlz** [comment]
I installed the helm chart on the master branch (install/kubernetes/helm/meshery) and it installs the Consul adapter. I also installed the helm chart from the meshery repo (https://meshery.io/charts/) and I can confirm that the consul adapter is not installed when using that chart ... is that enough to have this issue closed?

**Comment by leecalcote** [comment]
Hi @Ozrlz, great question. I think we are mostly there except for that last portion, which is that by default, the Meshery Adapter for Consul should be deployed when someone uses the helm chart from the meshery repo. Ideally, all available adapters are deploy by default. Users can customize the install to remove the adapters, if they like.

Does this make sense? Your help here would be much appreciated. To recap, we essentially need all adapters supported in the Meshery helm chart (https://hub.helm.sh/charts/meshery/meshery). We probably need a couple more issues opened here.

**Comment by Aisuko** [comment]
Close the issue due to we already have been added the Helm chart for Consul.
