### ISSUE TITLE
[Install]Meshery helm chart installation is not working

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1257]
**Description**

Meshery helm chart installation is not working. The deployment applications are fired up but meshery is not recognised as a service which makes the installation fail at port forwarding step.

**Expected Behavior**

Helm installation should work fine

**Comment by leecalcote** [comment]
As we go to provide this service, let's optimize for the local deployment scenario and use service `type: NodePort`

**Comment by Aisuko** [comment]
This not be an issue, you should make a choice of the service type that you need before deploying. Default the service type as NodePort that makes zero sense. Just look at the helm/charts project, you can make sure the right way or the best practice.

**Comment by kushthedude** [comment]
Can you please update the installation instruction if you think helm charts
are working fine?

**Comment by Aisuko** [comment]
It works for me. Need more information here.

```
➜  meshery git:(dev) kubectl port-forward meshery-66664cfcbd-qkl6m 8000:8080 -n meshery
Forwarding from 127.0.0.1:8000 -> 8080
Forwarding from [::1]:8000 -> 8080
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
```

**Comment by kushthedude** [comment]
> It works for me. Need more information here. And in my opinion, we should consider Ingress and ServiceMesh way
> 
> ```
> ➜  meshery git:(dev) kubectl port-forward meshery-66664cfcbd-qkl6m 8000:8080 -n meshery
> Forwarding from 127.0.0.1:8000 -> 8080
> Forwarding from [::1]:8000 -> 8080
> Handling connection for 8000
> Handling connection for 8000
> Handling connection for 8000
> Handling connection for 8000
> ```

It works till here, try open the port specified in the browser and see the connection handling error occuring

**Comment by Aisuko** [comment]
> > It works for me. Need more information here. And in my opinion, we should consider Ingress and ServiceMesh way
> 
> > 
> 
> > ```
> 
> > ➜  meshery git:(dev) kubectl port-forward meshery-66664cfcbd-qkl6m 8000:8080 -n meshery
> 
> > Forwarding from 127.0.0.1:8000 -> 8080
> 
> > Forwarding from [::1]:8000 -> 8080
> 
> > Handling connection for 8000
> 
> > Handling connection for 8000
> 
> > Handling connection for 8000
> 
> > Handling connection for 8000
> 
> > ```
> 
> 
> 
> It works till here, try open the port specified in the browser and see the connection handling error occuring

No,Meshery provider can be found on the web browser page at localhost with export port.
