### ISSUE TITLE
[Docs] Copy-to-clipboard for CLI commands

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1269]
**Current State:**
CLI commands included in the Meshery documentation have to be highlighted and copied by the reader. Sometimes the reader will accidentally include the `$` in what they copy and paste to their terminal. 

**Desired State:**
Improve the reader experience for Meshery CLI commands incorporating https://clipboardjs.com to capture various terminal commands into the reader's clipboard on click of the mouse. 

1. See  https://layer5.io/meshery/#getting-started as an example of how to do this. 
1. Use the same clipboard icon from layer5.io

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Jashpatel1** [comment]
So does that mean to include HTML in the [doc](https://github.com/meshery/meshery/blob/master/docs/pages/installation/index.md) for making use of clipboardjs?

**Comment by Nikhil-Ladha** [comment]
No @Jashpatel1 here docs refers to the Meshery Documentation Site, which is within the meshery repo itself, under the docs folder😬.

**Comment by Jashpatel1** [comment]
@Nikhil-Ladha  Yes, I am talking about the same. [This one](https://github.com/meshery/meshery/blob/master/docs/pages/installation/index.md), right?

The example which @leecalcote has mentioned is written in a HTML file. While the meshery docs are in Markdown, and clipboardjs supports HTML.

Correct me if I am wrong.

**Comment by Nikhil-Ladha** [comment]
Yes, @Jashpatel1 you are right. Sorry, I didn't check the link properly which you shared in the previous comment. I don't think we want to do the change in the markdown file, but the structure of the site is in a way that makes it a bit difficult to workaround. 
So, you can check if we could do that like adding a separate file or we will have to do something in the markdown itself.

**Comment by Jashpatel1** [comment]
@leecalcote I think it would be difficult to implement as it is in markdown.

**Comment by leecalcote** [comment]
@Jashpatel1 right. If you use the implementation done on the page that I linked to above, I think you'll have success.

**Comment by Jashpatel1** [comment]
@leecalcote  The example you have attached is written in HTML so it is easy to include clipboardjs, while the meshery docs are in markdown and clipboardjs dosent support markdown. In order to do this, there must be HTML. So are you saying to include HTML in the markdown file.

**Comment by leecalcote** [comment]
@Jashpatel1 yep, that'll work. 👍

**Comment by leecalcote** [comment]
@iambam or @Josephchinedu, you might like to pick you this issue.

**Comment by Fahdmoh01** [comment]
Kidnly assign me to this issue @Nikhil-Ladha

**Comment by chebro** [comment]
If there's no one working on it I'd like to take a dig at this!

**Comment by Fahdmoh01** [comment]
You can take this issue

**Comment by chebro** [comment]
This is my first time with Jekyll, how do we include the clipboard.js as a script? 😅

**Comment by Nikhil-Ladha** [comment]
You can take a look in the meshery, meshery.io repo . We use clipboard js in those sites too.
