### ISSUE TITLE
[meshery]  Meshery was deployed in the cluster but discover the cluster did not work 

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#1272]
**Description**

 I deployed Meshery into our cluster and wanna detect the cluster-config.yaml but it no working well,  the issue that you're describing is #921

**Expected Behavior**

import the local user's ~/.kube/config and connect to their current context.

**Comment by kushthedude** [comment]
@Aisuko Is this related for #1257, if yes then we can fix it in #1257 itself?

**Comment by Aisuko** [comment]
No, there are two different types of issues. 

> @Aisuko Is this related for #1257, if yes then we can fix it in #1257 itself?

No, these are two different types of issues.

**Comment by kushthedude** [comment]
Oh thanks for informing!

**Comment by Aisuko** [comment]
> Oh thanks for informing!

You are welcome.

**Comment by leecalcote** [comment]
@Aisuko is this the issue that you're describing? https://github.com/meshery/meshery/issues/921

**Comment by Aisuko** [comment]
> @Aisuko is this the issue that you're describing? #921

Yes, I deployed Meshery into our cluster and wanna detect the `cluster-config.yaml`  but it no working well

**Comment by leecalcote** [comment]
@Aisuko Oh, I see. Ok, #921 describes the a regression issue in which Meshery does not automatically import the local user's ~/.kube/config and connect to their current context. In the scenario in #921, Meshery is deployed out of cluster. // @kumarabd 

You may want to include a description in this issue (the boilerplate text is in the description now).

**Comment by leecalcote** [comment]
@kumarabd, perhaps, you can look at #1272 as you're fixing #921?

**Comment by Aisuko** [comment]
@kushthedude thanks

**Comment by Aisuko** [comment]
We Can close this issue first and if the same type of issue appears again, we can reopen or create a new one.
