### ISSUE TITLE
[Docs] Update Release page with latest releases and their release notes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1276]
**Current State:**
The [releases documentation page](https://meshery.layer5.io/docs/releases) is missing the latest releases.

**Desired State:**
Releases page should have all of the releases and their notes from https://github.com/layer5io/meshery/releases

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by jesuslerma** [comment]
Is this related to #510 ?

**Comment by leecalcote** [comment]
@jesuslerma, yes, sir. This is the manual effort in the meantime.

**Comment by elucidium** [comment]
Hello! I'm a first-time contributor, and I'd be glad to take this on! How would you prefer for releases without a "What's new?" section (specifically v0.4.0-beta.3 and v0.4.0-beta.1) to be documented?

**Comment by Code-Ebullient** [comment]
can i work on this? Is it still open?

**Comment by chandrashritii** [comment]
Hey @Code-Ebullient 
@elucidium is already working on this. Please take a look at some of the other open issues.

**Comment by leecalcote** [comment]
@Code-Ebullient thanks for asking! Let's find you a good few first issues...

**Comment by Code-Ebullient** [comment]
🤦 okay... @leecalcote

**Comment by leecalcote** [comment]
@Code-Ebullient -- here's one: https://github.com/meshery/meshery/issues/1282
