### ISSUE TITLE
[Docs] Updating year of Copyright in Meshery docs footer

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/meshery#1280]
**Current State:**
Copyright in the footer is 2019

**Desired State:**
Updating the copyright in the footer to 2020

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Code-Ebullient** [comment]
I'll work on this.
