### ISSUE TITLE
[Docs] Linkerd version number has an extra period

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1294]
**Current State:**
 There is an extra period in the supported Linkerd version number:
<img width="855" alt="Screen Shot 2020-07-20 at 7 52 42 AM" src="https://user-images.githubusercontent.com/7570704/87948460-533be600-ca6a-11ea-985b-d64c887eaf5c.png">

**Desired State:**
1. Edit this page - https://github.com/layer5io/meshery/blob/master/docs/_adapters/linkerd.md
1. Remove the "." that comes just after the "v", so that it reads `v2.5.0`

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Code-Ebullient** [comment]
On it sir, thanks
