### ISSUE TITLE
[Docs] Backfill all the releases on the releases page

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1303]
**Current Behavior**

There missing release tags in the https://meshery.layer5.io/docs/project/releases

**Desired Behavior**

Add all the release tags of Meshery till v0.0.1 in the https://meshery.layer5.io/docs/project/releases 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by PluckyPrecious** [comment]
Hi @kushthedude I'd like to give this a shot if still up for grabs 👍  . And the release tags should be "Annotated tags" yea?

**Comment by kushthedude** [comment]
Yes please go ahead @PluckyPrecious , You can find the releases in the releases section of the repo

**Comment by PluckyPrecious** [comment]
Hi @kushthedude  the tag release doc is available for review. 😅
