### ISSUE TITLE
[Docs] Improve Contributing guide

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#1313]
**Current State:**
It is clueless about how to get started with working on ui as it starts an error when running both meshery server and meshery ui. 

**Desired State:**
It should specify accessing ui though localhost:9081(meshery server) instead of localhost:3000 (ui server).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
I guess this is the issue you were talking about @anirudhjain75. https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#build-and-run-meshery-server . Here, it mentions to first setup the provider and then access the UI at 3000 port.

**Comment by anirudhjain75** [comment]
@Nikhil-Ladha ```Once you have the server up and running, you will be able to access the Meshery UI at http://localhost:3000. One thing to note is that for the UI dev server to work, you need Meshery server running on the default port of 9081. Any UI changes made now will automatically be recompiled and served in the browser.``` this is the current line. It says you'll have to access localhost:3000 inspite of localhost:9081

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha `Once you have the server up and running, you will be able to access the Meshery UI at http://localhost:3000. One thing to note is that for the UI dev server to work, you need Meshery server running on the default port of 9081. Any UI changes made now will automatically be recompiled and served in the browser.` this is the current line. It says you'll have to access localhost:3000 inspite of localhost:9081

But that comes after the setup procedure for make run-local, which states about logging into the provider before accessing the 3000 port. If you can check the link above, it will make my point clear.

**Comment by anirudhjain75** [comment]
Maybe just removing the part in `make run-ui-dev` should be fine 🤔 . @leecalcote whats your take on this ?

**Comment by Nikhil-Ladha** [comment]
I don't understand the issue here, anyways it's not necessary but still if it's a point of confusion then a line can be added stating that  `you need Meshery server running at 9081 port, and also have the provider configured there. Then, you can work on the 3000 port`.

**Comment by PluckyPrecious** [comment]
Hello @anirudhjain75 @Nikhil-Ladha can i work on this?

**Comment by Nikhil-Ladha** [comment]
Yeah sure @PluckyPrecious go ahead👍🏼. You can take some reference from the chat that we had here in the comments above.
