### ISSUE TITLE
[Docs] Readme.md link fix

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#1314]
**Current State:**
Kubernetes - minikube points to https://meshery.layer5.io/docs/installation/minikube

**Desired State:**
Kubernetes - minikube should point to https://meshery.layer5.io/docs/installation/platforms/minikube

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Hi @Anita-ihuman this might be an issue you would like to take on.

**Comment by Anita-ihuman** [comment]
Oh really 
Thanks 
Will start working on this

**Comment by leecalcote** [comment]
Excellent. Thank you, @Anita-ihuman!

**Comment by Shokescodes** [comment]
Hi @leecalcote . Thanks for the work you do for the community.
 I'm new to contributing to open source projects.
 Could you ping me as soon as your find some project I could contribute to ?

**Comment by leecalcote** [comment]
Hi @Shokescodes, sure, you bet. Here's one that you might try your hand at - https://github.com/meshery/meshery.io/issues/276

@Anita-ihuman and @Shokescodes  you're most welcome to join the Meshery community here - http://slack.meshery.io.
