### ISSUE TITLE
[UI] Can't delete Grafana board

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1330]
**Description**
When a user tries to delete metrics board imported from Grafana. The following error occurs.

Here is the console log: [localhost-1595869272498.log](https://github.com/layer5io/meshery/files/4983326/localhost-1595869272498.log)

![Untitled](https://user-images.githubusercontent.com/7570704/88570194-48042f80-d001-11ea-8e03-251d0b09a2fb.gif)

**Comment by PmcFizz** [comment]
I will see it

**Comment by leecalcote** [comment]
Awesome. Thank you, @PmcFizz. 👍

**Comment by PmcFizz** [comment]
Hi I want to know whether  I must create k8s cluster for this problem ？

**Comment by leecalcote** [comment]
It's easiest if you do, @PmcFizz. In order to do so, Docker Desktop and Minikube made this fairly straightforward. You might also want to walk through the service mesh workshop linked here - https://layer5.io/workshops

**Comment by PmcFizz** [comment]
Ok I get it

**Comment by PmcFizz** [comment]
hi I come again, when I recurrent this problem I don’t see it。 so I think maybe your board hava problem。 could you give me your Grafana board config ？

**Comment by PluckyPrecious** [comment]
> hi I come again, when I recurrent this problem I don’t see it。 so I think maybe your board hava problem。 could you give me your Grafana board config ？ @leecalcote

@leecalcote
