### ISSUE TITLE
[Docs] Windows installation instructions using wrong mesheryctl command

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1334]
**Current State:**
The instructions on [this page](https://meshery.layer5.io/docs/installation#windows) say to run `./mesheryctl start`

**Desired State:**
The instructions should say to run `./mesheryctl system start`

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by iknowahra** [comment]
I would like to take this 🤲

**Comment by leecalcote** [comment]
Thank you, @iknowahra. Please do. 👍 

// @usamaidrsk
