### ISSUE TITLE
[Docs] Homebrew installation instructions using wrong mesheryctl command

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1335]
**Current State:**
The homebrew instructions on [this page](https://meshery.layer5.io/docs/installation#homebrew) say to run `./mesheryctl start`

**Desired State:**
The instructions should say to run `./mesheryctl system start`

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
@iknowahra if you would, you can take this up too.

**Comment by iknowahra** [comment]
@Nikhil-Ladha I would like to do 👍

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I think it is already done :-)

Oops, seems like someone forgot to mention the issue😬. No worries you can work on any other issue you want. Also, feel free to join our slack workspace at slack.layer5io.com

**Comment by Nikhil-Ladha** [comment]
Fixed by #1342
