### ISSUE TITLE
[Docs] Revamp the contributing.md

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1344]
**Current State:**
There are several changes in Meshery & contributing document is not clear enough.

**Desired State:**
Contributing.md needs some revamping & proper structuring so that new contributors may follow it & get started with Meshery.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
@kushthedude if you could highlight the changes you are talking then, it would be easier to make the changes for the person who will take up the issue.

**Comment by kushthedude** [comment]
> @kushthedude if you could highlight the changes you are talking then, it would be easier to make the changes for the person who will take up the issue.

There a lot of changes which need to be then, that is why the issue is not marked as Good-First-Issue. It needs to be someone who already has meshery set-up & can let know what revamping needs to be done. If the issue would have a single area or a heading to change I would have already highlighted it & made it a good first issue.

**Comment by PluckyPrecious** [comment]
Hi @kushthedude I wanted to open an issue to help solve the typos and some grammatical error in the contributing.md and then I saw this. Just as @Nikhil-Ladha said, it will be great if you could highlight the changes so I can work on the issue, I'll ask others too then. Thanks.

**Comment by kushthedude** [comment]
> Hi @kushthedude I wanted to open an issue to help solve the typos and some grammatical error in the contributing.md and then I saw this. Just as @Nikhil-Ladha said, it will be great if you could highlight the changes so I can work on the issue. Thanks.

You can go ahead with typos & grammatical fixes 👍

**Comment by PluckyPrecious** [comment]
Do i open a new issue or mention this issue when i'm done with the edit?

**Comment by PluckyPrecious** [comment]
> > Hi @kushthedude I wanted to open an issue to help solve the typos and some grammatical error in the contributing.md and then I saw this. Just as @Nikhil-Ladha said, it will be great if you could highlight the changes so I can work on the issue. Thanks.
> 
> You can go ahead with typos & grammatical fixes 👍

Should i reference this issue when i'm done with my edit, or i should create a new issue?

**Comment by Nikhil-Ladha** [comment]
You can mention this issue only, but instead of saying ` This PR fixes` you should use ` This PR updates`. That, will suffice.

**Comment by kushthedude** [comment]
Please mention this issue when you open the PR.

**Comment by chandrashritii** [comment]
@kushthedude If you or someone else is not already working on it, I can take this one up.

**Comment by kushthedude** [comment]
Please go ahead!

**Comment by PluckyPrecious** [comment]
Hey @chandrashritii is there something that still need to be done on this issue?
