### ISSUE TITLE
[Docs] Links to supported platforms need updated in the README.md

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1362]
**Current State:**
The links in this section of [the README](https://github.com/layer5io/meshery/blob/master/README.md) have changed on the meshery.layer5.io/docs site.

<img width="412" alt="Screen Shot 2020-08-03 at 11 26 07 PM" src="https://user-images.githubusercontent.com/7570704/89252943-d0299c80-d5e0-11ea-87c8-f926ec7fdf9b.png">

**Desired State:**
Most of the links in the Meshery repo's README need updating with their new locations in the documentation site.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by edwvilla** [comment]
I would like to contribute! 😄

**Comment by leecalcote** [comment]
Hi @edwvilla! That would be fantastic. Yes, please do. If you run into any questions, there are number of other contributors wiling to help here - http://slack.meshery.io
