### ISSUE TITLE
[Docs] Helm link on instalation platforms needs to be updated

### ISSUE THREAD

**Issue by edwvilla** [layer5io/meshery#1371]
**Current State:**
The Helm link on [Instalation platforms](https://meshery.layer5.io/docs/installation/platforms) is broken as it leads to 404
seems like is redirecting to `.../installation/kubernetes#helm` updating it to `.../installation/platforms/kubernetes#using-helm` should fix it

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@edwvilla, good eye!
