### ISSUE TITLE
[Docs]Add section in docs about Meshery's SMI Conformance capability

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1373]
**Current State:**
Reference material for the short write-up: https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit#

**Desired State:**
Perhaps, add this new capability at in a new page under https://meshery.layer5.io/docs/functionality

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
@leecalcote I would love to work on this

**Comment by ghost** [comment]
I am guessing I need to add the document https://github.com/KarenEfereyan/laravella as a separate link in the https://meshery.meshery.io/docs/functionality file like performance and lifecycle management are, right?

**Comment by PluckyPrecious** [comment]
Hi @KarenEfereyan I think you'll need to create a file with the name ``smi-conformance-capability`` under https://meshery.meshery.io/docs/functionality and input the content in the document https://github.com/KarenEfereyan/laravella inside the file. 🤔

**Comment by KarenEfereyan** [comment]
Okay @PluckyPrecious

**Comment by KarenEfereyan** [comment]
@PluckyPrecious i can't seem to find that file on the repository. Am I in the wrong folder?
![Capture](https://user-images.githubusercontent.com/56835876/90311565-f5c57880-def3-11ea-89ce-fd89f8fef101.PNG)

**Comment by KarenEfereyan** [comment]
Never mind @PluckyPrecious I have gotten the docs folder. I have made a branch to work with. I see the functionality folder with the two files, one for lifecycle and performance management. I have created a new smi-conformance-compatibility file alongside them. But when i try to run vi <branchname> .md, I get an error that the required application is not installed. Same for make site. So I am guessing I need to install Go?

**Comment by KarenEfereyan** [comment]
I am currently trying to get Go installed. Another question I have though. In this file, https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit# Am I to just dump the contents into the .md file or just a section. I currently just pasted the whole contents in there. But I am taking cue from the two other files to add relevant markup, like headings and subheadings. I need clarifications, I hope I am not doing something wrong

**Comment by KarenEfereyan** [comment]
I have go installed right now. But when i run vi mypage.md, i get this and I dont really understand![IMG_20200815_135307_528.jpg](https://user-images.githubusercontent.com/56835876/90312725-ab95c480-defe-11ea-95f0-5fc2144d62ea.jpg)

**Comment by leecalcote** [comment]
Hi @KarenEfereyan, for this issue, you can skip installing go. This issue will only require use of Ruby (Jekyll and bundler). These instructions might help - https://github.com/meshery/meshery/tree/master/docs

// @NupurThakur27

**Comment by PluckyPrecious** [comment]
> Never mind @PluckyPrecious I have gotten the docs folder. I have made a branch to work with. I see the functionality folder with the two files, one for lifecycle and performance management. I have created a new smi-conformance-compatibility file alongside them. But when i try to run vi .md, I get an error that the required application is not installed. Same for make site. So I am guessing I need to install Go?

Hi, @KarenEfereyan sorry for the late reply. Meshery Documentation uses Jekyll. First install Ruby https://jekyllrb.com/docs/installation/, then install Jekyll and Bundler.

**Comment by PluckyPrecious** [comment]
> Hi @KarenEfereyan, for this issue, you can skip installing go. This issue will only require use of Ruby (Jekyll and bundler). These instructions might help - https://github.com/layer5io/meshery/tree/master/docs
> 
> // @NupurThakur27

@leecalcote I'm suggesting this https://github.com/layer5io/meshery/tree/master/docs be included in the 

> I am currently trying to get Go installed. Another question I have though. In this file, https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit# Am I to just dump the contents into the .md file or just a section. I currently just pasted the whole contents in there. But I am taking cue from the two other files to add relevant markup, like headings and subheadings. I need clarifications, I hope I am not doing something wrong

You're on the right track, please do your thing with the markup 👍🏽

**Comment by PluckyPrecious** [comment]
> I am currently trying to get Go installed. Another question I have though. In this file, https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit# Am I to just dump the contents into the .md file or just a section. I currently just pasted the whole contents in there. But I am taking cue from the two other files to add relevant markup, like headings and subheadings. I need clarifications, I hope I am not doing something wrong

Please go ahead and do your thing with the enhancement. 👍🏽

**Comment by KarenEfereyan** [comment]
Okay @leecalcote but am i supposed to create the file first before running vi <filename.md>
. because according to the documentation, that command should allow me edit or add a documentation

**Comment by KarenEfereyan** [comment]
@PluckyPrecious give me more details. I should install ruby first? Then jekyll and Bundler? Can you send links to download them. I really want to get this done with before today ends. I would be happy if you are here for me @PluckyPrecious

**Comment by PluckyPrecious** [comment]
I'm here for you maami 😄 you use windows yea?

**Comment by KarenEfereyan** [comment]
Okay please do. Yes i use windows

**Comment by KarenEfereyan** [comment]
Thank you so much sir
