### ISSUE TITLE
[Docs] Add entry for Open Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1375]
**Current State:**
Meshery docs do not list Open Service Mesh

**Desired State:**
- Ensure that OSM is listed here - https://meshery.layer5.io/docs/service-meshes
- OSM version v0.2.0
- OSM logo - [osm.svg.zip](https://github.com/layer5io/meshery.io/files/5039020/osm.svg.zip)

<img width="300" alt="Screen Shot 2020-08-06 at 9 27 16 PM" src="https://user-images.githubusercontent.com/7570704/89602475-68679180-d82c-11ea-9a22-6f300c85f761.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@Anita-ihuman @Adeola-Adesoba @PluckyPrecious @Ruth-ikegah any takers?

**Comment by PluckyPrecious** [comment]
@leecalcote I'll take this up.

**Comment by PluckyPrecious** [comment]
@leecalcote what is the osm port?

**Comment by leecalcote** [comment]
@PluckyPrecious good question! It is 10010 (or 10010/tcp).

**Comment by PluckyPrecious** [comment]
@leecalcote Fixed @kumarabd helped out. PR ready.
