### ISSUE TITLE
[mesheryctl] Provide consistent formatting of client and server version information 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1376]
**Current Behavior**
`mesheryctl version` currently returns a format like so:

<img width="1076" alt="Screen Shot 2020-08-08 at 3 35 06 PM" src="https://user-images.githubusercontent.com/7570704/89719335-db881980-d98c-11ea-942a-e0ffab03ff2e.png">

**Desired Behavior**
Ideally, the two GitSHA sections start at the same column (ideally, they are aligned)

**Comment by leecalcote** [comment]
@subhamkrai would you like to tackle this?

**Comment by subhamkrai** [comment]
@leecalcote In my system I ran `mesheryctl version` and for me it's aligned.

```
$ mesheryctl version
Client Version: 0.4.0-beta.4 	  GitSHA: 9b717e0988f07b928177053beab04a3d2726d428
Server Version: Unavailable 	  GitSHA: Unavailable
```

**Comment by leecalcote** [comment]
@subhamkrai sure. It won't be aligned on all terminals as-is. I'm hoping that we can use a format that is.

**Comment by subhamkrai** [comment]
> @subhamkrai sure. It won't be aligned on all terminals as-is. I'm hoping that we can use a format that is.

Okay, I'll take a look again.

**Comment by subhamkrai** [comment]
For which system we are getting above issue? Just to check changes working or not.

**Comment by leecalcote** [comment]
@subhamkrai here's another item we can fix:

```
➜  meshery-osm git:(master) mesheryctl version
Client Version: 0.4.1 	  GitSHA: 0a5af6139a8919c72ccfed8e8800d512137ded0a
Server Version: v0.4.1 	  GitSHA: 0a5af61
```

1. Can we have the "v" retained in the Client Version tag?
1. Can we have the GitSHA for the Server be full-length (like that of the Client)?

**Comment by KarenEfereyan** [comment]
@subhamkrai can i join you on this. I want to learn

**Comment by subhamkrai** [comment]
> @subhamkrai can i join you on this. I want to learn

Sure.

**Comment by clementkng** [comment]
Hi @leecalcote, this issue seems to have gone stale so I would like to take this on to learn more about Meshery. What work is left? It seems like the Client Version has `v` prepended now, but I can't confirm if the GitSHA is full length until I build successfully build mesheryctl 😃

**Comment by KarenEfereyan** [comment]
> Hi @leecalcote, this issue seems to have gone stale so I would like to take this on to learn more about Meshery. What work is left? It seems like the Client Version has `v` prepended now, but I can't confirm if the GitSHA is full length until I build successfully build mesheryctl 😃 

Sure @clementkng feel free. Btw you look a lot like coding dojo from youtube. Are you related?

**Comment by clementkng** [comment]
```
Clement-Ng-MBP:meshery clement.ng$ mesheryctl version
Client Version: v0.4.6 	  GitSHA: 58e1f507a6a1d773e6def988e93c817cd1e8fe4d
Server Version: v0.4.6 	  GitSHA: 58e1f507a6a1d773e6def988e93c817cd1e8fe4d
```

The second issue @leecalcote mentioned above seems to be fixed, there are `v` prepended and the GitSHAs are full length. I'm not sure the first issue can be fully resolved ie if there's a "beta" in one of the versions, the Client and Server versions will be misaligned. I'm actually not sure how Lee saw the bug above, since `git blame` seems to show that the `v` has always been a part of the Client version. In fact, based on the history, I'm surprised that the opposite wasn't the case before [this commit](https://github.com/meshery/meshery/commit/46ed0bb4a9fa4ad600d4504c63294b9acd0c08bc), where it seems the Client version had the `v` appended but the Server version did not.
When we were talking, I think a possible enhancement is use the shorter git hashes (since the longer ones are not necessary to find commits), but to avoid scope creep, I think we should close out this issue.

**Comment by clementkng** [comment]
@KarenEfereyan no I'm not related 😆

**Comment by leecalcote** [comment]
@clementkng Thank you for investigating. Here is a copy of the output from a `mesheryctl version` from the latest Meshery release:

```
➜  ~ mesheryctl version
Client Version: 0.4.6 	  GitSHA: 96f48cf4e73fa6e985dbde2e82f20327d2b79c57
Server Version: v0.4.8 	  GitSHA: e472b61
```

For what it's worth, note that I have installed `mesheryctl` using brew.

**Comment by leecalcote** [comment]
After upgrade of the `mesheryctl` client and running `mesheryctl version`:

```
➜  ~ mesheryctl version
Client Version: 0.4.8 	  GitSHA: e472b611c7d90c1dae1bb9cdab096bb5148b818d
Server Version: v0.4.8 	  GitSHA: e472b61
```

@clementng, I believe there is a difference in environment variables if you're running `make` -  https://github.com/meshery/meshery/blob/master/Makefile#L7-L8

**Comment by leecalcote** [comment]
Test with a later version:

```
➜  ~ mesheryctl version
Client Version: 0.4.8 	  GitSHA: e472b611c7d90c1dae1bb9cdab096bb5148b818d
Server Version: v0.4.10 	  GitSHA: 80a0373
```
