### ISSUE TITLE
[Docs] Fix broken links

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#1380]
**Current State:**
There are quite broken links in the documentation site. Here is a link https://meshery.layer5.io/docs/intallation/platforms/windows that was directed to from https://meshery.layer5.io/docs/installation/platforms/docker. There are a few more
https://meshery.layer5.io/docs/installation/installation that was directed from 
https://meshery.layer5.io/docs/installation/platforms/minikube.

**Desired State:**
These links should be fixed and also I would suggested having a testing framework for these. It would be better to check for broken links on every PRs. I would help in QA. 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by anirudhjain75** [comment]
https://www.deadlinkchecker.com/website-dead-link-checker.asp can be used to check for broken links. Do ignore the localhost ones. Here is a report I just generated. 
<img width="1440" alt="Screen Shot 2020-08-10 at 12 06 20 PM" src="https://user-images.githubusercontent.com/14249589/89757239-4dce3a80-db02-11ea-84c9-af4e747ed169.png">

**Comment by PluckyPrecious** [comment]
@anirudhjain75 if no one is on this I could take it up.

**Comment by Neilblaze** [comment]
Yeah sure @PluckyPrecious . Go for it :+1:

**Comment by anirudhjain75** [comment]
Sure @PluckyPrecious  :)
