### ISSUE TITLE
[Docs] Getting Started with Other Platforms

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1385]
**Current State:**
The [Getting Started with Other Platforms page](https://github.com/layer5io/meshery/blob/master/docs/pages/installation/platforms.md) currently has a table full of a list of platforms. It does not have platform logos included. Included the platform logo will improve legibility (readers eyes snap to the log) and readers will enjoy this table a bit more. - https://meshery.layer5.io/docs/installation/platforms

<img width="1032" alt="Screen Shot 2020-08-11 at 6 33 28 PM" src="https://user-images.githubusercontent.com/7570704/89959106-3f1a7d00-dc01-11ea-9ad5-2b165b663705.png">

**Desired State:**
- [ ] Similar to the Meshery Adapters table, the Supported Platforms table should include small platform logos (ideally in SVG format) included in each row of the table.
- [ ] The platform table in the [Meshery repo README.md](https://github.com/layer5io/meshery/blob/master/README.md) should also have this same set of platform logos.

<img width="1194" alt="Screen Shot 2020-08-11 at 6 34 37 PM" src="https://user-images.githubusercontent.com/7570704/89959194-71c47580-dc01-11ea-86be-40adb79008d8.png">

**Logos:**
- Docker Engine, Docker Desktop [docker.svg.zip](https://github.com/layer5io/meshery/files/5059969/docker.svg.zip)
- AKS [aks.svg.zip](https://github.com/layer5io/meshery/files/5059973/aks.svg.zip)
- EKS [amazon-eks](https://user-images.githubusercontent.com/7570704/89960181-e26c9180-dc03-11ea-839b-6f3a931d4549.png)
- GKE  [gke](https://user-images.githubusercontent.com/7570704/89960546-f06ee200-dc04-11ea-9d53-d2f15eb87ec6.png)
- Helm [helm.svg.zip](https://github.com/layer5io/meshery/files/5059977/helm.svg.zip)
- Kubernetes [kubernetes.svg.zip](https://github.com/layer5io/meshery/files/5059979/kubernetes.svg.zip)
- Minikube [minikube](https://user-images.githubusercontent.com/7570704/89960628-26ac6180-dc05-11ea-859c-7910e03e422e.png)
- OpenShift [openshift.svg.zip](https://github.com/layer5io/meshery/files/5059992/openshift.svg.zip)
- Homebrew [homebrew](https://user-images.githubusercontent.com/7570704/89960769-899df880-dc05-11ea-8c29-81a791d2d5a5.png)
- Scoop - none
- WSL2 [wsl2](https://user-images.githubusercontent.com/7570704/89960932-edc0bc80-dc05-11ea-954f-15e444d4874c.png)
- KinD [kind](https://user-images.githubusercontent.com/7570704/89960939-f2857080-dc05-11ea-92bd-d82ef55a8ea6.png)
- Raspberry Pi [rpi](https://user-images.githubusercontent.com/7570704/89960970-0d57e500-dc06-11ea-880a-c27c39449d5d.png)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by LifeofDan-EL** [comment]
Good day, I would like to contribute to this. I will love to ask if there's a specific place, where I can get the logos from?

**Comment by leecalcote** [comment]
@LifeofDan-EL thanks. That would be great. Unfortunately, no, we don't have a collection of these logos just, yet. We'll need to do some digging. I'll do this now...

**Comment by LifeofDan-EL** [comment]
Okay, if you can do that, I could add the logos under the assets file directory, for easier reference.

**Comment by leecalcote** [comment]
@LifeofDan-EL ok, good to go. All logos except Scoop (it doesn't have one) have been added to the issue description.

**Comment by LifeofDan-EL** [comment]
Thanks will work on it then.

**Comment by LifeofDan-EL** [comment]
Just to be clear, the table [here](https://github.com/meshery/meshery#run-meshery) should also have the logo right?
![image](https://user-images.githubusercontent.com/45920948/89963359-5a0be200-dc3f-11ea-82cf-434183ec5b09.png)

**Comment by leecalcote** [comment]
Right on, yes.

**Comment by LifeofDan-EL** [comment]
I made a PR https://github.com/meshery/meshery/pull/1386, so I can easily use the GIthub url for the issue.

**Comment by leecalcote** [comment]
@LifeofDan-EL Thank you. When you do use the image URLs, it might be best to use their relative path, for example: `<img src="/docs/assets/img/providers/provider_screenshot.png" alt="Providers">`.

PR #1386 uses the keyword `fixes` which will automatically close this issue when it is merged. Given that it is only a portion of the complete fix, if you update the PR description to use a different word like "addresses" or "supports" or "relates to", then GitHub won't automatically close this issue.

**Comment by LifeofDan-EL** [comment]
So this is what the Readme and Platform look like now, I used the URL from the GitHub location of the images. It loads faster and to make sure it works locally and remote. 
How does it look?  Any suggestion
![plaforms](https://user-images.githubusercontent.com/45920948/90033512-777c9280-dcb7-11ea-9df9-475b332ae8be.png)
![tw](https://user-images.githubusercontent.com/45920948/90033528-7ba8b000-dcb7-11ea-8983-59af097eaccd.png)

**Comment by leecalcote** [comment]
@LifeofDan-EL it looks pretty good. We lose a little of the indentation, it seems.

Relative URLs work both locally and remotely. There's no difference in load time after the PR is merged (they load from the same place). Relative URLs are less fragile.

We're missing a logo for Linux. Here you go - [linux.svg.zip](https://github.com/meshery/meshery/files/5065317/linux.svg.zip)

We're missing a logo for Windows. You can use the same logo that is provided for WSL 2.

We're missing a logo for Mac. Here you go - [apple.svg.zip](https://github.com/meshery/meshery/files/5065320/apple.svg.zip)

**Comment by LifeofDan-EL** [comment]
Added the new logos and I used relative URLs.
![Readme](https://user-images.githubusercontent.com/45920948/90069628-77e25100-dcea-11ea-9432-3ffcdf57898b.png)

**Comment by leecalcote** [comment]
Awesome. 😄

**Comment by LifeofDan-EL** [comment]
Made a PR, it was fun working on this.

https://github.com/meshery/meshery/pull/1390

**Comment by KarenEfereyan** [comment]
Waow @LifeofDan-EL  you make this look so easy. Let me find an issue to contribute to as soon as possible

**Comment by PluckyPrecious** [comment]
Hi @leecalcote can we close this issue now?

**Comment by LifeofDan-EL** [comment]
About this, just checked https://meshery.meshery.io/docs/installation/platforms and the images there are broken but the readme I worked on is working well. Any idea why this is so?
![df](https://user-images.githubusercontent.com/45920948/90319779-2547a580-df33-11ea-9583-03c6690562de.png)

**Comment by PluckyPrecious** [comment]
No idea why, but i think it will be looked into. See #1395

**Comment by LifeofDan-EL** [comment]
Thanks @PluckyPrecious I leave it in good hands. I'm always available to help.

**Comment by PluckyPrecious** [comment]
You rock @LifeofDan-EL. ✊🏽 Kindly check other issues in the repo, it sure will need your magic touch.
