### ISSUE TITLE
Add an "Edit this Page" link on each doc page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#139]
To encourage contribution, each Meshery docs page should have an "edit this page" link that opens to GitHub on the specific page the user is on.

**Comment by leecalcote** [comment]
@madhabpaul Are you up to the challenge here?

**Comment by madhabpaul** [comment]
Yes

**Comment by leecalcote** [comment]
Awesome. :)

**Comment by leecalcote** [comment]
@madhabpaul, you could do something like:

```<a href="{{.site.params.ghrepo}}/edit/master/docs/{{.file.path}}">Edit this Page</a>```

using variables like {{.File.Path}} documented here https://jekyllrb.com/docs/static-files/.

**Comment by leecalcote** [comment]
Opening up for an easy Hacktoberfest win for someone...

**Comment by Nikhil-Ladha** [comment]
Can i go for it @leecalcote sir?

**Comment by leecalcote** [comment]
Absolutely, @Nikhil-Ladha

**Comment by leecalcote** [comment]
Thanks, guys. We're able to close this issue with the new docs theme having "edit this page" out of the box.
