### ISSUE TITLE
[Docs] Fix missing documentation, logo path, Images and Table of Content

### ISSUE THREAD

**Issue by JubayerJoy** [layer5io/meshery#1395]
**Current State:**
- Documentation missing in https://meshery.layer5.io/docs/installation/platforms/windows
- The logos are broken in https://meshery.layer5.io/docs/installation/platforms
- Images are not shown in https://meshery.layer5.io/docs/guides/interpreting-performance-test-results
- Sections in the table of contents are repeated twice on,
   - https://meshery.layer5.io/docs/guides
   - https://meshery.layer5.io/docs/functionality

**Desired State:**
- [ ] Windows documentation should be added as soon as possible.
- [x] Logos should appear correctly.
- [x] Images should appear correctly.
- [ ] Table of contents should be fixed in,
  - https://meshery.layer5.io/docs/guides
  - https://meshery.layer5.io/docs/functionality

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@JubayerJoy thanks for this. Have a look at https://github.com/meshery/meshery/pulls/1388

**Comment by JubayerJoy** [comment]
@leecalcote, I have reviewed the PR. Some great work by @PluckyPrecious 🚀
That PR fixes [image issue](https://meshery.meshery.io/docs/guides/interpreting-performance-test-results).

I think windows documentation, broken logo, and ToC is not yet covered 😕  
@PluckyPrecious, what is your thought about this?

**Comment by PluckyPrecious** [comment]
Hi @JubayerJoy it is great if you can cover those as i'm on transit and will be off my system for now. @leecalcote what you say?

**Comment by chandrashritii** [comment]
@JubayerJoy Thanks for pointing these out. I'd like to take this one on if you haven't started working on it already.

**Comment by JubayerJoy** [comment]
@chandrashritii sure, I haven't started, go-ahead 👍

**Comment by kishore007k** [comment]
Is this issue still open? If so, I'll take this on.

**Comment by chandrashritii** [comment]
@kishore007k I'm working on this one at the moment. Let's find you another issue :)

**Comment by kishore007k** [comment]
@chandrashritii 👍🤞

**Comment by KarenEfereyan** [comment]
Is this issue still open?

**Comment by sbs2001** [comment]
https://meshery.meshery.io/docs/architecture is missing the images.

**Comment by JubayerJoy** [comment]
Hi @sbs2001, good catch!
A common practice is to *open a new issue* if you can't find the same issue listed or mentioned anywhere.
If you want you can create a new issue or I can open one for you if you want.

Cheers!

**Comment by sbs2001** [comment]
@JubayerJoy  

> If you want you can create a new issue or I can open one for you if you want.

No thanks !

> A common practice is to open a new issue if you can't find the same issue listed or mentioned anywhere.

FWIW this ticket is labeled `duplicate`  for some reason, add to that my issue is a subset of what you are proposing(atleast the title). So IMHO  opening a new issue  is not necessary.

**Comment by JubayerJoy** [comment]
@sbs2001 

> FWIW this ticket is labeled `duplicate` for some reason, add to that my issue is a subset of what you are proposing(atleast the title).

True, your issue is a subset of the issues mentioned in the title. It's labeled `duplicate` cause some of them are already covered by other tickets (You can see some of them are already fixed).

> So IMHO opening a new issue is not necessary.

My point is, I am **not updating this list** with similar issues, so the issue you mentioned **might go unnoticed**.
Each time an image breaks or document is missing, it falls under this title.  Should people comment again and again here to get the issue noticed?
So, why not open a new issue?

**Comment by chandrashritii** [comment]
@JubayerJoy This issue should be closed. The issue with the missing links in the architecture page have been captured in #1675. New issues should be opened to point out any future documentation errors

**Comment by chandrashritii** [comment]
//CC @leecalcote Closing this issue.
