### ISSUE TITLE
[Docs] Supported Platforms table missing bottom row

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1402]
**Description**
The Supported Platforms table in the [Meshery repo's README.md](https://github.com/layer5io/meshery/blob/master/README.md) is missing a cell.

**Expected Behavior**
The table should have a single row, spanning two columns at the bottom of the table.

**Screenshots**
<img width="825" alt="Screen Shot 2020-08-16 at 2 19 46 PM" src="https://user-images.githubusercontent.com/7570704/90342169-c4b87700-dfcb-11ea-8b71-5dbca9e2c559.png">

**Comment by Veri5ied** [comment]
I'll like to fix this issue

**Comment by leecalcote** [comment]
Thank you, @Veri5ied
