### ISSUE TITLE
[Docs] Add "Open Service Mesh" to navigation menu in Meshery docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1403]
**Current State:**
Open Service Mesh (OSM) is a service mesh supported by Meshery. A new page documenting the Meshery adapter for OSM has been created - https://meshery.layer5.io/docs/service-meshes/adapters/osm

**Desired State:**
An entry for this service mesh should be added to the navigation menu.

<img width="303" alt="Screen Shot 2020-08-16 at 2 24 00 PM" src="https://user-images.githubusercontent.com/7570704/90342276-7788d500-dfcc-11ea-96e3-cc0fb637db69.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by badta5te** [comment]
Hi, can i take this?

**Comment by PluckyPrecious** [comment]
Sure you can go ahead with it @badta5te

**Comment by badta5te** [comment]
Can you tell me what the problem is?
Trying to execute
```
make site
```
And I get an error:
```
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid YAML front matter in /Users/pavelmikhaylov/Documents/code/meshery/docs/pages/functionality/smi-conformance-capability.md
```

**Comment by leecalcote** [comment]
@KarenEfereyan FYI

@JubayerJoy do you mind having a look?

**Comment by JubayerJoy** [comment]
@badta5te, hi I am trying to reproduce this error.  I'll get back to you soon.

Meanwhile, you can make changes and open a PR. After each commit, wait a bit then netlify bot will deploy a version with changes you've made.

**Comment by leecalcote** [comment]
@badta5te this bug is causing your issue - https://github.com/meshery/meshery/issues/1421
