### ISSUE TITLE
[Docs] Add link to First Timers’ Welcome Guide in Project page 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1405]
**Current State:**
The Layer5 [projects page](https://meshery.layer5.io/docs/project) in the Meshery does not have a link to the [first timers' welcome guide](https://docs.google.com/document/d/1ZLfRf4BOlRkz8wEBr7hDtkQH0MGfr43kXcrP6QfDac0/edit).

**Desired State:**
First-time open source contributors should be encouraged and shown a link to this document.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by nuggetnchill** [comment]
[first timers' welcome guide ](https://docs.google.com/document/d/1ZLfRf4BOlRkz8wEBr7hDtkQH0MGfr43kXcrP6QfDac0/edit) requires access for me when I clicked on it

**Comment by leecalcote** [comment]
@nuggetnchill, oops. I linked to the wrong document. Here is the document that I meant to link to - https://docs.google.com/document/d/1tpg2sLxirozNt3Ofr3GdM002f9rExp74EqrsGZBU710/edit

**Comment by Kennygrace** [comment]
I would like to take this up

**Comment by leecalcote** [comment]
Thanks, @Kennygrace 👍

**Comment by leecalcote** [comment]
Ooh, wait. @seun-beta did not reference or have this issue assigned before working on it here already - https://github.com/meshery/meshery/pull/1418

**Comment by Kennygrace** [comment]
Does that mean it's no longer available?

**Comment by PluckyPrecious** [comment]
Hi @Kennygrace yes it’s no longer available for now, you could check other issues.💪🏽

**Comment by leecalcote** [comment]
@seun-beta, will you land a comment here signaling that you will pick up this issue (this way, it can be assigned to you).

**Comment by seun-beta** [comment]
@leecalcote  I am still on it. @PluckyPrecious is putting me through on it.
