### ISSUE TITLE
[Docs] Add link to Layer5 Community Welcome Guide in Project page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1406]
**Current State:**
The Layer5 [projects page](https://meshery.layer5.io/docs/project) in the Meshery does not have a link to the [Layer5 Community Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit).

**Desired State:**
First-time open source contributors should be encouraged and shown a link to this document.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Obizim** [comment]
I want to take this up

**Comment by PluckyPrecious** [comment]
Please go ahead @Obizim 💪🏽
