### ISSUE TITLE
[Docs] Add descriptions of load generators in Meshery Performance Management page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1407]
**Current State:**
The [Performance Management page](https://meshery.layer5.io/docs/functionality/performance-management) does not have a description of the three supported load generators:

- fortio
- wrk2
- Nighthawk

**Desired State:**
This page should describe the fact that Meshery supports these load generators and have a short description of what each load generator is. See the [service mesh landscape](https://layer5.io/landscape) for some of these details and [performance management design documents](https://drive.google.com/drive/u/0/folders/1lzL9SwcsEaYY8hT1I4nC5M91o2awgr9G).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Obizim** [comment]
I don't see where to get the details of the three supported load generators

**Comment by Annysah** [comment]
I would love to work on this, I would need a community member guidance too.

**Comment by PluckyPrecious** [comment]
Hi @Annysah sure you can go ahead with it, do go over to the #first-timers workspace and ask questions.😊

**Comment by PluckyPrecious** [comment]
Hi @Annysah situation report please, still up for this?
