### ISSUE TITLE
[Docs] Table of Supported Platforms shows broken links

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1408]
**Current State:**
The Supported Platforms page has missing images (broken links) of each of the platform's icons.

<img width="1067" alt="Screen Shot 2020-08-16 at 2 42 10 PM" src="https://user-images.githubusercontent.com/7570704/90342549-ba4bac80-dfce-11ea-9e9f-052b8b0f00d8.png">

**Desired State:**
Icons of each platform should be shown. Each of the links should be fixed.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by JamieTaylor94** [comment]
I'll pick this up if that's ok?
