### ISSUE TITLE
[Docs] Remove example of `brew upgrade mesheryctl` output

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1409]
**Current State:**
The [Quick Start guide](https://meshery.layer5.io/docs/installation/) provides sample output of a successful upgrade of `mesheryctl`. This sample log output is unnecessary and clutters the documentation.

**Desired State:**
The Quick Start guide should not have this section included in the docs.

**Screenshot**
<img width="1397" alt="Screen Shot 2020-08-16 at 2 48 45 PM" src="https://user-images.githubusercontent.com/7570704/90342693-def45400-dfcf-11ea-843f-a08c1e6f0dc3.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
@lee can I take this up?

**Comment by kushthedude** [comment]
Hey @KarenEfereyan, Please go ahead!

**Comment by KarenEfereyan** [comment]
@kushthedude I am on it. Thank you

**Comment by KarenEfereyan** [comment]
It does not matter that it was not assigned to me, right?

**Comment by ghost** [comment]
Im done Here is my PR https://github.com/meshery/meshery/pull/1412
Oh, @kushthedude you've merged it already. Thank you sir

**Comment by kushthedude** [comment]
> It does not matter that it was not assigned to me, right?

Oops my bad, Anyway you were quite fast to fix this 🚀 !
Thanks!
