### ISSUE TITLE
Move to Gorilla/mux for server routing

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1410]
**Current Behavior**

We are using **HTTProuter** for routing & serving our UI pages.

**Desired Behavior**

Use **Gorilla/mux** for server routing, remove complex network logic from handlers and use mux UI handlers to server SSR next UI bundle.

---
**Resources**

Read [this](https://www.nicolasmerouze.com/guide-routers-golang). article for a brief Comparision between HTTProuter & gorilla/mux.

**Comment by kalradev** [comment]
Hey!!

Can I work in this
@kushthedude

**Comment by kushthedude** [comment]
Sure go ahead!
