### ISSUE TITLE
[UI] Use dropdown+text field component in performance preference duration field

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1411]
**Current Behavior**

We have a text field for duration attribute of performance preferences in the UI, where as in the performance dashboard the field has been changed to dropdown+text.

**Desired Behavior**

Use dropdown+text field component in performance preference duration field

---
**Resources**

See PR https://github.com/layer5io/meshery/pull/1244/files

**Comment by leecalcote** [comment]
@PmcFizz this is a fantastic issue for you to tackle.

**Comment by PmcFizz** [comment]
Yes  ok  I will fix it quickly.

**Comment by leecalcote** [comment]
Awesome! Thank you, @PmcFizz

**Comment by leecalcote** [comment]
To help clarify this feature request (small UX improvement), @kushthedude, will you provide a screenshot that highlights the desired change?
