### ISSUE TITLE
Add tooltips for navigation menu items while in minimised state

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1413]
**Current Behavior**

When you minimise the sidebar, there is no tooltip for navbar items to let know which option is what.

**Desired Behavior**

Add tooltips for navigation menu items while in minimised state

---
**Resources**

- https://material-ui.com/components/tooltips/
- https://material-ui.com/api/tooltip/

**Comment by kalradev** [comment]
If no one is working on this, please assign it to me.
