### ISSUE TITLE
[Docs] SMI Conformance functionality page causing build errors

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1421]
**Description**
The recently created [SMI Conformance](https://github.com/layer5io/meshery/blob/master/docs/pages/functionality/smi-conformance-capability.md) functionality page is causing Jekyll build errors.

**Expected Behavior**
1) The front matter of this page needs to have a colon (:) after each key, like so:

```
---
layout: page
title SMI: Conformance Capability
permalink: functionality/smi-conformance-capability
type: functionality
---
```

2) A missing `/` has the permalink for the page showing in the wrong place. A forward slash is needed after "functionality".

3) Rename filename of this page to `smi-conformance.md` and update the permalink to `functionality/smi-conformance`

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by kalradev** [comment]
I want to start with this.

**Comment by leecalcote** [comment]
@kalradev, excellent!
