### ISSUE TITLE
[Docs] Align Logos in Run Meshery Table

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery#1436]
**Current State:**
The Logos in the Run Meshery table of the readme Isn’t well aligned 

**Desired State:**
Remove this “-“ and align the logo 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by 7daytheory** [comment]
I'll do it

**Comment by PluckyPrecious** [comment]
Hi @7daytheory if you can't seem to find your way around it, do well to hop on the [Community Slack](http://slack.meshery.io/) someone will gladly give you a hand. 😃

**Comment by 7daytheory** [comment]
> Hi @7daytheory if you can't seem to find your way around it, do well to hop on the [Community Slack](http://slack.meshery.io/) someone will gladly give you a hand.

Sorry, I have no issue with this it's pretty simple. I got sick as hell (not covid) and was not on top of my stuff.

If you've moved on that's fine - if not I can see what I can get done tonight without rushing

**Comment by leecalcote** [comment]
@7daytheory sounds great. Coincidentally, I juuust made a duplicate issue a little earlier describing a similar request. As you dig in here, do you mind considering the points described in issue https://github.com/meshery/meshery/issues/1476?

**Comment by leecalcote** [comment]
Seeing you comment made me realize that the new issue is a duplicate.

**Comment by 7daytheory** [comment]
> @7daytheory sounds great. Coincidentally, I juuust made a duplicate issue a little earlier describing a similar request. As you dig in here, do you mind considering the points described in issue https://github.com/meshery/meshery/issues/1476?

Has someone claimed the new duplicate issue?

**Comment by leecalcote** [comment]
@7daytheory no, sir. It’s all you.

**Comment by 7daytheory** [comment]
Kk
