### ISSUE TITLE
[Docs] Add Community Calendar to Docs footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1437]
**Current Behavior**
The current set of horizontal social buttons on the layer5.io site does not have a button for the community calendar.

**Desired Behavior**
In the same fashion as https://github.com/layer5io/layer5/issues/621, add the existing button for the community calendar from the layer5.io/meshery page to the site's footer.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by JubayerJoy** [comment]
I am working on it 💪

**Comment by leecalcote** [comment]
Thank you, sir.
