### ISSUE TITLE
Bug in login logout flow

### ISSUE THREAD

**Issue by kalradev** [layer5io/meshery#1442]
**Description**
Opened localhost:9081
It redirected me to localhost:9081/providers then oauth login selected github then I got logged in.
After logging in I logged out and it redirected me to localhost:9081/provider/ I selected meshery as provider
I thought it will redirect me to a login screen but there was no login screen
I thought I am logged in, but my kube config was not there. Also, get token (button in profile section) too was not working

**Expected Behavior**
After Selecting Meshery there should be a login screen

**Environment:**
 - Browser: Chrome, Firefox

**Screenshots**
![Screenshot from 2020-08-21 21-35-41](https://user-images.githubusercontent.com/32228313/90911380-87525000-e3f6-11ea-9a12-fc1898e7f8a1.png)
![Screenshot from 2020-08-21 21-35-45](https://user-images.githubusercontent.com/32228313/90911385-89b4aa00-e3f6-11ea-9285-87bd803d8663.png)
![Screenshot from 2020-08-21 21-35-52](https://user-images.githubusercontent.com/32228313/90911392-8c170400-e3f6-11ea-8cea-b3fea867b359.png)
![Screenshot from 2020-08-21 21-35-57](https://user-images.githubusercontent.com/32228313/90911399-8de0c780-e3f6-11ea-9558-ec6cf487921a.png)
![Screenshot from 2020-08-21 21-36-05](https://user-images.githubusercontent.com/32228313/90911403-90432180-e3f6-11ea-88a6-09dabcf9c5b0.png)
![Screenshot from 2020-08-21 21-36-28](https://user-images.githubusercontent.com/32228313/90911411-920ce500-e3f6-11ea-8b33-2a51ff119a39.png)

@leecalcote @kushthedude

**Comment by kushthedude** [comment]
There is no cookie token stored because you have used remote provider,
remote provider has jwt token stored on the remote server which you van
only see in logs once. Session cookie authentication is only present in the
local provider.
Coming to the '/' redirection, we cant redirect to login page as the user
may want to change the provider to remote, local or more which we will soon
be providing.

**Comment by kushthedude** [comment]
About the security issue, yes you are correct we do need to fix this in the
hydra jwt.

**Comment by KarenEfereyan** [comment]
@kalradev @kushthedude let me see if I can replicate the issue?
