### ISSUE TITLE
[Docs] Document adapter naming, display name, and navigation structure

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1444]
**Current State:**

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@kumarabd @anirudhjain75 progress to report here?

**Comment by KarenEfereyan** [comment]
@kumarabd @anirudhjain75  🤐🤐🤐🤐🤐

**Comment by kumarabd** [comment]
I guess my pr is already merged. @anirudhjain75  any tentative on the UI but getting merged?

**Comment by KarenEfereyan** [comment]
If its been merged, this issue should be closed, right?

**Comment by leecalcote** [comment]
@kumarabd this is a docs issue, requesting that you document the steps to Naming and exposing an adapter in the UI.
