### ISSUE TITLE
[Platform] Verify Meshery's compatibility with OpenShift as a supported platform

### ISSUE THREAD

**Issue by nveenjain** [layer5io/meshery#1445]
**Current Behavior**
It is listed as in-progress on ReadMe.

**Desired Behavior**
Support meshery on openshift and update the ReadMe.md

**Comment by leecalcote** [comment]
Expanding on this issue's description:

**Current Behavior**
It is listed as in-progress on ReadMe.

**Desired Behavior**
Meshery needs to be deployed on a recent version of OpenShift. 
- Using manifests, ideally, the same manifests used for vanilla Kubernetes (found in /install folder in this repo) are compatible with an OpenShift deployment. 
- Using Meshery Helm chart, confirm if any changes are needed.

Once compatibility is confirmed any deviations or platform-specific instructions to need to be documented. The Meshery readme and Meshery Docs should be updated to reflect status.

**Comment by UdokaVrede** [comment]
@LEE ok thanks, I would skip this

**Comment by hwpplayer1** [comment]
https://en.wikipedia.org/wiki/OpenShift We can start here for other Operating Systems to welcome their needs. And also here for technical details so Wikipedians can take a source our repository as an independent source as their understanding
