### ISSUE TITLE
[Docs] Add UI screenshot to UI Contributor docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1448]
**Current State:**
The [UI section of the CONTRIBUTING.md](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#ui-contribution-flow) is somewhat uninspiring. 

**Desired State:**
1. The contributing to UI section could use a screenshot of the Meshery UI
1. In addition to a screenshot in this section, the README should list Billboardjs as on one of the frontend technologies in use.

**Implementation**
1.  A screenshot of Meshery may be retrieved from https://meshery.io. Place a copy of the desired screenshot into the /ui/assets/img/readme directory in this repository.
1. List Billboardjs as one of the frontend technologies.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Kennygrace** [comment]
I'll like to take this up

**Comment by Ruth-ikegah** [comment]
Nice @Kennygrace you have been assigned to it!

**Comment by Ayushbajpai19** [comment]
I would like to contribute to the above issue, can you guide me through the process?

**Comment by Ruth-ikegah** [comment]
Hi @Ayushbajpai19 that's nice, but someone has already been assigned to this issue. Please hop in our slack channel : http://slack.meshery.io/

Let's find you another issue

**Comment by chandrashritii** [comment]
@Kennygrace Thank you for taking this up! Please let me know if you need any help in solving this issue 🎈

**Comment by PluckyPrecious** [comment]
> @Kennygrace Thank you for taking this up! Please let me know if you need any help in solving this issue 🎈

cc// @Kennygrace 😃

**Comment by pranikz** [comment]
Hey @PluckyPrecious  Will love to take this up I have a workaround for the same

**Comment by Ruth-ikegah** [comment]
That's nice of you @pranikz. @Kennygrace has been assigned to this issue but I think she might be having some trouble here. I will confirm and keep you updated about taking it up

**Comment by aditya2499** [comment]
Hi, If this is up for grab, I would like to work on it.

**Comment by PluckyPrecious** [comment]
Hi @aditya2499 do go ahead, looks like @Kennygrace might be fixed with other things.

Do join the [Meshery community](http://slack.meshery.io/) on slack to collaborate with other contributors.

**Comment by aditya2499** [comment]
Hi, 
I need to ask some clarifying doubts.
There is no assets directory under ui directory. Does the required path is docs/assets/img/readme?

**Comment by PluckyPrecious** [comment]
Hi, the required path is `ui/assets/img/readme`, you can create a new folder `assets/img/readme` under ui directory. 👍🏽

**Comment by aditya2499** [comment]
@PluckyPrecious I have opened the pull request.
