### ISSUE TITLE
[Docs] Remove the common issue heading in contributing.md

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1449]
**Current State:**

The common issue mentioned in contributing.md is not so common, it is OS-specific moreover it is seldom reproducible.

**Desired State:**

- Remove the common issues heading as it is now which makes the file look awkward.
- Add a note in this section https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#build-and-run-meshery-server about the GCC compiler to be used while building.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by tim-hanke** [comment]
I’d like to claim this issue, if available.

**Comment by kushthedude** [comment]
Yes please go ahead @tim-hanke

**Comment by Ruth-ikegah** [comment]
> I’d like to claim this issue, if available.

Nice Tim, go ahead!

**Comment by tim-hanke** [comment]
In the section to be moved: `Invalid C Headers ( Mac OS )`, it states 

> Replacing `gcc` with Clang by adding `export CC=gcc` to .bashrc / .zshrc should fix the issue.

I apologize if I'm misunderstanding this, but I am reading that section as saying the suggested fix is to use the gcc compiler, so shouldn't that say:

> Replacing Clang with gcc

If so, is this the place to change that as well?
