### ISSUE TITLE
[Docs] Move "Meshery Adapter for Open Service Mesh" from alpha to beta in Meshery README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1451]
**Current State:**
The Meshery Adapter for Open Service Mesh is listed in the alpha section of the [Supported Service Meshes](https://github.com/layer5io/meshery#supported-service-meshes) table.

**Desired State:**
The Meshery Adapter for Open Service Mesh should be listed in the beta section of the [Supported Service Meshes](https://github.com/layer5io/meshery#supported-service-meshes) table.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by hikky08** [comment]
Can I work on this

**Comment by hikky08** [comment]
Working on it

**Comment by Ruth-ikegah** [comment]
> Working on it

nice @hikky08 you have been assigned to it!

**Comment by hikky08** [comment]
> > Working on it
> 
> nice @hikky08 you have been assigned to it!

Thank you ma

**Comment by Ruth-ikegah** [comment]
> > > Working on it
> > 
> > 
> > nice @hikky08 you have been assigned to it!
> 
> Thank you ma, please check your twitter DM(I am sorry)

sure!
