### ISSUE TITLE
[Docs]Add RVM Description to Meshery Documentation

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery#1452]
**Current State:**
Windows users are having issues using Jekyll and there's no description to help with that.

**Desired State:**
Provide a description of RVM to the `set up your development environment` section of the Meshery Doc by adding this line.

`Note: Windows users can run Jekyll by following the [Windows Installation Guide](https://jekyllrb.com/docs/installation/windows/) and also install Ruby Version Manager [RVM](https://rvm.io) - a command-line tool which allows you to easily install, manage and work with multiple ruby environments on your local machine. Alternatively, if you're running Windows 10, updated to version 1903 Build 18362 or higher you can upgrade to Windows Subsystem for Linux [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)`

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by MoeRayo** [comment]
I'd like to do this

**Comment by PluckyPrecious** [comment]
Sure @MoeRayo do go ahead. 👍🏽

**Comment by MoeRayo** [comment]
![Screenshot_2020-08-25 meshery meshery](https://user-images.githubusercontent.com/48064606/91205681-db627a80-e6fd-11ea-9f7a-4d547ea85217.png)
@PluckyPrecious The above is what the site looks like currently, and i saw that some of the things i am required to add are already in the current page. so I would like to know, do I remove the current one totally and add this new one or do I add some of the things you just sent and reconstruct it?

**Comment by PluckyPrecious** [comment]
Good question. @MoeRayo 😊 This issue is to add an extra note for Windows users, as Jekyll doesn’t officially support windows. It will help guide them on the necessary step to follow during installation specifically for windows in order to have it run on their local machine. Please leave the current one as it is, you can add the additional lines right after *Jekyll Docs* .👍🏽
