### ISSUE TITLE
[Docs: UI] Fix social footer bar

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1454]
**Description**

The social icons in the footer bar are not properly aligned.

**Expected Behavior**

The social icons should be properly aligned and visible.

**Screenshots**
![Screenshot_2020-08-25 Meshery Documentation](https://user-images.githubusercontent.com/34476976/91177292-1b772c80-e701-11ea-8488-c7fa794bdec3.png)

**Environment:**
 - OS: Windows 10
 - Browser: Firefox
 - Device: Laptop

---
**To Reproduce**
1. Go to 'https://meshery.layer5.io/docs'
3. Scroll down to the footer.
4. Observe the social buttons.

**Comment by MoeRayo** [comment]
Is this taken yet or can I work on it?

**Comment by Ruth-ikegah** [comment]
Sure you can @MoeRayo assigned you to it!

**Comment by oyinmi** [comment]
Is this taken already?

**Comment by PluckyPrecious** [comment]
Hey @oyinmi yes it is, do check other issues. 👍🏽

**Comment by PluckyPrecious** [comment]
> Is this taken already?

Hola! @oyinmi I found one for you to get your hand on [here](https://github.com/layer5io/service-mesh-performance/issues/102)

**Comment by oyinmi** [comment]
@PluckyPrecious thank you.

**Comment by PluckyPrecious** [comment]
Issue fixed, I'll close now.
