### ISSUE TITLE
[UI] Notification board should close when notification is cleared

### ISSUE THREAD

**Issue by kalradev** [layer5io/meshery#1459]
**Current Behavior**

![Screenshot from 2020-08-25 23-23-40](https://user-images.githubusercontent.com/32228313/91209908-0c58a480-e72a-11ea-9af1-c16e4b5d482a.png)

When notification is cleared using the clear Icon, notification board doesnot close. 

**Desired Behavior**

It should close, because there is no use for the notification board after clearing notifications. 
User experience would be better this way.

**Comment by leecalcote** [comment]
Thanks for documenting this @kalradev.

**Comment by PmcFizz** [comment]
This‘s a good suggest. I will finish it .
@kalradev @leecalcote

**Comment by leecalcote** [comment]
Thank you, sir. @PmcFizz 👍
