### ISSUE TITLE
Generate cluster access for public clouds(GKE/EKS) via mesheryctl 

### ISSUE THREAD

**Issue by sakomws** [layer5io/meshery#146]
**Is your feature request related to a problem? Please describe.**
It would be nice via mesheryctl generate cluster access for public clouds:
```
https://github.com/layer5io/meshery/issues/102
```
**Describe the solution you'd like**
Need to translate this shell script to be part of mesheryctl:
```
https://github.com/layer5io/meshery/issues/102#issuecomment-491261460
```

**Describe alternatives you've considered**
Depending on use case, we can consider to use existing service account.

**Additional context**
N/A

**Comment by leecalcote** [comment]
@sakomws we should be good to close this with the addition of https://meshery.layer5.io/docs/installation#platform-gke-.

**Comment by leecalcote** [comment]
Ideally, this is `mesheryctl config generate -p <platform-name>`.

**Comment by leecalcote** [comment]
@jesuslerma fyi - https://github.com/meshery/meshery/issues/112#issuecomment-549596272

**Comment by chandresh-pancholi** [comment]
@leecalcote could you please provide quick starting point?

**Comment by jesuslerma** [comment]
The idea is to migrate this script: https://github.com/meshery/meshery/blob/master/docs/pages/installation/generate_kubeconfig_gke.sh

to go.

**Comment by leecalcote** [comment]
@codingmaths The same thing goes for users running Meshery against a Kubernetes cluster running in minikube. It would be nice if they could use mesheryctl  to generate the appropriate kubeconfig - https://meshery.meshery.io/docs/installation/minikube#2-generate-config-file

**Comment by kanishkarj** [comment]
@leecalcote, I would like to work on this if no one has picked it up yet. Few things here:

* What should be the structure of the command? `mesheryctl system config gke/eks/minikube` would that work?
* Could we just add the script to the Mesheryctl folder and then simple call the script with the corresponding arguments?
* When we execute the command we want Mesheryctl to update Meshery with the generated config right?

**Comment by leecalcote** [comment]
Great questions:

1. Thinking. @nitishm, did we cover this yet in the Meshery CLI design spec? 
2. Ideally not, but this could be a first iteration. Ideally, this script is converted to go. 
3. Yes, correct.

**Comment by nitishm** [comment]
> Great questions:
> 
> 
> 
> 1. Thinking. @nitishm, did we cover this yet in the Meshery CLI design spec? 
> 
> 2. Ideally not, but this could be a first iteration. Ideally, this script is converted to go. 
> 
> 3. Yes, correct. 

No we did not but sounds like a great idea.
