### ISSUE TITLE
Fix Welcome Bot Celebration Stargazers Link

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery#1467]
**Current Behavior**
Not displaying a link for contributors to click and star the project.
![welcome msg](https://user-images.githubusercontent.com/59584014/91340126-62335800-e7cf-11ea-9de9-1533cef696ba.PNG)

**Desired Behavior**
This section `[star the project](../stargazers)` needs to be clickable to direct contributors.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by MrJDavidT** [comment]
May I try to contribute?

**Comment by leecalcote** [comment]
@MrJDavidT that would be excellent. Jump into the community Slack workspace, if you get snagged or if you'd simply like to get more involved in the projects here: http://slack.meshery.io. 👍

**Comment by MrJDavidT** [comment]
Thank you. I will head over there.

**Comment by PluckyPrecious** [comment]
Hellos @MrJDavidT, how is it coming up? 😊

**Comment by PluckyPrecious** [comment]
Hello, @MrJDavidT thank you for your interest in contributing to Meshery project, this issue has been addressed by another contributor, kindly check out other issues in the repo you'll surely find one to pick up. 👍🏽 

I'll close this now.
