### ISSUE TITLE
[Docs] List SMI Conformance as a feature of Kuma adapter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1474]
**Current State:**
The documentation for the [Meshery adapter for Kuma](https://meshery.layer5.io/docs/service-meshes/adapters/kuma) is missing a list and description of all of the operations that it supports. 

**Desired State:**
Another supported feature of the adapter for Kuma is SMI Conformance - https://meshery.layer5.io/docs/functionality/smi-conformance. This needs to be highlighted as  functionality in each of the adapter docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@KarenEfereyan this might be of interest considering your prior work in this area.

**Comment by KarenEfereyan** [comment]
@leecalcote could you please assign it to me? Ill look into it later today

**Comment by leecalcote** [comment]
Hi @KarenEfereyan, heads-up, the Istio and Open Service Mesh adapters support the same operation.

**Comment by KarenEfereyan** [comment]
@Lee
Just under the lifecycle management, I would need to add the feature of smi conformance capability as one that kuma adapter supports, right?

**Comment by KarenEfereyan** [comment]
> Hi @KarenEfereyan, heads-up, the Istio and Open Service Mesh adapters support the same operation (need the same documentation update).

Are these to be treated as separate issues?. I am also done with the one for the Istio Adapter but what Issue number would that be?
