### ISSUE TITLE
[Docs] Improve legibility of supported platforms in Meshery README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1476]
**Description**
[The table ](https://github.com/layer5io/meshery#run-meshery) in the Meshery README.md containing supported platforms has a hyphen to indent each type of platform under its respective category. The hyphens are slightly distracting, making the table less legible.

**Expected Behavior**
Platforms listed under each category should be indented, but using whitespace (`&nbsp;`) or tabs (`&#9;`) not hyphens.

**Screenshots**
<img width="662" alt="Screen Shot 2020-08-28 at 4 41 14 PM" src="https://user-images.githubusercontent.com/7570704/91617532-ddbb1380-e94d-11ea-9aa1-3bffa79d355b.png">

**Comment by Kennygrace** [comment]
I'll like to take this up

**Comment by Ruth-ikegah** [comment]
Sure @Kennygrace . It has been assigned to you

**Comment by leecalcote** [comment]
Gasp! Oh, no. I created this issue not realizing that it is a duplicate of #1436. Another contributor previously took up that issue, and is toiling on it now. 

@Kennygrace, could I ask that we get you into another issue so as to avoid overlapping effort?

**Comment by Kennygrace** [comment]
Okay then

**Comment by KarenEfereyan** [comment]
@leecalcote how about we close this issue? Just so it doesn't cause any distractions for new contributors

**Comment by leecalcote** [comment]
Sounds real good, @KarenEfereyan.
