### ISSUE TITLE
[Docs: UI] Fix Mobile Display

### ISSUE THREAD

**Issue by akashgp09** [layer5io/meshery#1479]
**Description**

The mobile page has issues. Please help to make the display on mobiles work.

**Expected Behavior**

No extra spacing should be there on the right side and at the bottom.

**Screenshots**

<img src="https://i.imgur.com/7Rctb9U.jpg" height="550" >

**Environment:**
- OS: Android/IOS
- Browser:  Chrome  
- Device:  Samsung S5,IPhone 8,Iphone X 

---
**To Reproduce**
1. Go to 'https://meshery.layer5.io/docs'
2. View the website on Screen size < 768px
3. Observe a scroll bar is appeared below

**Comment by NorbertLuszkiewicz** [comment]
The problem is div with it class row on footer

**Comment by KarenEfereyan** [comment]
@akashgp09 could I please work on this issue?

**Comment by KarenEfereyan** [comment]
@NorbertLuszkiewicz I can't figure out which of these files I will need to make my editing in. I am very new to jekyll. Can you put me through on that?
