### ISSUE TITLE
Iincorrect link to slack chat room on contributing.md [Docs]

### ISSUE THREAD

**Issue by UdokaVrede** [layer5io/meshery#1483]
**Current State:**
The link to the slack channel on contributing.md currently leads to the github 404 page as shown below:
![issue](https://user-images.githubusercontent.com/63649352/91631986-98dabf80-e9d5-11ea-99c4-a1001f5681d1.png)
![cause](https://user-images.githubusercontent.com/63649352/91632051-17cff800-e9d6-11ea-9797-2805ec777b46.png)

**Desired State:**
The link should lead to the slack channel of layer5.io

---
**Contributor Resources**
- http://slack.layer5.io/

- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by akashgp09** [comment]
I would like to work on this issue.

**Comment by UdokaVrede** [comment]
@PluckyPrecious please look this up

**Comment by PluckyPrecious** [comment]
Nice one @UdokaVrede 👍🏽
