### ISSUE TITLE
[Docs] List SMI Conformance as a feature of the adapter for Open Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1485]
**Current State:**
The documentation for the [Meshery adapter for Open Service Mesh](https://meshery.layer5.io/docs/service-meshes/adapters/osm) is missing a list and description of all of the operations that it supports. 

**Desired State:**
Another supported feature of the adapter for Kuma is SMI Conformance - https://meshery.layer5.io/docs/functionality/smi-conformance. This needs to be highlighted as  functionality in each of the adapter docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Tagging @KarenEfereyan

**Comment by was-coder** [comment]
I will like to take on this issue @leecalcote but i need more explanation on it

**Comment by leecalcote** [comment]
@was-coder here’s an example that should help - https://github.com/meshery/meshery/pull/1492

**Comment by was-coder** [comment]
@leecalcote and @Ruth-ikegah  i already got the explanation, can i be assigned the issue

**Comment by leecalcote** [comment]
Sounds great, @was-coder
