### ISSUE TITLE
[Docs] List SMI Conformance as a feature of the adapter for Istio

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1486]
**Current State:**
The documentation for the [Meshery adapter for Istio](https://meshery.layer5.io/docs/service-meshes/adapters/istio) is missing a list and description of all of the operations that it supports. 

**Desired State:**
Another supported feature of the adapter for Kuma is SMI Conformance - https://meshery.layer5.io/docs/functionality/smi-conformance. This needs to be highlighted as  functionality in each of the adapter docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Tagging @KarenEfereyan

**Comment by lolyparty** [comment]
Hey, @KarenEfereyan are you on this?

**Comment by KarenEfereyan** [comment]
Yes but @lolyparty you Can go on

**Comment by KarenEfereyan** [comment]
I'm so sorry @lolyparty . I have a friend who has never contributed to open source before and I think this is a fairly simple issue for him. Do you mind?

**Comment by KarenEfereyan** [comment]
@EmmanuelTheCoder here is the issue

**Comment by lolyparty** [comment]
Ok no problem

**Comment by chandrashritii** [comment]
@EmmanuelTheCoder Please signal if you want to be assigned to this issue

**Comment by KarenEfereyan** [comment]
Nevermind @chandrashritii ill do it.  I think @EmmanuelTheCoder is having some delays. Ill try to reach out to him and there will be more issues in the future. This issue has dragged on for too long

**Comment by lolyparty** [comment]
@KarenEfereyan I'd still like to do it.

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan I'd still like to do it.

Oh no. I totally forgot @lolyparty I just made a PR. I'm so sorry. I'll make it up to you. Why are you still awake though?

**Comment by lolyparty** [comment]
Ok, No problem. Scrolling through Twitter lol.

**Comment by KarenEfereyan** [comment]
Scrolling through twitter. @leecalcote @lolyparty needs issues to tackle. She's here scrolling through twitter. Hahaha

**Comment by KarenEfereyan** [comment]
@lolyparty i tagged you to an issue. Watch out for it
