### ISSUE TITLE
[Docs] List supported operations for the Meshery adapter for Maesh

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1487]
**Description**

The operations supported by the adapter for Maesh are not listed in its [documentation](https://meshery.layer5.io/docs/service-meshes/adapters/maesh). Add the heading `Sample Applications` and include a list of the supported operations, with a small explanation for each. The operations can be found listed [here.](https://github.com/layer5io/meshery-maesh/blob/master/maesh/supported_ops.go); (lines 38-73). Look out for the following line: `opType: meshes.OpCategory_SAMPLE_APPLICATION`. This means that the operation listed is a sample application.

---

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by was-coder** [comment]
@Ruth-ikegah @leecalcote i want to take up this challenge

**Comment by was-coder** [comment]
@chandrashritii and @leecalcote i would like to take up this challenge

**Comment by chandrashritii** [comment]
@was-coder Sure. Go ahead 🎈
