### ISSUE TITLE
[Docs] List supported operations for the Meshery adapter for Linkerd

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1488]
**Current State:**

The operations supported by the adapter for Linkerd are not listed in its [documentation](https://meshery.layer5.io/docs/service-meshes/adapters/linkerd). 

**Desired State:**

Under the heading `Sample Applications` and include a list of the supported operations, with a small explanation for each. The operations can be found listed [here](https://github.com/layer5io/meshery-linkerd/blob/master/linkerd/supported_ops.go); (lines 37-64). Look out for the following line: `opType: meshes.OpCategory_SAMPLE_APPLICATION`. This means that the operation listed is a sample application.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by lolyparty** [comment]
Hey, I'd like to work on this issue

**Comment by chandrashritii** [comment]
Thanks for jumping in here @lolyparty. Sure. Go ahead!

**Comment by lolyparty** [comment]
I'm to add a list of supported operations with their names right? Also can I get a link to where I can read on the operations. Thanks  @chandrashritii

**Comment by leecalcote** [comment]
> I'm to add a list of supported operations with their names right? Also can I get a link to where I can read on the operations. Thanks @chandrashritii

@lolyparty see the link in the Desired State section in the issue description.

**Comment by lolyparty** [comment]
> > I'm to add a list of supported operations with their names right? Also, can I get a link to where I can read on the operations? Thanks @chandrashritii
> 
> @lolyparty see the link in the Desired State section in the issue description.

Ok thank you

**Comment by leecalcote** [comment]
@lolyparty you will want to try building the site with Ruby 2.6.7. You might want to use RVM (https://rvm.io) as a tool to help install different versions of Ruby.

**Comment by lolyparty** [comment]
> @lolyparty you will want to try building the site with Ruby 2.6.7. You might want to use RVM (https://rvm.io) as a tool to help install different versions of Ruby.

Ok, thank you. I'll try that.
