### ISSUE TITLE
[Docs] Update the list of supported operations for the Meshery adapter for Citrix (CPX)

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1489]
**Current State:**

The operations supported by the adapter for Linkerd are not listed in its [documentation](https://meshery.layer5.io/docs/service-meshes/adapters/cpx).

**Desired State:**

Under the heading `Sample Applications` and include a list of the supported operations, with a small explanation for each. The operations can be found listed [here](https://github.com/layer5io/meshery-cpx/blob/master/cpx/supported_ops.go); (lines 47-124). Look out for the following line: `opType: meshes.OpCategory_SAMPLE_APPLICATION`. This means that the operation listed is a sample application.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
@chandrashritii , hello, I want to work on this.

**Comment by chandrashritii** [comment]
@KarenEfereyan Sure. Go ahead!

**Comment by leecalcote** [comment]
Karen, given the consistency of your contributions, you’ve been invited to join the “Mesheryio” org on GitHub (very cool). Now that your user is a member of the org, your user account has permission to triage issues, including management of any issues’ assignees. If you see an issue with the help-wanted label that is unassigned, you’re most welcome to self-assign. 

Kudos on your new membership. Thank you for being an engaged and impactful contributor. 👍
