### ISSUE TITLE
[Docs]  List supported operations for the Meshery adapter for Octarine

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1490]
**Current State:**

The operations supported by the adapter for Linkerd are not listed in its [documentation](https://meshery.layer5.io/docs/service-meshes/adapters/octarine/octarine).

**Desired State:**

Under the heading `Sample Applications` and include a list of the supported operations, with a small explanation for each. The operations can be found listed [here](https://github.com/layer5io/meshery-octarine/blob/master/octarine/supported_ops.go); (lines 34-54). Look out for the following line: `opType: meshes.OpCategory_SAMPLE_APPLICATION`. This means that the operation listed is a sample application.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
@chandrashritii can I use this issue as a reference for the tutorial? The one I spoke about on Slack? I think its fairly simple and easy to understand.

**Comment by chandrashritii** [comment]
@KarenEfereyan Thank you for taking up the initiative to make a tutorial 🎈 
Considering that the tutorial is majorly on using Git (CLI and desktop app), and demonstrating how to sign off on your commits, the issue referred can be a relatively simple one. Regardless, I would suggest you take up something a bit more UI related because that'll be easier to showcase and will be more interesting than adding a few dry lines of documentation. It'll also be another chance to showcase the [meshery](https://meshery.io/), [layer5](https://layer5.io/) or the [smp](https://smp-spec.io/) sites. I'll make sure to point you to a few good issues on Slack.

**Comment by was-coder** [comment]
@chandrashritii I want to take up this issue

**Comment by was-coder** [comment]
@chandrashritii @Ruth-ikegah I want to take up this issue

**Comment by KarenEfereyan** [comment]
> @chandrashritii @Ruth-ikegah I want to take up this issue

@was-coder you can go ahead. Let us know if you have issues. Be sure to check out the contributions guide
