### ISSUE TITLE
[Docs] List supported operations for the Meshery adapter for Tanzu

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1491]
**Current State:**

The operations supported by the adapter for Linkerd are not listed in its [documentation](https://meshery.layer5.io/docs/service-meshes/adapters/tanzu-sm).

**Desired State:**

Under the heading `Sample Applications` and include a list of the supported operations, with a small explanation for each. The operations can be found listed [here](https://github.com/layer5io/meshery-tanzu-sm/blob/master/nsx-sm/supported_ops.go); (lines 47-124). Look out for the following line: `opType: meshes.OpCategory_SAMPLE_APPLICATION`. This means that the operation listed is a sample application.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Kennygrace** [comment]
I'll like to take this up

**Comment by KarenEfereyan** [comment]
> I'll like to take this up

Yippie.

**Comment by chandrashritii** [comment]
Sure @Kennygrace Go ahead 🎈

**Comment by PluckyPrecious** [comment]
Hey @chandrashritii i think you meant operations supported by the adapter for Tanzu are not listed.
