### ISSUE TITLE
[Backend]: Not able to ping GKE clusters

### ISSUE THREAD

**Issue by kalradev** [layer5io/meshery#1501]
**Description**
When a cluster is hosted on GKE, kubernetes services by Google. The server is not able to create a Client set and because of which it is not able to ping the cluster.

**Expected Behavior**
It should be able to ping

**Screenshots**

![no-ping](https://user-images.githubusercontent.com/32228313/91741571-87aad200-ebd2-11ea-8405-5e1915fba838.png)

---
[Optional] **To Reproduce**
1. Create a GKE cluster
2. Open the config with meshery
3. It will show an error not able to ping kubernetes 

[Optional] **Additional Context**
Error in logs is
```ERRO[0067] unable to create client set: No Auth Provider found for name "gcp"```

**Comment by leecalcote** [comment]
@kalradev did you run this? ` $ mesheryctl system config gke --token <PATH TO TOKEN>` from https://meshery.layer5.io/docs/installation/platforms/gke?

**Comment by kalradev** [comment]
No, Thanks for this. I thought this was an issue. I also found https://github.com/kubernetes/client-go/issues/242 related to this.

I am closing this.
