### ISSUE TITLE
[Docs] Update Consul version to 1.8.2, and possibly other minor fix

### ISSUE THREAD

**Issue by mgfeller** [layer5io/meshery#1504]
**Current State:**

The current version in the docs is v1.5.

Also, I think the sentence "The SMI adapter for Kuma can also be installed using Meshery." in https://meshery.layer5.io/docs/service-meshes/adapters/consul should be removed, as it concerns the Kuma adapter.

**Desired State:**

The version of Consul in the Consul adapter has recently been upgraded to 1.8

This should be reflected in these documents:

* https://meshery.layer5.io/docs/service-meshes/adapters/consul
* https://meshery.layer5.io/docs/architecture/adapters

The sentence mentioned above should be removed from the Consul document.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Rex739** [comment]
i want to work on this

**Comment by Ruth-ikegah** [comment]
Nice @Rex739 
@mgfeller he can go-ahead, right?

**Comment by mgfeller** [comment]
yes, @Ruth-ikegah. 
thank you @Rex739!

**Comment by Rex739** [comment]
![Screen Shot 2020-09-02 at 12 40 42 PM](https://user-images.githubusercontent.com/54443717/91976873-918b1d00-ed19-11ea-9389-d883dc86c304.png)
@mgfeller i couldn't locate the file path for this in the repo

**Comment by mgfeller** [comment]
Hi @Rex739, it is https://github.com/meshery/meshery/blob/master/docs/pages/service-meshes/adapters.md, and as you can see it is created based on the information from the individual adapter pages.

**Comment by Rex739** [comment]
oh i understand now
