### ISSUE TITLE
[Docs] Supported platforms should be alphabetically listed, grouped and indented by category

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1521]
**Current State:**
Items in the list of supported platforms should be alphabetically listed, grouped and indented by category.

<img width="778" alt="Screen Shot 2020-09-03 at 5 47 58 AM" src="https://user-images.githubusercontent.com/7570704/92105870-2557fa00-eda9-11ea-809c-b1b79ec02afb.png">

**Desired State:**
Each item under a platform category should be indented like the same supported platforms table in Meshery's main [README.md](https://github.com/layer5io/meshery#run-meshery)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by NorbertLuszkiewicz** [comment]
Hey I would love to tackle this one, but I have one question, can you send me where this file is

**Comment by Josephchinedu** [comment]
i'll love to tackle this

**Comment by iambami** [comment]
I'll love to do this

**Comment by leecalcote** [comment]
Thanks all. @NorbertLuszkiewicz given that you messaged earliest, let’s get this one over to you. Here’s a link to the page - https://github.com/meshery/meshery/blob/master/docs/pages/installation/platforms.md

**Comment by PluckyPrecious** [comment]
@

> i'll love to tackle this

Hey @Josephchinedu i assigned you to one already yesterday https://github.com/meshery/meshery/issues/683#issue-687374328

**Comment by PluckyPrecious** [comment]
> I'll love to do this

Hey @iambami i assigned you to one as well. https://github.com/meshery/meshery/issues/713#issue-692196499
