### ISSUE TITLE
Is there no mirror image

### ISSUE THREAD

**Issue by HFeilx** [layer5io/meshery#1524]
docker pull layer5/osm-consul:stable-latest
Error response from daemon: pull access denied for layer5/osm-consul, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by FelixStarship** [comment]
meshery-osm-deployment.yaml

-----------------------------------------master--------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-osm
  name: meshery-osm
spec:
  selector:
    matchLabels:
      io.kompose.service: meshery-osm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-osm
    spec:
      serviceAccount: meshery
      containers:
      - image: meshery/osm-consul:stable-latest
        name: meshery-osm
        ports:
        - containerPort: 10010
        resources: {}
      restartPolicy: Always
status: {}
@leecalcote

**Comment by leecalcote** [comment]
@HFeilx good eye. This should be:

```
 image: meshery/meshery-osm:stable-latest
```

@Hfelix, if you would like to fix and PR this just say the word, otherwise, @mgfeller will likely pick it up.

**Comment by leecalcote** [comment]
The line in need of fixing - https://github.com/meshery/meshery/blob/master/install/deployment_yamls/k8s/meshery-osm-deployment.yaml#L25

**Comment by kushthedude** [comment]
will be fixed by #1525

**Comment by leecalcote** [comment]
@HFeilx thank you for reporting this. If you pull down the HEAD of this repo (or simply copy the deployment spec), the Meshery adapter for OSM should deploy. Please let us know if you have any trouble here.

The community of contributors loves feedback. Please jump into http://slack.meshery.io. Any input you might have is most welcome.
