### ISSUE TITLE
[UI] Design a UI for Meshery Adapter

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#1527]
https://docs.google.com/document/d/1b8JAMzr3Rntu7CudRaYv6r6ccACJONAB5t7ISCaPNuA/edit#heading=h.blih70a9hxp is the doc for Meshery Adapters. We are excited to see the designs you come up with for adapter pages.

**Comment by KarenEfereyan** [comment]
Design is calling my name.. but 
Now i better go send @jesuslerma  a message

**Comment by jesuslerma** [comment]
> Design is calling my name.. but
> Now i better go send @jesuslerma a message

Hi @KarenEfereyan how can I help?

**Comment by KarenEfereyan** [comment]
@jesuslerma I'm trying to set up my development environment
Currently on docker but it seems my windows build is nor strong enough

**Comment by PmcFizz** [comment]
@KarenEfereyan Hi  I am develop on windows。 maybe you can tell your problem that  about  docker, I can provide some help.
