### ISSUE TITLE
The validation for protocol in URL donst allow urls without top level domain.

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/meshery#1528]
**Description**

The protocol wont consider `http://172.17.0.2:31329/productpage` as a vaild URL as it lacks a top level domain.
Rather it would accept `http://172.17.0.2:31329.com/productpage`
**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/44001539/92126718-24ad7b00-ee1e-11ea-870a-43178b4d1487.png)

**Comment by kushthedude** [comment]
@dhruv0000 I guess this is an error of regex being used for URL validation, I guess this regex should work fine
```js
export const compulsoryProtocolValidUrlPattern = new RegExp('^(https?:\\/\\/)' // compulsory protocol
  + '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' // domain name
  + '((\\d{1,3}\.){3}\\d{1,3}))' // OR ip (v4) address
  + '(\\:\\d+)?(\/[-a-z\\d%_.~+]*)*' // port and path
  + '(\\?[;&a-z\\d%_.~+=-]*)?' // query string
  + '(\\#[-a-z\\d_]*)?$', 'i'); // fragment locator
```

**Comment by KarenEfereyan** [comment]
Hmmn. I'm trying to understand this issue

**Comment by KarenEfereyan** [comment]
@kushthedude are you saying this regular expression you just provided will work? If yes, where should it be added?

**Comment by dhruv0000** [comment]
I checked the regex. It should work. As for where the place where the regex is matched, you can find it in the [MesheryPerformanceComponent](https://github.com/layer5io/meshery/blob/3811ad03accd03815ec460b4189da45db5a7f7a4/ui/components/MesheryPerformanceComponent.js#L121) @KarenEfereyan

**Comment by shubhamgupta2956** [comment]
Hello everyone. @KarenEfereyan are you working on this issue? If not, can I work on it?

**Comment by KarenEfereyan** [comment]
@shubhamgupta2956 i want to but im not sure how to. You can take it up but can i learn from you?

**Comment by shubhamgupta2956** [comment]
Yeah sure @KarenEfereyan. @kushthedude, @dhruv0000 can you please assign this issue to me?

**Comment by KarenEfereyan** [comment]
@shubhamgupta2956 it to you. Can we talk on slack? So i see how you solve it

**Comment by shubhamgupta2956** [comment]
Yeah sure. I am `Shubham Gupta` on slack also :slightly_smiling_face:

**Comment by dhruv0000** [comment]
Sure @shubhamgupta2956 . Ping me on slack if you both are still confused. @shubhamgupta2956 @KarenEfereyan

**Comment by KarenEfereyan** [comment]
@dhruv0000 definitely

**Comment by KarenEfereyan** [comment]
@dhruv0000 , Shubham has been so nice. We set up a zoom call and walked me through. I totally understand what was done now. I want to set up my development environment so that I can test the changes myself.

**Comment by shubhamgupta2956** [comment]
@dhruv0000 I have made a PR #1583. Please review it :slightly_smiling_face:

**Comment by dhruv0000** [comment]
Great @shubhamgupta2956 . @KarenEfereyan you can checkout the [UI contribution flow](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md/#contributing-ui) to setup your environment.
