### ISSUE TITLE
Version all Meshery Adapters and provide version numbers to users

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1530]
**Current Behavior**
Today, users are not able to view the version of any given Meshery adapter in either the Meshery UI or `mesheryctl`.

**Desired Behavior**
1. Meshery UI should be enhanced to show to show versions of each of the adapters.
1. `mesheryctl version` should be enhanced to show versions of each of the adapters, not just the client and server.

---
**Implementation**
1. "vX.X.X" tag built into CI build and release process of each adapter.
1. Version built into the meshes.proto for each adapter to provide to meshery server.
1. Meshery server to retrieve and display the version number of each adapter when hovering over any given adapter chip in the UI.
1. Meshery server to provide adapter version via ReST endpoint.
1. `mesheryctl version` needs a new subcommand `--all`

**Acceptance Tests**
- [ ] Adapter versions are retrievable via Meshery client and server.

**Comment by KarenEfereyan** [comment]
@leecalcote what system are we currently using for testing in Meshery. Im asking so that I know how to test the changes to ensure it works as wanted
