### ISSUE TITLE
[Docs] : METHODS OF SIGNING OFF COMMITS TOO MANY

### ISSUE THREAD

**Issue by KarenEfereyan** [layer5io/meshery#1537]
**Current State:**
At this [ url](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md/#contributing), under the 'Signing Off On Commits (Developer Certificate Of Origin)', there are about 3 or 4 methods highlighted to successfully sign off a commit. It makes the doc look a little cluttered.

**Desired State:**
 Remove all but the first two methods of signing commits

Methods to Sign Off Commits that should be left:
1.  Signing off my adding your name. 
Example below: 
   Signed-off-by: Jane Smith <jane.smith@example.com>

This method is perfect for those used to Github Desktop

2. Signing off using the -s flag
Example below: 
   git commit -s -m “your commit message goes here”

This method is perfect for users of bash, or Visual Studio Integrated terminal

This keeps that section neat and easy to navigate through for beginners

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by NorbertLuszkiewicz** [comment]
Hey I would love to tackle this one

**Comment by Nikhil-Ladha** [comment]
I don't think any changes are needed here.
// @leecalcote

**Comment by KarenEfereyan** [comment]
@leecalcote what do you think? If its not necessary, you can sure close the issue

**Comment by kushthedude** [comment]
Hey @KarenEfereyan, This is a highly opinionated issue, someone would want to configure his aliases or someone may want to use vs-code or someone may want to use -s flag. We need to highlight each and every method and let contributor decide which method suits him better, removing few options from the doc will limit contributor to adjust to our preferences which sometime may quite irritating and maybe a big hurdle while making a pr or pushing a commit every time.

For example, I have vs-code but I love to use my own personalised terminal with git aliases like `gcm`, `gcb` and more. So I guess this is not needed as of now, but sometime later if Layer5 introduces it's own CLA then we can surely amend the process 😄 .

Closing the issue for now, please feel free to reopen if anyone thinks that it is required!

/cc @leecalcote
