### ISSUE TITLE
[Docs] Found "University of Engineering Jaipur in Meshery Architecture Providers"

### ISSUE THREAD

**Issue by nikita15p** [layer5io/meshery#1541]
**Current State:**
In this page [here](https://meshery.layer5.io/docs/assets/img/architecture/meshery-architecture-providers.svg), University of Engineering Jaipur in providers

**Desired State:**
Expectation is to not have college name under providers. Not sure if it came in document by mistake.
![Architecture_meshery](https://user-images.githubusercontent.com/37657012/92320090-6582db00-f03c-11ea-8bfa-1ca6d82df507.png)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
I don't think it came by mistake, it is intentional and a future plan of doing so. @leecalcote can provide more insights on this.

**Comment by nikita15p** [comment]
@Nikhil-Ladha thanks we can close this issue if this is intentional.

**Comment by leecalcote** [comment]
Thank you for highlighting this, @nikita15p. In partnership with this university, it is our intention to aid in the facilitation of their research by allowing users to sign into their Provider; to use their Provider as a persistent store for performance, configuration, and validation test results.
