### ISSUE TITLE
Move from SMPS to SMP

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1542]
**Current Behavior**
SMPS has been renamed to SMP. (https://github.com/layer5io/service-mesh-performance/pull/119)

**Desired Behavior**
Use of the SMP package and all references to "SMPS" should be updated to "SMP".

References - https://github.com/layer5io/meshery/search?q=smps&unscoped_q=smps

**Comment by KarenEfereyan** [comment]
Waow. This seems an issue delicious enough to eat. Thumbs up to you @kalradev

**Comment by leecalcote** [comment]
Acronym soup!
