### ISSUE TITLE
[Docs] Add Learn-Layer5's port number to Network Ports section of Meshery Architecture page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1543]
**Reqeuest:**
List the network port used by the `Learn Layer5` application in the Network Ports section of the Meshery Docs - https://meshery.layer5.io/docs/architecture#network-ports

_Originally posted by @leecalcote in https://github.com/layer5io/meshery-osm/pull/45#issuecomment-687906509_

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
Hmmn. And here I was searching for an open contribution

**Comment by leecalcote** [comment]
@KarenEfereyan, ha! If @kumarabd will identify the appropriate port to reserve, I think you'll be set for taking on this issue.

**Comment by KarenEfereyan** [comment]
@kumarabd your attention is needed urgently. Hahaha

**Comment by ghost** [comment]
https://meshery.meshery.io/docs/architecture#network-ports  @lee this link

**Comment by ghost** [comment]
@leecalcote  the above link seems to be a list of all the ports reserved for the current meshery adapters. So my question is this? Is Learn Meshery an application? If it is, why and how should it be assigned to a given port?

**Comment by leecalcote** [comment]
@KarenEfereyan, yes, you're right. It is an application (two, in fact) that operates a bit like an adapter. Given it's first-class support in the Meshery project (one of those applications is the tool that runs SMI Conformance), we're reserving a port number for it to help provide clarity on its operations. Here's the port number allocated to it: 10011/tcp.

**Comment by KarenEfereyan** [comment]
So can I take up this issue

**Comment by PluckyPrecious** [comment]
Sure @KarenEfereyan as Lee mentioned, you can go ahead and Update Meshery Docs .

**Comment by KarenEfereyan** [comment]
@kumarabd and @leecalcote where exactly is the learn-layer 5 repo? I need to see its port number so I can update the meshery  docs with it

**Comment by kumarabd** [comment]
> @kumarabd and @leecalcote where exactly is the learn-layer 5 repo? I need to see its port number so I can update the meshery  docs with it

https://github.com/meshery/learn-meshery @KarenEfereyan
