### ISSUE TITLE
[Docs] Broken hyperlink in Meshery's README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1544]
**Description**
Broken hyperlink in [README](https://github.com/layer5io/meshery/blob/master/README.md)

**Expected Behavior**
Text should be hyperlinked. URL should be hidden.

**Screenshots**
<img width="887" alt="Screen Shot 2020-09-07 at 6 19 55 AM" src="https://user-images.githubusercontent.com/7570704/92382647-8d248280-f0d2-11ea-9cbf-c0e399922ba6.png">

**Comment by Gregxd11** [comment]
Hey there! May I try this one? I've not done a 'real' PR before and this would be perfect for me I think :smile:

**Comment by leecalcote** [comment]
Hi @Gregxd11, yes, that'd be great. 👍
