### ISSUE TITLE
[Meshery] Docker Compose: OSM and Tanzu SM Adapters are swapping network port assignments

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1548]
**Current Behavior**
The `docker-compose.yml` file used to run Meshery and its adapters locally needs to be updated to reflect recent [network port reservations](https://meshery.layer5.io/docs/architecture#network-ports).

**Desired Behavior**
- [ ] OSM should be using 10009.
- [x] Tanzu SM should be using 10010.

**Implementation**
1. Update the OSM entry in Meshery's [docker-compose.yml](https://github.com/layer5io/meshery/blob/master/docker-compose.yaml#L62)

**Comment by leecalcote** [comment]
Hi @ratatatCat, you might like to give this one a try instead of the broken, embedded YouTube video.

**Comment by leecalcote** [comment]
Or any of these [good first issues](https://github.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+org%3Alayer5io)

**Comment by Hack-Light** [comment]
Can I take on this? @leecalcote

**Comment by PluckyPrecious** [comment]
Sure, @Hack-Light go ahead.👍🏽
