### ISSUE TITLE
[Docs] Embedded YouTube video is broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1549]
**Current State:**
On [this page](https://meshery.layer5.io/docs/service-meshes/adapters/nsm/nsm#2-vpp-icmp-application), the embedded YouTube video is broken.

<img width="765" alt="Screen Shot 2020-09-07 at 3 56 54 PM" src="https://user-images.githubusercontent.com/7570704/92416468-3dba7280-f123-11ea-9a2d-a93d5d4f53cb.png">

**Desired State:**
The Youtube video should be playable from the documentation page itself.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by ratatatCat** [comment]
Hello! I'd like to take this one if it is still available. :-)

**Comment by jomefavourite** [comment]
I guess i

> Hello! I'd like to take this one if it is still available. :-)

I guess it's still open, I wanted to do it. But my forked repository of meshery isn't updated to the latest. It still loading, Why 😥
![Screenshot (165)](https://user-images.githubusercontent.com/54733225/92420550-f0aebe80-f16b-11ea-96e6-b9d4de54ae3d.png)

**Comment by ratatatCat** [comment]
I found another one, @jomefavourite, so no worries. Hopefully, you got your forked repo to load.

**Comment by jomefavourite** [comment]
> I found another one, @jomefavourite, so no worries. Hopefully, you got your forked repo to load.

Yes, I was able get the pull updates
