### ISSUE TITLE
How can I run the Go file on my windows OS

### ISSUE THREAD

**Issue by EmmanuelTheCoder** [layer5io/meshery#1553]
I want to make my first open source contribution. I have downloaded the Go software but I find it difficult to run the go file on my windows machine (the make run-local command in the contributing.md isnt working). help!

**Comment by leecalcote** [comment]
This sounds like a job for @vijcheru! 😄

**Comment by ameyaagashe** [comment]
I can help you @EmmanuelTheCoder It is simple. Ping me on Slack.

**Comment by leecalcote** [comment]
@EmmanuelTheCoder On the off chance that you're not in the Meshery Slack, you're encouraged to join - http://slack.meshery.io. Members like @ameyaagashe and @vijcheru are most inviting and willing to assist. 👍

**Comment by PmcFizz** [comment]
@EmmanuelTheCoder  I am develop on windows platform。 you can install  `mingw`  to run makefile.  It‘s [mingw website](https://osdn.net/projects/mingw/releases/)

**Comment by KarenEfereyan** [comment]
@PmcFizz im trying to install Docker on Windows but...
![docker](https://user-images.githubusercontent.com/56835876/93026024-c55c2180-f5fa-11ea-9539-61c41491f3e7.PNG)

**Comment by PmcFizz** [comment]
> @PmcFizz im trying to install Docker on Windows but...
> ![docker](https://user-images.githubusercontent.com/56835876/93026024-c55c2180-f5fa-11ea-9539-61c41491f3e7.PNG)

This problem happend because your windows version is low of windows is not active。If you don't active window you can install 
`Docker Toolbox for Windows`  follow [this document](https://docs.docker.com/toolbox/toolbox_install_windows/).

**Comment by KarenEfereyan** [comment]
Okay. But can i ping you on slack?

**Comment by PmcFizz** [comment]
> Okay. But can i ping you on slack?

I am not usually  login [slack](https://app.slack.com/client/TDL4L01AR/D016XAUQ4TW/user_profile/U016RBNFDC3) 。If you [send email to me](pangmengchen@gmail.com), I will reply you quickly.
