### ISSUE TITLE
[Docs] Remove reverse sort from Meshery Functionality page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1561]
**Current State:**
The Meshery Functionality page has the collection of Meshery features listed in reverse alphabetical order. This is unnecessary.

**Desired State:**
The Meshery Functionality pages should be listed in alphabetical order.

**Issue Resources:**
- [Doc page](https://meshery.layer5.io/docs/functionality)
- [Code](https://github.com/layer5io/meshery/blob/master/docs/pages/functionality/index.md)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
@leecalcote I am working on this.
