### ISSUE TITLE
[Docs] Update Meshery Contributing Doc

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery#1564]
**Current State:**
The CONTRIBUTING.md is missing the caveat about Jekyll production & dev env amongst others.

**Desired State:**

[ ] Add [this caveat as seen in line 71](https://github.com/layer5io/service-mesh-performance/commit/a8af02878eb4711ccadb2e4fe01dad7b65a5b1b3#diff-6a3371457528722a734f3c51d9238c13)  to the [CONTRIBUTING.md](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow) Documentation Contribution Flow section.

[ ] Add caveat to [serve the site](https://github.com/layer5io/meshery/tree/master/docs#3-serve-the-site) section in README.

[ ] Update README [Set up your development environment](https://github.com/layer5io/meshery/tree/master/docs#1-set-up-your-development-environment) section as seen in line [49-54](https://github.com/layer5io/service-mesh-performance/commit/a8af02878eb4711ccadb2e4fe01dad7b65a5b1b3#diff-6a3371457528722a734f3c51d9238c13).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Harshita-Kanal** [comment]
Can I take it up ?

**Comment by leecalcote** [comment]
@Harshita-Kanal, yes, that would be fantastic. Thank you.
