### ISSUE TITLE
Setup Dredd Hooks agnostic API Testing 

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1579]
### Only to be addressed once we have got API Documentation ready for Meshery https://github.com/layer5io/meshery/issues/638.

We need to Dredd Hooks once we have got our API Documentation in place. Dredd not only tests our APIs but also ensures that our documentation is up-to-date with our current API state.

**What is Dredd?**

Dredd reads your API description and step by step validates whether your API implementation replies with responses as they are described in the documentation.

More information can be found here https://github.com/apiaryio/dredd

**Comment by kushthedude** [comment]
^^ @leecalcote

**Comment by leecalcote** [comment]
Use of Dredd or something like it also forces us to ensure well-consider response codes.

**Comment by kushthedude** [comment]
> Use of Dredd or something like it also forces us to ensure well-consider response codes.

I have been going through this and some of our handlers have well-defined response codes, the handlers which are relatively newer needs more testing and error handling. Moreover, with bringing of Gorilla, it has made us relieve few of our error checks but yes I agree with the need to make our handlers more error responsive.

**Comment by KarenEfereyan** [comment]
@kushthedude and @leecalcote I will be watching this space. I really want to learn more about testing

**Comment by leecalcote** [comment]
@KarenEfereyan excellent. :)

@kushthedude, that's heartening to hear. @anirudhjain75, all's not yet lost. ;)
