### ISSUE TITLE
error 404 for minikube in /docs 

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#158]
**Describe the bug**
Deploying on local system works fine and minikube page is accessible, but after merging the PR with master , the link redirects to wrong URL

[original url / wrong url](https://meshery.layer5.io/docs/minikube) `https://meshery.layer5.io/docs/minikube`

[actual url which should be present](https://meshery.layer5.io/docs/installation/minikube) `https://meshery.layer5.io/docs/installation/minikube`

**Comment by leecalcote** [comment]
fixed by #157
