### ISSUE TITLE
[meshery] meshes.proto: Add OpCategory to EventResponse

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1584]
**Current Behavior**
Capturing a quick feature request to enhance `meshes.proto` to capture the:

- operation category

Include operation ID in the json payload? Or include in the meshes.proto (Event.Details).

**Desired Behavior**
Event.Details should be associated with the specific operation that invoked the results.

---
**Implementation**

**Mockups**

**Acceptance Tests**

**Comment by KarenEfereyan** [comment]
resources?

**Comment by leecalcote** [comment]
Removing Hacktoberfest label. Issue needs design.

**Comment by KarenEfereyan** [comment]
🤣🤣🤣
