### ISSUE TITLE
[Docs] Documentation of Windows Installation missing on Website.

### ISSUE THREAD

**Issue by tripathyprateek** [layer5io/meshery#1585]
**Current State:**

https://meshery.layer5.io/docs/installation/platforms/windows  returns a 404 error
**Desired State:**

This page should be showing installation steps for Windows. Just add this page to the above url https://meshery.layer5.io/docs/installation#windows
---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by KarenEfereyan** [comment]
Im on this

**Comment by abiodunolunu** [comment]
I'll do it

**Comment by KarenEfereyan** [comment]
> I'll do it

thanks abiodun. I've assigned the issue to you
