### ISSUE TITLE
[UI]: optimize front-end code handle console waring

### ISSUE THREAD

**Issue by PmcFizz** [layer5io/meshery#1588]
**Description**

when I develop front-end feature, the console show some waring,
as picture
![image](https://user-images.githubusercontent.com/13403284/93307563-b3b18e80-f833-11ea-926f-e87c245504c0.png)

fix these waring to get good code style。

**Expected Behavior**

no waring good code style

**Screenshots**

![image](https://user-images.githubusercontent.com/13403284/93307563-b3b18e80-f833-11ea-926f-e87c245504c0.png)

**Environment:**
 - OS: [Windows]
 - Browser: [Chrome]
 - Version: [master]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'http://localhost:3000/'
2. Click on 'F12'
3. Scroll down to 'console'

[Optional] **Additional Context**

**Comment by kushthedude** [comment]
Good of you to jump in here @PmcFizz 😄 , these are really annoying 😖 !

**Comment by leecalcote** [comment]
Much appreciated, @PmcFizz. 💯
