### ISSUE TITLE
Need to add more event types on the stream response

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#1589]
**Description**
Meshery streams the response from every adaptor operation back to the UI. This issue addresses the fact that these stream responses have no flexibility in identifying the type of the event being streamed.

**Expected Behavior**
The stream response should have an additional parameter where in we know which request it corresponds to. This needs a discussion, change in protocol buffers used across the adaptors.

**Comment by leecalcote** [comment]
Removing Hacktoberfest label. Issue inappropriate for Hacktoberfest. Requires much in-depth, project-specific knowledge.
