### ISSUE TITLE
Welcome bot conflicts with pr labeler 

### ISSUE THREAD

**Issue by MukulMaheshwari** [layer5io/meshery#1591]
**Description**
 
Welcome bot is not working as expected & seems to be conflicting with pr labeler. 
 * @leecalcote  mentioned this issue in mesher-ci slack.

**Expected Behavior**

Welcome bot should work without any conflicts & independent of labeler.

**Comment by leecalcote** [comment]
@MukulMaheshwari it'll be good to keep an eye on this PR https://github.com/meshery/meshery/pull/1595 that will soon merge to see if the welcome bot config is still conflicting with another config.

**Comment by kushthedude** [comment]
The issue was an invalid config.

**Comment by kushthedude** [comment]
Fixed in #1592

**Comment by leecalcote** [comment]
Much appreciated. It was painful not seeing new community members congratulated. :)
