### ISSUE TITLE
Clicking on Result displays an error in the Meshery UI

### ISSUE THREAD

**Issue by Techwinx1** [layer5io/meshery#1602]
**Description**

I discovered on the Meshery UI dashboard that when the Results button on the Result section is clicked it returns an error.

**Expected Behavior**
No error screen should be displayed .

**Screenshots**
Here is the link to the screenshot
https://bit.ly/3mLOrvV

**Environment:**
 - OS: [Windows]
 - Browser: [e.g. Chrome]
 - Version: [85]
 - Device: [laptop,]

---
 **To Reproduce the error**
1. Go to 'Meshery UI Dashboard'
2. Click on 'Results'
3. See the  error

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
@Techwinx1 thank you for raising this issue. Would you like to try to tackle this one, too?

**Comment by Techwinx1** [comment]
Yes i would

**Comment by dhruv0000** [comment]
Hey @Techwinx1 . Try running the backend and login using the meshery provider before messing around with the UI. Run `make build-ui run-local` and login at [http://localhost:9081/provider](http://localhost:9081/provider) before running your UI development server.

**Comment by Nikhil-Ladha** [comment]
Closing based on this [comment](https://github.com/layer5io/meshery/pull/1603#issuecomment-698439397)
