### ISSUE TITLE
Broken link to Maesh logo in README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1606]
@leecalcote it's also there for the [meshery readme](https://github.com/layer5io/meshery/blob/master/README.md) too!

![yoyo](https://user-images.githubusercontent.com/48355572/94187390-83b65b00-fec5-11ea-8d23-1929937d54fb.JPG)

_Originally posted by @Neilblaze in https://github.com/layer5io/layer5/issues/800#issuecomment-698526123_

**Comment by leecalcote** [comment]
@bartkalanski help! 😉

**Comment by bartkalanski** [comment]
I'm about to leave for work but could sort this within the next 24hrs ?

**Comment by leecalcote** [comment]
Sounds real good. ✔️

**Comment by bartkalanski** [comment]
I submitted a PR in issue #1609 so I believe you can close this :)

**Comment by Neilblaze** [comment]
Closed via #1609
