### ISSUE TITLE
[Docs] Translate Contributing Overview page to Spanish

### ISSUE THREAD

**Issue by jesuslerma** [layer5io/meshery#1608]
**Current State:**
The actual documentation is in english.

**Desired State:**
We're expecting to increase the number of spanish speakers users and contributors of meshery by doing this efford. We also need to define if we can use a switch between languages, if so we should discuss this in other issue.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Ozrlz** [comment]
Hi @jesuslerma I'd like to take this one;however, I don't quite understand how to approach the translated docs ... should I create a new .md document on the docs/pages/ directory with a spanish_ prefix? Or what is the recommended approach?

**Comment by jesuslerma** [comment]
Hi @Ozrlz I'm trying to take this one. Let me create a few of new issues to translate another pages and I'm going to assign some of it to you. Alsi, let me check how we can use the transalted guides when switching the language.

**Comment by viveksahu26** [comment]
Hey @jesuslerma , if this issue is available, I would like to work on it..
