### ISSUE TITLE
[Docs] Add traefikmesh to service mesh table

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1610]
**Current State:**

Maesh service mesh has officially changed its name to `traefikmesh` and has a new logo. The name and logo can be sourced from their site: [`traefikmesh`](https://traefik.io/traefik-mesh/)
 
**Desired State:**

Swap out the name and logo with the new ones in the Service Mesh table on:

- [Adapters page](https://meshery.layer5.io/docs/architecture/adapters)
- [Service Meshes page](https://meshery.layer5.io/docs/service-meshes) 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by dannylwe** [comment]
Hi, I'm new to open source. I'd like to take this up.

**Comment by PluckyPrecious** [comment]
Hi @dannylwe sure you can go ahead. Do join the Meshery community on [slack](http://slack.layer5.io/) to collaborate with other contributors.😊

**Comment by dannylwe** [comment]
> Hi @dannylwe sure you can go ahead. Do join the Meshery community on [slack](http://slack.layer5.io/) to collaborate with other contributors.😊

👍

**Comment by hexxdump** [comment]
I would like to contribute to this as well. @dannylwe @PluckyPrecious let me know if I can take can up any part of the problem?
@chandrashritii , right now Traefik(https://github.com/traefik/mesh) is at v1.4.0, what is the latest version of Traefik Meshery is going to support?
