### ISSUE TITLE
[CI] Stable release channel is missing in ci.yml

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1612]
**Description**
The stable channel for Meshery is missing.

Meshery Release v0.4.7 is not present in Docker Hub - 
https://hub.docker.com/repository/docker/layer5/meshery/tags?page=1. There is no `stable-latest` tag after the recent v0.4.6 release.

A new workflow (https://github.com/layer5io/meshery/blob/master/.github/workflows/build-and-release.yml) has been created. Is the intention for this to be a build only for the `mesheryctl` component?

**Comment by leecalcote** [comment]
I see the the stable release channel is present in the `build-and-release.yml`.

@kumarabd when initiating the `v0.4.7` release, what mechanism did you us to do so? The release look to have been performed by the user "GitHub actions". Was this done by pushing a new `git tag`? If so, I wonder if the workflow structure that we have in place supports this this mechanism as opposed to that of a user creating a release in the GitHub web UI.

**Comment by leecalcote** [comment]
A new stable release has been successfully made - `v0.4.8`. I'm reducing the severity of this issue. @kushthedude this issue might turn into a documentation issue to update Meshery Build & Release Strategy doc with the new structure of the workflows.

**Comment by kushthedude** [comment]
This is not a bug , this is a process which we have already discussed
several times that a release needs to be made manually to trigger the
release actions. If a bot release is done than GitHub wont bother the
action runner to run the release actions. There is no bug in ci.yml, stable
release channel is in place.

This issue should be closed.

**Comment by kumarabd** [comment]
@leecalcote  Im confused about this because I never intentionally used a github action user. It would be helpful for me if someone explains this to me.

**Comment by leecalcote** [comment]
Converting this issue to a docs issue. Meshery Build & Release Strategy doc needs updated with specifics on the release process.
