### ISSUE TITLE
[Docs] Update Meshery Architecture diagrams

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1615]
**Description**

Swap out the outdated Meshery architecture pictures in the [Architecture](https://meshery.layer5.io/docs/architecture) page in the Meshery docs.
The images can be sourced from the [Architecture folder](https://drive.google.com/drive/folders/1_aKPepn31LfXrWkdAdiZWgjdFVigTo1M?usp=sharing) in the Layer5 community drive.

The images have been named according to the headings in the documentation - Meshery architecture diagram, client and provider. They should be updated under their respective headings.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by lolyparty** [comment]
I would like to work on this

**Comment by leecalcote** [comment]
@lolyparty That would be most helpful. Thank you.
