### ISSUE TITLE
[UI] Dashboard to System Dashboard

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1633]
**Current Behavior**
The Dashboard page describes Meshery components and system status. This page is named "Dashboard".

**Desired Behavior**
This page should be renamed and updated to reflect more of what it is.

**Implementation**
1. This page should be renamed to "System Dashboard".
1. The two separate Prometheus and Grafana cards should be combined into a single "Metrics" card.

**Mockups**
![Frame 1-4](https://user-images.githubusercontent.com/7570704/94977143-13b75e80-04dd-11eb-8f17-dfac95387cdb.png)

**Acceptance Tests**
1. UI should like similar to the mockup with cards rearranged.
1. Dashboard component should be renamed to SystemDashboard.

**Comment by sandy9808** [comment]
I am not able to understand this point: **the The two separate Prometheus and Grafana cards should be combined into a single "Metrics" card.**

**Comment by leecalcote** [comment]
Screenshot of the current UI - 
![](https://meshery.io/images/screens/meshery-dashboard-no-shadow.png)

**Comment by karkranikhil** [comment]
Let me pick this up

**Comment by leecalcote** [comment]
Sounds great, @karkranikhil
