### ISSUE TITLE
[UI] Dashboard: "Release" Section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1634]
**Current Behavior**
Users of Meshery UI are unaware as to what version of Meshery and Meshery adapters are currently running.

**Desired Behavior**
Users could be helped within a new component that includes the current Meshery version numbers:

**Implementation**
1. Create a new card with title Release details
1. Include release channel radio buttons (leave disabled)
 
**Mockups**
![Frame 1-3](https://user-images.githubusercontent.com/7570704/94977124-fe423480-04dc-11eb-977f-23a55d5584b5.png)

**Acceptance Tests**
1. Latest available version should be retrieved from GitHub releases endpoint for layer5io/meshery
1. Current release version should be retrieved from Meshery endpoint

**Comment by m4tr1k** [comment]
Hi @leecalcote can I take a look at this issue?

**Comment by leecalcote** [comment]
@m4tr1k, yes, please. There is an endpoint missing in Meshery’s API to complete the release channels portion entirely. That’s ok. The UI functionality can be built out and disabled until the endpoint is ready.

**Comment by m4tr1k** [comment]
@leecalcote that was what I was going to ask because I was not sure how to get the release version
So I'll just give focus on the UI part!
