### ISSUE TITLE
[Docs] `mesheryctl upgrade` command is outdated

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1638]
**Current State:**
The [Meshery Upgrade guide](https://meshery.layer5.io/docs/guides/upgrade#upgrade-meshery-server-adapters-and-ui) lists `meshery upgrade` as the command to update the software. 

**Desired State:**
The current version of this command is `mesheryctl system upgrade`. The documentation should reflect this.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by hexxdump** [comment]
Hi lee, can I take this issue and work on it?

**Comment by lolyparty** [comment]
> Hi lee, can I take this issue and work on it?

Yes, go ahead.
