### ISSUE TITLE
[mesheryctl] Prompt user to update to latest Meshery server release and perform update

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1644]
**Current Behavior**
`mesheryctl version` will notify users of a later server version available and provides the user with instructions to do so, but does not update to the latest version on the user's behalf.

**Desired Behavior**
`mesheryctl` should perform the upgrade to the latest version of Meshery server on behalf of the user, if user so chooses. This update will be for Meshery server and Meshery adapters.

**Implementation**
`mesheryctl version` should call to the internal function/command that is equivalent to `mesheryctl system update`

**Mockups**
`mesheryctl version` should prompt the user with this question:

```
Update Meshery server and Meshery adapters to the latest available versions? (y/n):
```

**Acceptance Tests**
1. If later version of Meshery server is available and the user responds with "y", Meshery should automatically be updated.
1. Users should be able to invoke this operation for Meshery deployments on Docker.
1. Users should be able to invoke this operation for Meshery deployments on Kubernetes.
1. `mesheryctl` will not be updated.

---
**Additional Context**

> I have looked at the code but did not test it. However, I do have some suggestions. I think when mesheryctl is run with or without a parameter, the parameter should be saved and the version should be checked at that time and printed. The user should then be informed and should be prompted to run update at that time. If the user chooses not to update, then the parameter should be used to execute the requested command, else mesheryctl should invoke the update command and then execute the originally requested command by using the saved parameter.

Great suggestion, @vijcheru. I agree. In a subsequent PR, let's prompt the user with "Would you like to upgrade to vx.x.x now? (y/n)?" and process accordingly.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1640#issuecomment-703320153_

**Comment by vijcheru** [comment]
I thought I will add @ameyaagashe and @Ruth-ikegah  so that I can work with them. I am not trying to conscript me but only look forward to their views. They can drop out if they are not inclined to work on it. I will appreciate their views on this matter. Anybody else is welcome to join.
i

**Comment by leecalcote** [comment]
> I thought I will add @ameyaagashe and @Ruth-ikegah so that I can work with them. I am not trying to conscript me but only look forward to their views. They can drop out if they are not inclined to work on it. I will appreciate their views on this matter. Anybody else is welcome to join.

Excellent. 😄

**Comment by uds5501** [comment]
Picking this one up.
