### ISSUE TITLE
[Docs] README: Broken image of Meshery Architecture

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1645]
**Current State:**
Diagrams of Meshery's architecture were recently updated. This caused a broken link in the [architecture section of the main README](https://github.com/layer5io/meshery#meshery-architecture)

**Screenshot:**
<img width="719" alt="Screen Shot 2020-10-04 at 8 50 10 PM" src="https://user-images.githubusercontent.com/7570704/95033363-937f2d80-0683-11eb-8cdb-dcab7e6f6feb.png">

**Desired State:**
1. This image may be used to show Meshery's architecture - https://github.com/layer5io/meshery/blob/master/docs/assets/img/architecture/Meshery-client-architecture.svg
1. This image should be copied to the `docs/assets/img/readme` folder, so as to avoid having it broken again.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@spielers is this issue of interest?

**Comment by spielers** [comment]
@leecalcote Yeah I would love to resolve this issue
