### ISSUE TITLE
[Docs] README: incorporate SMP logo into Service Mesh Performance section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1646]
**Current State:**
The [section of the Meshery README](https://github.com/layer5io/meshery#standardized-service-performance-management) that covers service mesh performance does not include a copy of the SMP project logo.

**Desired State:**
Incorporate a small SMP logo into this section of the README.md. Find the SMP brand kit here - https://layer5.io/brand

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Aarush-Goyal** [comment]
@leecalcote I want to work on this

**Comment by Aarush-Goyal** [comment]
@leecalcote I have added the logo in the SMP section pls review the PR #1647

**Comment by leecalcote** [comment]
@Aarush-Goyal very nice. And you sized down the image to fit as well. 👍

**Comment by Aarush-Goyal** [comment]
Sir pls review this pr #1648 I have by mistake put Mesherey logo in place of SMP logo

**Comment by leecalcote** [comment]
Hi @Aarush-Goyal, oh, very good! Thanks for seeing this through. I'm pulling in others, so my lack of time doesn't kink up the works.

**Comment by leecalcote** [comment]
Thank you, @PluckyPrecious
