### ISSUE TITLE
[CI] Release new version of Meshery Helm chart on Artifact Hub

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1661]
**Current Behavior**
Meshery's Helm chart now includes support for additional Meshery adapters.

**Desired Behavior**
A new version of the Meshery Helm chart should be created and Artifact Hub updated - https://artifacthub.io/packages/helm/meshery/meshery

**Comment by leecalcote** [comment]
@Aisuko could you look into this?

**Comment by Aisuko** [comment]
> @Aisuko could you look into this?

No problems

**Comment by Aisuko** [comment]
Relevant PR:

Update version
https://github.com/meshery/meshery/pull/1781

Release to the chart repo
https://github.com/meshery/meshery.io/pull/364

**Comment by Aisuko** [comment]
We can seek for some helm release action. As I know there may some tools.

**Comment by Aisuko** [comment]
@leecalcote I 'd like to post the idea about this on our repo tab `Discussions`. how do you think about this sir? I mean this may a good place share something relevant the repo especially the `Github actions`

**Comment by leecalcote** [comment]
@Aisuko sounds real good, yes. 👍

**Comment by leecalcote** [comment]
Issue completed.
