### ISSUE TITLE
[mesheryctl] Update error message in `mesheryctl version` failure to connect to server

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1664]
**Description**
The error message shown when Meshery server is unavailable could be better phrased.

```
➜  .meshery mesheryctl version
Client Version: 0.4.12 	  GitSHA: 6f7a527f3fa5e713c52686f3387c3ae1b54de1f2
Server Version:  	  GitSHA: 6f7a527

failed to check for latest version of Meshery
```

**Expected Behavior**
Error message should be:

"Meshery server unreachable. Please confirm that Meshery is running and available. "

**Comment by tripathyprateek** [comment]
Can I take this up, and start contributing to Meshery.

**Comment by leecalcote** [comment]
Sounds great good. 👍

**Comment by ImagineZero0** [comment]
Can I work on this.?

**Comment by Nikhil-Ladha** [comment]
> Can I work on this.?

Sorry, @ImagineZero0 someone is already working on it. You can lookout for other open issues 🙂
