### ISSUE TITLE
Add Prettier code formatter to the UI 

### ISSUE THREAD

**Issue by daksh-sagar** [layer5io/meshery#1669]
**Current Behavior**

The UI code doesn't follow any formatting guidelines as of now. Devs can choose b/w single or double quotes, semi or no semicolon, etc. This results in inconsistently formatted code.

**Desired Behavior**

By introducing prettier to the UI, all the code will follow standard formatting. It is analogous to `gofmt`. After prettier is added devs won't have to worry about adhering to a particular way of formatting JS code, prettier will take care of it.

---
**Implementation**

Will have to introduce prettier as a dev dependency to the UI project and write a pre-commit hook that formats all the changed files.
**Mockups**

**Acceptance Tests**

**Comment by daksh-sagar** [comment]
@Nikhil-Ladha Please add to this issue if it's needed and if everyone agrees on this, I can start working on it.

**Comment by leecalcote** [comment]
I’m supportive of this suggestion. 

@kushthedude may have thoughts here as well.

**Comment by kushthedude** [comment]
We already have ES-Lint more better and stricter.

**Comment by daksh-sagar** [comment]
> We already have ES-Lint more better and stricter.

But it doesn't help with formatting from what I've seen. You're free to choose upon single quotes or double quotes, you can choose to leave out semi colons, etc

**Comment by daksh-sagar** [comment]
Eslint can be configured to point errors for the above things, but having a formatter which does these things for you is good, in my opinion.

**Comment by kushthedude** [comment]
Eslint can also format the file using fix flag, we have not made it
stricter as it will require more diligence from the contributor, hence we
have made them mandatory.

**Comment by daksh-sagar** [comment]
Cool, shall I close this then ?

**Comment by kushthedude** [comment]
Let us wait and hear out from others if we want more stricter rules with
ESLint, else we are good to close this.

**Comment by Nikhil-Ladha** [comment]
I think we are fine here.
