### ISSUE TITLE
[UI] Sort Adapter Operations Alaphbetically

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1670]
**Current Behavior**
Each Meshery Adapter's operations are read from the respective adapter in real-time when a user navigates to a particular service mesh page. There is no guaranteed ordering of the list of supported operations that the adapter will respond with. So, users will see a different order of menu items (sported operations) each time that they load the page. See screenshots:

First load of the Istio page:
<img width="424" alt="Screen Shot 2020-10-11 at 11 25 35 AM" src="https://user-images.githubusercontent.com/7570704/95684118-e8a3cd80-0bb4-11eb-9498-3a7e8121f89a.png">

Second load of the Istio page:
<img width="409" alt="Screen Shot 2020-10-11 at 11 25 28 AM" src="https://user-images.githubusercontent.com/7570704/95684122-f48f8f80-0bb4-11eb-9e9d-ed4e7b6c93e2.png">

**Desired Behavior**
Supported operations should be shown in the same order each time a user loads the page. Operations should be alphabetically sorted by name of the operation in the UI.

**Comment by gunishmatta** [comment]
I would like to work on this issue.

**Comment by tripathyprateek** [comment]
Great @gunishmatta I will assign you this.

**Comment by PluckyPrecious** [comment]
Hey @gunishmatta how is this coming up?

**Comment by leecalcote** [comment]
@gunishmatta or @HeroicHitesh are either of you available to resolve this issue this week?

**Comment by utkarsh-pro** [comment]
@leecalcote if no one is working on this then I'd like to pick it up

**Comment by leecalcote** [comment]
Thank you @utkarsh-pro
