### ISSUE TITLE
[UI] Remove "SMI Conformance results" chip from all Adapter pages

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1671]
**Current Behavior**
The SMI Conformance results chip is shown in each Adapter page.

**Desired Behavior**
This chip (button) was a temporary solution. Now that a permanent solution is in place, it can be removed.

**Screenshot**

Adapter chip:

<img width="343" alt="Screen Shot 2020-10-11 at 8 00 18 PM" src="https://user-images.githubusercontent.com/7570704/95695435-7bb42600-0bfc-11eb-8079-c099c4b36200.png">

**Comment by daksh-sagar** [comment]
@leecalcote I'll take this.
