### ISSUE TITLE
[Docs] Update Latest supported version of Istio to 1.7.3

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1676]
**Current State:**
Currently, the [Meshery Adapter for Istio ](https://meshery.layer5.io/docs/service-meshes/adapters/istio/istio)docs list 1.5 as the latest supported version.

**Desired State:**
v1.7.3 is the latest supported version, though. 

The data file for this adapter needs to be updated.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Maxgit3** [comment]
I am a new contributor to open source.  I would be willing to work on this.  thank you for your response.

**Comment by PluckyPrecious** [comment]
Sure @Maxgit3 do go ahead.👍🏽

**Comment by Maxgit3** [comment]
Thank you.  Looking into the issue now.
