### ISSUE TITLE
[mesheryctl] Support for shorthand flag `-t` missing in `system config`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1679]
**Description**
`mesheryctl mesheryctl system config minikube -t ~/Downloads/auth.json` produces the following error:
```
mesheryctl system config minikube -t ~/Downloads/auth.json
Error: unknown shorthand flag: 't' in -t
```

**Expected Behavior**
Both `--token` and `-t` should be supported aliases of this same flag.

**Comment by sladyn98** [comment]
https://github.com/meshery/meshery/blob/f8227b1978de965ecad238529a60fae35af61a99/mesheryctl/internal/cli/root/system/config.go#L173
The short flag `-t` is supported here . 
Could it be caused because it is chained with `minikube` ? 

CC @leecalcote

**Comment by leecalcote** [comment]
Good question. “Minikube” probably needs to be behind a flag itself, like `-p`

**Comment by sladyn98** [comment]
Yeah is there any existing command like minikube.go that we can probably extend and add subcomands to ?

**Comment by anirudhjain75** [comment]
This issue doesn't exist on latest master... Someone must have fixed it :)

**Comment by sladyn98** [comment]
Sounds good :+1:

**Comment by KarenEfereyan** [comment]
Could this be closed then @leecalcote ?

**Comment by sladyn98** [comment]
@leecalcote @KarenEfereyan I am not sure this is fixed yet. Some are still having issues with this

**Comment by leecalcote** [comment]
Reopening with more details on issue from @Bcoralm.

**Using Version:** 
```
Client Version: 0.4.14 	  GitSHA: dec0eeada6c059925bece36172271a995fca694e
```

**This error occurs:**

```
$ mesheryctl system config  minikube --token ~/Downloads/auth.json
sh: 2: set: Illegal option -o pipefail
Error generating config:exit status 2
```

On this OS/Kubernetes:

```
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-12-amd64
minikube version: v1.14.0
```

**Comment by leecalcote** [comment]
Another report from @icharlem.

**System details:**

```
@ubuntu@MINIKUBE:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

// @clementkng @hexxdump @anirudhjain75 @sladyn98

**Comment by leecalcote** [comment]
One issue here is that we’re assuming presence of kubectl and not handling this gracefully - https://github.com/meshery/meshery/blob/8e49e16e786252075f41ea5fb1af85e83ea9ae9a/mesheryctl/pkg/utils/scripts.go#L18

**Comment by leecalcote** [comment]
Any new leads here? This issue is also blocking creation of training labs.

**Comment by kushthedude** [comment]
Found the fix @leecalcote
