### ISSUE TITLE
[mesheryctl]: The attempt to install docker-compose while running mesheryctl fails due to permission issue. 

### ISSUE THREAD

**Issue by NupurThakur27** [layer5io/meshery#1682]
**Description**

Currently, The docker-compose installation fails as in Linux systems sudo permission is required to make any installation.

**Expected Behavior**

The attempt to install `docker-compose` should take sudo permission in Ubuntu and install it successfully.
**Screenshots**

![Screenshot from 2020-10-14 19-19-41](https://user-images.githubusercontent.com/39610703/95998322-620c1c00-0e52-11eb-8f79-144e72190aee.png)
![Screenshot from 2020-10-14 19-20-36](https://user-images.githubusercontent.com/39610703/95998369-6afced80-0e52-11eb-96e9-223fb953ea34.png)

**Environment:**
 - OS:  Ubuntu
 - Version:  20.04
 - Device: Laptop

---

**Comment by anirudhjain75** [comment]
Hi @NupurThakur27, Regarding this issue. It depends upon if docker is in sudoer group or not. Usually adding sudo to every docker command is annoying so you usually add docker to sudoer group, then passing sudo to docker compose is not necessary

**Comment by kalradev** [comment]
I was looking at the bash script. I found it complex for no reasons. 
![2020-10-14-200541_990x348_escrotum](https://user-images.githubusercontent.com/32228313/96004284-d47ffa80-0e58-11eb-913f-d3757ebec935.png)

Why is this code here? 
We can simply write 
`sudo mv ....`
instead of if else

**Comment by kushthedude** [comment]
> Why is this code here?
> We can simply write
> `sudo mv ....`
> instead of if else

Because this is needed to check for certain users, and this piece of code is certainly much more useful if you are using RHEL or SUSE remote subsystems.

**Comment by sladyn98** [comment]
@NupurThakur27 @anirudhjain75 Does this still need fixing ?
