### ISSUE TITLE
Results Table: first row of results table is always not selectable

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1692]
**Description**

Results Table: the first row of the results table is always not selectable

**Expected Behavior**

You should be able to select the first row using the checkbox.

**Screenshots**

<img width="1106" alt="Screenshot 2020-10-18 at 1 33 50 AM" src="https://user-images.githubusercontent.com/44091822/96352622-27201780-10e2-11eb-9537-7ecfbd454914.png">

**Comment by KarenEfereyan** [comment]
@kushthedude what could be causing that bug?

**Comment by leecalcote** [comment]
@dhruv0000 did you previously address this?

**Comment by dhruv0000** [comment]
Had a look a while back, couldn't figure it out that time. Taking a look again with a clean slate, I think I found the bug. A PR is incoming shortly.

**Comment by leecalcote** [comment]
Fantastic.
