### ISSUE TITLE
[UI] Grafana: Unable to persist board selection

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1699]
**Description**
When a user navigates to the http://localhost:9081/settings#metrics/grafana tab, choose a predefined board, modify the panels and choose to add the board, they receive an error stating the board settings could not be persisted.

When the user refreshes the page, though, the board has been persisted.

**Screenshots**
<img width="976" alt="Screen Shot 2020-10-19 at 11 54 46 AM" src="https://user-images.githubusercontent.com/7570704/96507168-70758180-121e-11eb-94c7-b9664d7a81a6.png">

**Comment by leecalcote** [comment]
@dhruv0000 we're hosting an Istio workshop on Wednesday. A fix on this issue will have a positive impact if fixed before Wed at midnight IST.

**Comment by leecalcote** [comment]
@dhruv0000 your efforts here have been an improvement. 👍 I still bump into this issue with high frequency.

**Comment by dhruv0000** [comment]
I cant seem to replicate the particular behaviour in my system.
![Grafana Problem](https://user-images.githubusercontent.com/44001539/98282294-0867bf00-1fc4-11eb-9ef5-3a0de8c172a1.gif)
