### ISSUE TITLE
[Docs] Translate Quick Start page to Spanish

### ISSUE THREAD

**Issue by alonsolopezr** [layer5io/meshery#1701]
**Current State:**
The actual documentation is in english.

**Desired State:**
I want to translate this page:https://meshery.layer5.io/docs/installation to spanish.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by jesuslerma** [comment]
Awesome, let me know if you need any here there :)

**Comment by leecalcote** [comment]
@alonsolopezr, I think this page is done, right? https://docs.meshery.io/es

**Comment by leecalcote** [comment]
Yes, I see it now.  Looks great.
