### ISSUE TITLE
[Docs] Translate Project page to Spanish

### ISSUE THREAD

**Issue by homero304** [layer5io/meshery#1703]
**Current State:**
The actual documentation is in english.

**Desired State:**
I want to translate this page:https://meshery.layer5.io/docs/project to spanish.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by jesuslerma** [comment]
Awesome, please go!

**Comment by homero304** [comment]
https://github.com/meshery/meshery/pull/1740
