### ISSUE TITLE
[mesheryctl] `version` command provides invalid upgrade prompt

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1707]
**Description**
`mesheryctl version` runs a check for the latest version of Meshery that is available and will inform the user if a later version is available than what the user has installed.

```
mesheryctl version
Client Version: 0.4.13 	  GitSHA: aa6dbc84ba47d81d087ae7c7f5693a0d8cce9cc2
Server Version: v0.4.13 	  GitSHA: aa6dbc8

v0.4.13 is not the latest Meshery release. Upgrade to v0.4.14. Run `mesheryctl system upgrade`
```

**Expected Behavior**
The prompt (instructions) provided in this output say to execute `system upgrade`. The command is actually `system update`.

**Comment by cardinalion** [comment]
I'll take this

**Comment by leecalcote** [comment]
@cardinalion, excellent. 😄
