### ISSUE TITLE
[mesheryctl] `version` command should provide an "operation in-progress" indicator to user

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1708]
**Current Behavior**
`meshery version` takes some time to execute the check against the GitHub API for the latest release of software. This check can take a few seconds, leaving the user to wonder what is going on.

```
mesheryctl version
Client Version: 0.4.13 	  GitSHA: aa6dbc84ba47d81d087ae7c7f5693a0d8cce9cc2
Server Version: v0.4.13 	  GitSHA: aa6dbc8

v0.4.13 is not the latest Meshery release. Upgrade to v0.4.14. Run `mesheryctl system upgrade`
```

**Desired Behavior**
Users should be shown an indicator that a check is being performed.

**Implementation**
Show user the info message: ```Checking for latest version of Meshery....```

**Comment by cardinalion** [comment]
I'll take this

**Comment by leecalcote** [comment]
Sounds great, @cardinalion. 👍
