### ISSUE TITLE
[UI] Navigation Menu Icon Not Scaling

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1712]
**Description**
The lefthand navigation menu icons do not scale on browser zoom.

**Expected Behavior**
The icons should enlarge/shrink as the user zooms their view.

**Screenshots**
<img width="2278" alt="Screen Shot 2020-10-20 at 9 01 00 PM" src="https://user-images.githubusercontent.com/7570704/96664248-f88b8200-1317-11eb-9d63-abe0a7c824d1.png">

**Comment by leecalcote** [comment]
Related issue - https://github.com/meshery/meshery/issues/1146

**Comment by codetheorem** [comment]
Assign this to me.

**Comment by leecalcote** [comment]
Thanks for picking this up, @codetheorem. There are a few other icons that don't scale here that are not encircled in the screenshot.

**Comment by arpitkarnatak** [comment]
I can work on this issue

**Comment by leecalcote** [comment]
Thanks for picking this up, @arpitkarnatak

**Comment by PluckyPrecious** [comment]
Hey @arpitkarnatak how is this coming up?

**Comment by Ayush-Khandelwal-007** [comment]
@leecalcote I would like to work on this.

**Comment by leecalcote** [comment]
Hi @Ayush-Khandelwal-007, that would be great. 👍
