### ISSUE TITLE
[mesheryctl] Use of `utils.AuthConfigFile` in `mesheryctl system config`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1716]
`mesheryctl system config` requires use of the user's Meshery token.

Use of `utils.AuthConfigFile` (example here) - https://github.com/layer5io/meshery/blob/49819bd9438140cc7ad5572716c1ae2c158e511c/mesheryctl/internal/cli/root/perf/perf.go#L161 seems to provide CLI users with the convenience of assuming a default location for the token file. Is that something we might incorporate here? If so, consistency of UX is ideal.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1715#discussion_r508993735_

**Comment by leecalcote** [comment]
// @anirudhjain75

**Comment by anirudhjain75** [comment]
This is already done, Ain't it @leecalcote . Fixed this before
