### ISSUE TITLE
[meshmap] Smooth transition on zoom and reposition

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1718]
Pretty neat. I _think_ that this will serve us well. Do we have the ability to make this a smoother transition?

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1717#issuecomment-713530716_

**Comment by vineethvanga18** [comment]
@leecalcote Yes we can do this. But we currently have an issue with state. The re-rendering when we click on a node grows exponentially
![highlight_and_fit](https://user-images.githubusercontent.com/44473939/96727230-76ab5f80-13d0-11eb-8983-e4a47c485733.gif)

**Comment by leecalcote** [comment]
Thanks for looking at this. More to be investigated here. Will you create an issue?

**Comment by vineethvanga18** [comment]
Yes
