### ISSUE TITLE
[UI] Disable Nighthawk as an available choice of load generator

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1720]
**Description**
This feature is dysfunctional currently. 

**Expected Behavior**
Radio button should be disabled.

**Comment by Nikhil-Ladha** [comment]
Do we only need to disable the button or even hide it from the UI?
I can give a try if you say so @kushthedude , @leecalcote .

**Comment by leecalcote** [comment]
Actually, I think we might be ok to close this issue now. Is that right, @kushthedude? Is Nighthawk working now?

**Comment by kushthedude** [comment]
> Actually, I think we might be ok to close this issue now. Is that right, @kushthedude? Is Nighthawk working now?

Not in production bundle, but I am hoping for some solution this Wednesday 🙂

**Comment by leecalcote** [comment]
@kushthedude any luck? If not, it's been two weeks. We should disable in the UI.
