### ISSUE TITLE
[meshmap] MesheryVisualizeComponent renders multiple times

### ISSUE THREAD

**Issue by vineethvanga18** [layer5io/meshery#1725]
**Description**

With each click on a node or edge, the number of times the graph renders grows exponentially.  The problem is with state in MesheryVisualizeComponent. There are multiple changes to the state of drawer(open or close) when clicked on a node, which causes re-renders(and causes delay in final render). 

**Expected Behavior**

When clicked on a node or edge the graph should render once. 

**Screenshots**

![highlight_and_fit (1)](https://user-images.githubusercontent.com/44473939/96826162-64710600-1450-11eb-9c42-5fe73319b30f.gif)
Here you see the second click on a node delays opening of drawer and this delay increases exponentially. See console to get an idea.

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18
