### ISSUE TITLE
[Docs] Readme - Update Maesh Logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1727]
**Description**
This section of the README (https://github.com/layer5io/meshery#supported-service-meshes) uses the version of the Maesh logo that has text included ("Traefik Maesh"), but shouldn't.

**Comment by leecalcote** [comment]
@akashprasher over to you! :)

**Comment by akashprasher** [comment]
The PR(https://github.com/meshery/meshery/pull/1733) also Fixes this issue
As I have changed the origin file It'll reflect everywhere it is being used.

**Comment by leecalcote** [comment]
This makes sense, but please don't do so across repos as we will inevitably end up with broken links, since people can't/don't track dependencies from other repos.
