### ISSUE TITLE
[Docs] README - Add NGINX Service Mesh adapter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1729]
**Current Behavior**
NGINX Service Mesh is missing. A new adapter has been created - https://github.com/layer5io/meshery-nginx-sm

**Desired Behavior**
- Meshery's readme should have NGINX Service Mesh adapter listed as an alpha adapter.
- use the Nginx service mesh logo recently included in the https://layer5.io/landscape

<img width="602" alt="Screen Shot 2020-10-22 at 4 33 34 PM" src="https://user-images.githubusercontent.com/7570704/96932344-589f3700-1484-11eb-8810-6c5dd23eb030.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by UnkleTayo** [comment]
I would like to work on this issue

**Comment by kishore007k** [comment]
Yeah sure @UnkleTayo ✌

**Comment by UnkleTayo** [comment]
I will start right away
