### ISSUE TITLE
[UI] Alphabetically sort the Management sub-menu items (service mesh names)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1731]
**Description**
Service meshes are not listed in alphabetical order in the navigation menu, but should be.

**Screenshots**
<img width="267" alt="Screen Shot 2020-10-22 at 7 27 17 PM" src="https://user-images.githubusercontent.com/7570704/96943220-1504f700-149d-11eb-8250-da1300119ac0.png">

**Comment by Kennygrace** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Sounds real good, @Kennygrace.

**Comment by tripathyprateek** [comment]
@Kennygrace assigning you this. Please reach out to us on Slack if you hit any roadblock.

**Comment by leecalcote** [comment]
Hi @Kennygrace, are you available to resolve this issue this week?

**Comment by Kennygrace** [comment]
Yes @leecalcote

**Comment by Kennygrace** [comment]
Please, what part of the code do I have to go to make the changes, I've been trying to find it I can't seem to locate it

**Comment by tangledbytes** [comment]
> Please, what part of the code do I have to go to make the changes, I've been trying to find it I can't seem to locate it

https://github.com/meshery/meshery/blob/master/ui/components/Navigator.js#L488 I am not sure but I think this is the function which needs to be modified

**Comment by Nikhil-Ladha** [comment]
Maybe we can simply edit the array to have the data in alphabetical order that would be better. And sorting time would be saved too. As wr are anyways using a static data here.

**Comment by ayushk1804** [comment]
Is the issue still open?
