### ISSUE TITLE
[Docs] Reorder menu items in alphabetical order

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1735]
**Current State:**
NGINX Service Mesh was recently added to the docs - https://meshery.layer5.io/docs/

**Desired State:**
It is out of alphabetical order.

**Screenshot**
<img width="219" alt="Screen Shot 2020-10-23 at 3 58 32 AM" src="https://user-images.githubusercontent.com/7570704/96978629-2de4cb00-14e4-11eb-88a6-084385096c89.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by amanda-ariyaratne** [comment]
Hello, Can I work on this?

**Comment by kishore007k** [comment]
Sure @amanda-ariyaratne. 👍
