### ISSUE TITLE
[Docs] Restyle Landing page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1738]
**Description**

 The landing page of the Meshery docs site has too much whitespace. Remove the whitespace and restyle appropriately

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Ready to close this PR or is there outstanding work needed here?

**Comment by leecalcote** [comment]
Please propose a design, if work remains.

**Comment by chandrashritii** [comment]
@leecalcote The page was already updated but can be improved upon. I'll send through a design asap
