### ISSUE TITLE
[Docs] Revert Meshery Architecture diagram to SVG

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1748]
**Current State:**
The first arch diagram on [this page](https://meshery.layer5.io/docs/architecture) uses a png not an svg like the others. 
The docs should be using vector-based images where possible, not rasterized images. The image is of poor quality and has an errant, floating OSM icon on it.

**Desired State:**
1. Download this diagram as an SVG from the [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.ga01cadb669_0_0).
1. Delete .png image and replace with SVG.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by bartkalanski** [comment]
Looks like the issue has been fixed in #1748 @leecalcote

**Comment by leecalcote** [comment]
@bartkalanski good eye. I missed this one. @bartkalanski, it'd be good to have your 👀 on PRs like these (or any other PRs that you'd like to review). Great way for you to engage even more, learn more, and to avoid me bottlenecking progress. 😅

**Comment by leecalcote** [comment]
Oh! I see in part what you mean now. I see that the issue was assigned to you. Right, ok.

**Comment by bartkalanski** [comment]
> @bartkalanski good eye. I missed this one. @bartkalanski, it'd be good to have your 👀 on PRs like these (or any other PRs that you'd like to review). Great way for you to engage even more, learn more, and to avoid me bottlenecking progress. 😅

I will do for sure!

> Oh! I see in part what you mean now. I see that the issue was assigned to you. Right, ok.

It was, but it doesn’t matter, it’s probably better that a brand new person to Layer5 has done this!
