### ISSUE TITLE
Add "Getting Involved" section to docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#176]
A new "Getting Involved" section needs to be added to the Meshery docs. It should include the same links and invitations found in the Community section here - https://layer5.io/meshery/#community. 

Also, a link to the [welcome guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit?usp=sharing) needs to be added to the Meshery project page under the Community section.

**Comment by leecalcote** [comment]
@arghac14 would you like to give this one a go as well?

**Comment by arghac14** [comment]
@leecalcote  sure! but exactly where should I put the 'Getting involved' html file? Is it here https://github.com/meshery/meshery/tree/master/docs/_layouts ?

And yes, I'll add the link to the welcome guide under the Community section.

**Comment by leecalcote** [comment]
@arghac14 thank you. Good question. You're looking in the right place. Instead of the "Getting Involved" (or maybe it should be called "Contributing") being a link to one document, it'll be a new section on the [Overview](https://github.com/meshery/meshery/blob/master/docs/index.md) page. This new section is to contain the same [Community information](https://github.com/meshery/meshery/blob/master/_includes/meshery.html#L216-L236) - 
![Screen Shot 2019-08-02 at 6 51 26 AM](https://user-images.githubusercontent.com/7570704/62368599-b3044e80-b4f2-11e9-9cc6-f9626374a1da.png)

**Comment by arghac14** [comment]
@leecalcote review the PR.

**Comment by leecalcote** [comment]
Fixed by #182

**Comment by leecalcote** [comment]
@arghac14 good deal. Jump into Slack here -- http://slack.meshery.io, if you would.

**Comment by leecalcote** [comment]
@raghavaggarwal99, there's a misspelling in the Community section - "callendar" that needs to be corrected. Could you please fix this?

**Comment by leecalcote** [comment]
@raghavaggarwal99 seeing now that this issue was fixed above (https://github.com/meshery/meshery/issues/176#issuecomment-517721505), I'll close this issue and open a new one for the misspelling issue.
