### ISSUE TITLE
[Docs] Invite Meshery Users to list presentations

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1762]
Add something like "Have you given a presentation? Add yours here!" with link to submit docs issue. Be inspired from here - https://linkerd.io/community/

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1726#r510296657_

**Comment by chandrashritii** [comment]
This has already been fixed in #1726 

![Screenshot_2020-10-27 Resources](https://user-images.githubusercontent.com/34476976/97326285-da82cc00-1899-11eb-8a00-f650e7f56f8b.png)

**Comment by leecalcote** [comment]
Oh, good deal. Please fix the mis-phrased sentence.

**Comment by chandrashritii** [comment]
Sure. Which sentence would that be? @leecalcote

**Comment by leecalcote** [comment]
"We'd love you to 'love'" - needs rephrased.
