### ISSUE TITLE
[Docs] Resources: book cover image is skewed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1763]
The book cover image is skewed.
<img width="258" alt="Screen Shot 2020-10-22 at 11 23 23 AM" src="https://user-images.githubusercontent.com/7570704/96901609-18768f00-1459-11eb-8bff-69b08bbf6490.png">

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1726#r510295544_

**Comment by chandrashritii** [comment]
This has already been fixed in #1726 

![Screenshot_2020-10-27 Resources(1)](https://user-images.githubusercontent.com/34476976/97326350-ecfd0580-1899-11eb-97bb-ba7060acb86f.png)

**Comment by leecalcote** [comment]
Thank you, @chandrashritii
