### ISSUE TITLE
[Meshery] Expose currently subscribed release channel name in System Dashboard.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1766]
@kushthedude, can you highlight what changes will need to be done in the build system in order to provide release channel name "stable" or "edge" as an environment variable, so that the `/api/server/version` endpoint can be enhanced to include the channel name?

- Dockerfile: https://github.com/layer5io/meshery/blob/3abaa633b14e331187396f32d36c7d5f1f55b989/Dockerfile#L3-L4
- GitHub action: https://github.com/layer5io/meshery/blob/3abaa633b14e331187396f32d36c7d5f1f55b989/.github/workflows/build-and-release.yml#L63

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1761#discussion_r511622200_

**Comment by kushthedude** [comment]
@uds5501 The following is a quick change, you may want to incorporate. Right now we are passing server release as a docker environment variable here https://github.com/meshery/meshery/blob/ab1567e3ae4836d8b4aaf3f5140895699fb52f95/.github/workflows/build-and-release.yml#L65 
But this is the case only with stable releases. So what needs to be done over here is whenever a edge version is built and pushed we should add an addition  `--build-arg GIT_VERSION="edge-latest"` here https://github.com/meshery/meshery/blob/ab1567e3ae4836d8b4aaf3f5140895699fb52f95/.github/workflows/build-and-release.yml#L55 ,

**Comment by uds5501** [comment]
@kushthedude consider it done

> @uds5501 The following is a quick change, you may want to incorporate. Right now we are passing server release as a docker environment variable here
> 
> https://github.com/meshery/meshery/blob/ab1567e3ae4836d8b4aaf3f5140895699fb52f95/.github/workflows/build-and-release.yml#L65
> 
> 
> But this is the case only with stable releases. So what needs to be done over here is whenever a edge version is built and pushed we should add an addition `--build-arg GIT_VERSION="edge-latest"` here
> https://github.com/meshery/meshery/blob/ab1567e3ae4836d8b4aaf3f5140895699fb52f95/.github/workflows/build-and-release.yml#L55
> 
> ,
