### ISSUE TITLE
[Docs] - Missing Images in Documentation Overview Section

### ISSUE THREAD

**Issue by akashprasher** [layer5io/meshery#1772]
**Current State:**

Missing Image of Logos in Documentation (https://meshery.layer5.io/docs/overview)

![image](https://user-images.githubusercontent.com/42891970/97443674-55f38480-1951-11eb-8480-06a9e0a23e0f.png)

**Desired State:**

These are the logos which supposed to appear in the documentation

![image](https://user-images.githubusercontent.com/42891970/97444290-fcd82080-1951-11eb-817b-66041c5dd3a3.png)
ScreenShot from [ReadMe.md](https://github.com/layer5io/meshery/blob/master/README.md)

**Possible Fixes**

1. Missing Logo Image can be fixed by changing the source. The same links for images can be used as they are used in the file [README.md](https://github.com/layer5io/meshery/blob/master/README.md)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by PluckyPrecious** [comment]
Hey @akashprasher are you on this?

**Comment by leecalcote** [comment]
Copying the logo files from either the meshery.io or the layer5.io site would work well here.

**Comment by akashprasher** [comment]
@PluckyPrecious No, not now but assign me in next 5-6 hours. If no-one else want to work on this.

**Comment by akashprasher** [comment]
Now, I'm on this!
