### ISSUE TITLE
[Docs] Translate "Functionality" section to Spanish

### ISSUE THREAD

**Issue by jlcastrogro** [layer5io/meshery#1776]
**Current State:**
Documentation is in English

**Desired State:**
Translate "functionality" section to Spanish

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by jlcastrogro** [comment]
I will to translate it :)

**Comment by leecalcote** [comment]
Excellent. 😄 Thank you, @jlcastrogro
