### ISSUE TITLE
Fix the icon of meshery chart

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#1784]
**Description**

![Screenshot from 2020-10-29 12-55-53](https://user-images.githubusercontent.com/8053949/97527366-175bd980-19e6-11eb-84d5-32e0aa42b14b.png)

**Expected Behavior**

![Screenshot from 2020-10-29 12-55-19](https://user-images.githubusercontent.com/8053949/97527343-07dc9080-19e6-11eb-912e-dedba0b22304.png)

Maybe we need the icon format and address like below
https://raw.githubusercontent.com/ceph/ceph-csi/v3.1.1/assets/ceph-logo.png

The icon address below:
https://raw.githubusercontent.com/layer5io/meshery/master/ui/public/static/img/meshery-logo/meshery-logo.svg

**Screenshots**

**Environment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
Collection of Meshery logos available in the community drive as well as here - https://meshery.io/brand

**Comment by Aisuko** [comment]
https://github.com/meshery/meshery.io/pull/365

**Comment by Aisuko** [comment]
The PR may not solve the issue, I have to check the reason
