### ISSUE TITLE
[Docs] `mesheryctl` installation instructructions for Brew

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1785]
**Current State:**
These three lines can be reduced to two lines.

<img width="677" alt="Screen Shot 2020-10-29 at 12 07 01 AM" src="https://user-images.githubusercontent.com/7570704/97528021-c236ae00-197a-11eb-8aeb-6fdbde9c5680.png">

**Desired State:**
Two lines should be:

```
brew install layer5io/mesheryctl
mesheryctl system start
```

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by abhishekkumkar** [comment]
@leecalcote can you assign this to me?

**Comment by AreebKhan619** [comment]
Hi! Would Like to work on this.

**Comment by leecalcote** [comment]
Hi @abhishekkumkar, thank you for volunteering. 👍 

Hi @AreebKhan619, good of you to jump in. There's more where this comes from here - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+label%3A%22help+wanted%22+

**Comment by abhishekkumkar** [comment]
@leecalcote sir can you please guide me, in which file do I need to do the changes?

**Comment by leecalcote** [comment]
@abhishekkumkar here you are - https://github.com/meshery/meshery/blob/master/docs/pages/installation/index.md
