### ISSUE TITLE
Create a Docker App for Meshery

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#179]
**Describe the solution you'd like**
CNAB compliant packaging of Meshery as a Docker App

**Is your feature request related to a problem? Please describe.**
Docker App will be a convenient way of sharing Meshery, it's adapters and their configuration. Some adapters, like the [meshery-octarine](https://github.com/layer5io/meshery-octarine) adapter have a number of environment variables necessary for the adapter to run.

**Functional design specification**
Doc - https://drive.google.com/open?id=1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0

**Comment by leecalcote** [comment]
@scotty-c is at bat here.

**Comment by scotty-c** [comment]
@leecalcote I will look at this later next week after Cloud Native Days NZ

**Comment by girishranganathan** [comment]
hello @scotty-c, do you have any updates for us here?

**Comment by girishranganathan** [comment]
Adding @nunix :)

**Comment by leecalcote** [comment]
@nunix, with the first version of this Docker App complete, we can tie-off this issue with an update to Meshery's docs regarding Docker App deployment.

**Comment by nunix** [comment]
yes will do 💯 once done, I will then do the other one for porter.
