### ISSUE TITLE
Mesheryctl system status gives empty output if meshery is not running

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1795]
**Description**

Mesheryctl system status gives empty output if meshery is not running
```sh
./mesheryctl system status
Meshery status...
Name   Command   State   Ports
```
**Expected Behavior**

It should give some descriptive response if meshery is not running

**Comment by tharun208** [comment]
I like to pick this up

**Comment by kushthedude** [comment]
Pr is already put up for the issue 😅.
