### ISSUE TITLE
ReleaseDrafter should use RELEASEDRAFTER_PAT  instead of GH_Token

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1799]
**Description**

It is a pain to copy-paste and manually makes releases, which completely is overwork gave we have releaseDrafter already installed.

**Expected Behavior**

Make releaseDrafter use Personal_Pat Token.

**Change to be made**

Change this line https://github.com/layer5io/meshery/blob/7dcb3445bedced319ff9b2a31bf1be20b89af523/.github/workflows/release-drafter.yml#L18 to 
```yaml
          GITHUB_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
```

**Comment by karleypetracca** [comment]
I'd like to take this one!

**Comment by leecalcote** [comment]
Thank you, @karleypetracca. 👍
