### ISSUE TITLE
Verify Meshery compatibility with AKS

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#180]
**Describe the solution you'd like**
Meshery compatibility with AKS has not been verified. Compatibility with this managed Kubernetes platform should be confirmed. Any changes needed should be flagged in an issue for implementation. [Platform Compatibility](https://meshery.layer5.io/docs/installation#platform-compatibility-) in the Meshery documentation should be updated to reflect compatibility.

**General Deployment Flow**
Install Meshery locally. Point to AKS cluster. Update documentation based on experience.

Steps:

1. Install Meshery locally. Use `mesheryctl` (or `meshery`) either of which runs all the services on `Docker` using `docker-compose`.
2. Open Meshery UI (http://localhost:9081).
3. Configure Meshery to use kubeconfig specific to the AKS deployment. [using the kubeconfig file mostly found in your $HOME/.kube/config (OR) by getting the config from `kubectl config view --raw > config` command]
3. Deploy each supported service mesh & a sample app in that environment using Meshery.
4. Performance test each supported service mesh in the environment using Meshery.
5. Create issues and update documentation with changes needed.

**Comment by leecalcote** [comment]
@scotty-c on point here.

**Comment by scotty-c** [comment]
@leecalcote I will look at this later next week after Cloud Native Days NZ

**Comment by scotty-c** [comment]
@leecalcote just started working on this today. Will update shortly

**Comment by leecalcote** [comment]
@chandresh-pancholi We're in need of getting this up promptly. Do you think you can have a draft PR'ed tomorrow? If not that's ok, we just need to plan accordingly.

**Comment by leecalcote** [comment]
@scotty-c we are getting closer here...

**Comment by leecalcote** [comment]
> @chandresh-pancholi We're in need of getting this up promptly. Do you think you can have a draft PR'ed tomorrow? If not that's ok, we just need to plan accordingly.

Is this something that you might be able to look at?
