### ISSUE TITLE
[Docs] Translate Architecture page to Spanish

### ISSUE THREAD

**Issue by Drake8710** [layer5io/meshery#1803]
**Current State:**
Actual Architecture page in available in English only

**Desired State:**
Architecture page translated to Spanish.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
I will assign it to you @Drake8710 😆
