### ISSUE TITLE
[Docs] Search feature is broken

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery#1838]
**Description**

Fix the search feature in Meshery docs

---
[Optional] **To Reproduce**
1. Go to 'https://meshery.layer5.io/docs/'
2. Try using the search bar

**Comment by EmmanuelTheCoder** [comment]
@chandrashritii, I just checked the search bar and they work fine.

**Comment by chandrashritii** [comment]
@EmmanuelTheCoder That's odd. The search feature has been broken since a few months. It's not working for me. Just to confim, you're talking about the search feature on  https://meshery.layer5.io/docs, right?
Also, if it is working for you, that's great. Can you post a screenshot?
