### ISSUE TITLE
[UI] Add Documentation, Issue, Community, Mailing List links

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1855]
### Current Behavior
Meshery's UI doesn't provide convenient links to frequently referenced resources.

### Desired Behavior
Meshery's UI should have the following links:

- documentation - http://docs.meshery.io (not https)
- community - http://slack.layer5.io (not https)
- mailing list - https://meshery.io/subscribe
- issue - https://github.com/layer5io/meshery/issues/new/choose

### Mockups
![Frame 2-2](https://user-images.githubusercontent.com/7570704/98040966-d0575500-1de6-11eb-940f-55155b267e56.png)

**Comment by KarenEfereyan** [comment]
@leecalcote the links change to https on clicking, though. How can that be fixed? Plus I just got some time on my hands so I'll get to that other pending task of mine today

**Comment by leecalcote** [comment]
@KarenEfereyan good question regarding. http --> https - that behavior is by design and intended. If you try to visit https on those links directly, you'll likely find that they don't work.

**Comment by leecalcote** [comment]
@Surajbokde interested in picking this one up?

**Comment by chebro** [comment]
Hi, I would like to contribute!

**Comment by chebro** [comment]
I just ran the ui server, and I have a quick question, should the new links be appended below the current "community" link or should they replace it?

<img src="https://user-images.githubusercontent.com/54331348/98340675-be1e2680-2033-11eb-88ea-4cf019807002.png" width="400">

**Comment by Nikhil-Ladha** [comment]
Hi @chebro , In the issue description the links are mentioned and 'community' is one of them but with a different link. So, you can remove this community link and add the 'community' option with the link in the issue description. :)

**Comment by chebro** [comment]
I've created a PR! 

PS: I think I've signed the commit with my GPG key, which uses github's private email. If that is a problem let me know, I'll force push a new commit.

**Comment by PluckyPrecious** [comment]
> I've created a PR!
> 
> PS: I think I've signed the commit with my GPG key, which uses github's private email. If that is a problem let me know, I'll force push a new commit.

It’s perfectly okay 👌🏽
