### ISSUE TITLE
Floating Label collapse to textField irrespective of input value

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1865]
**Description**

Floating Label collapse to textField irrespective of the input value
**Expected Behavior**

Floating Label should not collapse when input is present
**Screenshots**

<img width="940" alt="Screenshot 2020-11-06 at 6 28 00 AM" src="https://user-images.githubusercontent.com/44091822/98313206-58ad4400-1ff9-11eb-9991-6bf608daee01.png">

**Comment by leecalcote** [comment]
@kushthedude would you like to tackle this one?
