### ISSUE TITLE
[Docs] Broken Link

### ISSUE THREAD

**Issue by akashgp09** [layer5io/meshery#1876]
**Current State:**

The **Service Mesh Day** link is broken in README file

<img src="https://i.ibb.co/jD4pD00/Whats-App-Image-2020-11-07-at-22-35-21.jpg"/>

**Desired State:**

Update it to https://servicemeshday.com/schedule.html

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Yashs911** [comment]
Hi @akashgp09 I would like to work on this issue
