### ISSUE TITLE
[Docs] Use of Scoop as the Windows package manager to install mesheryctl 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1879]
**Current State:**
Meshery's documentation for Windows installations does not highlight the [`mesheryctl` Scoop package](https://github.com/layer5io/scoop-bucket) as one that is available. 

**Desired State:**
Two pages need updated:

1. the [Using mesheryctl](https://meshery.layer5.io/docs/guides/mesheryctl#windows) guide to suggest using Scoop first, before suggesting that the binary can been directly downloaded (direct download should be the catch-all option). 
1. the [Windows platform page](https://meshery.layer5.io/docs/installation/platforms/windows) should highlight that installing `mesheryctl` is the first step to deploying Meshery.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@tripathyprateek any luck here?

**Comment by tripathyprateek** [comment]
Yes @leecalcote I tried it on my local machine and it works. I will make required changes in the Docs and update accordingly. Sorry I was blocked with other works for a while.

**Comment by favourch** [comment]
Any luck here?

**Comment by leecalcote** [comment]
@favourch, you’re help in documenting and testing this is much appreciated.

**Comment by leecalcote** [comment]
@favourch would you like to try your hand at this?

**Comment by favourch** [comment]
I'm on it @leecalcote . I'll reach out for clarity on expectations on the slack channel.

**Comment by leecalcote** [comment]
Awesome. Thank you, @favourch

**Comment by favourch** [comment]
@leecalcote It looks like a lot has changed in the codebase because I cant seem to navigate to `/docs/guides/mesheryctl#windows `

**Comment by leecalcote** [comment]
@favourch no sweat. I think we have this covered now. I'll close this issue now. if you don't find scoop info in the docs, please reopen this issue.
