### ISSUE TITLE
[mesheryctl] `system config` assumes user's OS is Mac or Linux

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1894]
**Description**
`mesheryctl system config aks` configure access to an AKS cluster using the `az` cli. It writes a kubeconfig file to `/tmp`, which is not a filesystem location that is compatible with Windows.
The same is the case with other Kubernetes provider like minikube & GCP, all the scripts should be OS-Aware and should handle the stuff.

**Expected Behavior**
All `mesheryctl` commands should be OS-agnostic or take the OS into considering and support each OS specifically.

**Environment:**
- Host OS: Windows
- Meshery Version: v0.4.18

**Solution:**
This issue can be solved by writing the kubeconfig file to the same location of other Meshery application files: `$HOME/.meshery`

**Comment by leecalcote** [comment]
@hexxdump will you review the state of these config scripts and assess where we have OS-specific gaps?

**Comment by hexxdump** [comment]
> @hexxdump will you review the state of these config scripts and assess where we have OS-specific gaps?

yes @lee, there are few instances where the Windows vs Mac/Linux differences are there. I will check how we can tackle this problem.

**Comment by leecalcote** [comment]
Thank you, @hexxdump. 😄

**Comment by hexxdump** [comment]
The issues are happening due to the fact that TARGET_FOLDER is defined to be "$HOME/.meshery" in all cases minikube/GKE/AKS/EKS. Need to change this to consider all OSes. Working on a fix.
