### ISSUE TITLE
[mesheryctl] `system config aks` kubeconfig generation script does not honor temp location or filename

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1896]
**Description**
See func [GenerateConfigAKS()](https://github.com/layer5io/meshery/blob/master/mesheryctl/pkg/utils/scripts.go#L134)

**Expected Behavior**
The value set [here](https://github.com/layer5io/meshery/blob/master/mesheryctl/internal/cli/root/system/config.go#L185) should be used in the func GenerateConfigAKS().

**Comment by kushthedude** [comment]
It does honor the same file name and location

**Comment by kushthedude** [comment]
Can you retry, it generates the file in same location and list the contexts to choose b/w?

**Comment by leecalcote** [comment]
Perhaps, the issue is that this variable is errant and not used?
```
		configPath := "$HOME/.meshery/aks-kubeconfig.yaml"
```

**Comment by kushthedude** [comment]
This variable is only used while searching for contexts in the config file
created. All the three scripts have dynamic file location naming in the
script itself rather than passing this variable. As script needs to create
directory if not found can be the reason this variable is not passed.

**Comment by kushthedude** [comment]
Oh, sorry for the misunderstanding the variable needs to be changed to honor the latest script.

**Comment by leecalcote** [comment]
Couple other considerations:

1) avoid writing file to temp location altogether. manipulate contents in memory and write to Meshery's app folder (~/.meshery) when final product is ready, if you can.
2) consider the OS/arch when both interfacing with the filesystem and when running the bash script.
