### ISSUE TITLE
[UI] Add external link icon to four navigation menu items

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1897]
**Current Behavior**
The four hyperlinks to the left of the vertical, red rectangle highlighted in the screenshot all lead to external URLs. 

**Desired Behavior**
Each of these should carry an external link icon on their (upper) right hand side.

<img width="74" alt="Screen Shot 2020-11-09 at 7 57 06 PM" src="https://user-images.githubusercontent.com/7570704/98617947-c4c3cc80-22c5-11eb-8c8b-bc6ad01bb381.png">

### Screenshot
<img width="1949" alt="Screen Shot 2020-11-09 at 7 51 14 PM" src="https://user-images.githubusercontent.com/7570704/98618055-fb014c00-22c5-11eb-87f9-01a69512b496.png">

**Comment by KarenEfereyan** [comment]
OKay, so the link image icon should be used to contain the external link and the actual text should not be a link, right?

**Comment by KarenEfereyan** [comment]
What file is this in @leecalcote ? I mean the code?

**Comment by leecalcote** [comment]
The actual text is and should be a hyperlink. The icon is a user experience improvement to set expectations with the user that when they click, they will navigated to an external site.￼￼

**Comment by Sudhish2101** [comment]
I have added the external link icons. Comments.

**Comment by KarenEfereyan** [comment]
> I have added the external link icons. Comments.

Great. Ill take a look
