### ISSUE TITLE
[CI] Broken link in PR Template

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1905]
**Description**
Please see https://github.com/layer5io/layer5/issues/1131#issue-740013639.

**Expected Behavior**
The PR template in this repository needs updated.

**Comment by leecalcote** [comment]
@Aniruddha-Shriwant help!

**Comment by Aniruddha-Shriwant** [comment]
Will make a PR soon :)

**Comment by Aniruddha-Shriwant** [comment]
Done @leecalcote 😉
