### ISSUE TITLE
[UI] Error while starting a mesh on UI does not provide detailed logs 

### ISSUE THREAD

**Issue by nikita15p** [layer5io/meshery#1909]
**Current Behavior**
get `exit status 1` error when deploying a mesh  on  meshery UI at http://localhost:9081/management. Meshery has detected a kind cluster and then I tried to deploy osm , kuma, instio mesh. 
Environment: mesheryctl downloaded for windows machine from [here](https://github.com/layer5io/meshery/releases/download/v0.4.19/mesheryctl_0.4.19_Windows_x86_64.zip)

**Desired Behavior**
Expectation is to start the mesh or give detailed error instead of throwing `exit status 1` 

---
[Optional]

### Mockups

![exit status](https://user-images.githubusercontent.com/37657012/98815743-9ec93400-244d-11eb-9b7f-4c21f802f2e5.PNG)

**Comment by leecalcote** [comment]
Good highlight, @nikita15p. As a small item, would you mind opening a copy of this issue in the respective adapter repos?

**Comment by leecalcote** [comment]
@kumarabd is an Istio v1.5.1 issue open on the adapter for Istio?

**Comment by leecalcote** [comment]
Fixed
