### ISSUE TITLE
[Charts] Consistent hyphenation for helm chart names

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1912]
@Aisuko thanks for this. It would be great if we can revisit the other charts and update their names to include consistent hyphenation (e.g. meshery-consul)

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/1900#discussion_r521516040_

**Comment by Aisuko** [comment]
> @Aisuko thanks for this. It would be great if we can revisit the other charts and update their names to include consistent hyphenation (e.g. meshery-consul)
> 
> _Originally posted by @leecalcote in [#1900 (comment)](https://github.com/meshery/meshery/pull/1900#discussion_r521516040)_

No problems.

**Comment by Aisuko** [comment]
Bump the charts version and add new charts to the Artifact Hub
https://github.com/meshery/meshery.io/pull/376
