### ISSUE TITLE
[UI] Issue with latest mui-datatables 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1915]
**Description**
With the latest version of this library, the facet to toggle the display of the sub-table here crashes the performance results page:

![Untitled](https://user-images.githubusercontent.com/7570704/98890202-0a68cc80-2461-11eb-8486-ef21ff670e00.gif)

**Comment by leecalcote** [comment]
@ramrodo an example of a dependent library update causing failures - https://github.com/meshery/meshery/pull/1883

**Comment by leecalcote** [comment]
Frustrating as this issue only seems to manifest itself when the UI is built into a Docker container.

**Comment by ramrodo** [comment]
Ok, I'll take a look at that issue building with Docker

**Comment by ramrodo** [comment]
Hey @leecalcote, I updated the **mui-datatables** package and I can not reproduce the issue. Maybe it was due to something else. I just created this [PR#1925 ](https://github.com/meshery/meshery/pull/1925) to upgrade it (without having issues)

**Comment by leecalcote** [comment]
You're right in that there were 5 or so dependency updates happening at about the same time. My suspicion now lies within the billboard.js package...
