### ISSUE TITLE
Preconfiguration UI tweaks

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#192]
**Description**
Meshery UI needs two changes to improve the description of its functionality and to better indicate to users which screen they are currently on or navigating to.

Two changes highlighted in red in screenshot.
![Screen Shot 2019-08-07 at 8 12 45 AM](https://user-images.githubusercontent.com/7570704/62626097-31defa00-b8ec-11e9-9865-3e8286891968.png)

**Comment by leecalcote** [comment]
@Nikhil-Ladha PR #230 does a good job of knocking out the first enhancement requested in this issue.

The second enhancement request may not be as obvious, since I posted a mockup of the "after" version of what is being asked for. Here is a "before" screenshot:

<img width="1031" alt="Screen Shot 2019-08-25 at 11 35 47 AM" src="https://user-images.githubusercontent.com/7570704/63652995-a14a4b80-c72c-11e9-9a15-47fe755fde20.png">

Notice that the gear icon is missing next to the "Configure playground" text. For the second portion of this enhancement, could you add the gear icon next to the button text?

Also, while we're making tweaks here, let's add a third enhancement: change the text from "Configure playground" to "Configure Settings". Could you make this update as well?

Thanks for working on this, @Nikhil-Ladha.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha PR #230 does a good job of knocking out the first enhancement requested in this issue.
> 
> The second enhancement request may not be as obvious, since I posted a mockup of the "after" version of what is being asked for. Here is a "before" screenshot:
> 
> <img alt="Screen Shot 2019-08-25 at 11 35 47 AM" width="1031" src="https://user-images.githubusercontent.com/7570704/63652995-a14a4b80-c72c-11e9-9a15-47fe755fde20.png">
> 
> Notice that the gear icon is missing next to the "Configure playground" text. For the second portion of this enhancement, could you add the gear icon next to the button text?
> 
> Also, while we're making tweaks here, let's add a third enhancement: change the text from "Configure playground" to "Configure Settings". Could you make this update as well?
> 
> Thanks for working on this, @Nikhil-Ladha.

Yeah, sure will do that as well
