### ISSUE TITLE
[Docs] Add latest Meshery Release Notes to Docs Releases page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1926]
**Current State:**
The Documentation's [Release page](https://meshery.layer5.io/docs/project/releases) is missing entries for the latest Meshery releases.

**Desired State:**
[Release Notes](https://github.com/layer5io/meshery/releases) can be copied and pasted into the docs.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
This activity needs a volunteer to automate it - https://github.com/meshery/meshery/issues/510

**Comment by ayushk1804** [comment]
Our [GitHub release version](https://github.com/meshery/meshery/releases) is at 0.4.22, while according to the [Meshery website release page](https://meshery.layer5.io/docs/project/releases), it's at 0.4.4. Is that an error, and needs to be fixed along with adding updated release notes?

**Comment by leecalcote** [comment]
@ayushk1804, nope. We need to add entries in the docs for all the releases between v0.4.4 and v0.4.22

**Comment by ezioishan** [comment]
Hey @leecalcote , I would like to work on this issue.

**Comment by leecalcote** [comment]
Thank you, @ezioishan

**Comment by ezioishan** [comment]
I have added all the necessary release info

**Comment by leecalcote** [comment]
Good work here, @ezioishan
