### ISSUE TITLE
Request to join the organisation

### ISSUE THREAD

**Issue by akshitagupta15june** [layer5io/meshery#1929]
**Current Behavior**

**Desired Behavior**

---
[Optional]

**Comment by shivaylamba** [comment]
@akshitagupta15june We request you to make some contributions to the organization and the projects before getting an invitation to the Org. You can join our slack : http://slack.layer5.io/
And look at our welcome guide : https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit

**Comment by leecalcote** [comment]
Hi @akshitagupta15june, I welcome you to join the Meshery Community - http://slack.meshery.io. It's warm and welcoming. Please jump in! Additional information and resources about the community and it's projects available here - https://meshery.io/community

**Comment by kushthedude** [comment]
In addition to what @leecalcote, you need to contribute to the community either code-based, documentation based, or whatever is your expertise to get an invitation for the organization.
Hoping to see you hop in our slack 😄 !
