### ISSUE TITLE
[UI] Collapsible Help button on Meshery UI

### ISSUE THREAD

**Issue by tripathyprateek** [layer5io/meshery#1947]
**Current Behavior**

**Desired Behavior**

Instead of having 3 buttons for help, all of them would be under a collapsible Help button in the left side nav
---
[Optional]

**Comment by kushthedude** [comment]
Any screenshot of which page this is talking about 😄?

**Comment by tripathyprateek** [comment]
> Any screenshot of which page this is talking about 😄?

I had a discussion with @leecalcote over this. A help button on the leftside nav bar on the Meshery UI page below all the adapters needs to be added so that anyone having problems with Meshery can troubleshoot.

**Comment by leecalcote** [comment]
Collapsing of these underneath a Help icon 
<img width="264" alt="Screen Shot 2020-11-19 at 12 36 20 PM" src="https://user-images.githubusercontent.com/7570704/99708763-dba3b500-2a63-11eb-8d93-710afe6588fd.png">

**Comment by leecalcote** [comment]
@tripathyprateek it would be good to propose a design here (a simple / quick mockup)

**Comment by tripathyprateek** [comment]
> @tripathyprateek it would be good to propose a design here (a simple / quick mockup). The Help icon could oppose the collapse arrow, potentially.

yes Lee. A arrow opposing the collapse arrow was what I had in my mind which expands to show all the links upon hovering.

**Comment by leecalcote** [comment]
Let's stick with the Material UI elements for now. If you would, have a look at the button and effect used in the lower, righthand corner - https://imgur.com/D9DSyuk. We won't want the same ripple effects, nor necessarily floating effect of the main button itself, but having the four help links (with just icons) expand out to the right (if a Help icon button is in the lower, lefthand corner) might work out very well. Here's the site - https://github.com/jameshamann/jekyll-material-theme

**Comment by tripathyprateek** [comment]
> Let's stick with the Material UI elements for now. If you would, have a look at the button and effect used in the lower, righthand corner - https://imgur.com/D9DSyuk. We won't want the same ripple effects, nor necessarily floating effect of the main button itself, but having the four help links (with just icons) expand out to the right (if a Help icon button is in the lower, lefthand corner) might work out very well. Here's the site - https://github.com/jameshamann/jekyll-material-theme

Yes @leecalcote I will be using the Material UI elements and won't add the ripple effects.

**Comment by leecalcote** [comment]
@tripathyprateek any luck?

**Comment by tripathyprateek** [comment]
@leecalcote yes I got  it working when the nav bar is expanded but its not working when its smaller. Havent worked on it lately due to exams.
