### ISSUE TITLE
[Docs] `mesheryctl system config eks` documentation published prematurely

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1951]
**Current State:**
Currently, `mesheryctl` does not have such a command. Docs for this command were published prematurely and should be removed until this command is released.

**Desired State:**
Manual instructions for any special considerations for an EKS should be shown.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by ameyaagashe** [comment]
Would be a nice feature to have a copy icon to each command for this page:
https://meshery.meshery.io/docs/installation/platforms/eks

Desired Behaviour:
One click on "Copy" icon, would copy the command.

Current Behaviour:
Select the text and then do Ctrl + C to copy the command.

**Comment by leecalcote** [comment]
@ameyaagashe agree - https://github.com/meshery/meshery/issues/1269

**Comment by ameyaagashe** [comment]
https://meshery.meshery.io/docs/installation/platforms/eks
Step 4. should read as meshery token like below:
kubectl describe secret  meshery-token-5z9xj

**Comment by ameyaagashe** [comment]
Any update on this ticket?

**Comment by leecalcote** [comment]
Feature released.

**Comment by leecalcote** [comment]
Fixed in v0.5.0
