### ISSUE TITLE
[Docs] Side contents menu doesn't display sub-headings on the page

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1953]
**Current State:**
Side contents menu doesn't display sub-headings on the page

<img width="1204" alt="Screenshot 2020-11-20 at 1 04 23 AM" src="https://user-images.githubusercontent.com/44091822/99715042-5ef8f100-2acc-11eb-8a70-cb7627deb0a7.png">

**Desired State:**

Sub-headings in the given page should be listed on the side-menu for better UX and better navigation through the page.
<img width="1192" alt="Screenshot 2020-11-20 at 1 04 38 AM" src="https://user-images.githubusercontent.com/44091822/99715058-61f3e180-2acc-11eb-9c2f-62acd5223b3e.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@chandrashritii do you have progress to report here?

**Comment by leecalcote** [comment]
@chandrashritii each of the pages that you're updating need to include an h1, h2, h3, and so on in sequence otherwise the TOC won't generate and show.
