### ISSUE TITLE
[CI] Notify Slack on Star of GitHub Repo workflow broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1954]
**Description**
When a GH user stars one of the `layer5io` repos, a notification will be sent to the #buzz channel in the community Slack. The [slack.yaml workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/slack.yml) is currently broken.

**Logs**
See the logs from [this workflow run](https://github.com/layer5io/meshery/actions/runs/372398164):

```
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by vineethvanga18** [comment]
@leecalcote The `set-env`  is deprecated now
