### ISSUE TITLE
brew installation does not work

### ISSUE THREAD

**Issue by jiraguha** [layer5io/meshery#1956]
**Description**

`brew install layer5io/mesheryctl` does not work for me. Nothing specific happens. I see no mesheryctl binary in `brew list`
**Expected Behavior**

expect `mesheryctl version` to work!
**Screenshots**

**Environment:**
- Host OS: Mac OS X 10.15.7 x86_64
- Meshery Version: N/A
- Brew: Homebrew 2.5.11
---
[Optional] **To Reproduce**
1. use `brew install layer5io/mesheryctl`
2. Tip on `mesheryctl version`

[Optional] **Additional Context**

Maybe I am the only only one having this issue?

**Comment by leecalcote** [comment]
@jiraguha thank you for raising this issue. Will you paste the output of the `brew install meshery/mesheryctl` command here? // @kushthedude

**Comment by kushthedude** [comment]
Are you sure you tapped the meshery/tap before installing?

**Comment by jiraguha** [comment]
Ho, sorry, I had more logs shown the first time I tried. Now I have only:
```
❯ brew install meshery/mesheryctl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
==> Updated Casks
appcode-eap
```

not sure it help!

**Comment by kushthedude** [comment]
> Are you sure you tapped the meshery/tap before installing?

@jiraguha

**Comment by leecalcote** [comment]
@kushthedude Meshery's instructions do not include the `tap` command explicitly, but are trying to be as concise as possible and use `meshery` in the `install` command to assist with the potentially missing tap.

**Comment by jiraguha** [comment]
@kushthedude. I have just tapped and nothing! In my previous attempt I did... but If tap was needed I would assume to have a specific error showing that I need to tap?

**Comment by leecalcote** [comment]
@jiraguha if you run `brew tap meshery/homebrew-tap`, then install, does this help?

**Comment by jiraguha** [comment]
> @jiraguha if you run `brew tap meshery/homebrew-tap`, then install, does this help?

No :-/ 

I moved to the bash installation which works :-)

**Comment by kushthedude** [comment]
@jiraguha Please do 
```sh
brew tap meshery/tap
brew install mesheryctl
```

**Comment by jiraguha** [comment]
Great this works! Even if I have conflic with my bash installation which was waited. Thanks.

Maybe the doc should include tap process.

**Comment by kushthedude** [comment]
Thanks for confirming @jiraguha , I guess we need some docs update.
/cc @leecalcote @chandrashritii

**Comment by leecalcote** [comment]
Thank you, gents! Yes, indeed. @chandrashritii, will you kindly have issues opened for meshery.io, docs.meshery.io and meshery.io/meshery to include the tap command?
