### ISSUE TITLE
Another Sample application from Google to use?

### ISSUE THREAD

**Issue by sakomws** [layer5io/meshery#197]
**Feature Request**
Add to the collection of supported sample apps by including Google's microservices demo app: 
https://github.com/GoogleCloudPlatform/microservices-demo

**Comment by leecalcote** [comment]
Sounds great, @sakomws. Good suggestion.

**Comment by girishranganathan** [comment]
I will try to explain the steps needed to add this application as a sample, please feel free to propose changes:

~1. checkout the https://github.com/GoogleCloudPlatform/microservices-demo repo: `git clone https://github.com/GoogleCloudPlatform/microservices-demo`~
~1. install skaffold following instructions from: `https://skaffold.dev`~
~1. from inside the checked out folder `microservices-demo` run `skaffold build`, which will just build all the needed docker images from the source code~
~1. You should now have the following docker images in your local:~
    - ~emailservice~
    - ~productcatalogservice~
    - ~recommendationservice~
    - ~shippingservice~
    - ~checkoutservice~
    - ~paymentservice~
    - ~currencyservice~
    - ~cartservice~
    - ~frontend~
    - ~loadgenerator~
    - ~adservice~
~1. Now we need to tag each of these with a sensible name under `meshery/` docker org. A prefix like `meshery/google-demo-` might be good.~
~1. now update each of the individual `kubernetes-manifests` files with the new image name~

We came across the releases folder which contains manifests with images managed by Google themselves [here](https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/release).

1. Now that we know where to grab the manifests from, lets start with one adapter, `meshery-istio` for instance.
1. In the supported_operations.go file, we will have to add a new sample application, associate it with SAMPLE_APPLICATION category
1. In istio.go or a suitable file, we will have to write a method/function which will grab the 2 yaml files from this folder [here](https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/release), put them together and return the new yaml
1. In the istio.go file, in the ApplyOperation method, we will have to update the switch case to include an extra case for this new operation
1. In that case block we will call the new method we created above to get the complete yaml

The rest of the flow is in place and they will take care of the rest.

**Comment by subhamkrai** [comment]
Okay

**Comment by leecalcote** [comment]
@subhamkrai do you have any outstanding changes left on https://github.com/meshery/meshery-istio/pull/19? @girishranganathan, I think we're ready for a final review of PR19.
