### ISSUE TITLE
Notification menu icon misaligned

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#199]
**Description**
The Notifications icon falls out of alignment with other icons.

**Steps to Reproduce**
When you adjust the zoom in your browser, it becomes obvious that the notification icon is out of alignment.

**Screenshots**
<img width="244" alt="Screen Shot 2019-08-12 at 10 14 35 AM" src="https://user-images.githubusercontent.com/7570704/62876284-3b9c9f00-bcea-11e9-92bf-1c857c52de0e.png">

**Enviroment:**
 - Browser: Safari 12
Does not happen in Chrome.

**Comment by leecalcote** [comment]
Could be a good one for @cruiser1789...

**Comment by wdtamagi** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
@wdtamagi yes, please. That would be lovely.

**Comment by leecalcote** [comment]
@wdtamagi if you'll jump on this Slack, we'll be sure to get you engaged in the community and any help that you need— http://slack.meshery.io

**Comment by wdtamagi** [comment]
Thanks @leecalcote !
