### ISSUE TITLE
[UX] Non-human readable error message: kubeconfig read failure

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1992]
**Description**
This error message (in the screenshot below) is shown to users in a toaster notification. This message is shown when the user is initializing Meshery.

**Expected Behavior**
Notifications shown to users should be human-readable. The contents of this notification need to be replaced or this notification not given to the user.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/7570704/100543070-975aa680-3213-11eb-9af0-b07a4acbc7aa.png)

**Comment by utkarsh-pro** [comment]
@leecalcote I think this particular notification is generated only upon user interaction (it's a feedback notification), so should we remove it? In case of modifying the error notification, should "Kubernetes config could not be validated" part be changed or the message after it?
