### ISSUE TITLE
[mesheryctl] `system config` throws no such file or directory error 

### ISSUE THREAD

**Issue by uds5501** [layer5io/meshery#1993]
**Description**

I am trying to run meshery with minikube following the startup guide. According to the instructions, I downloaded the `auth.json` file and ran `mesheryctl system config minikube -t ~/Desktop/auth.json` which throws the following error stack:

```
/home/uddeshya/Desktop/auth.json
Error getting contexts : open $HOME/.meshery/aks-kubeconfig.yaml: no such file or directory
```

**Expected Behavior**

Expected it to work without any errors

**Screenshots**

![Screenshot from 2020-11-29 20-21-42](https://user-images.githubusercontent.com/21087061/100545160-94e26600-3280-11eb-8629-533a8e3b91be.png)

**Environment:**
- **Host OS**: Ubuntu 20.04
- **Meshery Version**: 
Client Version: 0.4.24 	  GitSHA: 8a95887a4c4ff9681d8c27ad8d3a83840f8524c8
Server Version: v0.4.24 	  GitSHA: 8a95887

- **Kubernetes Version**: 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- **Browser**: Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)

---
[Optional] **To Reproduce**
1. `minikube start --driver=docker`
2. `mesheryctl system start`
3. `mesheryctl system config minikube -t ~/Desktop/auth.json`

**Comment by kushthedude** [comment]
Already fixed, release is to be made hence the error
