### ISSUE TITLE
[mesheryctl] Duplicate listing of meshery config file location in global flag help

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1994]
**Description**
The help text under the Global Flag section of `mesheryctl` lists the location of the Meshery configuration file twice:

```
Usage:
  mesheryctl system update [flags]

Flags:
  -h, --help   help for update

Global Flags:
      --config string              config file (default location is: /Users/lee/.meshery/meshery.yaml)
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: /Users/lee/.meshery/mesheryctlConfig.yaml) (default "/Users/lee/.meshery/mesheryctlConfig.yaml")
```

**Expected Behavior**
This file location should only be shown to the user once in this output.

- Meshery Version: v0.4.24

**Comment by kushthedude** [comment]
There are two files indeed, meshery config used as the dockerCompose file and mesheryCtl config which has hard-coded configs for CLI tool.

**Comment by uds5501** [comment]
@kushthedude I'd like to take this one!
