### ISSUE TITLE
Create appropriate interfaces for different meshes to plugin their implementations

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#2]

**Comment by girishranganathan** [comment]
Hello @rootsongjc, thx for your interest in this project. 
This project was initially meant as a learning tool for the Istio workshops we had presented. Now we are in the process of converting it into a tool/platform for performance analysis. 
I noticed you have forked this project which is wonderful but please be aware that we will making quite a few breaking changes to update its course to meet the project goals and also to make it easier for integrating other meshes into it.
Feel free to reach out to me on slack/github if you have any thoughts, questions or feedback.

**Comment by girishranganathan** [comment]
Hello @rootsongjc, we have made some initial progress in cleaning the code a bit. Adding support for a new mesh should be reasonably straight forward now.

The instructions to add support for a new mesh at the moment:
- create a folder for your mesh under the `meshes` directory
- create an implementation for the interface in the `meshes/mesh_client_interface.go`.
- create an instance of your new type in the `cmd/main.go` file
- pass it to the ServerConfig

We will continue to work on making this experience better. 

Please feel free to reach out to me or @leecalcote with any questions/suggestions you have at anytime.

**Comment by rootsongjc** [comment]
@girishranganathan [SOFAMesh](https://github.com/alipay/sofa-mesh) is forked from istio, it will be merged to upstream in the future, so I want to delay the test for SOFAMesh. I hope you can understand.
