### ISSUE TITLE
[Docs] Copy-to-clipboard copies $ along with the code snippet

### ISSUE THREAD

**Issue by chebro** [layer5io/meshery#2007]
**Current State:**
The [clipboardjs](https://clipboardjs.com) feature incorporated doesn't work as expected, it copies the whole code segment including the `$`. This defeats the purpose of issue #1269, who's goal was to aid the user in not copying the `$` by accident.

**Desired State:**
Improve the reader experience for Meshery CLI commands, by only copying the code snippet, excluding the `$`.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Great point, @chebro.

**Comment by leecalcote** [comment]
@chebro would you like to work on this or is @chandrashritii?

**Comment by chebro** [comment]
> @chebro would you like to work on this or is @chandrashritii?

I can take a stab at this :)
