### ISSUE TITLE
[UI] Collapsed NavBar not showing External Links properly

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/meshery#2008]
**Description**

![image](https://user-images.githubusercontent.com/44001539/100670133-75346600-3384-11eb-921a-096e41eaaf57.png)

**Expected Behavior**

**Screenshots**

**Environment:**
- Browser: Chrome

---
[Optional] **To Reproduce**
1. Go to meshery
2. Click on collapse navigation

[Optional] **Additional Context**

**Comment by uds5501** [comment]
@dhruv0000 not reproducible in my local system
![image](https://user-images.githubusercontent.com/21087061/100716607-eef93d80-33de-11eb-856e-fe914f8b96da.png)

**Comment by kushthedude** [comment]
Try wide screen @uds5501

**Comment by uds5501** [comment]
@kushthedude looks like it's more of a zoom in and zoom out issue

**Comment by uds5501** [comment]
@kushthedude I'd like to pick this one up, will it be fine to resize the navbar to accomodate the external links or should the external links be resized to fit into current navbar size (if it's possible)

**Comment by kushthedude** [comment]
> @kushthedude I'd like to pick this one up, will it be fine to resize the navbar to accomodate the external links or should the external links be resized to fit into current navbar size (if it's possible)

@dhruv0000 @leecalcote what do you suggest over here? Both would work for me.

**Comment by dhruv0000** [comment]
If you can make the external link icon smaller and align it on the top right, it would be great (if possible). If not, resizing the navbar to accommodate the external links looks good.

**Comment by uds5501** [comment]
@dhruv0000 got it, will give it a try and will ping here for any queries.
