### ISSUE TITLE
[mesheryctl] unable to ping kubernetes error

### ISSUE THREAD

**Issue by uds5501** [layer5io/meshery#2010]
**Description**

I am unable to ping Kubernetes even when uploading system configs.
Configs tried : 
- kind
- minikube

**Expected Behavior**

It should give "pinged successfully"

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/100709402-0d0d7080-33d4-11eb-91c7-4437f4509013.png)

**Environment:**
- Host OS:  Ubuntu 20.04
- Meshery Version: 
Client Version: 0.4.24 	  GitSHA: 8a95887a4c4ff9681d8c27ad8d3a83840f8524c8
Server Version: v0.4.25 	  GitSHA: 6b23b79
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- Browser: Chrome

**Comment by leecalcote** [comment]
@uds5501 have a peak at this diagram - https://docs.google.com/drawings/d/1t40B6sn7RVH3z0ZVOvFD4wxv8YXemyq5JlHugy9_x7A/edit?usp=sharing

**Comment by leecalcote** [comment]
Also, give this a shot: `docker network connect bridge meshery_meshery_1`

**Comment by leecalcote** [comment]
@uds5501 you and I have a date on tomorrow's Newcomers call. Let's get you over this hump.

(yes, I said a "date" 😉 )
