### ISSUE TITLE
[UI] MeshSync: Include list of existing namespaces in /management namespace text field

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2015]
**Current Behavior**
The individual service mesh management pages have a namespace field with "default" prepopulated. 

**Desired Behavior**
The namespace field should not only show "default" as an option, but should also include the list of namespaces that are currently present in the user's Kubernetes environment. Pre-populating this text field will be a UX improvement and it will also help with cleanliness of input.

In general, the namespace field should be behave similarly as to how the "Mesh Adapter URL" field functions on the Settings page - http://localhost:9081/settings#service-mesh

**Implementation**
Using the MeshSync endpoint at `/api/mesh/scan` (e.g. http://localhost:9081/api/mesh/scan), populate the Namespace field (shown in the screenshot below) with the namespaces returned in this API.

<img width="1775" alt="Screen Shot 2020-12-01 at 3 05 51 PM" src="https://user-images.githubusercontent.com/7570704/100796915-f9b7d080-33e6-11eb-8075-503369f1eae2.png">

- List "default" in light gray text as the default value for this text field.
- Enhance text field to include a dropdown selector as well as text from the user.

# Acceptance Tests
1. User can type in a string of a new namespace.
1. User can select the name of any existing namespace.
1. If no namespace is returned in the MeshSync API, show "default" in the text field.
1. Namespaces should be alphabetically ordered.
1. If one or more namespaces are returned in the MeshSync API, show the first namespace as the select item.

**Comment by Keenal** [comment]
I would like to take up this issue.

**Comment by leecalcote** [comment]
Very good!

**Comment by MaximeCoignus** [comment]
Hi @leecalcote,

Can I also work on this issue?

**Comment by leecalcote** [comment]
Nice to hear of your collaboration here, @Keenal and @MaximeCoignus

**Comment by DeveloperAspire** [comment]
Is this Issue from Meshery Websites or the Documentation?

**Comment by Keenal** [comment]
> Is this Issue from Meshery Websites or the Documentation?

It's a Meshery UI issue. Not related to Documentation.

**Comment by leecalcote** [comment]
@Keenal @MaximeCoignus I'll remove your assignment to the issue, assuming that you've moved on. Just signal if that is not the case.

**Comment by vineethvanga18** [comment]
@leecalcote We might want to "graphqlise" this?
// cc @kumarabd
