### ISSUE TITLE
[Docs] quick-start link redirects to a 404 page

### ISSUE THREAD

**Issue by Shulammite-Aso** [layer5io/meshery#2019]
**Current State:**
![Peek 2020-12-02 17-32](https://user-images.githubusercontent.com/48386390/100902920-4241bd80-34bd-11eb-9345-1dc0f2271cae.gif)

**Desired State:**
Should redirect to a getting started list of documentations, like the **concepts** link.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Yikes! Thank you for raising this issue, @Shulammite-Aso. Will you please run a quick retest and confirm if you're still seeing this issue?

**Comment by leecalcote** [comment]
@Shulammite-Aso would you like to make an attempt to fix this, if you're still experiencing it?

**Comment by Shulammite-Aso** [comment]
Oh! I think it works fine now:
![Screenshot from 2020-12-03 07-55-49](https://user-images.githubusercontent.com/48386390/100975020-3e518200-3535-11eb-86cf-bc4e0553c1b3.png)

**Comment by leecalcote** [comment]
Ok, whew! I noticed this issue recently and tried to be quick to get it addressed.

Thanks for pointing it out.
