### ISSUE TITLE
[UI] Kubernetes config error on service management page

### ISSUE THREAD

**Issue by Keenal** [layer5io/meshery#2024]
**Description**

When I try to access any one of the service mesh management page, I come across this error: "Unable to fetch prometheus and grafana scan data: No valid kubernetes config found." It redirects me to [http://localhost:3000/settings#service-mesh](http://localhost:3000/settings#service-mesh) page

**Expected Behavior**

Instead, upon selecting a service mesh management page, I should be seeing something like this: 
![image](https://user-images.githubusercontent.com/14351534/100973170-0f70e700-3508-11eb-9402-0f69cc15415f.png)

**Screenshots**

This is what I get when I try selecting a service management page: 
![image](https://user-images.githubusercontent.com/14351534/100972802-64602d80-3507-11eb-9763-6dc1659815b4.png)

**Environment:**
- Host OS: Windows
- Meshery Version: not sure?
- Kubernetes Version: N/A
- Browser: Chrome

---
**To Reproduce**
1. Go to any one of the service management page
2. Click on 'Configure Settings'
3. See error

**Comment by leecalcote** [comment]
@anirudhjain75, we need to improve the user experience here. Will you take a crack at this? No toaster notification should be shown, however, we might consider another helpful indicator.

**Comment by anirudhjain75** [comment]
How about just having this toaster when grafana and Prometheus configuration tab is opened ?

**Comment by leecalcote** [comment]
Good suggestion. We're abusing the toaster notifications overall and need to pull away from them in general. To close out this issue, the toaster notification can be muted (not sent). The user will see that no prometheus and Grafana instances have been discovered when they come upon an empty text field on the Metrics tab.

Meshery's integration with either Prom or Graf doesn't strictly need Kubernetes.
