### ISSUE TITLE
[Docs] Invalid markdown in heading on lifecycle management page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2025]
**Current State:**
This page (https://meshery.layer5.io/docs/functionality/lifecycle-management) has the following issue:
<img width="913" alt="Screen Shot 2020-12-03 at 12 48 45 AM" src="https://user-images.githubusercontent.com/7570704/100974348-bc943100-3501-11eb-930d-d0a5c66dd13b.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@Shulammite-Aso, a small item you might consider tackling...

**Comment by Shulammite-Aso** [comment]
Thanks @leecalcote i'll be happy to work on this

**Comment by leecalcote** [comment]
Oh, very good! 😄

**Comment by Shulammite-Aso** [comment]
**Deploying a service mesh** should be a subheading under **Service Mesh Lifecycle Management** i suppose?

**Comment by leecalcote** [comment]
Right, yes, @Shulammite-Aso. A `##`, so to speak.
