### ISSUE TITLE
[Docs] Show/hide button UX issues

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2026]
**Current State:**
A show/hide button is being used in some of the Meshery docs. It has two usability issues:

1. It is not obvious that users can click on the show/hide buttons like [this one for WSL](https://meshery.layer5.io/docs/installation/platforms/windows#choosing-your-wsl-version).
2. The button acts differently depending upon whether the user fully depresses the button or not.
 
![Dec-03-2020 01-08-09](https://user-images.githubusercontent.com/7570704/100975745-1c8bd700-3504-11eb-87ff-33f0fa446b3b.gif)

**Desired State:**

1. Change the cursor to a pointer on hover.
2. Make the click action consistent in its behavior.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@Shulammite-Aso here's a freshly created issue with a little more bite to it in case you'd like to give it a go.

**Comment by Shulammite-Aso** [comment]
Can work on this @leecalcote.  Could you share link to a page where i can see that button?

**Comment by Nikhil-Ladha** [comment]
> Can work on this @leecalcote. Could you share link to a page where i can see that button?

The link is mentioned in the issue description itself.
https://meshery.layer5.io/docs/installation/platforms/windows#choosing-your-wsl-version

**Comment by Shulammite-Aso** [comment]
> The link is mentioned in the issue description itself.
> https://meshery.layer5.io/docs/installation/platforms/windows#choosing-your-wsl-version

Oh! thanks @Nikhil-Ladha. Not sure how i missed that earlier🤦‍♀️
