### ISSUE TITLE
[CI] Enable Jekyll / Netlify preview deployments for issues with the `area/docs` label

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2031]
@kushthedude will you address this as part of the investigation in the the PR labeler bot?

**Comment by Nikhil-Ladha** [comment]
You mean deployment preview, for PRs with updates to the docs site, right?

**Comment by kushthedude** [comment]
Redirection issue is still present which won't let give accurate deploys

**Comment by leecalcote** [comment]
Gents, the docs site is no longer served at https://meshery.meshery.io/docs, but is now served at https://docs.meshery.io. We should be free of the redirect issue now.

**Comment by kushthedude** [comment]
done

**Comment by leecalcote** [comment]
Wonderful. 😄 Thank you, @kushthedude

**Comment by leecalcote** [comment]
Looking good, @kushthedude. Thank you for this test - https://github.com/meshery/meshery/pull/2050
