### ISSUE TITLE
mesheryctl start: Linux compatible command to mirror MacOS experience

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#204]
**Description**
When users run `mesheryctl start`, each of Meshery's containers are initialized, and in the case of users running on MacOS, the user's default browser is opened to `http://localhost:9081`. Meshery should have a similar experience in place for Linux desktop users.

**Implementation**
- `xdg-open` is a Linux equivalent command to MacOS's `open` command and will be used to open Linux user's preferred browser to Meshery's start page.
- `mesheryctl start` needs to be enhanced to check [ostype](https://github.com/layer5io/meshery/blob/912d47edd2fc0168ec903c87d5db248fb6bea874/mesheryctl/cmd/vars.go#L53) before executing either the [`open` or the `xdg-open` commands](https://github.com/layer5io/meshery/blob/master/mesheryctl/cmd/start.go#L54).

**Comment by anandrkskd** [comment]
Yes it's working great.

**Comment by leecalcote** [comment]
Thanks @subhamkrai and @anandrkskd!
