### ISSUE TITLE
[CI] Notify Slack on star of repo workflow broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2040]
**Description**
The slack.yml workflow (https://github.com/layer5io/meshery/blob/master/.github/workflows/slack.yml) is broken. This workflow is invoked whenever a GitHub user stars the layer5io/meshery repo. We have this same workflow included in all of the layer5io repos.

**Expected Behavior**
The community slack's #buzz channel should receive notification when this repo is starred.

**Screenshots**
See a recently failed workflow for error logs - https://github.com/layer5io/meshery/actions/runs/402296162

**Comment by leecalcote** [comment]
@vishal267 or @SudhanAruna, you might be interested in picking this one up.

**Comment by leecalcote** [comment]
Another recent example - https://github.com/meshery/meshery/actions/runs/403584179

**Comment by SudhanAruna** [comment]
@leecalcote  Sorry for this. Issue is because of the missing indentation in line 10 ( slack.yml file).
I'll fix it ASAP.

**Comment by leecalcote** [comment]
Oh, that would be great. Thank you, @SudhanAruna

**Comment by leecalcote** [comment]
Thanks for this fix, @SudhanAruna. 👍
