### ISSUE TITLE
[Docs] Components and their languages

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2044]
**Current State:**
The [Meshery Architecture page](http://docs.meshery.io/concepts/architecture) has a list of components.

<img width="699" alt="Screen Shot 2020-12-05 at 10 24 07 PM" src="https://user-images.githubusercontent.com/7570704/101271489-c22f8800-3748-11eb-9adb-7f7a9fbace77.png">

**Desired State:**
These components should be list in an html table to improve readability.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by sumit-kushwah** [comment]
Ok, @leecalcote  I am working on it.

**Comment by leecalcote** [comment]
Nice work, @sumit-kushwah
