### ISSUE TITLE
[NATS] Continual IDE error

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2047]
**Description**
The following notification is visible in VS Code:

**Screenshots**
<img width="543" alt="Screen Shot 2020-12-05 at 11 56 12 PM" src="https://user-images.githubusercontent.com/7570704/101272846-a1b9fa80-3755-11eb-954e-baf3634950cd.png">

**Comment by kalradev** [comment]
I checked in my vscode and I am not receiving any such notifications

**Comment by leecalcote** [comment]
I think we're past this issue now. Thank you, gents.
