### ISSUE TITLE
Docs: http://docs.meshery.io/docs/installation/platforms/minikube

### ISSUE THREAD

**Issue by ameyaagashe** [layer5io/meshery#2067]
**Current State:**
HTTP 404, page not found.
**Desired State:**
Valid documentation for minikube
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@ameyaagashe where are you finding the invalid link?

**Comment by chandrashritii** [comment]
You have an extra (/docs) in the link there. The page is available at http://docs.meshery.io/installation/platforms/minikube @ameyaagashe
