### ISSUE TITLE
M0: Extend Load Generation w/wrk2 - Build and Packaging

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#209]
**Description**
See #126 for full description of Load Generator Integration Epic.

**Milestone 0: Build and Packaging**

- [x] Compile wrk2 (with json compatibility) as a Docker build step as part of the multi-stage build.

- [x] Bundle the compiled wrk2 along with Meshery in the Docker container image (probably in the same folder (OR) include it in the PATH so that wrk2 executable can be found when running exec call.

**Additional context**
See [Load Generator Integration design doc](https://docs.google.com/document/d/1jZMOih3Qn1ixrq1Ve6fkdZZ4TuKNoF_qfClDZTnLNcw/edit#).

**Comment by sakows** [comment]
https://github.com/meshery/meshery/pull/291
