### ISSUE TITLE
use Istio-vet to validate Istio config before applying it on the mesh

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#21]

**Comment by leecalcote** [comment]
<img width="1205" alt="meshery" src="https://user-images.githubusercontent.com/7570704/53050223-74a43700-345e-11e9-9ed9-88ee35556c1c.png">

**Comment by leecalcote** [comment]
Potentially of interest, @venilnoronha?

**Comment by venilnoronha** [comment]
@leecalcote yes, thanks!

**Comment by venilnoronha** [comment]
I've created PR meshery/meshery-istio#6 to address this.

**Comment by nrjpoddar** [comment]
Hi @leecalcote, can we jump on a short meeting to discuss how meshery can use istio-vet & also enhancements you would like to see in istio-vet?

**Comment by venilnoronha** [comment]
@nrjpoddar I believe `istio-vet` does a runtime analysis of the environment. Can it do a static analysis of Istio yaml configuration?

**Comment by nrjpoddar** [comment]
Yes, that is correct. Istio currently provides static analysis logic in `istioctl`, `galley` & `pilot` which are scattered all over and we didn't want to copy that logic again in `istio-vet`.

I believe static analysis belongs in `galley` and/or `istioctl`. As `galley` is registered as admission webhook it can reject invalid configuration.

**Comment by leecalcote** [comment]
Hi @nrjpoddar, yes, it'd be great to collaborate with you here. Your guidance and counsel on the approach to the integration would be ideal. If convenient, we hold a weekly community meeting on Fridays at 2pm Central (currently). Details here - https://meshery.io/meshery/#contributing

If this time doesn't work, yes, let's catch up separately. There's a community slack here - http://slack.meshery.io
