### ISSUE TITLE
[mesheryctl] Add Meshery adapters to `system context`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2105]
### Current Behavior
Users desire to only deploy specific Meshery adapters based on their service mesh needs.

### Desired Behavior

The Meshery configuration file (`config`) describes `contexts` which define Meshery deployments: server location, adapters, release channel subscription, user tokens and so on.

While the deployment artifacts (Docker compose file, Kubernetes manifests, helm charts and so on) for Meshery will be in separate files, each `context` defined in the Meshery `config` file should carry the definition of which adapters are to be included in which Meshery deployment.

**Note:**
- _Refer to the `system context` section of [Meshery CLI Commands & Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.fpuuy11gk85g)
- _This issue only describes itemizing adapters in contexts. A subsequent issue will describe how the presence or absence of an adapter in a context affects a Meshery deployment._
- _This issue is dependent upon #2104_

### Implementation
- Include a list of Meshery adapters in each context.
- Provide a `--adapters [istio | linkerd | osm | ... ]` flag to accept 1 or more adapter names.
- Provide `-a` as shorthand for `--adapters`.

### Acceptance Tests
1.  `config` file is valid yaml.
2. Any given `context` includes includes an `adapters` collection with 0 or more adapters defined.
3. `system context create <name>` that does not include `--adapters` flag will create a context that includes all adapters.

---

### Acceptance Tests

3. An empty adapters collection results in no adapters provisioned.

**Comment by leecalcote** [comment]
@sladyn98 interested?

**Comment by navendu-pottekkat** [comment]
@leecalcote I can take this up if no one is working on this.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat I was looking to start contributing in Go. Could I consider this issue for the same? Is it solvable by someone with an intermediate knowledge of Go?

**Comment by leecalcote** [comment]
The new `context` command enables users to adjust which adapters they want to have running. While this command doesn't provide the flag listed above (`--adapters`), yet, Meshery's docs need to be updated to provide users a description of the `config.yaml`(meshconfig) file and how to update it.

**Comment by navendu-pottekkat** [comment]
@leecalcote @metonymic-smokey Adding the `--adapters` flag should be straightforward. That can be done now I think...

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat , this is what I've done so far:
![image](https://user-images.githubusercontent.com/48997495/109280553-3443d480-7841-11eb-98d5-b8fc341640da.png)

Used `pflag` for the same and it accepts 1 or more string values.  
I understood this flag will mainly be used with the `context` command. Could you please give me some idea on what I should implement next to include these adapters in the `config.yaml` file?

Thanks!

**Comment by navendu-pottekkat** [comment]
I guess the flag would be used in the `context create` command. So this flag could be local to it. We can modify the context create function to write the list of adapters specified to the specified context when it is created.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat , 
Thanks for the suggestion!
I've changed it to a flag local to `system context create`.  
![image](https://user-images.githubusercontent.com/48997495/109319378-ce714000-7874-11eb-8ca1-daf6a1805c96.png)

![image](https://user-images.githubusercontent.com/48997495/109319490-ef399580-7874-11eb-846a-da1cca3640dc.png)


Thanks!

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey Great work! Are you writing the specified adapters to the `config.yaml` file?

@leecalcote This is the desired behaviour right?

> I guess the flag would be used in the context create command. So this flag could be local to it. We can modify the context create function to write the list of adapters specified to the specified context when it is created.

**Comment by leecalcote** [comment]
Sounds good. If a user wants to modify their context, they can either delete the context and recreate or they can edit the `config.yaml`.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat , @leecalcote , 
I've opened a draft PR for this issue. 
I'm unsure as to why my tests are failing.  Could you please let me know how to fix those?  

These are the screenshots of my changes:  
1. 
![image](https://user-images.githubusercontent.com/48997495/109376767-e2f11f00-78ec-11eb-8225-9d9ab457f03f.png)

2. 
![image](https://user-images.githubusercontent.com/48997495/109376812-0f0ca000-78ed-11eb-9e07-0a0eb556cbd9.png)

Please review it and let me know how I should proceed.

Thanks!
