### ISSUE TITLE
[Docs] Meshery Error Code Reference

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2107]
**Current State:**
Meshery documentation does not have a reference for users to lookup specific error codes the stumble upon while using Meshery. The adapter v2 architecture includes a reorganized set of error codes, classified by relevant functional area. Each error code is to carry the following helpful information:

- Code
- Severity
- Short Description
- Long Description
- Probable Cause
- Suggested Remediation

Error codes will fall into specific, predetermined number range in order to categorize the error by functional area / component, so that users might easily reference and troubleshoot error codes. Each error code is to be used as a unique identifier of the problem faced. Ranges defined for error codes:

| Category              | Error Code Range |
|-----------------------|------------------|
| GRPC Server           | 600 to 699       |
| Configuration package | 700 to 799       |
| Tracing package       | 800 to 899       |
| Meshery               | 10000 to 10099   |
| Meshery adapter       | 10100 to 10199   |
| Meshkit               | 10200 to 10299   |
| Istio Service mesh    | 11000 to 11099   |
| Linkerd Service mesh  | 11100 to 11199   |
| Open Service mesh     | 11200 to 11299   |
| Kuma Service mesh     | 11300 to 11399   |
| Citrix Service mesh   | 11400 to 11499   |
| Network Service mesh  | 11500 to 11599   |
| Consul Service mesh   | 11600 to 11699   |
| Octarine Service mesh | 11700 to 11799   |
| Nginx Service mesh    | 11800 to 11899   |

Error codes consist of different categories. Predefined ranges help users quickly understand the source of a given error.

**Desired State:**
A new documentation page should be created in the Reference section: "Error Code Reference" that includes a table that includes a column for each of the attributes in the list above.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by diru1100** [comment]
Can I take this issue?

**Comment by leecalcote** [comment]
That’s be great, yes, @diru1100

**Comment by diru1100** [comment]
Hey @leecalcote,

Should I somehow replicate all the errors and fill the table accordingly? 

Is this how the table supposed to look like? http://bit.ly/mehsery_error_codes

Any resources would be appreciated.

**Comment by leecalcote** [comment]
@diru1100 here’s an example of what we’re looking to create - https://www.cisco.com/c/en/us/support/docs/cloud-systems-management/intelligent-automation-cloud-40/117458-ptn.html

We don’t have all of the individual error codes and their information today. As you go to layout a structure on the page, it would be good to create a Jekyll datafile to store the error codes and avoid maintaining a long markdown table.

**Comment by leecalcote** [comment]
@diru1100 checking on progress. How is this coming along. @chandrashritii might offer context, if that would help.

**Comment by diru1100** [comment]
I will create the layout and send the pr soon. Thanks for checking

**Comment by leecalcote** [comment]
@diru1100, sounds real good. You might be interested in the larger effort here, too - #2399

**Comment by mgfeller** [comment]
See also https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.iz2q58cb347d
