### ISSUE TITLE
[Docs] `mesheryctl system channel`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2110]
**Current State:**
A new `mesheryctl system channel` command has been delivered.

**Desired State:**
The [mesheryctl Command Reference](http://docs.meshery.io/reference/mesheryctl) should include this command and its usage.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@metonymic-smokey would you like to pick up this issue?

**Comment by metonymic-smokey** [comment]
@leecalcote ,
This is what I've done till now to document `channel`. Let me know if there is something I should change.

1. I have added the `channel` subcommands under the `flags` column
![image](https://user-images.githubusercontent.com/48997495/110064677-98135380-7d93-11eb-9a7d-6ec25b2d6dfa.png)


2.
 ![image](https://user-images.githubusercontent.com/48997495/110064572-597d9900-7d93-11eb-8333-68dc08dbe18d.png)

(I've opened an issue for the extra blank lines in meshery.io)

Thanks!

**Comment by leecalcote** [comment]
@metonymic-smokey, this looks just right for the command reference, yes. 

Individual pages with command examples and a longer description of their behavior is needed. // @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
Looks good!

@leecalcote @metonymic-smokey As I was working on the mesheryctl command doc, I thought we could present the commands in a different way in the future when we add individual documentation for each commands. I will get this done hopefully over the weekend and we can look into how we can better structure the mesheryctl docs.
