### ISSUE TITLE
[Docs] Document `system context`

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2112]
**Current State:**
[context](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.fpuuy11gk85g) support is a new capability to be released under v0.5.0 and will be included in the [Meshery v0.5.0 Release Announcement](https://docs.google.com/document/d/1f7mGHtjHiywbN9UzwuldOX8x_Lpv2Ss8i4b045Np9OM/edit#)

**Desired State:**
Documentation of this feature and its behavior is needed. 

**Desired State:**
1. Improve the documentation and publish (see https://docs.meshery.io/reference/mesheryctl)
2. Highlighted in yellow needs to be changed (see [design spec](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.fpuuy11gk85g)
3. Add behavior section for every sub-command

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by navendu-pottekkat** [comment]
Fixed in #2546
