### ISSUE TITLE
[UI] Add Meshery icon as the favicon in UI and Provider UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2113]
**Current Behavior**
Meshery doesn't have a favicon defined for it's UIs.

**Desired Behavior**
A favicon should be defined and Meshery logo included in both the "provider UI" and "UI".

**Comment by jomefavourite** [comment]
Hi, I'll like to take up this issue but could the issue be vivid

**Comment by jomefavourite** [comment]
Please the links to where I'm to add the favicons

**Comment by lolyparty** [comment]
Hey, @leecalcote I'll like to work on this, but I might need help as I don't think I've worked on the frontend of meshery before.
