### ISSUE TITLE
Helm install through github pages instead of cloning git repo.

### ISSUE THREAD

**Issue by rajdas98** [layer5io/meshery#2115]
**Current Behavior**

Currently, meshery is installing by the following steps which requires cloning of git repo.
```
$ git clone https://github.com/layer5io/meshery.git; cd meshery
$ kubectl create namespace meshery
$ helm template meshery --namespace meshery install/kubernetes/helm/meshery | kubectl apply -f -

```
**Desired Behavior**

Instead of cloning, it can be hosted using Github pages and following will be the commands
```
helm repo add meshery https://layer5io.github.io/meshery/
helm install meshery --namespace meshery layer5io/meshery
```
---
[Optional]

**Comment by rajdas98** [comment]
Happy to take this issue, if possible

**Comment by rajdas98** [comment]
cc: @leecalcote

**Comment by leecalcote** [comment]
@rajdas98 I completely missed this. Yes, this is a great suggestion. Let's do it. 👍

**Comment by leecalcote** [comment]
@rajdas98, would you like to tackle this in this repo under `/docs` and in the `meshery.io` repo on the project site?

**Comment by leecalcote** [comment]
// @Aisuko

**Comment by Aisuko** [comment]
Hi, guys @leecalcote  @rajdas98  The desired behavior looks good.

**Comment by rajdas98** [comment]
> @rajdas98, would you like to tackle this in this repo under `/docs` and in the `meshery.io` repo on the project site?

Sure @leecalcote , I will raise a PR soon. Thanks

**Comment by leecalcote** [comment]
Nice! Thank you. :smile

**Comment by leecalcote** [comment]
@rajdas98 just to clarify, this is just an update in the instructions, right? The Meshery chart is available in Artifact Hub today.

We'll want to update the instructions on the meshery.io website as well - https://github.com/meshery/meshery.io/blob/master/_includes/getting-started.html

**Comment by Aisuko** [comment]
Close due to https://github.com/meshery/meshery.io/pull/402
