### ISSUE TITLE
[Docs] Update Meshery README - Traefik Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2122]
**Current State:**
In the [README](https://github.com/layer5io/meshery/blob/master/README.md) should reflect this., the Meshery Adapter for Maesh entry needs updated.

**Desired State:**
1. The Meshery Adapter for Maesh has been renamed to "Meshery Adapter for Traefik Mesh".
2. The Meshery Adapter for Traefik Mesh is now in **beta**. 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@notsureifkevin, good news! The Meshery Adapter for Traefik Mesh is now in beta. Would you like to pick up this issue?

**Comment by notsureifkevin** [comment]
@leecalcote sure, it's a slow week being the holidays and all, you can assign this to me.

**Comment by chandrashritii** [comment]
That's great! @notsureifkevin Take it away :) Do let me know if you have any questions

**Comment by leecalcote** [comment]
Much appreciated, @notsureifkevin 👍
