### ISSUE TITLE
[Docs] Maesh has been renamed to Traefik Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2123]
**Current State:**
The Maesh project underwent a name change and is now referred to as "Traefik Mesh".

**Desired State:**
The Meshery documentation needs updated to reflect this project name change - http://docs.meshery.io/concepts/architecture/adapters

The GitHub repository for Meshery Adapter for Traefik Mesh has also recently been updated. All links to https://github.com/layer5io/meshery-maesh need to be updated to https://github.com/layer5io/meshery-traefik-mesh

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by pjzzz** [comment]
I would like to work on this.

**Comment by pjzzz** [comment]
Just to confirm, I will need to change everywhere the old URL is present to the new URL and "Maesh" to "Traefik Mesh" almost everywhere be it filename, etc.

**Comment by leecalcote** [comment]
@pjzzz yes, that same is true with in the confines of `/docs`
