### ISSUE TITLE
[mesheryctl] Modify `system reset` behavior to account for contexts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2125]
**Current Behavior**
`system context` is a new construct in `mesheryctl` (see the Meshery CLI & Documentation design spec). 

**Desired Behavior**
`system reset` needs to stop resetting the `meshery.yaml` file and start resetting a given context to the same defaults provided in `config` when a new context is created.

**Comment by SudhanAruna** [comment]
@leecalcote can I work on this issue? 
Should I start working on this issue after `system context` command implementation is merged?

**Comment by navendu-pottekkat** [comment]
@leecalcote This issue is duplicated and was fixed in #2248 . We can close this.

**Comment by leecalcote** [comment]
Thank you.
