### ISSUE TITLE
[Docs] Ordering of release versions on Releases page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2126]
@SudhanAruna, well done! One small item to deal with here: the descending order of releases by version number is being itemized slightly out of order with the string “v0.4.9” coming before “v0.4.25", because the “9” is greater than “2", as opposed to “25” being greater than “9".

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/issues/2039#issuecomment-749192526_

**Comment by leecalcote** [comment]
@SudhanAruna this one has your name on it. :)

**Comment by SudhanAruna** [comment]
@leecalcote looking into it

**Comment by SudhanAruna** [comment]
Shall I add the date as front matter when release note file created in the CI then we can print release as we expect in release page.
Is there any other approach to sorting the release collections?

**Comment by leecalcote** [comment]
@SudhanAruna that sounds reasonable to me. Having the date as a front matter variable should allow you to manipulate it and `sort` using Jekyll / Liquid / Ruby.
