### ISSUE TITLE
[mesheryctl] `system channel` return current release channel subscription

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2128]
**Current Behavior**
When a user executes `mesheryctl system channel`, they do not receive confirmation of which release channel they are subscribed.

example running v0.4.27:
```
$ mesheryctl system channel
Please subscribe to either the 'stable' or 'edge' release channel.
```

**Desired Behavior**
`mesheryctl system channel` should confirm the user's current release channel subscription based on `current-context` from the `~/.meshery/config.yaml` file.

Output should read:

```
$ mesheryctl system channel
Currently subscribed to: edge-latest

See --help for additional usage.
```

**Comment by Maxgit3** [comment]
Is this something I can look into?

**Comment by leecalcote** [comment]
@Maxgit3 sounds good. This issue is dependent upon #2104 being merged, which should happen shortly. See @anirudhjain75 with any questions. 👍

**Comment by leecalcote** [comment]
Being addressed in #2256

**Comment by navendu-pottekkat** [comment]
@leecalcote Is this the same functionality as `mesheryctl system channel view` ? Do we need to add this currently?

**Comment by navendu-pottekkat** [comment]
@leecalcote Can we close this one?

**Comment by navendu-pottekkat** [comment]
@Maxgit3 The same functionality is achieved through `mesheryctl system channel view` command. So this issue is stale.

Closing this issue...
