### ISSUE TITLE
[CI] Improve the release-drafter workflow to use release event

### ISSUE THREAD

**Issue by SudhanAruna** [layer5io/meshery#2138]
**Current Behavior**
The release-drafter workflow is triggered based on push event but creating release note file and other related jobs should triggered after a release (current logic is based on using push event).

**Desired Behavior**
Using release event to trigger following jobs.
- Writing release note file.
- Creating pull request.
- Verify PR

**Comment by leecalcote** [comment]
@ramrodo use of the `release` event trigger is something for us to look at switching over to.
