### ISSUE TITLE
[Platform] Meshery support for Podman

### ISSUE THREAD

**Issue by tripathyprateek** [layer5io/meshery#2158]
#### Current Behavior
Meshery deploys as a set of containers. Deployment manifests/packages/tooling has been provided for Docker and Kubernetes-based platforms - https://docs.meshery.io/installation/platforms

RedHat based Linux distribution have shifted to using Podman instead of Docker. Running Meshery on one of these distros means installing Docker. 

#### Desired Behavior

Make it more convenient to tun Meshery on podman systems. Support podman as a platform.

#### Implementation
1. Use [podman-compose](https://github.com/containers/podman-compose) which has been created to mirror `docker-compose`, which is what `mesheryctl` uses to deploy Meshery locally.
2. Add "podman" as a platform type to Meshery config file (`config.yaml`) (using `mesheryctl system context`)

#### Acceptance Tests
1. All `mesheryctl system` commands should behave in the same way they do against `docker-compose` as the platform.

**Comment by jaybatra26** [comment]
@leecalcote  Please shed some light on point 2. What is the config.yaml here you are referring to?

**Comment by jaybatra26** [comment]
Hi @leecalcote Do I have to make changes in a this file most likely. https://github.com/layer5io/meshery/blob/master/mesheryctl/pkg/utils/helpers.go#L208

**Comment by leecalcote** [comment]
@jaybatra26 hopefully, this helps - https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.fpuuy11gk85g

**Comment by jaybatra26** [comment]
Thanks @leecalcote
