### ISSUE TITLE
Use SASS instead of css in js

### ISSUE THREAD

**Issue by yolossn** [layer5io/meshery#2159]
**Current Behavior**

Right now we are using css in js (using styled-components). This works fine but writing css or sass in their respective files have some advantages.

**Desired Behavior**

Use SASS modules as it provides the following advantages:

1. It generates a javascript object which can be imported and passed into react components via props
2. It is namespaced to the files in which they are imported so under no circumstances you'd be overriding a style defined in another stylesheet.
3. It can be written in .sass files hence taking full advantage of IDE's syntax highlighting etc.
4. It does not trigger a recompile on save unlike css in js which makes development experience very very better.
5. SASS in general provides mixins, variables etc thus reducing repetition.

Refer Slack Conversation: https://layer5io.slack.com/archives/CFGG6U10E/p1609304846106400

---
[Optional]

**Comment by EmmanuelTheCoder** [comment]
I think CSS-in-JS is actually okay here and there's no point changing it since it doesn't in anyway affect application. Moreover, Styled-Components also offer all the advantages of SASS you listed.
