### ISSUE TITLE
Docs menu is off

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#216]
**Screenshots**
<img width="1219" alt="Screen Shot 2019-08-20 at 9 26 23 PM" src="https://user-images.githubusercontent.com/7570704/63398181-56c67900-c392-11e9-9578-b99a5ad0c25a.png">

**Enviroment:**
 - Browser:  chrome and safari

**Comment by leecalcote** [comment]
Closed by #227.

**Comment by leecalcote** [comment]
Couple possible solutions here:

1) update the Jekyll version number in the [/docs/Gemfile](https://github.com/layer5io/meshery/blob/master/docs/Gemfile#L11) to v4.0 (or higher) 

or

2) Copy the javascript and css files from a local build under the ```_site``` folder and merge into our /docs locally, so that GitHub does NOT have to dynamically pull in a remote theme when it builds. Remove the [remote-theme reference](https://github.com/layer5io/meshery/blob/master/docs/_config.yml#L28) in our _config.yml.

**Comment by leecalcote** [comment]
PR #243 was submitted to fix GitHub Pages issues with "just-the-docs" theme. Changes in PR #243 did not help the situation, but produced this issue:

![Screen Shot 2019-09-04 at 3 45 04 PM](https://user-images.githubusercontent.com/7570704/64290134-24d51b00-cf2b-11e9-8fc3-2f4c941ec0c7.png)

**Comment by leecalcote** [comment]
@Nikhil-Ladha FYI - the latest supported version of Jekyll on GitHub Pages is 3.8.5 - https://pages.github.com/versions/

**Comment by Nikhil-Ladha** [comment]
Sir, I have made the changes and the PR has been merged as it was approved by @girishranganathan .
Now it's looking good. You can check it once

**Comment by leecalcote** [comment]
<img width="560" alt="Screen Shot 2019-09-05 at 1 26 25 PM" src="https://user-images.githubusercontent.com/7570704/64369818-be133880-cfe2-11e9-8ec7-4e3111f49330.png">

Way to be @nikhil-ladha!

**Comment by leecalcote** [comment]
Fixed
