### ISSUE TITLE
[mesheryctl] View current-context support for `system channel`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2164]
#### Current Behavior
Contexts are a new feature in `mesheryctl`. Support for  contexts needs to be added to all `mesheryctl system` commands. See [Meshery CLI Commands](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#) for more "context" (yes, that was a pun).

#### Desired Behavior
`mesheryctl system channel` should return the user’s current subscription: “edge” or “stable”.

#### Implementation
1. Display the “channel” property from the `current-context` in the `~/.meshery/config.yaml` file.

#### Acceptance Tests
1. `mesheryctl system channel` needs to work like `system context`

**Comment by SudhanAruna** [comment]
@leecalcote Sorry I couldn't work on this. I'll complete it and update you ASAP.
