### ISSUE TITLE
mesheryctl system start error without SAAS_BASE_URL

### ISSUE THREAD

**Issue by eastfisher** [layer5io/meshery#2165]
**Description**

When I exec `mesheryctl system start`, the `meshery_meshery_1` status is Exit 1, and the dashboard cannot open.

Adding `SAAS_BASE_URL=https://meshery.layer5.io` to meshery.yaml and the restart can solve this problem.

**Expected Behavior**

successfully open http://localhost:9081

**Screenshots**

**Environment:**
- Host OS: macOS v11.1
- Meshery Version: v0.4.27
- Kubernetes Version: v1.19.3
- Browser: Chrome

**Comment by leecalcote** [comment]
Thank you for filing this issue, @eastfisher!

**Comment by leecalcote** [comment]
Hi @eastfisher, thanks again for raising this issue. Very helpful. Hopefully, you find that this fixes the issue. 

You might not be familiar with `mesheryctl system reset`, which will help in situations like this in the future. 👍
