### ISSUE TITLE
[Lifecycle] Display adapter version numbers in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2196]
#### Current Behavior
Meshery adapters have different version numbers. Users are not given a mechanism to investigate what version of each adapter that they are running.

#### Desired Behavior
Users should see the version of each Meshery adapters that they are running.

#### Acceptance Tests
1. User can see Meshery adapter version in adapter chip (see screenshot).
2. User can see Meshery adapter version in "Release" dashboard panel (see mockup).

#### Screenshot
<img width="331" alt="Screen Shot 2021-01-01 at 4 39 39 PM" src="https://user-images.githubusercontent.com/7570704/103447364-fa46bf80-4c4f-11eb-8b6d-f7fb7f8e6c56.png">

**Comment by chinmaym07** [comment]
Hey @kumarabd just to verify .. Is this issue resolved ??
