### ISSUE TITLE
UX: Dismissing an individual notification closes the Notification bar.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#220]
**Issue Description**
Current behavior is that when a user dismisses an individual notification, the entire Notification bar is dismissed as well.
![Untitled](https://user-images.githubusercontent.com/7570704/63514258-d7c66300-c4ad-11e9-927b-271022ce25e9.gif)

**Enhancement Description**
Ideally, when a user dismisses an individual notification, the Notification bar will remain open until the user shifts focus elsewhere.

**Comment by girishranganathan** [comment]
2a0fb9dab55600cc9142e045ae6c2d6c4ab4101d addresses this issue

**Comment by girishranganathan** [comment]
fixed in #234
