### ISSUE TITLE
[Docs] Add component version grouping and upgrade concerns to "Upgrading Meshery"

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2201]
**Current State of the Meshery Docs**

The [Upgrading Meshery](url) section of the Meshery documentation can be enhanced with further information.

**Desired State of the Meshery Docs**

Add the following details to the "Upgrading Meshery" section:

<img width="756" alt="Screenshot 2021-01-04 at 1 09 19 PM" src="https://user-images.githubusercontent.com/10404724/103512268-6f073d00-4e8e-11eb-9e89-d0c3feee9e94.png">

The information in this screenshot is also available in [slide 11](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.gaaab8c13c4_0_0) of the architecture deck.

A new table describing reflecting considerations for each of the Meshery components and how they are versioned should be included in the "Upgrading Meshery" doc.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
I updated the issue's description.

**Comment by leecalcote** [comment]
@hwpplayer1 are you interested in taking this on?

**Comment by hwpplayer1** [comment]
Yes @leecalcote I want to practice it

**Comment by leecalcote** [comment]
@hwpplayer1 to clarify, this issue describes the need for an update to Meshery docs. Are you wanting to pick up this issue to update documentation?

Trying out the upgrade process separately is great, too.

**Comment by hwpplayer1** [comment]
> @hwpplayer1 to clarify, this issue describes the need for an update to Meshery docs. Are you wanting to pick up this issue to update documentation?
> 
> Trying out the upgrade process separately is great, too.

Yes I am doing that. Now

**Comment by hwpplayer1** [comment]
`Your Ruby version is 2.7.0, but your Gemfile specified 2.7.1` on 

```
hwpplayer1@hwpplayer1-Aspire-V3-772G:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

So it will take time to compile `ruby` from source.

But I will write the documentation and I want it

Thanks for your understanding @leecalcote

**Comment by leecalcote** [comment]
No sweat. Take your time. 👍

**Comment by hwpplayer1** [comment]
https://blog.codeonion.com/2020/05/19/how-to-install-ruby-2-7-1-and-rails-6-0-0-in-ubuntu-20-04-focal-fossa-with-bash-shell-script/ is a working solution for `ruby` itself

**Comment by leecalcote** [comment]
Thanks for this @hwpplayer1. 👍
