### ISSUE TITLE
[mesheryctl] config: “platform” awareness for system commands for Docker

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2207]
### Current Behavior:
A context unaware static config file (meshery.yaml) which is used for deploying meshery in docker.  Meshery will support three types of platforms: docker, kubernetes, podman. 

### Desired Behavior:
All system commands should be cognizant of the specific platform used by each context and interface with that platform accordingly.

### Future: 
Meshery may differentiate between different types of Kubernetes systems.

### Implementation:
1. Use viper to read, modify, write (rewrite) the meshery.yaml.
2. Viper should update the meshery.yaml according to the context configuration specified in config.yaml.
3. Only one `meshery.yaml` will be managed by `mesheryctl`.
4. `docker-compose` is being wrapped for start, stop, logs, restart

### Acceptance Tests:
1. All `system` commands are aware of the `platform` attribute.
2. Only one `meshery.yaml` will be present in the `~/.meshery` app folder.
3. Each system command will consider the platform type prior to executing.

### Out of Scope:
1. Users will not be provided the ability to bring their own docker-compose.yaml as opposed to using meshery.yaml.

**Comment by navendu-pottekkat** [comment]
@leecalcote This issue will be fixed with epic #2393 and epic #2307 .

@aneeshnema and I are working on it.

**Comment by navendu-pottekkat** [comment]
mesheryctl is now both docker and kubernetes platform aware. Closing.
