### ISSUE TITLE
UI: "Enter" not allowed for submitting form; Click-only form submit

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#221]
**Description**
When users are filling in the Settings screens, they must click on the Submit button in order for the form to be submitted. Often users will be typing values into the fields on the forms. Rather than making the user remove hand from the keyboard to grab the mouse, it would be ideal if the form is configured to submit on press of the Enter button, too, as an alternative mechanism to submit the form.

**Expected Behavior**
Form submits when a user either clicks Submit or when a user presses the "Enter" key.

**Screenshots**
<img width="844" alt="Screen Shot 2019-08-22 at 7 44 28 AM" src="https://user-images.githubusercontent.com/7570704/63515585-cb8fd500-c4b0-11e9-913d-ae8a5434be50.png">

**Comment by JayWelsh** [comment]
@leecalcote Was this not fixed by #229 ?

**Comment by leecalcote** [comment]
@JayWelsh, good catch! You’re right. Closing this issue...

**Comment by leecalcote** [comment]
@JayWelsh we highly welcome any of your UI expertise in the Meshery project. Please don't be shy, if at all interested. Have a look around in here -- http://slack.meshery.io
