### ISSUE TITLE
[Docs] Screenshots need to be re-aligned on main README

### ISSUE THREAD

**Issue by alphaX86** [layer5io/meshery#2213]
**Current State:**
The screenshots are bit off-aligned with the titles while the user is browsing in GitHub

**Desired State:**
The paragraphs, pictures must be aligned correctly in the main README page

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by alphaX86** [comment]
I spotted on the Functionalities section, where the title and picture are off-bit aligned.
![image](https://user-images.githubusercontent.com/59508546/103775680-6ceedb00-5054-11eb-9ae3-cae403bc4f28.png)

**Comment by alphaX86** [comment]
What do you think of this? Does it need to be kept constant or leave as it is?

**Comment by leecalcote** [comment]
@alphaX86, yes, if you'd like to square off these features sections, I think that would be an improvement.

**Comment by alphaX86** [comment]
Great, I'll ping you once it's done!

**Comment by alphaX86** [comment]
@leecalcote the PR is ready for review!
