### ISSUE TITLE
Operator view in the configuration and main page

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2214]
#### Desired Behavior
A new section needed to be created for the operator flow. Below are the screenshots for the design.

#### Mockups
![System Dashboard](https://user-images.githubusercontent.com/10404724/103779502-df15ee80-5059-11eb-91c7-63370dc058c5.png)
![Settings](https://user-images.githubusercontent.com/10404724/103779511-e0dfb200-5059-11eb-8390-2531c900c92b.png)

**Comment by leecalcote** [comment]
Thanks, Dhruv.
