### ISSUE TITLE
Settings: Issues connecting to Prometheus

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#222]
**Description**
When configuring a connection to Prometheus in the Settings screen, give the user instruction and an example of submitting a Grafana board. 

Improvements:
1. Show "Panel" dropdown only after Board yam is submitted. 
1. Do no show an error initially, but an example board config.

**Screenshots**
The following screen is shown after entering a valid Prometheus endpoint. It should not have a Panel dropdown.

<img width="825" alt="Screen Shot 2019-08-22 at 7 39 53 AM" src="https://user-images.githubusercontent.com/7570704/63515701-0d208000-c4b1-11e9-87bc-f7722137c34c.png">

The following error is shown when hovering over the red X:

<img width="814" alt="Screen Shot 2019-08-22 at 7 39 59 AM" src="https://user-images.githubusercontent.com/7570704/63515742-275a5e00-c4b1-11e9-85fb-5f13ff0e4d70.png">

**Comment by girishranganathan** [comment]
I have attempted to fix this in PR #309. Closing for now. Please reopen as needed.
