### ISSUE TITLE
Docs:

### ISSUE THREAD

**Issue by hwpplayer1** [layer5io/meshery#2222]
**Current State:**
https://docs.meshery.io/guides/mesheryctl-commands seems that it exists and shows a general command line interface documentation but it returns 404 error
**Desired State:**
It should be a documentation for 
```
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [flags]
  mesheryctl [command]

Available Commands:
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  perf        Performance Testing
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string              config file (default location is: /home/hwpplayer1/.meshery/meshery.yaml)
  -d, --debug                      Debug flag
  -h, --help                       help for mesheryctl
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: /home/hwpplayer1/.meshery/mesheryctlConfig.yaml) (default "/home/hwpplayer1/.meshery/mesheryctlConfig.yaml")
  -v, --version                    Version flag

Use "mesheryctl [command] --help" for more information about a command.
```
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thank you for this, @hwpplayer1. Here's the intended link - https://docs.meshery.io/reference/mesheryctl (if you didn't already find it).

**Comment by hwpplayer1** [comment]
@leecalcote It seems that is explains the necessary details about commands. If it is acceptable by you and by the "community" so then I will work on it for training purposes. And I will try to write articles, presentations(in any file format) Thanks and to be honest I could not be able to find it before you wrote.

**Comment by leecalcote** [comment]
@hwpplayer1, yes, that sounds great. Here's another helpful reference - [Meshery CLI Commands](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#). @anirudhjain75 is a good individual to engage for clarification of behavior and design. This doc is available in the Meshery Community drive.

**Comment by leecalcote** [comment]
@hwpplayer1, as you go along here, we have a practice of elevate works by community members with https://meshery.io/blog as a platform to do so.

**Comment by hwpplayer1** [comment]
@leecalcote That is better and better for collaboration across the Internet I mean the collaborative editing and writing a manual and a blog. I will find a quick solution a topic as fast i can do Thanks

**Comment by hwpplayer1** [comment]
https://meshery.io/blog/getting-started-with-mesheryctl If it is acceptable I will translate this documentation to Turkish @leecalcote

**Comment by leecalcote** [comment]
@hwpplayer1 that would nice, yes, please.

**Comment by hwpplayer1** [comment]
I don't know if it is right place but I guess it will be a hackish solution to paste here the output and then maybe we can fix more quickly 

# mesheryctl komut satırı aracına başlamak isteyenlere

**no easier way to get started with a service mesh**

# MESHERY'e Başlamak İsteyenlere

Meshery'den haberi olmayanlar için Meshery, kullanıcılara servis ağı operasyonel en iyi uygulamaları, yaşam döngüsü ve konfigürasyon yönetimi sağlayan, ancak aynı zamanda çeşitli servis ağları arasında birlikte çalışarak size araçlar ve bilgiler sağlayan bir çoklu servis mesh yönetim arayüzüdür. Ek yükünüzü minimumda tutarken hizmet ağı performansınızdan en iyi şekilde yararlanabilirsiniz.

Meshery'nin vizyonu, bulut altyapısının herhangi bir hizmet ağı katmanının çalışmasını basitleştirmek ve herhangi bir modern iş yükünün tasarlandığı ve dağıtıldığı herhangi bir şekilde yaygın olarak mevcut bir katman olarak kaçınılmaz, nihai, her yerde bulunan benimseme hizmeti ağlarını hızlandırmaktır. Meshery, [Meshery](https://meshery.io/community) tarafından üretiliyor ve Meshery, Microsoft, HashiCorp, CNCF, RedHat gibi çeşitli teknoloji devleriyle ve daha pek çok üye kaydedilecek teknoloji ortaklığı olan, ilk topluluk hizmet ağı şirketidir. Topluluk, trend olan açık kaynak projelerinin bakımcıları, Google SoCers, Docker Captains, hizmet ağı bakımcıları, Cloud Native Ambassadors ve çok daha fazlası [(katılın!)](http://slack.meshery.io/).

## MESHERYCTL NEDİR?

Meshery, hizmet ağlarınızı, yani mesheryctl'yi yönetmek ve karşılaştırmak için size temiz, sağlam, basitleştirilmiş bir komut satırı arayüzü sunar. Mesheryctl ile, yalnızca adaptörlerinizi ve kapsayıcılarınızı yönetmekle kalmaz, aynı zamanda komut satırını kullanarak ağınızı kıyaslayabilirsiniz. mesheryctl, bir dizi platforma destek sağlar, böylece kullanıcıları asla kaçırmayız. mesheryctl, aşağıdaki komutu çalıştırarak tek bir bash komutuyla kurulabilir:

```
$ curl -L https://git.io/meshery | bash -
```

terminalinizde. Meshery'nin 9081 numaralı bağlantı noktasında kurulduğunu ve çalıştırıldığını göreceksiniz. Çıkışı şu şekilde göreceksiniz:

```
Extracting mesheryctl-v0.3.14...
Archive:  /Users/kush/meshery.zip
  inflating: LICENSE
  inflating: README.md
  inflating: mesheryctl
Installing mesheryctl in /usr/local/bin.
mesheryctl installed.
permissions moved to kush
Removing installation files and opening Meshery...Updating Meshery now...
Pulling meshery          ... download complete
Pulling meshery-istio    ... done
Pulling meshery-linkerd  ... done
Pulling meshery-consul   ... done
Pulling meshery-octarine ... done
Pulling meshery-nsm      ... done
Pulling meshery-cpx      ... done
Pulling watchtower       ... done
```

ve sonra Meshery UI(Kullanıcı Arayüzüne)'a  https://localhost:9081 sayfasından erişebileceksiniz.

Eğer bash'nin mesheryctl almanın tek yolu olup olmadığını merak ediyorsanız, işte mesheryctl alabileceğiniz tüm farklı yolları açıklayan platformların listesi.

| Platform      | Supported? |
| ----------- | ----------- |
| - [Docker](https://meshery.meshery.io/docs/installation/docker)      | ✔️       |
| - [Docker - Docker App](https://meshery.meshery.io/docs/installation/docker)   | ✔️       |
| - [Kubernetes](https://meshery.meshery.io/docs/installation/kubernetes) | ✔️ |
| - [Kubernetes - AKS](https://meshery.meshery.io/docs/installation/aks) | ✔️ |
| - [Kubernetes - Docker Desktop](https://meshery.meshery.io/docs/installation#mac-or-linux) | ✔️ |
| - [Kubernetes - EKS](https://meshery.meshery.io/docs/installation/eks) | ✔️ |
| - [Kubernetes - GKE](https://meshery.meshery.io/docs/installation/gke) | ✔️ |
| - [Kubernetes - Helm](https://meshery.meshery.io/docs/installation/kubernetes#helm) | ✔️ |
| - [Kubernetes - Minikube](https://meshery.meshery.io/docs/installation/minikube) | ✔️ |
| - Kubernetes - OpenShift | In Progress |
| [Linux](https://meshery.meshery.io/docs/installation#mac-or-linux)	| ✔️ |
| [Mac](https://meshery.meshery.io/docs/installation#mac-or-linux) | ✔️ |
| - [Mac - Homebrew](https://meshery.meshery.io/docs/installation#mac-or-linux) | ✔️ |
| [Windows](https://meshery.meshery.io/docs/installation#windows) | ✔️ |
| - [Scoop](https://meshery.meshery.io/docs/installation#windows) | ✔️ |
| - [WSL2](https://meshery.meshery.io/docs/installation/wsl2) | ✔️ |
| Raspberry Pi | In Progress |

Popüler platformların hiçbirini değerine göre kaçırmadığımıza inanıyoruz, yakında RaspberryPi ve OpenShift için destek sunacağız 🎉🎉🎉.

Gereksinimleri düşünüyorsanız, mesheryctl çalıştırmanız gerekecek, bu yüzden başarılı bir şekilde mesheryctl çalıştırmak için sadece şunlara ihtiyacınız olacak:

```
a running Docker daemon
```

## MESHERYCTL'e bir bakış

Başarıyla kurduğunuzda, yeni bir CLI Command MesheryCTL'nin gücüne sahip olacaksınız. Uçbiriminize mesheryctl yazarken, mesheryctl'nin destekleyebileceği çeşitli alt komutlar ve bayraklar gösterilecektir.

```
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Available Commands:
  help        Help about any command
  perf        Performance Management
  system      Meshery Lifecyle Management
  version     Print mesheryctl version

Flags:
      --config string    config file (default location is: $HOME/.meshery//meshery.yaml)
  -h, --help            help for mesheryctl
  -v, --version         Version of mesheryctl

Use "mesheryctl [command] --help" for more information about a command.
```
Mesheryctl sistemini başlattığınızda, Meshery adaptörlerini ve en son docker görüntülerini çekecektir. Meshery, Kubernetes yapılandırmanızı da algılar ve Kubernetes'in çalışıp çalışmadığını size bildirir. Meshery, web tabanlı kullanıcı arayüzünü localhost port 9081 üzerinde çalıştıracak ve bu güçlü yardımcı programla hizmet ağlarınızı yönetmeye başlamadan önce Sağlayıcı seçiminizi yapmanıza izin verecektir.

```
Mesheryctl'in en ilginç alt komutlarından biri perf'dir.
```

Perf alt komutu, hizmet ağı dağıtımınızın performansını ve bunların üzerinde çalışan iş yüklerinizi yönetmenizi sağlar. Komut satırı arayüzünün kendisinden Meshery UI'yi kullanmadan hizmet ağınızı karşılaştırmanıza olanak tanır. Mesheryctl perf yazdıktan sonra, CLI ile kontrol edebileceğiniz tüm güçlü bayrakları size sunacaktır, buna kaydetmiş olabileceğiniz bir dizi performans testi profiline işaret eden bir --file bayrağı da dahildir.

```
Performance Management and Benchmarking using Meshery CLI.

Usage:
  mesheryctl perf --[flags]

Available Flags for Performance Command:
  name[string]                  (optional) A short descriptor to serve as reference for this test. If not provided, a random name will be generate.
  url[string]                   (required) URL endpoint to send requests.
  duration[string]              (required) Length of time to perform test (e.g 30s, 15m, 1hr). See standard notation https://golang.org/pkg/time/#ParseDuration
  load-generator[string]        (optional) Name of load generator to be used to perform test (default: "fortio")
  mesh[string]                  (optional) Name of the service mesh to be tested (default: "None")
  provider[string]              (required) Choice of Provider (default: "Meshery")
  concurrent-requests[string]   (optional) Number of parallel requests to be sent (default: "1")
  qps[string]                   (required) Queries per second (default: "0")
  file[string]                  (optional) file containing SMPS-compatible test configuration. See https://github.com/meshery/service-mesh-performance-specification
  help                          Help for perf subcommand

url, duration, concurrent-requests, and qps can be considered optional flags if specified through an SMPS compatible yaml file using --file
```

`mesheryctl perf --[flags]` için bir örnek kullanım

`mesheryctl perf --name "a quick stress test" --url http://192.168.1.15/productpage --qps 300 --concurrent-requests 2 --duration 30s --token "provider=Meshery"`

Ayrıca, URL, süre, eşzamanlı istekler ve qps belirtmeniz gerekmemesi koşuluyla, perf alt komutu içeren bir SMPS Yapılandırma dosyası da sağlayabilirsiniz. Ancak, belirtilirse, dosya aracılığıyla sağlanan değer, CLI aracılığıyla değer tarafından geçersiz kılınır. Dosya yapılandırması hakkında daha fazla bilgi için buraya bakınız.

` mesheryctl perf --name "a quick stress test" --file {path}/smp.yaml --token "provider=Meshery"`

## Bir Sonraki Adım nedir ?

Meshery, dünyanın dört bir yanından katılımcıları kendine çeken, sürekli büyüyen bir topluluktur. Kod yazmak isteyenler, topluluk yöneticisi veya pazarlamacı talepleri olsun, her zaman herkese bir rolümüz var. Meshery topluluğu sizi sıcak bir şekilde karşılamaya her zaman açıktır.

Bu sizi heyecanlandırıyorsa, [Meshery topluluğuna sadece bir tıklamayla katılın](http://slack.meshery.io/) ve kaçırılmadığınızdan emin olmak için biri orada olacaktır.

Stay meshy and happy meshing!

[Written by - Kush Trivedi](https://github.com/kushthedude)

**Comment by hwpplayer1** [comment]
@kushthedude @leecalcote Thanks Could you please check it whether it has syntax issues or not ?

**Comment by leecalcote** [comment]
@hwpplayer1 if you have an appetite for it, you may want to work on a Turkish translation of the Meshery Docs in the same fashion is being done for Spanish (see https://docs.meshery.io/es) by @alonsolopezr @jesuslerma @rubenlorenzo @homero304 @jlcastrogro @drake8710

**Comment by hwpplayer1** [comment]
Yes @leecalcote I am keen to become a `technical writer` to welcome #newcomers all around world. But I need more 24 hours. Thanks.
