### ISSUE TITLE
Issue: [mesheryctl] Add “channel” and “version” attributes to config for Docker

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2225]
### Implementation:
- Write to meshery.yaml

### Acceptance Tests:
1. Meshery config will have:

```
channel: stable
version: v0.4.27
```
with version being optional and -latest being implied if version isn't supplied in that, afterall, users will have subscribed to a release channel.

1. Allow users to deal (start, stop, reset, log) with multiple platforms. Few examples
```Docker: use docker-compose (using extend)
Kubernetes - use kubernetes client go
Podman - podman-compose
```

2. The meshery.yaml is modified and maintained by viper. The selected context configuration is reflected in the meshery.yaml by viper.

3. Allow deployment of specific version of meshery as well as subscription to channels 
Stable
Edge
Specific Version to use version tags: stable-{$version}

**Comment by leecalcote** [comment]
@anirudhjain75 will you de-duplicate this and other surrounding issues?

**Comment by leecalcote** [comment]
@navendu-pottekkat do we need this reopened or is this too old of a design/issue?

**Comment by navendu-pottekkat** [comment]
@leecalcote we don't need to reopen this. This is already added to mesheryctl now...
