### ISSUE TITLE
Issue: [mesheryctl] channel: support `context` and config.yaml

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2226]
### Implementation:
- Write to config.yaml

### Acceptance Tests:
1. Meshery config will have:

```
channel: stable
version: v0.4.27
```
with version being optional and -latest being implied if version isn't supplied in that, afterall, users will have subscribed to a release channel.

1. Allow users to deal (start, stop, reset, log) with multiple platforms. Few examples
```Docker: use docker-compose (using extend)
Kubernetes - use kubernetes client go
Podman - podman-compose
```

2. The meshery.yaml is modified and maintained by viper. The selected context configuration is reflected in the meshery.yaml by viper.

3. Allow deployment of specific version of meshery as well as subscription to channels 
Stable
Edge
Specific Version to use version tags: stable-{$version}

**Comment by leecalcote** [comment]
@metonymic-smokey will you verify that what is describe here is the current behavior of this command?

**Comment by metonymic-smokey** [comment]
@leecalcote , I'll get to this!
Give me a week to test it out.

**Comment by metonymic-smokey** [comment]
@kumarabd 
When I run the `mesheryctl system channel` command in the issue, I get an error stating `--version` is not a valid flag. 
![image](https://user-images.githubusercontent.com/48997495/109622801-8434db00-7b62-11eb-8c68-78df768056ed.png)

Could you tell me what the expected behaviour is or where I'm going wrong?

When i remove `version` from `config.yaml` or change `channel` in the file to latest, those work as expected, when I run `mesheryctl system channel view`.

Thanks!

**Comment by metonymic-smokey** [comment]
@leecalcote does this issue also involve adding support for the two flags mentioned in the issue or is it just verifying and documenting the available flags and their behaviour?

Thanks!

**Comment by leecalcote** [comment]
@metonymic-smokey, if you think you have a handle on adding the two flags, let's proceed with both adding them and documenting the command. 👍

**Comment by navendu-pottekkat** [comment]
@leecalcote @metonymic-smokey `--context` flag is global to all the system commands in mesheryctl. Add the `--context` flag will switch the context temporarily. This is implemented in the `system channel` command.

To specify the channel and version, we could use something like `mesheryctl system channel set stable-v0.5` as per the current implementation by @anirudhjain75 

The problem with adding a `--version -v` flag is the we have a `--verbose -v` flag globally for all mesheryctl commands.

So, I think it is fine to keep the current implementation as it is. (I hope I'm not missing anything else)

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat got it!  
I thought it would be neater to have a separate `--version` flag with another shorthand but i think you have a point saying the current implementation is fine.  
I'll just check the docs for these flags and work on them then.  
Thanks!

**Comment by navendu-pottekkat** [comment]
Yes, I agree that it would be neat. But if that collides with the `--verbose` flag, it would be better if we keep it this way.(Although we do not have much verbose logs in mesheryctl)

**Comment by navendu-pottekkat** [comment]
@leecalcote @kumarabd , we have this functionality already added in the `context set [release-version]` command. Closing this issue...
