### ISSUE TITLE
Promote Meshery Adapter for Traefik Mesh to Beta

### ISSUE THREAD

**Issue by utkarsh-pro** [layer5io/meshery#2245]
#### Current Behavior

Currently meshery release bundles 9 adapters as the adapter for traefik mesh (10th adapter) was in initial testing phase. Recently the Meshery UI was enhanced to support traefik mesh and it's associated operations  and hence Meshery adapter for traefik mesh is ready to be used along with the other adapters.

#### Desired Behavior

New meshery releases should start including the traefik mesh adapters.

---

#### Implementation

Meshery spins up the adapters inside the docker containers. The configurations of the same are specified in the `docker-compose.yaml`. A new service needs to be added to the compose file with image: `layer5/meshery-traefik-mesh:stable-latest` and the exposed port would be `10006` with service name `meshery-traefik-mesh`. Along with this, `meshery-traefik-mesh:10006` needs to be added to `ADAPTER_URLS` environmental variable in the meshery service so that meshery can discover the adapter for communication.

**Comment by utkarsh-pro** [comment]
With a simple and quick edit of a YAML file, the Meshery Adapter for Traefik Mesh will be released. @SantoDE, would you or @mmatur @dtomcej like to do the honors here?

**Comment by SantoDE** [comment]
Im not fully aware of what I need to do, but if you hit me up, sure :)

**Comment by leecalcote** [comment]
This is exciting! @SantoDE essentially all that needs done here is to make an entry for meshery-traefik-mesh in this [docker-compose.yaml](https://github.com/layer5io/meshery/blob/cdb1ca33921f86328536a7df3e4b83dda6159d4e/docker-compose.yaml#L46-L51) (meshery-kuma highlighted as an example). The Meshery Adapter for Traefik Mesh runs on port 10006.

**Comment by leecalcote** [comment]
Thanks for picking this one up, @SantoDE. We would like to enable users with Traefik Mesh in the Meshery v0.5.0 release. A series of beta releases will start to release shortly.

**Comment by SantoDE** [comment]
PR Up :) @leecalcote

**Comment by leecalcote** [comment]
Awesome! 💥
