### ISSUE TITLE
[mesheryctl] Display version and channel on system channel

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2246]
#### Desired Behavior

`mesheryctl system channel` -> returns current channel and version with Usage
`mesheryctl system channel view` -> returns list of all context with their respective channels

#### Acceptance Tests
Test 1) **Show user details of current-context channel and usage. Do not confirm context.**
```
$ mesheryctl system channel
Channel: stable
Version: latest

Usage: ....
```

Test 2) **Show user details of current-context channel. Confirm context.**
```
$ mesheryctl system channel view
Context: local
Channel: stable
Version: latest
```

Test 3) **Show user details of all contexts’ channel**
```
$ mesheryctl system channel view -all
Context: local
Channel: stable
Version: latest

Context: test
Channel: edge
Version: latest
```

**Comment by jaybatra26** [comment]
Hi @anirudhjain75  and @leecalcote Can I take this up?

**Comment by leecalcote** [comment]
Hi @jaybatra26, in general, yes, that would be nice. A quick check, though, as I think @navendu-pottekkat might already be working on this with @anirudhjain75.

**Comment by anirudhjain75** [comment]
I was taking this up... It entails more than mentioned

**Comment by leecalcote** [comment]
@jaybatra26 let's get you another one. This one is open and might be of interest - https://github.com/meshery/meshery/issues/2158

**Comment by jaybatra26** [comment]
@leecalcote  Sure. Looking into it. Thanks :)
