### ISSUE TITLE
[mesheryctl] make `system reset` context-aware

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2248]
#### Current Behavior
`mesheryctl system reset` incidentally crosses release channels by reaching out to GitHub and pulling the latest `docker-compose.yaml`.

#### Desired Behavior
`reset` needs to consider for the current-context and the `channel` and `version` attributes when pulling from GitHub.

#### Implementation
1. No behavior change for `edge` channel. Just grab latest from GitHub `master` branch.
1. For `stable` channel:
   1.  if version is specified grab the the `docker-compose.yaml` from the git history at that release tag.
   1.  if version is “latest”, then reuse `version` for checking for latest stable release tag and then pull the docker-compose.yaml based on that tag.

**Comment by navendu-pottekkat** [comment]
@leecalcote @anirudhjain75 I can try to work on this. I think it would be good one to start and learn.

**Comment by anirudhjain75** [comment]
Great. Fell free to reassign it to yourself
