### ISSUE TITLE
Discover Grafana and Prometheus

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#225]
**Enhancement Description**

- [ ] Meshery should be able discover if it deployed on kubernetes
- [ ] If not, then wait until connection to kubernetes is configured
- [ ] Once connected to kubernetes, ability to discover if Grafana and Prometheus exist on the cluster and present the choices to the user to select one amongst them (OR) enter a new server (which is the existing route)

**Comment by ashiscs** [comment]
This issue is already fixed and needs to be closed!
