### ISSUE TITLE
Implement a minimum Code Coverage Report to meshery project

### ISSUE THREAD

**Issue by ramrodo** [layer5io/meshery#2251]
#### Current Behavior

We need to be able to see a Code Coverage Report and measure how many tests we have and those that are missing. This will allow us 

#### Desired Behavior

Have a Code Coverage Report on every PR and/or in the README.md.
We can start with the simplest implementation that measures the code coverage of unit tests or an only workflow. Then, we can create more issues to improve it.

---
[Optional]

#### Implementation

There are many tools that can be used: codecov or others. Feel free to choose the best.

**Comment by ramrodo** [comment]
@mgfeller maybe is interested in this also and can give some help and opinions on this.

**Comment by mgfeller** [comment]
@ramrodo thanks! it will really be valuable to include that in our workflows. my background on test coverage is mainly Java related tooling, though. 

It would be useful to have a tool that can analyze and report and possibly fail the build on test coverage in new and changed code, in addition to coverage of the whole code base of course. Also, would be nice to have a report covering coverage over time to  visualize the improvement.

@Aisuko may be interested and can surely give some help on this. Haven't we started using codecov in one repo already?

**Comment by Aisuko** [comment]
@mgfeller No problems. Because the unit-test closed, we did not start using the codeCov, but this time we can add it to the repo. codecov action is good.  But I do not have the permission I guest.

![image](https://user-images.githubusercontent.com/8053949/104719648-c0a1a880-5767-11eb-87f6-d8c8cd2839c7.png)

**Comment by leecalcote** [comment]
@shubhank-saxena, is the Codecov GitHub Action above what you had in mind as well?

When someone does request permission to install on of these apps, go ahead and request it for “All repositories”, if you would.

**Comment by shubhank-saxena** [comment]
I think this is not a GitHub action, but rather application access of codecov to the repositories. 
Yes, we need to enable it for all repositories, and then we need two things -
- a codecov.yml to have our desired codecov settings
- integration of codecov in out CI pipeline to post the coverage report
