### ISSUE TITLE
https://docs.meshery.io/service-mesh-performance is empty

### ISSUE THREAD

**Issue by hwpplayer1** [layer5io/meshery#2253]
#### Description
[This page](https://docs.meshery.io/guides/interpreting-performance-test-results) has a broken link to the SMP project. 

#### Expected Behavior
The first link on the page should point to https://smp-spec.io.

#### Screenshots/Logs

https://docs.meshery.io/service-mesh-performance page is where i point to

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thanks, @hwpplayer1. Where did you find this link? We'll want to know this, so that we can fix the source.

**Comment by leecalcote** [comment]
Ok, I see a link located on https://docs.meshery.io/guides/interpreting-performance-test-results.

**Comment by leecalcote** [comment]
@hwpplayer1 be sure to create docs issues using the docs issue template, if you would. It has additional information for contributors on how to contribute to docs. --> https://github.com/meshery/meshery/issues/new?assignees=&labels=area%2Fdocs&template=documentation.md&title=%5BDocs%5D

**Comment by jaybatra26** [comment]
Hi @leecalcote Can I take this up?

**Comment by leecalcote** [comment]
Thank you, @jaybatra26, yes 👍
