### ISSUE TITLE
[Meshery Operator] Unhandled error on load of /settings

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2261]
#### Description
The following error is shown when running `make run-ui-dev` with no Kubernetes or Meshery Server present:

<img width="984" alt="Screen Shot 2021-01-18 at 10 50 08 PM" src="https://user-images.githubusercontent.com/7570704/104989270-b25dc180-59df-11eb-9cb9-677fca7e70f2.png">

#### Expected Behavior
Errors should be handled and users notified via toaster notification (if needed).

**Comment by leecalcote** [comment]
@dhruv0000 are we past this issue?

**Comment by leecalcote** [comment]
@dhruv0000 is this fixed?

**Comment by dhruv0000** [comment]
Yes, it was fixed.
