### ISSUE TITLE
[MeshSyncv1] Add discovery of traefik-mesh-controller pod

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2262]
#### Current Behavior
Deployments of Traefik Mesh are not discovered and shown in the System Dashboard.

#### Desired Behavior
Add discovery of the "traefik-mesh-controller" pod to MeshSync v1.

**Comment by leecalcote** [comment]
@kumarabd let's transition this to MeshSyncv2...

**Comment by leecalcote** [comment]
@utkarsh-pro, which service meshes does the control plane dashboard not support?

**Comment by tangledbytes** [comment]
@leecalcote dashboard should support the following service meshes:
1. Istio
2. Linkerd
3. Traefik Mesh
4. Consul
5. Octarine
6. Open Service Mesh
7. Kuma
8. Nginx Service Mesh (Disabled for now, https://github.com/meshery/meshery/issues/2533)
9. Network Service Mesh
10. Citrix Service Mesh

**Comment by leecalcote** [comment]
Thank you, sir. 👍
