### ISSUE TITLE
[Docs] v0.5.0 Release: MeshSync

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2267]
**Current State:**
MeshSync is a new capability to be released under v0.5.0 and will be included in the [Meshery v0.5.0 Release Announcement](https://docs.google.com/document/d/1f7mGHtjHiywbN9UzwuldOX8x_Lpv2Ss8i4b045Np9OM/edit#)

**Desired State:**
Documentation of this feature and its behavior is needed. Here is a start:

### Understanding MeshSync
MeshSync, an event-driven, continuous synchronization routine performs the task of ensuring that the state of configuration and status of operation of any service mesh and of the Kubernetes environment are known to Meshery. MeshSync runs as a Kubernetes custom controller under the control of Meshery Operator. Both Meshery Operator and MeshSync are deployed by Meshery upon successfully initializing connection with your Kubernetes cluster.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Aisuko** [comment]
Our document may need to update, I hit the issue after the followed step of our document that 

```
➜  docs git:(doc/meshSync) bundle install  
Your Ruby version is 2.7.0, but your Gemfile specified 2.7.1

```

**Comment by leecalcote** [comment]
Yeah... sometimes a discrepancy between what Ruby version that is configured in Jekyll and what Ruby version you have in your local dev environment. I use http://rvm.io/ to manage multiple versions of Ruby on my local system. I believe that you’ll want to ensure that you have a Ruby 2.7.1 environment on your local system (or you can use `make Docker` to build the site, but it’s a little slower.

**Comment by Aisuko** [comment]
Yep, you are right sir. Finally, I change to use  `rvm`  rather than install the latest ruby into the system directly. So should we update the documents?

**Comment by leecalcote** [comment]
Oh, very good. Yes, that'll work - updating the Ruby version number of the Jekyll system sounds good.
