### ISSUE TITLE
Rename image for NGINX sm

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2274]
#### Description
Rename docker image name for NGINX service mesh in the docker-compose.yml

#### Current image
local/meshery-nginx-sm:stable-latest

#### Expected image
layer5/meshery-nginx-sm:stable-latest

#### Environment:
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser:

**Comment by navendu-pottekkat** [comment]
@kumarabd Please check and merge
