### ISSUE TITLE
Register Meshery images as Official Docker images

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2279]
#### Current Behavior
Docker images for Meshery are not listed as Official images. 

#### Desired Behavior
Starting with [layer5/meshery](https://hub.docker.com/r/layer5/meshery) image, work through the process of having Meshery images listed as Official in Docker Hub. See https://github.com/docker-library/official-images#contributing-to-the-standard-library

**Comment by diru1100** [comment]
May I take this issue? Looks like a good way to learn best practices in docker and about meshary at once :)

**Comment by leecalcote** [comment]
@diru1100 sounds real good. @mkycia is a great individual to engage and collaborate with on this effort.
