### ISSUE TITLE
Attain CII Silver

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2280]
#### Current Behavior
The [Meshery project](https://bestpractices.coreinfrastructure.org/en/projects/3564) is currently a CII "passing" level project.

#### Desired Behavior
The Meshery Project will ideally be a "silver" level project by working through each of the silver level requirements: https://bestpractices.coreinfrastructure.org/en/projects/3564?criteria_level=1

**Comment by diru1100** [comment]
It seems that there are a varied amount of tasks which are to be done to attain silver status. 

Should one create a new issue for every task and tag this as the main issue there?

**Comment by leecalcote** [comment]
Individual issues would be great. 👍
