### ISSUE TITLE
[UI] Cleanup top portion of Management page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2281]
#### Current Behavior
The /management page recently underwent some changes and is need of a little cleanup. See the mockup below.

#### Implementation
1.  Make the changes shown in red.
2. Place the drop-down list onto it's own paper (or card).
3. Make "Manage Service Mesh" a bold font weight.

#### Mockup

<img width="1462" alt="Screen Shot 2021-01-18 at 11 03 21 PM" src="https://user-images.githubusercontent.com/7570704/105284828-d99bc680-5b78-11eb-898c-c8ab68c03457.png">

**Comment by killbotXD** [comment]
Hey, @leecalcote If no one is working on this can I take this issue?

**Comment by leecalcote** [comment]
Hi @killbotXD, yes, please. That would be great!

**Comment by anirudhjain75** [comment]
Feel free to
