### ISSUE TITLE
[Docs] Website is not responsive

### ISSUE THREAD

**Issue by diru1100** [layer5io/meshery#2290]
**Current State:**

Not responsive UI

**Desired State:**

Responsive and fits in all types of screens

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thank for filing this issue, @diru1100. This is a good goal and something that we should do. If there are specific areas in the docs to make responsive or new approaches to certain challenges (like image sizing), please do itemize them and let’s start knocking them down (implementing). 👍

**Comment by leecalcote** [comment]
@diru1100 would you like to work on this (be assigned this issue)?

**Comment by diru1100** [comment]
@leecalcote I think this issue is more broad and can have mutliple sub issues. I will try to solve some of them.
