### ISSUE TITLE
[mesheryctl] Add persistent `--verbose` `-v` flag for all commands

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2295]
#### Current Behaviour

Currently, there is a `--debug` `-d` flag which sets output to verbose mode. _It seems to have some error in its implementation._

There is a top level `version` command and a `--version` `-v` flag which is obsolete given the current usage. 

#### Desired Behaviour

1. No need for `--version` `-v` flag. 
2. `--verbose` `-v` for verbose logs.

#### Implementation

Change the flag to `--verbose` `-v` and fix it if there are any errors.

Remove the `--version` `-v` flag.

#### Future Scope

Add more debug logs to commands that does not have any currently.

**Comment by leecalcote** [comment]
Separate from the docs update, it would be good to include this function in a `mesheryctl` Contributor's Guide - https://github.com/layer5io/meshery/issues/2303
