### ISSUE TITLE
Meshery bash script fails due to config.yaml

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2296]
#### Description
The meshery bash script will not flow cleanly through the install process because it will not find a config.yaml file. It will then stop and prompt the user to create one.

#### Expected Behavior
 We can take a couple of different approaches:
1. Add a variable to the installer script for platform type (similar to what has been done to support `MESHERY_VERSION`)
2. Add a `--silent` to the system star command.

Both of these can be implemented (and probably should) over time. Given where we are with the current lack of support for `platform: kubernetes` in the `config.yaml` and `system start` command, let's move forward with option 2 as a fix for this issue.

#### Environment:
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

<!-- Optional

**Comment by kumarabd** [comment]
@hexxdump Something that you might be interested in...

**Comment by navendu-pottekkat** [comment]
@kumarabd Since we are planning on `platform: kubernetes` support, we may need to come back to this issue at a later time. So we may need to keep this on hold till we have the `platform: kubernetes` support.

**Comment by hexxdump** [comment]
> @hexxdump Something that you might be interested in...

Sure @kumarabd . let me take a look

**Comment by leecalcote** [comment]
_Discussion recap:_

A design spec is needed for this issue as it pertains to the upcoming support for `platform:kubernetes` in `mesheryctl`. As we go to make the first beta release today, new users are going to run into this issue immediately, and so, we should give consideration to a quick fix.

A quick solution could be to include the --silent flag (as recently suggested by @Michael Gfeller), which would auto answer “yes” to creating the missing config.yaml. This quick fix may in fact be a decent long-term solution as well.

Both of these can be implemented (and probably should) over time. Given where we are with the current lack of support for `platform: kubernetes` in the `config.yaml` and `system start` command, let’s move forward with the --silent as a fix for this issue.
