### ISSUE TITLE
[Docs] Meshery UI Contributor Guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2304]
**Current State:**
Meshery UI has a number of aspects to it like use of rest, graphql, nextjs, react, billboardjs and so on.

New and existing contributors to Meshery's web user interface will benefit from a contributor guide.

**Desired State:**
- Create a README.md in the /ui folder that serves as a contributor guide to this component.
- Add link to this README in the main Meshery CONTRIBUTING.md.
- Include description of things like:
   - Meshery UI doing server-side rendering of NextJS/React components.
   - Meshery UI uses billboard.js as the charting library. 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by jomefavourite** [comment]
I'll like to take this task

**Comment by leecalcote** [comment]
Sounds real good, @jomefavourite

**Comment by leecalcote** [comment]
@Nikhil-Ladha what else can we add to this doc? There are certain conventions and tools that we should probably highlight in the doc. Methods for identifying when to build a component vs. not. and so on...

**Comment by Nikhil-Ladha** [comment]
Yes, there can ve different types of issues, and they have different level of complexity. I will try and open a PR, to include those updates.
