### ISSUE TITLE
[mesheryctl] [child] platform support during “bash script” installation(`platform: kubernetes`)

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2309]
See Epic #2307 for context and further description of this issue.

**Current Behavior**
When a user tries to install Meshery through bash,

```
$ curl -L https://git.io/meshery | bash -
```

the [bash script](https://github.com/layer5io/meshery/blob/master/meshery) _optionally_ runs [`mesheryctl system start`](https://github.com/layer5io/meshery/blob/566261f9f9618af1200a16ec593b327644e98d67/meshery#L99) at the end of the install procedure, and assumes a Docker-host installation is desired. 

i.e. It doesn’t not provide consideration for Kubernetes as a target platform. 

**Desired Behavior**
Identify Kubernetes as a target platform. 

**Implementation**
Create a separate flag to identify target platform type, supporting either “docker” or "kubernetes”.

Assignee: @hexxdump

**Comment by navendu-pottekkat** [comment]
@hexxdump We have added support for `platform: kubernetes` in the `system start` command. I think we can discuss on how to add support in the bash script installation now.

**Comment by leecalcote** [comment]
We need to add support for `platform: kubernetes` to `mesheryctl system context create` as well.

**Comment by navendu-pottekkat** [comment]
> We need to add support for `platform: kubernetes` to `mesheryctl system context create` as well.

@leecalcote added in this [PR](https://github.com/layer5io/meshery/pull/2559)

**Comment by navendu-pottekkat** [comment]
During bash script installation, when a new config file is created, it should ask if the platform is `docker` or `kubernetes` instead of assuming the platform is `docker`.

The bash script installation command should have a `--docker` and `--kubernetes` flag which will allow the user to override this question.

Meshery should be deployed on the corresponding platform specified by the user through the flag or from their response while creating the config file. (Which it should automatically if the `platform` is set to `kubernetes` in the `config.yaml` file)

@leecalcote this is the flow right? (FYI @hexxdump )

**Comment by leecalcote** [comment]
Yes, @navendu-pottekkat. Your last description is spot on.
