### ISSUE TITLE
[mesheryctl] [child] make `system reset` platform aware(`platform: kubernetes`)

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2310]
See Epic #2307 for context and further description of this issue.

**Current Behavior**

`mesheryctl system reset` will pull the context specific `docker-compose.yaml` files and does not consider for the current platform. Only the channel and version are considered.

**Desired Behavior**

`mesheryctl system reset` should also consider for the `platform`. Specifically, if the platform is Kubernetes, retrieve the specific Kubernetes manifest files as it currently does for `platform: docker`.

**Comment by leecalcote** [comment]
@aneeshnema given you recent work on `system reset`, you may want to pick up this issue.

**Comment by navendu-pottekkat** [comment]
@leecalcote Working on this requires [this PR](https://github.com/layer5io/meshery/pull/2365) to be done and merged. Once that is done, @aneeshnema can take this up.

**Comment by navendu-pottekkat** [comment]
@aneeshnema We have [added](https://github.com/layer5io/meshery/pull/2365) `platform: kubernetes` support to the `system start` command. I think we can start working on this issue.

**Comment by aneeshnema** [comment]
Does the same #2366 `version` and  `channel`  rules apply here?
