### ISSUE TITLE
[mesheryctl] [child] make `system logs` platform aware(`platform: kubernetes`)

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2312]
_See Epic #2307 "provide support for `platform: kubernetes`" for context and further description of this issue._

**Current Behavior**

`mesheryctl system logs` will start logs from Meshery server running on Docker. The current implementation defaults to Docker as the platform and the logs are obtained as shown-

https://github.com/layer5io/meshery/blob/b0c1a7fa39dd0456f9112be068d2601bfe17d465/mesheryctl/internal/cli/root/system/logs.go#L51

**Desired Behavior**

`mesheryctl system logs` should check the current platform and if the platform is Kubernetes, it should get the logs from Kubernetes. (_May involve port-forwarding/streaming from Kube-API_) 

// Adding @abhishekkumkar to this thread.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya Assigning it to you 🚀

**Comment by navendu-pottekkat** [comment]
Wait, I can't seem to assign it to you.

**Comment by piyushsingariya** [comment]
I'm not sure. Why this is happening?

**Comment by aneeshnema** [comment]
there you go

**Comment by navendu-pottekkat** [comment]
Do you need to be on the thread to be assigned? I was not able to add @piyushsingariya that is why I asked to comment on the thread.
