### ISSUE TITLE
[CI] [integration] [/settings] Test the "Discover Cluster" configuration

### ISSUE THREAD

**Issue by ramrodo** [layer5io/meshery#2316]
#### Current Behavior
There is no integration test that validates the functionality of the **Discover Cluster** button.

#### Desired Behavior
Have an integration test that clicks on the **Discover Cluster** and validates the connection established to the k8s cluster.

#### Implementation
You should mock the backend responses.

#### Acceptance Tests
The integration test should:
1. go to settings, click on "Discover Cluster" button, and be redirected to the "Cluster Configuration" section
2. validate the existence of the UI component in the cluster configuration

The above steps are referenced in the next images:

![image](https://user-images.githubusercontent.com/2797052/106366011-c6b68e00-62fe-11eb-968e-ade344cab79a.png)

![image](https://user-images.githubusercontent.com/2797052/106366016-cae2ab80-62fe-11eb-9c03-e7772f851d23.png)

This issue is related to the umbrella issue: #1037

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)
- [Functional Testing with Cypress in Meshery UI](https://layer5ng.netlify.app/blog/meshery/functional-testing-with-cypress-in-meshery-ui)
- There is already an e2e test that validates this functionality: [PR#2139](https://github.com/layer5io/meshery/pull/2139)
- Here is an integration test that you can take as an example: [PR#1853](https://github.com/layer5io/meshery/pull/1853)

**Comment by jesuslerma** [comment]
Can I work on this?

**Comment by ramrodo** [comment]
Sure! @jesuslerma. I just assigned it to you. Thanks.

**Comment by piyushsingariya** [comment]
Hey @jesuslerma Are you still working on this? or Can I take over?

**Comment by piyushsingariya** [comment]
Hey @ramrodo, @jesuslerma isn't responding, can I takeover?

**Comment by ramrodo** [comment]
@piyushsingariya let me try to reach him. If not, I'll let you know and re-assign to you

**Comment by jesuslerma** [comment]
Sorry for being a blocker. Please go @piyushsingariya
