### ISSUE TITLE
[CI] [integration] [/settings] Test the "Service Mesh" configuration

### ISSUE THREAD

**Issue by ramrodo** [layer5io/meshery#2317]
#### Current Behavior
There is no integration test that validates the functionality of the **Service Meshes** configuration.

#### Desired Behavior
Have an integration test that configures a service mesh adapter and validates the successful configuration submitted.

#### Implementation
You should mock the backend responses.

#### Acceptance Tests
The integration test should:
1. go to settings, specify the "Mesh Adapter URL" for Consul
2. submit the configuration
3. test that the confirmation message is displayed

The above steps are referenced in the next images:

![image](https://user-images.githubusercontent.com/2797052/106366264-455ffb00-6300-11eb-9587-cd2ca8d77009.png)

![image](https://user-images.githubusercontent.com/2797052/106366266-47c25500-6300-11eb-9c0a-9f75e42eb398.png)

This issue is related to the umbrella issue: #1037

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)
- [Functional Testing with Cypress in Meshery UI](https://layer5ng.netlify.app/blog/meshery/functional-testing-with-cypress-in-meshery-ui)
- There is already an e2e test that validates this functionality: [PR#2218](https://github.com/layer5io/meshery/pull/2218)
- Here is an integration test that you can take as an example: [PR#1853](https://github.com/layer5io/meshery/pull/1853)

**Comment by piyushsingariya** [comment]
I'll like to give this a shot:smile:

**Comment by Vi1234sh12** [comment]
@ramrodo  Can I work on this?

**Comment by ramrodo** [comment]
@Vi1234sh12 let me ask. Hey, @piyushsingariya are you working on this?

**Comment by piyushsingariya** [comment]
Yes! I am working on this one.

**Comment by ramrodo** [comment]
@Vi1234sh12 it's already been doing but let me create more issues and I'll let you know

**Comment by Vi1234sh12** [comment]
sure!
