### ISSUE TITLE
"meshery.yaml" not getting created when single command install is run

### ISSUE THREAD

**Issue by pranav-bhatt** [layer5io/meshery#2318]
#### Description

The [single command install](https://docs.meshery.io/installation/quick-start#install-meshery) fails when it executes `mesheryctl system start`, as it doesn't find "meshery.yaml" created. Tried on various platforms.

Work around was to manually copy "meshery.yaml" [from here](https://github.com/layer5io/meshery/pull/174/files/37a12a5be2b290e26315f36c159da0af2d427968). 

```
Installing mesheryctl in /usr/local/bin.
mesheryctl installed.
permissions moved to root
Removing installation files and opening Meshery...Docker is not running.
Start Docker now [y/n]? Attempting to start Docker...
Prerequisite Docker started.
Docker-Compose is not installed
Attempting Docker-Compose installation...
Prerequisite Docker Compose is installed.
Error: failed to start Meshery
See https://docs.meshery.io/guides/mesheryctl/#meshery-lifecycle-management for usage details
: open /root/.meshery/meshery.yaml: no such file or directory
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string   config file (default location is: /root/.meshery/config.yaml)
```
I've confirmed that no "meshery.yaml" file gets created either (Is this expected?):

<img src="https://user-images.githubusercontent.com/42911524/106430068-4ecc9d00-6491-11eb-8d02-c42f1ec28207.png" height="50">

#### Expected Behavior

Should succesfuly create a default "meshery.yaml", and continue without issues.

#### Environment:
- Host OS: Ubuntu 20.04, Ubuntu 18.04, CentOS 7, WSL2
- Meshery Version: 0.5.0-beta-1
- Kubernetes Version: -
- Browser: -

<!-- Optional 
#### To Reproduce
(Side note: As of this release, although the [installation script](git.io/meshery) includes the `--silent` flag, the release is older, and doesn't include the flag, and spits out an error.) 

1. Run the [single command install](https://docs.meshery.io/installation/quick-start#install-meshery)

**Comment by leecalcote** [comment]
@pranav-bhatt, will you confirm that you're using the "stable-v0.5.0-beta-1" client (mesheryctl as opposed to Meshery Server)?

**Comment by pranav-bhatt** [comment]
@leecalcote [this](https://github.com/meshery/meshery/releases/download/v0.5.0-beta-1/mesheryctl_0.5.0-beta-1_Linux_x86_64.zip) (https://github.com/meshery/meshery/releases/download/v0.5.0-beta-1/mesheryctl_0.5.0-beta-1_Linux_x86_64.zip) is the file that gets downloaded and used.

**Comment by kumarabd** [comment]
@pranav-bhatt will you be able to verify if this has been resolved in the edge channel?

**Comment by pranav-bhatt** [comment]
Could you tell me what changes I might need to make for checking that?

**Comment by leecalcote** [comment]
@ramrodo, this is a good question to ponder for the special case of the `mesheryctl` binary of the Edge Release Channel.
