### ISSUE TITLE
"--silent" flag added to mesheryctl script not present in latest release

### ISSUE THREAD

**Issue by pranav-bhatt** [layer5io/meshery#2319]
#### Description

As of release 0.5.0-beta-1, although the [installation script](git.io/meshery) includes the `--silent` flag (#2298) . However, since the release is older, it doesn't include the flag, and spits out an error. 

This should automatically get fixed once a new release comes out.

**Comment by navendu-pottekkat** [comment]
@leecalcote @hexxdump Should we patch this on a new release.

**Comment by leecalcote** [comment]
Great question, yes, let's land the `channel view` PR and cut another beta release.

@ramrodo, one thing for use to work through on CI is the fact that goreleaser doesn't bundle and push new scoop and homebrew formulas if it finds "alpha" or "beta" in the release tag. I have recently tried to change this behavior with an update in the goreleaser config. My latest change may provide the intended affect. We'll want to watch this behavior in "stable-v0.5.0-beta-2" release.

**Comment by leecalcote** [comment]
Goreleaser behavior update - https://github.com/meshery/meshery/issues/2300

**Comment by ramrodo** [comment]
@leecalcote To fix that in **goreleaser** we need to set `prerelease: auto` and manage a tag e.g. `v1.0.0-rc1`:

```
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  # prerelease: auto
```

Taken from PR:
**Add check if tag contains indicator for pre release #871** :
 https://github.com/goreleaser/goreleaser/pull/871

**Comment by ramrodo** [comment]
@leecalcote I created this PR hoping that could solve the problem: https://github.com/meshery/meshery/pull/2364

**Comment by leecalcote** [comment]
@hexxdump do you consider this issue complete?

**Comment by hexxdump** [comment]
> @hexxdump do you consider this issue complete?

The '--silent` flag has been replaced with `--y` flag for all `mesheryctl system` commands.
