### ISSUE TITLE
[CI] Convert Dependabot integration to config-based.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2349]
@ramrodo, I recently updated issue labels to move `ui` out of `area/ui` and into `component/ui`. At the same time, I created `area/ux`. Dependabot config needs updated to reflect this change. Note from Dependabot above:

```
The following labels could not be found: area/ui.
```

I will update the Dependabot integration to use config files, so that you might access and manage this config as well.

<img width="1247" alt="Screen Shot 2021-02-02 at 2 10 49 PM" src="https://user-images.githubusercontent.com/7570704/106656625-88b8a480-6560-11eb-8be2-15c7bbdcbcbe.png">

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/issues/2329#issuecomment-771946069_

**Comment by ramrodo** [comment]
Sounds good. Thanks @leecalcote

**Comment by leecalcote** [comment]
Done
