### ISSUE TITLE
[Docs]Broken link in the docs of Lifecycle Management

### ISSUE THREAD

**Issue by tripathyprateek** [layer5io/meshery#2367]
**Current State:**
https://docs.meshery.io/functionality/lifecycle-management#service-mesh-lifecycle-management first line's link points to a address which doesn't exist. The correct link should be https://docs.meshery.io/service-meshes
**Desired State:**
Update the link to the correct address.
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thank you, @tripathyprateek. If you would like to take on this issue, you're welcome to self-assign. Good of you to call out this bug. 👍
