### ISSUE TITLE
[Docs] Installation: 404

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2373]
**Current State:**
The [Installation page](https://docs.meshery.io/installation/) returns a 404 error.

**Desired State:**
This page should instead show a collection (a bulleted list) of pages with the frontmatter category value of "installation". See https://docs.meshery.io/guides as an example.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Anita-ihuman** [comment]
Is this issue still up? 
if yes, can I take it up?

**Comment by leecalcote** [comment]
Yes, this issue is still open. That would be great, @Anita-ihuman.

**Comment by Anita-ihuman** [comment]
Please I am a bit confused about something,
 what is the frontmatter category value of "installation"? 
and the file I am supposed to fix the issue on should be in this folder I guess? https://github.com/layer5io/meshery/tree/master/docs/pages/installation.

**Comment by Anita-ihuman** [comment]
@leecalcote

**Comment by Anita-ihuman** [comment]
The quick start displays this content, https://docs.meshery.io/installation/quick-start#configure-your-environment 
So I want to understand if this is what the installation page is expected to return.
And if this is not, what should the bullet point be listing?
@leecalcote
