### ISSUE TITLE
[Docs] Scoop: Create mesheryctl installation guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2374]
**Current State:**
The Meshery Docs are missing a page dedicated to user instructions for installing `mesheryctl` with Scoop.

**Desired State:**
A dedicated page with category of "installation" should reflect the instructions available on https://github.com/layer5io/scoop-bucket.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by alphaX86** [comment]
Can I look on to this? Seems impressive!

**Comment by alphaX86** [comment]
After all, I'm free from exams after long time!

**Comment by alphaX86** [comment]
@leecalcote can I take up this issue or not?

**Comment by leecalcote** [comment]
Hi @alphaX86, yes, that would be great.

**Comment by alphaX86** [comment]
Thanks! I'll let you know when it's done

**Comment by alphaX86** [comment]
#2413 is closed, #2414 is the correct one
