### ISSUE TITLE
[Docs] Homebrew: Create mesheryctl installation guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2375]
**Current State:**
The Meshery Docs are missing a page dedicated to user instructions for installing `mesheryctl` with Homebrew.

**Desired State:**
A dedicated page with category of "installation" should reflect the instructions available on https://github.com/layer5io/homebrew-tap.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by metonymic-smokey** [comment]
@leecalcote I'd like to start working on this issue.

**Comment by leecalcote** [comment]
@metonymic-smokey sounds real good. 👍

**Comment by metonymic-smokey** [comment]
@leecalcote , the existing meshery docs have a `Supported Platforms` section and a separate section `Guides/using mesheryctl`. I think, reading the issue, that the new page should be a separate section `Installing mesherycytl` and have placed it so.
![image](https://user-images.githubusercontent.com/48997495/107767065-6e4daa80-6d5a-11eb-9e02-afd2db68f01c.png)
Is this placement alright?

Thanks!

**Comment by leecalcote** [comment]
Hi @metonymic-smokey, I think we're done here, correct?

**Comment by metonymic-smokey** [comment]
Yes, this can be closed @leecalcote.
