### ISSUE TITLE
[Docs] Promote Meshery Adapter for NGINX SM to beta

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2376]
**Current State:**
The Meshery Adapter for NGINX SM is in beta state.

**Desired State:**
The following areas should reflect a "beta" status for this adapter:
- [ ] The README in the root of this repo.
- [x] https://docs.meshery.io/service-meshes/adapters/nginx-sm.

Related - https://github.com/layer5io/meshery.io/issues/398
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Good sir, @bartkalanski, while your in the README, will you promote **Meshery adapter for Kuma** and **Meshery adapter for Open Service Mesh** to "stable" and do so in the docs.meshery.io and meshery.io as well?

**Comment by bartkalanski** [comment]
> Good sir, @bartkalanski, while your in the README, will you promote **Meshery adapter for Kuma** and **Meshery adapter for Open Service Mesh** to "stable" and do so in the docs.meshery.io and meshery.io as well?

Yes no problem, I'll get this done by tomorrow eve!
