### ISSUE TITLE
[mesheryctl] The failing test case due to Order mismatch when iterating over the array.

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2380]
Testcase for mesheryctl system channel --all is failing because of order mismatch during run time. 

Possible fix could be persisting the order by sorting based on keys and render the array through that. Need more suggestions to continue further work

The failing test case is because of Order mismatch when iterating order the array which is strange 🤔. Other than that everything is fine

_Originally posted by @anirudhjain75 in https://github.com/layer5io/meshery/issues/2256#issuecomment-771677608_

**Comment by navendu-pottekkat** [comment]
@anirudhjain75 Any updates to this issue? 

// We need to start working on unit tests for mesheryctl commands @aneeshnema @piyushsingariya @metonymic-smokey

**Comment by anirudhjain75** [comment]
Not that I know of. I made this with comments so someone from community can work on this

**Comment by navendu-pottekkat** [comment]
Unit tests for mesheryctl have not yet been added. This test will most likely be modified when the other tests are written. Closing this...
