### ISSUE TITLE
[mesheryctl] system start not recognizing user's current context

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2382]
#### Description
Meshery v0.5.0-beta-2 was released and an urgent defect has been identified in `mesheryctl system start`. This command does not recognize user’s current-context, and therefore, prevents them from starting Meshery.

```
$ mesheryctl system start
13:23:31 current context not set
```
#### Expected Behavior
- `start` should read the current-context from user's meshconfig (`config.yaml`).
- timestamp should not be shown to the user.

#### Environment:
- Meshery Version: v0.5.0-beta-2

**Comment by anirudhjain75** [comment]
This issue does not exist on latest master. I'll check the above mentioned tag

**Comment by leecalcote** [comment]
Fixed
