### ISSUE TITLE
[UI] Switch to Activate Operator 

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/meshery#2385]
#### Description
The switch to Activate operator shows its disabled when the operator is active.

#### Expected Behavior

The switch should reflect the operator state.
#### Environment:
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

<!-- Optional

**Comment by leecalcote** [comment]
@kumarabd is this in fact complete?

**Comment by dhruv0000** [comment]
yes. This was demoed in March 24th's Dev call.
