### ISSUE TITLE
[mesheryctl] Respect current-context, fetch correct docker-compose.yaml

### ISSUE THREAD

**Issue by aneeshnema** [layer5io/meshery#2393]
#### Description

Whenever `mesheryctl` cannot find `docker-compose.yaml` it downloads it from Github, but all it does not take into account the `correct-context` and always download the latest file from the master branch.
[Several instances](https://github.com/layer5io/meshery/search?q=fileURL) of this behaviour needs to be corrected.

`mesheryctl system reset` has been updated to fetch correct `docker-compose.yaml`  file from GitHub corresponding to the `channel` and `version` specified in the `current-context`. 

The logic inside `resetMesheryConfig` can be extracted to create a separate helper function that fetches correct file.
https://github.com/layer5io/meshery/blob/1a91051afe17d82a668c7429c735bf7ed94970c7/mesheryctl/internal/cli/root/system/reset.go#L80-L90

 

#### Expected Behavior

`mesheryctl` should fetch correct `docker-compose.yaml` based on `current-context`

#### Child Issues

Issue #2394 [mesheryctl] Feature: Add current-context support to `system update`
Issue #2395 [mesheryctl] Feature: Add current-context support to `system log`
Issye #2396 [mesheryctl] Feature: Add current-context support to `system start`

**Comment by navendu-pottekkat** [comment]
@aneeshnema You can make this an epic issue and add child issues for each of the commands.
