### ISSUE TITLE
[Docs] Alphabetically sort Meshery Docs Overview sections

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2398]
**Current State:**
Each of the bulleted lists here are not sorted.

<img width="1082" alt="Screen Shot 2021-02-10 at 1 18 54 PM" src="https://user-images.githubusercontent.com/7570704/107560182-a7dbb580-6ba2-11eb-80b3-a4bdf07ec0b6.png">

**Desired State:**
Ideally, each list is alphabetically sorted.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by UpasanaGhosh** [comment]
Hi, Can I take this up?

**Comment by leecalcote** [comment]
That would be great, @UpasanaGhosh

**Comment by alphaX86** [comment]
Is the issue open for grab? I mean for now 😅 Came a bit late IG

**Comment by Comurule** [comment]
@leecalcote, is this still free to try? 

CC
@PluckyPrecious

**Comment by PluckyPrecious** [comment]
Hi @UpasanaGhosh how is the task coming up? We understand schedules can get quite busy, do you mind @Comurule taking this up?

**Comment by UpasanaGhosh** [comment]
Hi @PluckyPrecious Sure @Comurule can this up. I was facing some environment issues so couldn't make much progress.

**Comment by PluckyPrecious** [comment]
> Hi @PluckyPrecious Sure @Comurule can this up. I was facing some environment issues so couldn't make much progress.

Oh my! Do take care and stay safe, we look forward to your contribution soonest.

**Comment by leecalcote** [comment]
Most of the pages are now sorted alphabetically with two (or three) sections remaining.

**Comment by laurencun** [comment]
@leecalcote Happy to contribute if you still need assistance with this issue.

**Comment by leecalcote** [comment]
Hi @laurencun, yes, that would be wonderful. 👍

**Comment by leecalcote** [comment]
@aayushdutt i wonder if you might be able to solve this one.

**Comment by Khusyasy** [comment]
Hi, is this issue still open?

**Comment by leecalcote** [comment]
Hi @Khusyasy, yes, it is. It would be great if you would like to take a crack at it.

**Comment by Khusyasy** [comment]
Okay @leecalcote I'll take a look at this one as soon as possible.

**Comment by Khusyasy** [comment]
Hey @leecalcote I'm sorry I think I can't finish this task, because I'm using a windows machine and it seems that I can't set up and run the project.

**Comment by chinmaym07** [comment]
Hey @Khusyasy 👋🏻 No problem ... 
I think this issue is of [docs.meshery.io](https://docs.meshery.io/) & it is built using Jekyll ..

You can refer to this [docs.meshery.io readme](https://github.com/meshery/meshery/tree/master/docs) to setup & run the project locally .. 
If you still face the issue do reach out to us on slack . We'll be more happy to help 👍🏻 😁 

Have you joined the Layer5 Community - http://slack.meshery.io? We have many helpful people that can point out resources for Jekyll & help you in setting up the project locally.

If you are willing to work on it again .. Please self-assign this issue .!!

**Comment by Alenjojo** [comment]
Hey @leecalcote  i would be happy to resolve this issue. Its my first time in meshery will be able to help you to rearrange it in alphabetical order

**Comment by leecalcote** [comment]
Thanks much, @Alenjojo. I’m tagging @chinmaym07 here as the last individual to work on this issue, so that he can decide where how he would like to proceed.

**Comment by chinmaym07** [comment]
Hey @Alenjojo .. 👋🏻 
You can definitely work on this .. My PR is incomplete right now .. You can refer to it & also refer to [this](https://github.com/meshery/meshery/pull/2865#pullrequestreview-655013890) comment to get a clear idea of the issue..

This issue doesn't require the files to be renamed. But it requires to restructure the way that we are iterating and sorting the pages in jekyll.
I'll assign it you .. You can work on it  ... If you face any difficulty . Please ping me on slack .. I'll try my best to help you & complete this issue . 👍🏻 🚀

**Comment by Alenjojo** [comment]
thank you so much @chinmaym07  , i will for sure if i need any

**Comment by leecalcote** [comment]
I spent a little bit of time today updating quite a few docs, including an update that takes care of this issue. Thank you all for making various attempts at this.
