### ISSUE TITLE
border radius in tweet panel in the footer

### ISSUE THREAD

**Issue by AJOO7** [layer5io/meshery#2400]
#### Description
the lower-right  border radius and lower-left border radius vary when scrolled inside the block 

#### Expected Behavior
the border radius must remain constant 

#### Screenshots/Logs

![border-issue](https://user-images.githubusercontent.com/67185443/107686532-5da22380-6ccb-11eb-8d2e-3925ff9c90a2.PNG)
![border-issue2](https://user-images.githubusercontent.com/67185443/107686541-60047d80-6ccb-11eb-8d36-5c3b5868f363.PNG)

#### Environment:
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

<!-- Optional 
#### To Reproduce
1. Go to '.https://meshery.io/blog/.'
2. Scroll down to '.footer..'

**Comment by leecalcote** [comment]
Thank you for raising this up, @AJOO7. 👍 Let us know how you would like to proceed:

1. An existing contributor in the community can pick this up.
1. If you would like to address (fix) this issue, you're most welcome to do so.

**Comment by AJOO7** [comment]
@leecalcote i would like to take the issue

**Comment by AJOO7** [comment]
@leecalcote  i have found that overflow must be hidden but facing problem finding the source code for website

**Comment by leecalcote** [comment]
@AJOO7 oh, I see. If you haven't joined the Meshery Community (http://slack.meshery.io), I encourage you to. You'll find helpful contributors inside. 👍

**Comment by Nikhil-Ladha** [comment]
I think the issue was on the meshery.io site?
It looks good now and if the above is true we can close the issue.
