### ISSUE TITLE
GraphQL Endpoint for ServiceMesh Addons

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2401]
#### Current Behavior
A New graphql Endpoint required that would provide the status of AddOns on a given service mesh. 
Endpoints required:
- `/api/mesh/adapter/scan`

Input:
- Service Mesh Name
- List of addons to request

Output:
- List of Addons and their status

---
[Optional]

**Comment by leecalcote** [comment]
Proposal: move to `/api/meshsync/mesh`

**Comment by leecalcote** [comment]
@kumarabd was this implemented? Will you update the endpoints spreadsheet to reflect this?

**Comment by kumarabd** [comment]
@leecalcote yes it is implemented. It's a graphql query/subscription used in the Addons component of the management section. The endpoints are already updated in the docs.

**Comment by leecalcote** [comment]
Thank you, @kumarabd
