### ISSUE TITLE
GitHub Action to send notification to Slack when project is starred

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#241]
**How can we help?**
As we track the adoption and use of Meshery as an open source project, it would be nice to see notifications sent to #meshery-notifications channel when a user stars the project.

*Implementation*
Use GitHub Actions to publish to Meshery's slack account.

**Comment by girishranganathan** [comment]
We can leverage GitHub Actions for this.
[Here](https://github.com/marketplace/actions/post-slack-message) is a GitHub Action we can leverage.
Events we can use are listed [here](https://help.github.com/en/articles/events-that-trigger-workflows#event-restrictions). Trigger on the ```watch``` event.

Repo for Meshery's Github actions - https://github.com/meshery/l5act

We have the GitHub Actions config file here: https://github.com/meshery/l5act/blob/master/.github/workflows/ci.yml

You can try copying this file and starting to work on a simpler file which will trigger on `watch` event and use the `post-slack-message` action to send a slack message.
