### ISSUE TITLE
[Docs] Update database architectural diagram

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2421]
**Current State:**
The diagram on this page - https://docs.meshery.io/concepts/architecture/database is outdated.

**Desired State:**
The representative slide in [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.gbba492491e_0_5) (slide 7) should be exported to SVG and used replace the existing slide.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by alphaX86** [comment]
@leecalcote what kind of picture do you expect? The whole slide or the Physical schema alone? I'd like to take this one

**Comment by leecalcote** [comment]
Thanks for asking, @alphaX86. I adjusted the diagram to fill the slide more completely. This allows us to simply download the entire slide as SVG without need for modification.

In the slide's earlier format, it would have been best to take the innards of the slide only.

**Comment by alphaX86** [comment]
Done! @leecalcote it may need to test to see if it works! :)
