### ISSUE TITLE
[Docs] Add Artifact Hub Reference in Kubernetes installation page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2422]
**Current State:**
The Helm chart for Meshery is available on Artifact Hub - https://artifacthub.io/packages/helm/meshery/meshery

**Desired State:**

The [Kubernetes page](https://docs.meshery.io/installation/platforms/kubernetes#using-helm) should have a section describing the chart and pointing to Artifact Hub - 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by AkiraBrand** [comment]
I'd like to work on this, please!

**Comment by leecalcote** [comment]
That would be great, @AkiraBrand. 👍

**Comment by leecalcote** [comment]
@AkiraBrand this item is still very much desired. Is this something you're still considering to knock out?

**Comment by leecalcote** [comment]
Let’s hide (via a toggle - see WSL page for an example) the helm v3 and v2 instructions and instead list the artifact hub method prominently.
<img width="809" alt="Screen Shot 2021-04-01 at 11 30 00 PM" src="https://user-images.githubusercontent.com/7570704/113380714-8eedb600-9342-11eb-9fdc-35f463bb96f1.png">
