### ISSUE TITLE
[UI] Management: Kubernetes chip and paper card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2433]
#### Desired Behavior
Please make the two enhancements described in the mockup.

#### Mockups

<img width="898" alt="Screen Shot 2021-02-21 at 8 10 21 PM" src="https://user-images.githubusercontent.com/7570704/108648585-3e508680-7481-11eb-92bf-962e55dc3c08.png">

**Comment by leecalcote** [comment]
@Nikhil-Ladha I wonder if this might be two small enhancements you could make.

**Comment by Nikhil-Ladha** [comment]
Sure, I will take it up.
