### ISSUE TITLE
[UI]: Header overlaps with the navbar on collapsing

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#2442]
#### Description

The header of a page overlaps the navbar when the navbar is collapsed

#### Expected Behavior

The header of a page shouldn't overlap with the navbar when it is collapsed. The width of the collapsed navbar has to be increased.

#### Screenshots/Logs

![Screenshot from 2021-02-23 21-08-25](https://user-images.githubusercontent.com/29438875/108868638-6b856c00-761c-11eb-925b-7602f3b8b48c.png)

#### Environment:
- Browser: Chrome, Firefox

<!-- Optional 
#### To Reproduce
1. Open Meshery
2. Collapse the navbar and find the issue

**Comment by Nikhil-Ladha** [comment]
It was after a long long time I opened Meshery and found a UI issue instantly.....Wow! 😆

**Comment by chinmaym07** [comment]
@Nikhil-Ladha Can I fix this ?

**Comment by Nikhil-Ladha** [comment]
Sure...go ahead.

**Comment by Nikhil-Ladha** [comment]
> I think reducing z-index value will solve this problem .

That is a workaround, not a solution I would say. Because, if you inspect and see you can notice the width being lesser than what it should be.

**Comment by chinmaym07** [comment]
Yes got it .. Width of collapsed drawer is less thankx 👍🏻
