### ISSUE TITLE
[Docs] Describe how users can adjust which adapters to deploy using meshconfig

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2444]
The new `context` command enables users to adjust which adapters they want to have running. While this command doesn't provide the flag listed above (`--adapters`), yet, Meshery's docs need to be updated to provide users a description of the `config.yaml`(meshconfig) file and how to update it.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/issues/2105#issuecomment-784345742_

**Comment by metonymic-smokey** [comment]
@leecalcote could I work on adding the `context` command to the docs with this since I had worked on adding the `--adapters` flag?
git
Thanks!

**Comment by leecalcote** [comment]
@metonymic-smokey, that sounds great. 👍

**Comment by metonymic-smokey** [comment]
@leecalcote 
I am a little unsure about certain things on this issue:
1. Do I add the `context` specific commands to the same column or let them remain in `flag`? Will document `--adapters` accordingly.
2. Which section do I add the part about specifying `config.yaml` adapters?

I have documented the `context` commands for now, let me know if there are any changes to be made.

For now, I have added `context`

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey as @alphaX86 is working on redesigning the command reference page, we might need to pause this and wait for it to be refactored. Maybe the current structure of the YAML file would be changed. It should be done soon, we can modify this after that...
