### ISSUE TITLE
[UI] Add example usage in each of the Performance Test's Request Header fields

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2448]
#### Current Behavior
The performance test form is not as intuitive as it could be. Users need example values in the fields in order to better use the tool.

<img width="855" alt="Screen Shot 2021-02-23 at 11 42 19 AM" src="https://user-images.githubusercontent.com/7570704/108884650-76181500-75cc-11eb-9ddd-b3e87e9dfaa8.png">

#### Desired Behavior
Show example values in each field.
Request Header (example: {"host":"bookinfo.meshery.io"})

#### Mockups
<img width="855" alt="Screen Shot 2021-02-23 at 11 42 19 AM" src="https://user-images.githubusercontent.com/7570704/108896178-2fc9b280-75da-11eb-8e8b-0ec8c15350ea.png">

**Comment by leecalcote** [comment]
@pranav-bhatt will you suggest other fitting examples for Request Cookies, Content Type, and Request Body?

**Comment by leecalcote** [comment]
@adithyaakrishna this is something you might do.

**Comment by adithyaakrishna** [comment]
Yeah sure @leecalcote 
Do assign me this, I would love to do this🚀
