### ISSUE TITLE
[UI] Add margin between cards within paper background

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2453]
#### Description
There is a lack of margin between the cards in the `/management` page.

#### Expected Behavior
Cards should be comfortably separated by whitespace akin to how they are on the main system dashboard.

#### Screenshots/Logs
<img width="1370" alt="Screen Shot 2021-02-24 at 10 14 09 AM" src="https://user-images.githubusercontent.com/7570704/109057735-bc8e7200-76a7-11eb-9798-0f276e329dc7.png">

**Comment by Nikhil-Ladha** [comment]
@leecalcote this is the old view ig. Though, I think in the new view we might need as well, but could you confirm once?

**Comment by leecalcote** [comment]
Checking... I used `mesheryctl system channel switch edge` to switch to the edge release channel only to find that the edge-latest releases are being built, but not pushed to Docker Hub. I have just updated this workflow and am having the `edge-latest` build pushed now...

**Comment by adithyaakrishna** [comment]
@leecalcote I guess this is fixed right now, as there are margins ~16px between the cards in PR #2615  , please do let me know if it isn't, would love to take it up :)

**Comment by leecalcote** [comment]
Good eye. I believe this is just a duplicate of the other issue. Closing out...
