### ISSUE TITLE
[UI] Fixing alignment of Meshery Navbar logo With The screen title

### ISSUE THREAD

**Issue by austinogiza** [layer5io/meshery#2455]
#### Current Behavior
While Meshery UI looks amazing, I haven noticed a few sections that will greatly improve our UI. Currently the meshery logo in the sidebar and the title of the screen isn't aligned/is misaligned

#### Desired Behavior
Horizontal alignment of the logo section with the global nav bar section.

<img width="886" alt="109069719-e66c8680-76f1-11eb-9682-1e5f191e25ff" src="https://user-images.githubusercontent.com/7570704/109070620-55c58480-76b8-11eb-815f-32a8427d7dfa.png">

**Comment by chinmaym07** [comment]
Can I knock this?

**Comment by austinogiza** [comment]
@chinmaym07  definitely
