### ISSUE TITLE
[UI] Changing Meshery title font weight

### ISSUE THREAD

**Issue by austinogiza** [layer5io/meshery#2456]
#### Current Behavior
Currently the typography of meshery is coming together, and we will like to make slight adjustments, like the font weight of the title

#### Desired Behavior
Adjusting the font weight from bold(700) to medium(500). 
![title1](https://user-images.githubusercontent.com/44683018/109083930-1f632600-7707-11eb-930c-b8fb4e1766fe.PNG)
![title](https://user-images.githubusercontent.com/44683018/109083936-212ce980-7707-11eb-8817-e831ef27b797.PNG)
#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by ramrodo** [comment]
I changed it to **[UI]** because I think it is something related to UI. If I understood it wrong, please let me know.

**Comment by leecalcote** [comment]
Thank you, @ramrodo. Yes, that’s right.
