### ISSUE TITLE
[CI] Bug in workflow trigger to notify remote providers

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2458]
#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by leecalcote** [comment]
@kumarabd Fixed?

Please take a moment to review your currently assigned issues and make quick updates where you can. 👍

**Comment by leecalcote** [comment]
@kumarabd status?

**Comment by kumarabd** [comment]
Yes this is done @leecalcote
