### ISSUE TITLE
Create an adapter for Mae.sh

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#248]
**Enhancement Description**
mae.sh is a new service mesh from Containous. We need a new adapter for Mae.sh.

**Comment by leecalcote** [comment]
In preparation for this effort, the “meshery-maesh” repo has been created.

**Comment by ashiscs** [comment]
@girishranganathan sir, this issue is already addressed and needs to be closed in my opinion!

**Comment by leecalcote** [comment]
@ashiscs sounds good. A non-functional template has been created.

@SantoDE, @mmatur @dtomcej we would love to have you engage to tie off the last portion of the [Meshery adapter for Maesh](https://github.com/meshery/meshery-maesh).

**Comment by kushthedude** [comment]
Not stale

**Comment by leecalcote** [comment]
@utkarsh-pro, up to the challenge? This service mesh is now called Traefik Maesh

**Comment by utkarsh-pro** [comment]
> @utkarsh-pro, up to the challenge? This service mesh is now called Traefik Mesh

@leecalcote YES! :rocket:
