### ISSUE TITLE
[CI] Update GitHub workflows to prevent initiation of Netlify builds unless changes to /docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2489]
Deploy preview for *meshery-docs* ready!

Built with commit 88755e1cb9c2c0eadee83a2a5a3f0cc373fe0128

https://deploy-preview-2487--meshery-docs.netlify.app

_Originally posted by @netlify in https://github.com/layer5io/meshery/pull/2487#issuecomment-788175738_

**Comment by leecalcote** [comment]
@ramrodo I know this was taken care of in the past, but behavior has resurfaced. Ideally, this is configuration that we make inside of the workflows (not leveraging netlify's configuration or logic).

**Comment by ramrodo** [comment]
@leecalcote I think I finally fixed it. I followed this hack for ignoring **dependabot** updates also:
https://www.netlify.com/blog/2020/04/27/ignore-unnecessary-builds-to-optimize-your-build-times/

adding this to our Netlify config:
https://github.com/meshery/meshery/pull/2487/commits/eb99ee094549916b28439510d43b0e702ad458a6#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489edR5

And as you can see here:
https://app.netlify.com/sites/meshery-docs/deploys/603d76e4bafc0d0008a69355

it was finally canceled.
