### ISSUE TITLE
[UI] Increase font weight of meshery welcome screen

### ISSUE THREAD

**Issue by austinogiza** [layer5io/meshery#2498]
#### Current Behavior
The "Please choose a provider to continue" font weight is currently 500

#### Desired Behavior
Proposing the increase of the font weight of the "Please choose a provider to continue" from 500 to 700

#### Implementation
below is the design we currently have and how it should look like
<img width="1134" alt="meshery-issue" src="https://user-images.githubusercontent.com/44683018/109693519-0b497980-7b8a-11eb-9e9e-821a4f6b1fc0.png">

**Comment by Jagrati24** [comment]
I'd like to take up this issue.

**Comment by austinogiza** [comment]
@Jagrati24 Thank you

**Comment by leecalcote** [comment]
@Jagrati24 how is this coming along? Can we offer any help?

**Comment by adithyaakrishna** [comment]
@leecalcote Can I work on this? 👀
Ig I can finish it off with another issue #2448  as this is a very simple fix
