### ISSUE TITLE
[UI] Control Plane Dashboard for Kuma

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2501]
#### Current Behavior
When Kuma service mesh is running, Meshery doesn't show a control plane dashboard for this service mesh like it does for other service meshes.

#### Desired Behavior
A control plane dashboard should be visible in the System Dashboard page for Kuma.

**Comment by vineethvanga18** [comment]
Closing this @leecalcote

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18
