### ISSUE TITLE
[Docs] Add Meshery and mesheryctl roadmap into a ROADMAP.md file

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2519]
**Desired State**

A high level outline of Meshery and `mesheryctl` roadmap is to be added in the root of the `meshery` repo in a `ROADMAP.md` file.

Reference document- [Meshery Roadmap](https://docs.google.com/document/d/1kvcz8jdvFwXmYBBaY2-3fHHUUoy1GJLpZZXuoxZQoOk/edit)

**Comment by alphaX86** [comment]
Hi @navendu-pottekkat, what kind of page is that? A page to be added in DOCS site or put as a normal file in GitHub repo?

**Comment by navendu-pottekkat** [comment]
@alphaX86 This will be a normal markdown file in the root of this repo. I will add it by EOD.

**Comment by alphaX86** [comment]
OK cool, can we work on it?

**Comment by navendu-pottekkat** [comment]
I'm working on it now... 

@alphaX86 I will share the design spec of the new docs page after the Meshery dev call today. That would be a good issue for you to take up.

**Comment by alphaX86** [comment]
Alright! 👍
