### ISSUE TITLE
[Docs] Command reference entry for mesheryctl pattern

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2521]
**Current State:**
[mesheryctl pattern](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.fpuuy11gk85g) support is a new capability to be released under v0.6.0 and will be included in the [Meshery v0.6.0 Release Announcement]()

**Desired State:**
Documentation of `pattern` command and its behavior is needed. 

**Desired State:**
1. Improve the documentation and publish (see https://docs.meshery.io/reference/mesheryctl)
1. Add a section for every sub-command and flag

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by navendu-pottekkat** [comment]
@leecalcote This will be fixed in #2529 . So could we close this issue?

**Comment by leecalcote** [comment]
This issue can be made a child of the other, if you like.

**Comment by navendu-pottekkat** [comment]
The pattern command was added to the [mesheryctl Command Reference](https://github.com/layer5io/meshery/pull/2546) in [this PR](https://github.com/layer5io/meshery/pull/2546). Closing this issue...
