### ISSUE TITLE
[mesheryctl] Remove Octarine from default listing

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2526]
#### Current Behavior
Octarine is listed as one of the service meshes in the default mesheryctl context created.

#### Desired Behavior
1. Remove ocarine-adapter from the mesheryctl template which is used for generating contexts.
ref - https://github.com/layer5io/meshery/blob/master/mesheryctl/pkg/utils/helpers.go#L97
2. Remove ocarina from docker-compose.yml in meshery root directory.
---
[Optional]

**Comment by leecalcote** [comment]
@anirudhjain75 or @aneeshnema, would you like to take this?
