### ISSUE TITLE
[Docs] redesign mesheryctl Command Reference

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2529]
**Current State:**

[mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl) is a central document which shows all the available `mesheryctl` commands and their usage.

**Desired State:**

However, the current page is not intuitive to the user and also misses documentation for some of the new commands added in `mesheryctl`.

The goal of the new design should be the following-

1. **Improved mesheryctl Command Reference page** that the users can refer to.
2. **Links added to each of the commands** which will point to the individual doc of each command.(individual docs are not added currently)

See [user stories in the design spec](https://docs.google.com/document/d/1Iw88bZEL_fWeajxHh0BgmhuXGKl455P4CF-vm1yCkU8/edit#heading=h.nj62kbe4pwcb) for more info.

The following principles should be followed while designing and maintaining the document-

* **Intuitive**
The document should be intuitive to the user. They should be able to easily understand the layout of the commands and should be able to easily check the subcommands and flags for each of the commands.

* **Ease of access**
Each of the commands will have a separate documentation page and link to that page should be added to the corresponding command in the table.

**Implementation:**

* Improve the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl) page with inspiration from the [mesheryctl Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit?usp=sharing) doc.

The table should have the following columns-

1. command/arguments- The base command/argument
2. flag- Flags available for the given command
3. function- The function of the given command
4. usage- Example usage of the given command

* Add links in each entry in the table corresponding to a command which points to individual docs of the respective command (individual docs are not added currently). 

---
**Contributor Resources:**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl)
- [mesheryctl Command Reference and Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit?usp=sharing)
- [design spec- mesheryctl Command Reference](https://docs.google.com/document/d/1Iw88bZEL_fWeajxHh0BgmhuXGKl455P4CF-vm1yCkU8/edit#)

**Comment by navendu-pottekkat** [comment]
@alphaX86 all yours for the taking!

**Comment by alphaX86** [comment]
Well well, @navendu-pottekkat I accept! 😁👍

**Comment by alphaX86** [comment]
@navendu-pottekkat Am I supposed to create a separate table for `system channel` and `system context`?

**Comment by alphaX86** [comment]
I'm asking this to avoid issues, coz in sheet it's like that

**Comment by navendu-pottekkat** [comment]
It could be on the same table. Both of these will come under **Meshery Lifecycle and Troubleshooting** table.

**Comment by navendu-pottekkat** [comment]
That would be 5 tables in total. This is similar to the existing doc.

**Comment by alphaX86** [comment]
Okie, I did the Pattern configuration table and it looked good, but the `validate` command under `mesh` made one problem but I'm resolving it now

**Comment by navendu-pottekkat** [comment]
Nice! This doc is going to be referred a lot in the future. 🚀
