### ISSUE TITLE
Include setup script in goreleaser for mesheryctl

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#254]
**Enhancement Description**
When a user downloads the mesheryctl package from the [Meshery repository's releases](https://github.com/layer5io/meshery/releases), a zip/tar archive is downloaded to their local system. After the user uncompresses the zip/tar, a short deployment script  (`setup`) should be included for ease of moving the `mesheryctl` binary into their /usr/local/bin folder.

Setup Script (`setup`)
```
#!/usr/bin/env bash
mv ./mesheryctl /usr/local/bin/mesheryctl
sudo chmod a+x /usr/local/bin/mesheryctl
```

*Implementation*
1. Create a script file including the commands above.
1. Name the script file `setup`.
1. Create a new folder in the Meshery repo called `scripts` under the [mesheryctl directory](https://github.com/layer5io/meshery/tree/master/mesheryctl).
1. Put `setup.sh` script into the `scripts` folder.
1. update [.goreleaser.yaml](https://github.com/layer5io/meshery/blob/master/.goreleaser.yml) to include the `setup` script in each of the zip/tar packages that it creates.

**Comment by subhamkrai** [comment]
closed issue #254
