### ISSUE TITLE
[meshery] Adapter not active when deployed using docker

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2541]
#### Description

The adapters are not active when deployed using mesheryctl system start on docker platform.

#### Expected Behavior

Docker platform hosted meshery should be same as kubernetes hosted ones

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/14249589/110824729-531e7e00-82b9-11eb-97f1-74a6d26d5a81.png)

#### Environment:
- Host OS: Windows
- Meshery Version: 0.5.0 rc

**Comment by leecalcote** [comment]
@anirudhjain75, I believe this issue is related to -- https://github.com/meshery/meshery/discussions/2591

**Comment by leecalcote** [comment]
@piyushsingariya is this still an issue?

**Comment by piyushsingariya** [comment]
Yeah, I'm facing it.

**Comment by leecalcote** [comment]
This issue is no longer present in the latest release of Meshery. Please reopen if you find otherwise. Thanks for reporting this issue.
