### ISSUE TITLE
[mesheryctl] Issue with mesheryctl update script version matching

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2542]
#### Description

There is an issue with strings used for comparing version of mesheryctl

#### Expected Behavior

Should not show update message if user is on latest version

#### Screenshots/Logs

``` PS C:\Users\aniru> mesheryctl.exe perf --url https://google.com --token '.\Downloads\auth(1).json'
A new release of mesheryctl is available: 0.5.0-rc-5 → v0.5.0-rc-5
https://github.com/layer5io/meshery/releases/tag/v0.5.0-rc-5
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl ```

**Comment by piyushsingariya** [comment]
Looks like [this](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/root.go#L71) fails to compare the versions as the `latest` contains `v` as the prefix, and result in printing the error.

**Comment by piyushsingariya** [comment]
Hey @anirudhjain75 This issue has been already resolved with #2552

**Comment by anirudhjain75** [comment]
Sure feel free to close it :)

**Comment by navendu-pottekkat** [comment]
Yep, this could be closed.
