### ISSUE TITLE
Install meshery to a local binary directory

### ISSUE THREAD

**Issue by fruffy** [layer5io/meshery#2547]
#### Current Behavior
Currently, the installation for meshery on Linux system is  `curl -L https://git.io/meshery | bash -`
This fails when the permission to write to /usr/local/bin is not given.

```bash
Installing mesheryctl in /usr/local/bin.
mv: inter-device move failed: meshery/mesheryctl' to '/usr/local/bin/mesheryctl'; unable to remove target: Permission denied
Permission Resolved: mesheryctl installed using sudo permissions.
chown: changing ownership of '/usr/local/bin/mesheryctl': Operation not permitted
Unable to write to /usr/local/bin/mesheryctl. Please verify write permission for fruffy.
```
For now, I just download the install file, edit it manually, and then run the installation.

#### Desired Behavior
It would be nice to have the option to install to a local directory. For example, `~/.local/bin/`. I am not sure if that is already possible with the current install script. 
Also if there is any file the current working directory that has the same name as one of the files that is being unpacked (for example, LICENSE, README.md), the installation will fail with a confusing error message. 

---
[Optional]

**Comment by leecalcote** [comment]
@fruffy which Linux distro are you running?

// @hexxdump

**Comment by fruffy** [comment]
A fairly standard Ubuntu Server machine: 
```bash
> cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
I also had the same problem on my local desktop, which uses a Ubuntu 20.10 flavor.

**Comment by hexxdump** [comment]
@leecalcote, we could prompt the user in meshery script to choose a preferred installation path.
I have noticed the error too with the existing LICENSE, README.md files.
I will take a look at improving these scenarios.
