### ISSUE TITLE
Update release version numbers in Meshery docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#255]
**Description**
The release version numbers listed in the docs are out of date based on recent renumbering of the Meshery release version numbers.

*Implementation*
The version numbers on this page (https://meshery.layer5.io/docs/installation/releases) needs to be updated to reflect the version numbers in the repo's releases page (https://github.com/layer5io/meshery/releases).

Here is the docs [releases](https://github.com/layer5io/meshery/blob/master/docs/installation/releases.md) table.

**Comment by agarwalrohit2503** [comment]
I have done it please have a check on it

**Comment by leecalcote** [comment]
Fixed by #257. Thank you, @agarwalrohit2503! :)
