### ISSUE TITLE
[Helm] Meshery service is exposed over 8080; should be 9081

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2575]
#### Current Behavior
Meshery server deployments on Docker expose the Meshery UI over port 9081 by default, while Helm deployments of Meshery expose the UI over 8080. These should be the same by default.

#### Desired Behavior
Port 9081 should be used to expose Meshery service in the helm chart - https://github.com/layer5io/meshery/blob/master/install/deployment_yamls/k8s/meshery-service.yaml#L14-L15

**Comment by s1ntaxe770r** [comment]
Hey, if this hasn't been assigned to anyone I'd like to work on this.

**Comment by leecalcote** [comment]
@s1ntaxe770r that'd be excellent. 👍

**Comment by Aisuko** [comment]
@s1ntaxe770r For Helm chart of Meshery, we can replace the service port from `8080` to `9081`, and please see here https://github.com/meshery/meshery/blob/67f1f917a20ab1ffb517df44f34bc1804ab75e7f/install/kubernetes/helm/meshery/values.yaml#L55

And for the direct way to deploy Meshery by `yaml` , we should replace only one `port` below https://github.com/meshery/meshery/blob/67f1f917a20ab1ffb517df44f34bc1804ab75e7f/install/deployment_yamls/k8s/meshery-service.yaml#L14
