### ISSUE TITLE
[UI] Card margins on Management page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2576]
#### Current Behavior
Left and right margins on the sides of the cards on the /management pages are unequal.

#### Desired Behavior
These margins should be the same on both sides of the card.

#### Screenshot
<img width="640" alt="Screen Shot 2021-03-21 at 12 02 43 AM" src="https://user-images.githubusercontent.com/7570704/111894708-f3238800-89da-11eb-83c2-863e01a8f9fa.png">

**Comment by adithyaakrishna** [comment]
@leecalcote I would love to work on this :)

**Comment by leecalcote** [comment]
Excellent, @adithyaakrishna 👍

**Comment by TeezyOg** [comment]
Is there set dimensions for each box specifically within the code ? If yes couldn't you just set the boxes to the same size in accordance with the specific page to precisely position each box with the same dimensions ?

**Comment by leecalcote** [comment]
@TeezyOg, yes, you could, although in that case, the web app would not be responsive to different sized displays and browser widths.

**Comment by TeezyOg** [comment]
Understood ill give it some more thought.

**Comment by leecalcote** [comment]
@adithyaakrishna are you working on this? If not, please remove your assignment.

**Comment by adithyaakrishna** [comment]
@leecalcote I'm working on this, I had a tough time setting up the Local Dev Environment, Sorry for the delay but Once I get this up and running I will make a PR immediately :/

**Comment by adithyaakrishna** [comment]
Hey @leecalcote, so I was going through this, I found the issue 

**Problem:** 
![image](https://user-images.githubusercontent.com/23498248/112981013-3bc80780-9178-11eb-85e1-ae3d3d82527a.png)

**The padding of the cards are set to 8px, so as there are two cards next to each other, the total padding is 16px**

**Solution:** 
![image](https://user-images.githubusercontent.com/23498248/112981900-6d8d9e00-9179-11eb-97dc-35315eedb8b0.png)

**The padding of the overall box is set to 16px, by increasing it to 24px, we can fix this across all the pages**

**Comment by leecalcote** [comment]
Thanks. Does this maintain even spacing on the top and bottom of the cards when they are in rows?

**Comment by adithyaakrishna** [comment]
Yes, Across all pages

**Comment by leecalcote** [comment]
+ @dhruv0000

**Comment by TeezyOg** [comment]
Well done 👏
