### ISSUE TITLE
[UI] Management: Alignment of section titles

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2577]
#### Current Behavior
Section titles on the /management page are center-aligned.

#### Desired Behavior
Section titles on the /management page should be left-aligned.

#### Mockups
![Untitled copy](https://user-images.githubusercontent.com/7570704/111894761-73e28400-89db-11eb-9797-9ae161407cf5.png)

**Comment by sestissi16** [comment]
Is this still an issue that needs to be fixed? I would love to work on it!

**Comment by leecalcote** [comment]
@sestissi16 that'd be great. 👍

**Comment by TeezyOg** [comment]
I would love to see if I can help if you are still looking for people to contribute.

**Comment by leecalcote** [comment]
@TeezyOg wonderful. There are many more issues where this one comes from. 😄 I welcome and encourage you and @sestissi16 to join the Meshery Community (https://meshery.io/community) at http://meshery.slack.com. There are warm and welcoming contributors inside. 😉

**Comment by igallup** [comment]
Have room for another?  I was hoping to dip my toes in.

**Comment by leecalcote** [comment]
@igallup yes, indeed. This [Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit#) serves as a great resource. The community Slack is the center of gravity for engaging and getting started. Jump in: http://meshery.slack.com.

**Comment by AmjadNoor** [comment]
@leecalcote I think there is no progress in this issue can you assign me please.

**Comment by sestissi16** [comment]
> @leecalcote I think there is no progress in this issue can you assign me please.

Hi! I want to make progress but I'm having a hard time finding where the title for each section is actually being set. Do you know which component that's in?

**Comment by TeezyOg** [comment]
Do you guys use discord ?

**Comment by leecalcote** [comment]
@TeezyOg, Slack - https://github.com/meshery/meshery/issues/2577#issuecomment-804481136

**Comment by TeezyOg** [comment]
Okay...

**Comment by leecalcote** [comment]
@sestissi16 here you are - https://github.com/meshery/meshery/blob/9107f204739aabf5d5fe40fd54faf4c11350433f/ui/components/MesheryAdapterPlayComponent.js#L1096-L1104

**Comment by DineshKoushik** [comment]
Hi, I can see there are no pull requests created, so I assume that this issue still exists, can I help you guys in ay way?

**Comment by theprogrammedwords** [comment]
This issue can be closed I think as the PR is merged. Thanks.

**Comment by leecalcote** [comment]
@theprogrammedwords you're right! Thank you.
