### ISSUE TITLE
[mesheryctl] Add --yes/-y flag to system commands

### ISSUE THREAD

**Issue by metonymic-smokey** [layer5io/meshery#2582]
#### Current Behavior
Certain `mesheryctl system` commands require the user to manually enter yes/no as confirmation.

#### Desired Behavior
Addition of the `--yes`/`-y` flag, which the user can then use to avoid entering y/n later. If the flag is not entered, the user will have to enter y/n as usual.

**Comment by shoebsd31** [comment]
does it mean "yes for all" if --silent is added as an argument ?

**Comment by metonymic-smokey** [comment]
@shoebsd31 yes, it does mean that. There is only yes/no confirmation at present, which the `--silent` flag will address.

**Comment by kumarabd** [comment]
@metonymic-smokey Rather its the default values of every respective confirmation correct?

**Comment by piyushsingariya** [comment]
Hey @metonymic-smokey Can I raise a PR on this?

**Comment by metonymic-smokey** [comment]
Go ahead @piyushsingariya !

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey We have added this consideration to [this](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.xja8az6ed0dy) design spec. We may need to rethink how and what the flags are that are used here.
