### ISSUE TITLE
[Docs] Add instructions for golangci-lint

### ISSUE THREAD

**Issue by metonymic-smokey** [layer5io/meshery#2588]
**Current State:**
`CONTRIBUTING.md` does not specify requiring `golangci-lint` to be installed separately. It just mentions the `make golangci-run` command to be run.
MacOS and Linux users have to install the tool separately prior to running the command.

**Desired State:**
Add `golangci-lint` as a prerequisite for testing Go code, in the docs(`CONTRIBUTING.md`).

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thanks for getting this filed, @metonymic-smokey

**Comment by sakshi3537** [comment]
I would like to take up this issue.

**Comment by leecalcote** [comment]
Sounds great, @sakshi3537 👍

**Comment by piyushsingariya** [comment]
Hey @sakshi3537 any update over this?

**Comment by sakshi3537** [comment]
> Hey @sakshi3537 any update over this?

Actually I got busy somewhere and didn't do it yet, but I will complete it in 2-3 days.

**Comment by metonymic-smokey** [comment]
I think the PR for this was merged right @sakshi3537 ?
Next time, just mention the issue number according to the PR template, makes it easier to keep track :)

**Comment by sakshi3537** [comment]
@metonymic-smokey Yes it has been merged. and yeah I will keep it in mind for the next time.

**Comment by metonymic-smokey** [comment]
@leecalcote this issue can be closed.
