### ISSUE TITLE
[Docs] Footer: Update copyright year to 2021

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2589]
**Current State:**
The Meshery docs footer has 2020 copyright listed.

<img width="451" alt="Screen Shot 2021-03-24 at 8 32 27 AM" src="https://user-images.githubusercontent.com/7570704/112318856-7d8a1700-8c7b-11eb-91dd-9afecca2c71c.png">

**Desired State:**
Should be 2021.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by onwuvic** [comment]
@leecalcote can I pick this up?

**Comment by leecalcote** [comment]
@onwuvic, that would be excellent, yes.
