### ISSUE TITLE
[Performance] Profile card not showing details on backside

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2593]
#### Description
Blank backside of performance test card.

https://user-images.githubusercontent.com/7570704/112370249-2439dc00-8cab-11eb-8208-2c96d6e75cd0.mov

#### Expected Behavior
Should see test details.

#### Screenshots/Logs
- No errors in the browser console.
- Data is present in HTML, just not visible in browser.

<img width="1327" alt="Screen Shot 2021-03-24 at 2 02 02 PM" src="https://user-images.githubusercontent.com/7570704/112370167-0ff5df00-8cab-11eb-80d3-ebd98ebd30b0.png">

#### Environment:
- Meshery Version: v0.5.0
- Browser: Safari

**Comment by leecalcote** [comment]
@utkarsh-pro did you find the culprit here?

**Comment by leecalcote** [comment]
perhaps, something specific to my user or more likely specific to my .meshery/ local files.

**Comment by utkarsh-pro** [comment]
@leecalcote, that's strange even if that's the case. Lemme quickly ask a few folks on slack to see if someone else has also encountered the same issue?
