### ISSUE TITLE
Helm installation for individual adapters

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2600]
#### Implementation
If a user insists on running meshery inside the Kubernetes cluster using helm charts, currently all of the adapters get deployed by default. We would need a provision in the helm `values.yml` to specify the list of adapters to run before installing inside the cluster.

Ref: https://github.com/layer5io/meshery/tree/master/install/kubernetes/helm/meshery

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Aisuko** [comment]
Actually, we have the conditions under the `value.yaml` below. Those conditions can work well.

https://github.com/meshery/meshery/blob/3e366a9c5d38ece0bed770e386c8f37f64f7d8e7/install/kubernetes/helm/meshery/values.yaml#L100-L118

**Comment by leecalcote** [comment]
Nice. We're missing this in the doc on Helm installs. It'd be great to get a small set of instructions on this here - https://docs.meshery.io/installation/platforms/kubernetes#using-helm

**Comment by Aisuko** [comment]
Copy that. Add it to my schedule. I'd like to post the parameter sheet to the document, make any sense?  https://github.com/meshery/meshery/tree/3e366a9c5d38ece0bed770e386c8f37f64f7d8e7/install/kubernetes/helm/meshery#values
