### ISSUE TITLE
[mesheryctl] [child] Create `mesheryctl exp preflight` to verify environment readiness for a Meshery deloyment 

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2607]
Refer epic #1754 for more info.

Refer the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) for current status of `mesheryctl`.

#### Desired Behavior

`mesheryctl exp preflight` command should be added which verifies the presence of dependencies and overall environment readiness for a Meshery deployment.

```
➜  ~ mesheryctl exp preflight

Docker
--------------
√ Docker is running
√ docker-compose is available

Kubernetes API
--------------
√ can initialize the client
√ can query the Kubernetes API
√ has required level of privileges

Kubernetes Version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version
```

#### Acceptance Tests

- [ ] Users may or may not be installing to Docker, so failure of Docker being available should only be shown as a warning.
- [ ] Meshery requires "ClusterAdmin" role in order to be able to provide and manage service meshes. This check should verify that the Meshery ServiceAccount has the "ClusterAdmin" role assigned.

#### Future
`mesheryctl exp preflight` will be moved to `mesheryctl system preflight` and `mesheryctl system check --preflight`.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by navendu-pottekkat** [comment]
@piyushsingariya FYI

**Comment by piyushsingariya** [comment]
Hey @navendu-pottekkat can you drop some references to be sure about how to make this from scratch?
Also, I researched and couldn't found any solid way to check about the `docker` part, so if you have any clue about that too it would be helpful.

**Comment by navendu-pottekkat** [comment]
We kind of do the docker checks in the `preReqCheck` function in the `helpers.go` file... I guess this would only include that... We do not need to check anything else right @leecalcote ?

**Comment by piyushsingariya** [comment]
`preReqCheck` performs platform-based checks and uses several other functions I'm writing one inspired by this.

**Comment by leecalcote** [comment]
Gents, the milestone (version) for this issue is set for v0.9.0.  If we can complete this before that release, that would be great. We need to complete the other functions schedule in the milestones in v0.6, v0.7, v0.8 first though see the roadmap.md) in the root folder of this repo. 

This issue (and its parent issue) large in nature and will require a written design spec before it is scheduled for implementation. For now, I’m unassigning the issue, so that we can focus on v0.6.0 issues.

**Comment by piyushsingariya** [comment]
@navendu-pottekkat @kumarabd How exactly we can verify that the Meshery ServiceAccount has the "ClusterAdmin" role?

**Comment by kumarabd** [comment]
@piyushsingariya from the manifest I believe. @navendu-pottekkat  can you help me out with the location where mesheryctl fetches from?

**Comment by pottekkat** [comment]
The manifest files are fetched from here- https://github.com/meshery/meshery/tree/master/install/deployment_yamls/k8s

These are then stored locally in `.meshery/manifests` folder.

@kumarabd

**Comment by leecalcote** [comment]
Quick confirmation - does the compose.yaml live in the manifests folder, too?

**Comment by navendu-pottekkat** [comment]
Nope, it lies outside @leecalcote

**Comment by piyushsingariya** [comment]
@navendu-pottekkat if manifest files are the way to check the "ClusterAdmin" role, then do we actually need to verify that in preflight? I mean we're already stating that in our manifest files so it doesn't make sense to verify that through checking files :thinking:. plus where exactly we are assigning "ClusterAdmin" role in the files?

and what are the minimum versions for kubectl and k8s respectively?

**Comment by piyushsingariya** [comment]
@leecalcote @kumarabd 
> what are the minimum versions for kubectl and k8s respectively?

**Comment by piyushsingariya** [comment]
@navendu-pottekkat These are the permissions for the meshery serviceAccount.
```
-> kubectl auth can-i --list --as=system:serviceaccount:meshery:meshery
Resources                                       Non-Resource URLs   Resource Names   Verbs
selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
destinationrules.networking.istio.io            []                  []               [get list watch create update patch delete]
gateways.networking.istio.io                    []                  []               [get list watch create update patch delete]
serviceentries.networking.istio.io              []                  []               [get list watch create update patch delete]
virtualservices.networking.istio.io             []                  []               [get list watch create update patch delete]
                                                [/api/*]            []               [get]
                                                [/api]              []               [get]
                                                [/apis/*]           []               [get]
                                                [/apis]             []               [get]
                                                [/healthz]          []               [get]
                                                [/healthz]          []               [get]
                                                [/livez]            []               [get]
                                                [/livez]            []               [get]
                                                [/openapi/*]        []               [get]
                                                [/openapi]          []               [get]
                                                [/readyz]           []               [get]
                                                [/readyz]           []               [get]
                                                [/version/]         []               [get]
                                                [/version/]         []               [get]
                                                [/version]          []               [get]
                                                [/version]          []               [get]

```
any thought/approach on verifying (programmatically) the permissions?

**Comment by leecalcote** [comment]
@piyushsingariya alternatively or in addition to this, can you verify that the meshery service account is has the clusteradmin role?

**Comment by piyushsingariya** [comment]
```
NAME  ROLE         AGE
clusterrolebinding.rbac.authorization.k8s.io/meshery-crb    ClusterRole/meshery-cr   8d
```
I don't think we are assigning clusteradmin to meshery service account? or may be I'm mistaken. :thinking:

**Comment by piyushsingariya** [comment]
@leecalcote @kumarabd I just had a small doubt while working on figuring how to verify the `clusteradmin` role and that is,

if `preflight` is the check for verifying env details before meshery deployment then why are we having this check with pre-deployment? I mean this should be the part of the post-deployment checks.

**Comment by leecalcote** [comment]
Piyush, you're right. This check is a health check of an existing Meshery
deployment. I haven't been able to keep pace your work here, but will
acknowledge the that original issue's design may need reflection. A `system
check` with `--preflight` flag to confirm a lesser number or different
considerations is most likely necessary.

**Comment by piyushsingariya** [comment]
So for the `preflight` command, we don't need to include `cluster-admin` role check, and with that, I think I'm ready to raise a PR.

after that, I'll work on collecting all these things that I learned during this time in a design spec for the `system check`.
