### ISSUE TITLE
[mesheryctl] Bug: version/tag of the docker images in the manifest files not according to version specified in context

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2610]
#### Description

`mesheryctl` should fetch Kubernetes manifest files according to the `version` and `channel` of the `current-context` specified by the user in the `~/.meshery/config.yaml` file.

This is handled by the `FetchManifests` function-

https://github.com/layer5io/meshery/blob/3e366a9c5d38ece0bed770e386c8f37f64f7d8e7/mesheryctl/pkg/utils/platform.go#L101

Although we fetch the manifest files from the appropriate release in GitHub, the images specified in the manifest files are unaltered and the manifest files are applied to the cluster. 

https://github.com/layer5io/meshery/blob/3e366a9c5d38ece0bed770e386c8f37f64f7d8e7/install/deployment_yamls/k8s/meshery-istio-deployment.yaml#L25

As seen above the tag is `stable-latest` and it would not change even if the user specified a different `channel` and `version`.

#### Expected Behavior

The tag of the images should be re-written according to the `current-context` before the manifest files are applied to the cluster.

#### Implementation
Given the current implementation of "context support" throughout `mesheryctl`, and `version` and `channel` are pulled to fetch the specific manifests, these could be easily written to the manifest files using viper.

Similar implementation can be found for the `system start` command in `start.go` file.

**Comment by piyushsingariya** [comment]
Can i try?

**Comment by navendu-pottekkat** [comment]
Sure @piyushsingariya ! Assigning...

**Comment by piyushsingariya** [comment]
@navendu-pottekkat So we basically have to edit the manifest files, I get that part. but how exactly we do this? and I didn't found any implementation mentioned in `start.go`

**Comment by navendu-pottekkat** [comment]
Yes. Once we download the manifest files, we have to edit it. We can use viper for that. In `system start` i.e `start.go` , this is used to rewrite the `meshery.yaml` file in the case for Docker. Check from line 95 in start.go 

Let me know if this is still confusing...

**Comment by piyushsingariya** [comment]
I read the code but I'm not able to grasp how exactly I have to edit-out these manifest files? Because these manifest files and meshery.yaml are too different.

**Comment by piyushsingariya** [comment]
Okay @navendu-pottekkat, I think I'm getting hold of how to use viper and how to follow up the code in the case of docker. I just have one slight doubt, I have to implement this from very scratch, I mean building structs and proceeding ahead, right?

**Comment by piyushsingariya** [comment]
@navendu-pottekkat I highly doubt what I'm doing right now, So I'm dropping a sample code that I have added so have a look at it.
`start.go`
```
		// fetch the manifest files corresponding to the version specified
		manifests, err := utils.FetchManifests(version)

		if err != nil {
			return err
		}
               
// NEW CHANGES               
		for _, manifestFile := range manifests {
			utils.ViperCompose.SetConfigFile(manifestFile.Path)
			err = utils.ViperCompose.ReadInConfig()
			if err != nil {
				return err
			}

			compose := &utils.K8sCompose{}
			err = utils.ViperCompose.Unmarshal(&compose)
			if err != nil {
				return err
			}

			spliter := strings.Split(compose.Image, ":")
			compose.Image = fmt.Sprintf("%s:%s-%s", spliter[0], version, "latest")

			utils.ViperCompose.Set("spec.template.spec.containers", compose)
			err = utils.ViperCompose.WriteConfig()
			if err != nil {
				return err
			}

		}
```
and this is K8sCompose in `utils/compose.go`
```
type K8sCompose struct {
	Name      string   `yaml:"spec.template.spec.containers.name,omitempty"`
	Image     string   `yaml:"spec.template.spec.containers.image,omitempty"`
	Ports     []string `yaml:"spec.template.spec.containers.ports,omitempty"`
	Resources []string `yaml:"spec.template.spec.containers.resources,omitempty"`
}
```

**Comment by navendu-pottekkat** [comment]
@piyushsingariya Sorry for responding late. I was travelling.

Was this code working? The way you are implementing this looks correct. i.e you would have to create a struct and unmarshal the manifest files and use viper to modify the tag on the image.

**Comment by piyushsingariya** [comment]
Hi @navendu-pottekkat It was not working, and I figured out that the above sample code is :vomiting_face: 
and now I have figured out what's the actual way of doing this but I'm having a hard time writing those changes to YAML files

**Comment by navendu-pottekkat** [comment]
I guess writing those changes back would be similar to the docker implementation... We only have to change the tags right?

**Comment by piyushsingariya** [comment]
When I do that yaml files kind of complete changes plus I'm also having some trouble getting the image tag from yaml
It's not working the way it supposed to be working.

**Comment by navendu-pottekkat** [comment]
Most likely an issue with the created struct... We can discuss this

**Comment by piyushsingariya** [comment]
@navendu-pottekkat I'm finally able to change the yaml files as supposed but their are still few things needs to be corrected.
Check the comparison here [Link](https://www.textcompare.org/?id=606835b8e5cd4f0014e74aa4) and I'm stuck with this error now
```
: failed to apply manifests: Error Applying manifest.no matches for kind "Deployment" in version ""
```

**Comment by navendu-pottekkat** [comment]
@piyushsingariya I do see some other changes in the link you shared...

**Comment by piyushsingariya** [comment]
Yeah, I'm having trouble dealing with them, could you check the changes so that you could guess what's going wrong?
