### ISSUE TITLE
[mesheryctl] Bug:  `meshryctl perf` fails at attaching authorization details to request

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery#2617]
#### Current Behavior
`./mesheryctl perf --url https://foo.com` fails at attaching details to the request
![image](https://user-images.githubusercontent.com/50979887/113107951-1b548780-9222-11eb-820c-00849c3f585a.png)

**Comment by leecalcote** [comment]
@piyushsingariya thanks for raising this up. Based on our findings on today's call is the `issue/invalid` label appropriate on this issue?

**Comment by piyushsingariya** [comment]
Yeah! I should close this issue
