### ISSUE TITLE
Create Alpine version of Meshery docker image

### ISSUE THREAD

**Issue by s1ntaxe770r** [layer5io/meshery#2619]
#### Current Behavior

Currently Meshery has variants of it's docker [image  ]( https://hub.docker.com/r/layer5/meshery/tags)   (edge and stable )

#### Desired Behavior

Produce a docker image that uses alpine in the final build stage and integrate that with the CI workflow

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@kumarabd once the binaries for wrk2 and nighthawk are built using Ubuntu, can Alpine be used as the final image format?

**Comment by kumarabd** [comment]
Im afraid not. We have third party binaries embedded in our image thus we are constraint towards having it as a ubuntu base image. // @s1ntaxe770r

**Comment by leecalcote** [comment]
wrk2 runs on Alpine. Does this only leave nighthawk as the incompatible binary?

**Comment by leecalcote** [comment]
@s1ntaxe770r might join today's CNCF Service Mesh WG call. If so, creation of a Nighthawk build compatible with an Alpine image could be discussed. // @meshery/getnighthawk-maintainers @meshery/ci-release-contributors
