### ISSUE TITLE
[mesheryctl] `pattern list`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2623]
Refer the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) for current status of `mesheryctl`.

#### Current Behavior
Related to #2266 and #2621, `mesheryctl` v0.5.0 supports the following `exp pattern` command operations:

```
Available Commands:
  apply       Apply pattern file
  delete      Delete pattern file
```

Meshery release v0.6.0 will support `pattern` as a stable command with `list` being one of the subcommands.

#### Desired Behavior
The following commands should be supported as well:

```
  list       Display list of all available pattern files

Flags:
   -a, --all    Display full length user and pattern file identifiers. 
```

### Implementation
1. Use `http://<current-context-endpoint>/api/experimental/patternfile` to retrieve a list of available patterns.
1. Require use of token to auth to endpoint.
1. Provide legible list of patterns in tabular format with optional `-a`, `--all` to show all pattern file metadata (not pattern itself).
1. Show total count of available patterns.

#### Acceptance Tests
1. `pattern list` command should be return the names of all available pattern
2. `pattern list` will require `-t` or `--token` has a valid token file as a flag.
3. `pattern list` will display the list of patterns in a tabular format. See table mockup.
3.a. Timestamps will be converted from `2021-03-23T20:28:50.229379Z` format to `MM/DD/YYYY HH:HH:HH`
3.b. User IDs will be truncated after first 8 characters.
4. `pattern list -a` will display the list of patterns in a tabular format with no truncation of details. See table mockup.

### Mockups
`list` output:

```
NAME                                    USER ID             CREATED          UPDATED
canary-rollout.yaml            090e7114...       01-13-2021       01-15-2021
split-traffic-50-50.yaml    090e7114...       03-23-2021     03-25-2021

Total: 2
```

`list -a` output:
```
PATTERN ID                                                               NAME                                   USER ID                                                                    CREATED      UPDATED
2a634cfe-87d5-478e-9fda-168580ff83ba     canary-rollout.yaml            090e7114-509a-4046-81f1-9c5fb8daf724    01-13-2021 08:20:10      01-15-2021 08:20:10
2a634cfe-87d5-478e-9fda-168580ff83ba     split-traffic-50-50.yaml    090e7114-509a-4046-81f1-9c5fb8daf724      03-23-2021 20:28:50     03-25-2021 20:28:50

Total: 2
```
Includes pattern id, full length ids, and hour:min:sec

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by s1ntaxe770r** [comment]
Hi,  i would like to work on this

**Comment by piyushsingariya** [comment]
@s1ntaxe770r any update over here?

**Comment by s1ntaxe770r** [comment]
Yeah , I'm almost done just need to format dates and also waiting on #2671 to be merged in so i can use --token as a global flag
