### ISSUE TITLE
[mesheryctl] `pattern view`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2624]
Refer the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) for current status of `mesheryctl`.

#### Current Behavior
Related to #2266 and #2621, `mesheryctl` v0.5.0 supports the following `exp pattern` command operations:

```
Available Commands:
  apply       Apply pattern file
  delete      Delete pattern file
```

Meshery release v0.6.0 will support `pattern` as a stable command with `view` being one of the subcommands.

#### Desired Behavior
The following subcommands and flags should be supported as well:

```
  view       Displays the contents of a specific pattern file

Flags:
   -a, --all    Display the contents of all available pattern files
   -o json     Displays the contents of the pattern(s) in json format
```

### Implementation
1. Use `http://<current-context-endpoint>/api/experimental/patternfile` to retrieve a list of available patterns.
1. Require use of token to auth to endpoint.
1. Display the contents of the pattern(s) in yaml format with optional `-a`, `--all` flag to show all pattern file content.
1. Display the contents of the pattern(s) in json format with optional `-o json` flag.
1. Do not show total count of available patterns.

#### Acceptance Tests
1. `pattern view [pattern-name|pattern-id]` command should display the contents of the requested pattern. Patterns may be identified by name or by id.
2. `pattern view [pattern-name|pattern-id]` will require `-t` or `--token` has a valid token file as a flag.
3. `pattern view [pattern-name|pattern-id]` will display the contents of the pattern in yaml format by default. See mockup.
4. `pattern view [pattern-name|pattern-id]-o json` will display the contents of the pattern in yaml format by default. See mockup.
5. `pattern view -a` will display the contents of all available patterns in yaml format by default. See mockup.
6. `pattern view -a -o json` will display the contents of all available patterns in json format. See mockup.

### Mockups
`view -a` output:

```
patterns:
- id: 2a634cfe-87d5-478e-9fda-168580ff83ba
  name: canary-rollout.yaml
  user_id: '090e7114-509a-4046-81f1-9c5fb8daf724'
  pattern_file: "name: IstioSM\nservices:\n  istio:\n    type: Pod\n    namespace:
    istio-system\n    settings:\n      version: 1.8.2\n    traits:\n      mTLS:\n
    \       policy: mutual\n        namespaces:\n          - istio-test\n      automaticSidecarInjection:\n
    \       namespaces:\n          - default\n          - istio-test\n      meshmap:\n
    \       position:\n          posX: 98\n          posY: 54.8   \n          \n  istio2:\n
    \  type: Service\n   namespace: LinkerD-system\n   settings:\n     version: 1.8.2\n
    \  traits:\n     mTLS:\n       policy: mutual\n       namespaces:\n         -
    istio-test\n     automaticSidecarInjection:\n       namespaces:\n         - default\n
    \        - istio-test\n     meshmap:\n       position:\n         posX: 298\n         posY:
    54.8\n"
  created_at: '2021-03-23T20:28:50.229379Z'
  updated_at: '2021-03-23T20:28:50.229389Z'
- id: 3850572d-c7b5-4260-8c06-a45932a7b658
  name: pattern.yaml
  user_id: 6e955e6d-7a8f-4687-b0bb-17504aa8d520
  pattern_file: "name: IstioSM\nservices:\n  istio:\n    type: Pod\n    namespace:
    istio-system\n    settings:\n      version: 1.8.2\n    traits:\n      mTLS:\n
    \       policy: mutual\n        namespaces:\n          - istio-test\n      automaticSidecarInjection:\n
    \       namespaces:\n          - default\n          - istio-test\n      meshmap:\n
    \       position:\n          posX: 98\n          posY: 54.8   \n          \n  istio2:\n
    \  type: Service\n   namespace: LinkerD-system\n   settings:\n     version: 1.8.2\n
    \  traits:\n     mTLS:\n       policy: mutual\n       namespaces:\n         -
    istio-test\n     automaticSidecarInjection:\n       namespaces:\n         - default\n
    \        - istio-test\n     meshmap:\n       position:\n         posX: 298\n         posY:
    54.8"
  created_at: '2021-03-08T18:11:24.874038Z'
  updated_at: '2021-03-23T05:33:34.357108Z'
```

`view -a -o json` output:
```
  "patterns": [
    {
      "id": "2a634cfe-87d5-478e-9fda-168580ff83ba",
      "name": "canary-rollout.yaml",
      "user_id": "090e7114-509a-4046-81f1-9c5fb8daf724",
      "pattern_file": "name: IstioSM\nservices:\n  istio:\n    type: Pod\n    namespace: istio-system\n    settings:\n      version: 1.8.2\n    traits:\n      mTLS:\n        policy: mutual\n        namespaces:\n          - istio-test\n      automaticSidecarInjection:\n        namespaces:\n          - default\n          - istio-test\n      meshmap:\n        position:\n          posX: 98\n          posY: 54.8   \n          \n  istio2:\n   type: Service\n   namespace: LinkerD-system\n   settings:\n     version: 1.8.2\n   traits:\n     mTLS:\n       policy: mutual\n       namespaces:\n         - istio-test\n     automaticSidecarInjection:\n       namespaces:\n         - default\n         - istio-test\n     meshmap:\n       position:\n         posX: 298\n         posY: 54.8\n",
      "created_at": "2021-03-23T20:28:50.229379Z",
      "updated_at": "2021-03-23T20:28:50.229389Z"
    },
    {
      "id": "3850572d-c7b5-4260-8c06-a45932a7b658",
      "name": "pattern.yaml",
      "user_id": "6e955e6d-7a8f-4687-b0bb-17504aa8d520",
      "pattern_file": "name: IstioSM\nservices:\n  istio:\n    type: Pod\n    namespace: istio-system\n    settings:\n      version: 1.8.2\n    traits:\n      mTLS:\n        policy: mutual\n        namespaces:\n          - istio-test\n      automaticSidecarInjection:\n        namespaces:\n          - default\n          - istio-test\n      meshmap:\n        position:\n          posX: 98\n          posY: 54.8   \n          \n  istio2:\n   type: Service\n   namespace: LinkerD-system\n   settings:\n     version: 1.8.2\n   traits:\n     mTLS:\n       policy: mutual\n       namespaces:\n         - istio-test\n     automaticSidecarInjection:\n       namespaces:\n         - default\n         - istio-test\n     meshmap:\n       position:\n         posX: 298\n         posY: 54.8",
      "created_at": "2021-03-08T18:11:24.874038Z",
      "updated_at": "2021-03-23T05:33:34.357108Z"
    }
  ]
}
```

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by aneeshnema** [comment]
Currently, meshery has two API endpoints to fetch/search patterns:

1. `api/experimental/patternfile/{id}` can be used to fetch certain pattern based on the id provided.
2. `api/experimental/patternfile?search={name}` can be used to search patterns based on the name.

Since we want to allow the user to use both id or name to get a specific pattern, how do we differentiate what has the user provided, name or id? 
The API calls are different for different use case, and hence we cannot simply make our code indifferent. Either we can add a flag to signal that we want to use id or name explicitly, or if there's a way to distinguish, we can use that.

PS: I don't think there's a way to distinguish them.

**Comment by leecalcote** [comment]
Hmm. // @utkarsh-pro @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
`mesheryctl pattern view --name <name>` or `mesheryctl pattern view --id <id>` should work in the case where we cannot distinguish them.

**Comment by utkarsh-pro** [comment]
Why not adopt a convention that if given parameter is a valid uuid (not guid, we specifically use uuid v4 for the pattern ids) then mesheryctl will search for the patternfile using the first endpoint while in other cases it will use the second endpoint?

Checking if a string is a valid uuid v4 should be as simple as matching a regex // @aneeshnema @leecalcote @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
That seems like a neat solution.
