### ISSUE TITLE
.travis.yml no longer needed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#264]
**Description**
Now that the project has switched to GitHub Actions for CI, the [.travis.yml](https://github.com/layer5io/meshery/blob/master/.travis.yml) can be removed (deleted) from the project.

**Implementation**
1. Delete the .travis.yaml file from the root folder of the project.
1. Delete the .travis.yaml file from the mesheryctl folder - https://github.com/layer5io/meshery/blob/master/mesheryctl/.travis.yaml

**Comment by leecalcote** [comment]
Fixed by #266

**Comment by donnisnoni95** [comment]
Then close it

**Comment by leecalcote** [comment]
Good work here. We need to remove travis.yml from other Mesheryio repos as well.
