### ISSUE TITLE
[mesheryctl]  Meshery Operator and its custom resources not deleted on `system stop`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2656]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl system stop` on Kubernetes does not remove the Meshery Operator and its custom resources.

#### Desired Behavior
Meshery Operator should be removed from the cluster, if present.

#### Implementation
1. Before deleting the Meshery Server pod, invoke the Meshery Server endpoint that manages Meshery Operator in order to delete the Operator.
1. After successful removal of the Operator, proceed with deleting Meshery deployment.

#### Acceptance Tests
1. Operator and any of its CRs should be deleted.
2. Meshery Server and adapters should be deleted.
3. `meshery` namespace should be deleted. 

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by metonymic-smokey** [comment]
@leecalcote could I work on this issue?

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey Sure, go ahead
