### ISSUE TITLE
[Provider] Meshery remote provider not available in Provider UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2657]
#### Description
Meshery Remote Provider is missing in the dropdown list of supported providers.

#### Expected Behavior
"Meshery" should be a choice.

#### Screenshots/Logs
<img width="501" alt="Screen Shot 2021-04-02 at 4 48 06 PM" src="https://user-images.githubusercontent.com/7570704/113459592-9e6d0d80-93db-11eb-8b2c-ba53d930f93e.png">

#### Environment:
- Meshery Version: v0.5.0 and v0.5.1
- Platform: Docker and Kubernetes
- Browser: Chrome and Safari

**Comment by leecalcote** [comment]
@kumarabd @utkarsh-pro is this happening in your environments?

**Comment by utkarsh-pro** [comment]
@leecalcote we haven't deployed latest version of meshery cloud to production however we merged @kumarabd's PR which changed the capabilities endpoint to `/:meshery-version/capabilities`. Right now, there is no such endpoint as the latest meshery server is expecting so it fails to load the capabilities and hence nothing shows up in the UI.

**Comment by leecalcote** [comment]
oh, that makes sense. @kumarabd we have a mismatch here.

**Comment by leecalcote** [comment]
Fixed in new Meshery Cloud release.
