### ISSUE TITLE
[mesheryctl] HTTPS used as endpoint in newly created contexts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2658]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
https://localhost:9081/api/server/version is an invalid endpoint for most Meshery deployments. New `context`s created should default to `http`, not `https`.

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by metonymic-smokey** [comment]
@leecalcote is this an issue specific to v0.5.1?
I created a context using v0.5 and it defaulted to `http` not `https`.

**Comment by leecalcote** [comment]
Hmm. I’m pretty sure that I was seeing this in v0.5.0 and v0.5.1. I wonder if you will have different results if you specify Kubernetes as the platform.

**Comment by metonymic-smokey** [comment]
@leecalcote this issue doesn't exist in v0.5-beta. It's a new issue in v0.5.

**Comment by leecalcote** [comment]
@metonymic-smokey Thank you. That sounds about right.

**Comment by navendu-pottekkat** [comment]
We changed this didn't we? i.e we changed to `http`

**Comment by navendu-pottekkat** [comment]
Closing this as we have already fixed this in PR #2602
