### ISSUE TITLE
[UI] - Changing Favicon from Non-Transparent With White Background to Transparent

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/meshery#2661]
#### Description
The favicon for **Meshery** has a white background.

#### Expected Behavior
The favicon of meshery should have a transparent logo. 

#### Screenshots/Logs:

**Before:**
![image](https://user-images.githubusercontent.com/23498248/113045344-5cb24c00-91bc-11eb-9be5-3ebb2e9d5151.png)

**After:**
![image](https://user-images.githubusercontent.com/23498248/113472281-d332a080-947f-11eb-9c50-9d2a566456e2.png)

#### Environment:
- Meshery Version: v0.5.0
- Kubernetes Version: 
- Host OS: Windows 10 Home 64-Bit
- Browser: Chrome, Mozilla Firefox

**Comment by adithyaakrishna** [comment]
Hey @leecalcote ,
This is the issue regarding the Favicon and it has been fixed in PR #2615

**Comment by leecalcote** [comment]
Oh, I see. Ok, you’ve already fixed this. Got it. Excellent.
