### ISSUE TITLE
[CI] Label Bot: Design Required label

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2669]
#### Current Behavior
GitHub issues that receive the "issue/design required" label do not automatically receive helpful, additional context like a comment from a bot with a link to the process document, [Creating a Functional Specification](https://docs.google.com/document/d/1RP3IWLc-MiQS-QYasqCoVuCH7--G87p5ezE5f_nOzB8/edit?usp=sharing). Contributors are not likely to know where to find this document or how to proceed with creating a design specification.

See the comments in this example issue: https://github.com/layer5io/meshery/issues/2668

#### Desired Behavior
Ideally, a bot will fire up and comment a helpful comment that includes a link to the document.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by alphaX86** [comment]
Well, I have some Q here.... what type of bot it's using to label issues? The GitHub Actions or the probot one? And what kind of triggering do you expect to fire the bot up? 
These are the Q I need for now

**Comment by leecalcote** [comment]
Probot is being used. Application of the `issue/design required` label is the ideal trigger, if possible.

**Comment by alphaX86** [comment]
Alright, I'll look on it and try

**Comment by alphaX86** [comment]
Well I got one from GitHub Actions....
https://github.com/peaceiris/actions-label-commenter

Will this suffice?

**Comment by alphaX86** [comment]
Can I work this then? :)

**Comment by leecalcote** [comment]
@alphaX86 yes, looks good. 👍
