### ISSUE TITLE
Examine and consider implementing the CII best practices "passing" checklist

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#267]
See - https://github.com/coreinfrastructure/best-practices-badge#summary-of-best-practices-criteria-passing-level

**Comment by leecalcote** [comment]
Related to https://github.com/meshery/meshery/issues/43

**Comment by leecalcote** [comment]
The following badge needs propagated across of the the meshery repositories:

```
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/3564/badge)](https://bestpractices.coreinfrastructure.org/projects/3564)
```

**Comment by leecalcote** [comment]
Meshery and all of its repos have been submitted to the CII Best Practices program and are currently at a 98% pass rate for the Passing level badge - https://bestpractices.coreinfrastructure.org/en/projects/3564

**Comment by ashiscs** [comment]
This issue is already fixed and needs to be closed.
