### ISSUE TITLE
[meshery] `api/experimental/patternfile/{id}` throws Internal server error on invalid id 

### ISSUE THREAD

**Issue by aneeshnema** [layer5io/meshery#2678]
#### Description
`api/experimental/patternfile/{id}` throws Internal server error (500) on invalid id 
the response `failed to delete the pattern: record not found` is also wrong 

#### Expected Behavior
The API should give a 404 response and the body should have the following message
`failed to get the pattern: record not found`

**Comment by leecalcote** [comment]
A fine-looking write up. :)
