### ISSUE TITLE
[Provider UI] Eliminate extra mouse click in dropdown selection

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2682]
#### Current Behavior
Users get confused when they select a provider and their selection is seeming unaccepted. See the recorded demo.

#### Desired Behavior
This dropdown list in the Provider UI, should close with the selected item highlighted when the user chooses one.

#### Implementation
See the provider ui folder in the root of this repo.

#### Screencast

https://user-images.githubusercontent.com/7570704/114090247-cd243180-987c-11eb-8f8a-d1fc5825905a.mov

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Lezette** [comment]
I would like to work on this issue @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
sure @Lezette! Knock it off!

**Comment by Chadha93** [comment]
@Ruth-ikegah I would also like to take up this issue. But where can I find the "select your provider" field in the meshery live site?
because I am not able to find that particular field there.

**Comment by Nikhil-Ladha** [comment]
Ohh unfortunately 😛  , this issue is fixed in duplicated issue #2751. Hence, we can close the issue it seems.

**Comment by Nikhil-Ladha** [comment]
@leecalcote you can close when you check it.

**Comment by leecalcote** [comment]
Oh, I see. Ok, yes, closing out this duplicate issue.
