### ISSUE TITLE
[Docs] README: Add WebAssembly feature description

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2683]
**Current State:**
Meshery supports deployment of WebAssembly filters to Envoy-based data planes. The https://meshery.io site describes this feature:

<img width="1322" alt="Screen Shot 2021-04-08 at 3 37 54 PM" src="https://user-images.githubusercontent.com/7570704/114093180-6a349980-9880-11eb-8789-6c31a235f0a0.png">

**Desired State:**
This repo's [readme.md](https://github.com/layer5io/meshery#readme) should describe the feature in the same way.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Abiola-Farounbi** [comment]
Hi, I would like to be assigned this issue

**Comment by leecalcote** [comment]
Wonderful. 😀
