### ISSUE TITLE
[Docs] README: Update the SMP screenshot

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2684]
**Current State:**

The screenshot showing a performance graph to describe the SMP feature is out of date in the [Meshery README](https://github.com/layer5io/meshery#readme).

**Desired State:**

A [new, animated gif](![](https://meshery.io/images/screens/service%20mesh%20performance%20example.gif)
) shows off this feature in a better way. The readme should be updated to use this new gif.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by deepthiir** [comment]
Hey @leecalcote, Can I work on this?

**Comment by Anita-ihuman** [comment]
I will like to take up this issue

**Comment by leecalcote** [comment]
Excellent, @Anita-ihuman :)
