### ISSUE TITLE
[mesheryctl] logs: unable to see a Meshery container's logs on Kubernetes platform

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2698]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Unable to view logs for a Meshery container.

#### Screenshots/Logs
```
➜  ~ kubectl get pods -A
NAMESPACE      NAME                                     READY   STATUS    RESTARTS   AGE
istio-system   istio-egressgateway-96cf6b468-vv5bc      1/1     Running   0          9m41s
istio-system   istio-ingressgateway-57b94d999-f6kl4     1/1     Running   0          9m40s
istio-system   istiod-58c5fdd87b-mllzf                  1/1     Running   0          10m
kube-system    coredns-f9fd979d6-8h89q                  1/1     Running   3          2d2h
kube-system    coredns-f9fd979d6-lm2bm                  1/1     Running   3          2d2h
kube-system    etcd-docker-desktop                      1/1     Running   3          2d2h
kube-system    kube-apiserver-docker-desktop            1/1     Running   3          2d2h
kube-system    kube-controller-manager-docker-desktop   1/1     Running   3          2d2h
kube-system    kube-proxy-dq85p                         1/1     Running   3          2d2h
kube-system    kube-scheduler-docker-desktop            1/1     Running   3          2d2h
kube-system    storage-provisioner                      1/1     Running   5          2d2h
kube-system    vpnkit-controller                        1/1     Running   3          2d2h
meshery        meshery-74745fb8c9-6bkh2                 1/1     Running   0          14m
meshery        meshery-consul-6c77dcd486-684cp          1/1     Running   0          14m
meshery        meshery-cpx-5bc6f8dddf-c6zsv             1/1     Running   0          14m
meshery        meshery-istio-5977448cb8-qrl48           1/1     Running   0          14m
meshery        meshery-kuma-9c4f9879c-kb8b7             1/1     Running   0          14m
meshery        meshery-linkerd-f4c6db56d-vdhm2          1/1     Running   0          14m
meshery        meshery-nsm-6bb69cc498-52z5l             1/1     Running   0          14m
meshery        meshery-operator-549bf67565-4v4m5        2/2     Running   0          19m
meshery        meshery-osm-f4f7b47c6-hptk5              1/1     Running   0          14m
meshery        meshery-traefik-mesh-cd95d64b-npr8r      1/1     Running   0          14m
➜  ~ mesheryctl system logs meshery-cpx-5bc6f8dddf-c6zsv
Error: unknown command "meshery-cpx-5bc6f8dddf-c6zsv" for "mesheryctl system logs"
Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

- Meshery Version: v0.5.2
- PlatformL kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by piyushsingariya** [comment]
Currently, we do not support printing logs for a specific pod/deployment, logs are printed collectively.
and, I did suggest that in slack for an extension in the `system logs` in which logs could be printed for specific deployment but I guess everyone missed it :confused:

**Comment by piyushsingariya** [comment]
@navendu-pottekkat we can add a flag `-n` to grab the deployment name and if it is there we could print out logs specific to that deployment name. :thought_balloon:

**Comment by leecalcote** [comment]
@piyushsingariya,  interacting. What would the”n” stand for?

**Comment by piyushsingariya** [comment]
@leecalcote I was thinking `-n` as the "name" of the deployment we want to print the logs for.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya @leecalcote Why would we need a flag? Just mentioning the adapter name should work right?

**Comment by piyushsingariya** [comment]
@navendu-pottekkat How exactly? I'm not aware of it. could you enlighten me? :thinking: 
Can we grab args with cobra without flags?

**Comment by navendu-pottekkat** [comment]
Yes, we can. The logs subcommand could have a postional argument for the logs subcommand. See https://github.com/spf13/cobra#positional-and-custom-arguments

**Comment by Naimaoye** [comment]
can I have this please?

**Comment by navendu-pottekkat** [comment]
Sure @Naimaoye

**Comment by navendu-pottekkat** [comment]
@Naimaoye Progress on fixing this issue? Any blockers?
