### ISSUE TITLE
Create new Meshery project site at https://meshery.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#270]
**Enhancement Description**
Currently, https://layer5.io/meshery serves at the main project page. As a project Meshery has grown significantly - to the point that it needs its own project. The domain "meshery.io" has been reserved for this purpose.

**Good Example Sites:**

- https://dapr.io
- any of the CNCF Projects
   - https://www.cncf.io/projects/ (graduated / incubating)
   - https://www.cncf.io/sandbox-projects/ (sandbox)

**Comment by girishranganathan** [comment]
closing this because we have a site now
