### ISSUE TITLE
[mesheryctl] `system context list` to list all the contexts

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2708]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system context view` will show the config for the `current-context` and `mesheryctl system context view --context <context name>` will show the config for the context `<context name>`.

#### Desired Behavior

However, users cannot view all the available contexts from the CLI and would have to manually check the `~/.meshery/config.yaml`.

A new subcommand `mesheryctl system context list` that will list the `current-context` and all the available contexts.

```
❯ mesheryctl system context list

Current context: prod-east-1

Available contexts:

local
prod-east-1
dev
```

Users will then be able to use this context name to view the config of the context- `mesheryctl system context view --context dev`.

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by Kn99HN** [comment]
Hi,

Can I work on this?

**Comment by navendu-pottekkat** [comment]
@Kn99HN Sure, go ahead. I will assign it to you.
