### ISSUE TITLE
Install: Adapters Detect Existing Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#271]
**Description**
Whether a user is running Meshery in or out of a cluster, it does not require users to configure connections to its adapters. In the same fashion that Meshery is cognizant of its own adapters, establishes connection to them and verifies their status, so too, should Meshery use its adapters to detect the presence of a previously deployed service mesh. To facilitate time-to-value in using Meshery, adapters automatically detect existing service mesh deployments.

**Behavior**
- [ ] After v0.3.0, Meshery users can click on an adapter to verify connectivity between Meshery and the adapter. Users also need to ability to click on an adapter to detect the presence of an existing service mesh deployment (each adapter will look for its specific type of service mesh).
- [ ] Users should be able to invoke an ad-hoc detection operation using each or any adapter.

**Implementation and Related Challenges**
Each adapter will implement detection in a manner that is specific to its type of service mesh. Support for this functionality will be tracked under each individual adapter's repository.

- [ ]  Create a new operation in Meshery UI.
- [ ] Set Meshery to automatically run this operation upon registration of / connection to an adapter.

**Comment by girishranganathan** [comment]
This is related to #321, just realized it.

**Comment by leecalcote** [comment]
Duplicated by #781

**Comment by leecalcote** [comment]
Completed
