### ISSUE TITLE
[Docs] Main contributing docs missing link to mesheryctl contributing.md

### ISSUE THREAD

**Issue by Maxgit3** [layer5io/meshery#2716]
**Current State:**  In the github repo under the contributing mark down file there is no link to to the mesheryctl contributing markdown file.

**Desired State:**  A small section about contrtibuting to mesheryctl and a link to the mesheryctl contributing file

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Good one, @Maxgit3 👍

**Comment by leecalcote** [comment]
@Maxgit3, would you like to address this issue?

**Comment by Maxgit3** [comment]
@leecalcote sure I can work on this

**Comment by leecalcote** [comment]
Thank you, @Maxgit3

**Comment by adithyaakrishna** [comment]
@Maxgit3 Any progress here? 👀

**Comment by Chadha93** [comment]
@adithyaakrishna can I take up this issue, if yes, you can assign me

**Comment by adithyaakrishna** [comment]
@Chadha93 I guess, @Maxgit3 is working on this, let's wait for 2 days. If it's not done, then you can go ahead :)

**Comment by Maxgit3** [comment]
@adithyaakrishna sorry for the late reply.  I was going to work on it after figuring out the other issue.  if need be, you can assign it to another.

**Comment by adithyaakrishna** [comment]
@Chadha93 You can go ahead with this 🚀

**Comment by Chadha93** [comment]
@adithyaakrishna I have made the required changes you may kindly check and provide feedback.
