### ISSUE TITLE
[UI] Add comma to one thousandths place in performance test results number

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2717]
#### Current Behavior
On the http://localhost:9081/performance page, large performance test result numbers are missing commas (see screenshot).

#### Desired Behavior
A comma should be inserted into each thousandths place in the performance results number. This insertion can be done client-side in React.

#### Screenshot
<img width="712" alt="Screen Shot 2021-04-15 at 1 59 28 PM" src="https://user-images.githubusercontent.com/7570704/114924029-20edc800-9df3-11eb-9ab3-d4a4ef6eb32c.png">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by adithyaakrishna** [comment]
@leecalcote Can I work on this? 👀

**Comment by Kn99HN** [comment]
Hi, I can add this since it should be pretty quick

**Comment by leecalcote** [comment]
Very good!
