### ISSUE TITLE
[UI] Programs page is covered by footer

### ISSUE THREAD

**Issue by Kn99HN** [layer5io/meshery#2723]
#### Description
Programs page at `https://meshery.io/programs` is hidden by the footer

#### Expected Behavior
Subcribe form should be visible to user and not hidden

#### Screenshots/Logs

<img width="1440" alt="Screen Shot 2021-04-17 at 5 13 09 PM" src="https://user-images.githubusercontent.com/44149581/115126876-4f5cd600-9fa0-11eb-9cba-b01e41e20c99.png">

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS: MacOS
- Browser:  Firefox latest version

**Comment by Kn99HN** [comment]
Whoops, wrong repo

**Comment by chinmaym07** [comment]
Hey @Kn99HN  Good catch.. This is a valid issue ..
Please Open it here https://github.com/meshery/meshery.io
