### ISSUE TITLE
[Docs] Broken link on Nginx Service Mesh page

### ISSUE THREAD

**Issue by s1ntaxe770r** [layer5io/meshery#2726]
**Current State:**
The [link](https://docs.meshery.io/service-meshes/adapters/nginx-sm) to check progress on the Nginx Service Mesh adapter currently returns a 404. 

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/53065463/115236459-4d675400-a113-11eb-90d5-bd8443b9a134.png">

**Desired State:**
Add an appropriate link to the page.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
@s1ntaxe770r The Correct Link is, https://github.com/meshery/meshery-nginx-sm Right? 👀 
Also, Can you please assign this to me? 😶
