### ISSUE TITLE
[roadmap] Docs: Update mesheryctl section for v0.5.0

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2729]
#### Current Behavior
Meshery's roadmap for the `mesheryctl` v0.5.0 release is in need of retroactive updating.

#### Desired Behavior
The [roadmap.md](https://github.com/layer5io/meshery/blob/master/ROADMAP.md) should reflect the following for the mesheryctl section:

```
| v0.5.0 | Release channel subscriptions with system channel, Deployment management with system context |
```

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Aisuko** [comment]
Close due to #2734
