### ISSUE TITLE
Grafana Board retrieval timing out

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#273]
**Description**
After connecting to a Grafana endpoint, when clicking the Boards drop-down, no indicator is shown that the user's request is being executed and no boards are listed in the drop-down.

This operation takes a long time and appears to the user as if it is failing / timing out. 

**Expected Behavior**
1. User should see a waiting indicator.

**Screenshots**
<img width="864" alt="Screen Shot 2019-09-17 at 8 35 59 PM" src="https://user-images.githubusercontent.com/7570704/65096694-7948b380-d98b-11e9-85be-98fba3a720c3.png">

**Comment by ashiscs** [comment]
Sir,can you provide me the link of this code,so that i could update it?

**Comment by leecalcote** [comment]
@girishranganathan

**Comment by leecalcote** [comment]
@ashiscs I believe that the population of the MUISelect on this page starts here in React:

https://github.com/meshery/meshery/blob/75871e1f0ca25803ad3a7dad8526ef163e774b24/ui/components/GrafanaSelectionComponent.js#L49

and is handled by this javascript component:

https://github.com/meshery/meshery/blob/75871e1f0ca25803ad3a7dad8526ef163e774b24/ui/components/GrafanaComponent.js#L153

and is backed by this struct in go:

https://github.com/meshery/meshery/blob/a919ecb4a16e05c72f8e3e2f5c25b07e7badd3c0/models/grafana.go#L6

and is updated by this routine in go:

https://github.com/meshery/meshery/blob/a919ecb4a16e05c72f8e3e2f5c25b07e7badd3c0/helpers/grafana.go#L105

@girishranganathan, will you confirm?

**Comment by girishranganathan** [comment]
That looks right. A simpler strategy would be to first try increasing the timeouts for these calls.

**Comment by leecalcote** [comment]
@girishranganathan assuming this is the timeout setting for getting these boards - https://github.com/meshery/meshery/blob/75871e1f0ca25803ad3a7dad8526ef163e774b24/ui/components/GrafanaComponent.js#L85, what sort of timeout is appropriate? We'll need to show the user an indicator that the system is performing action. We may need to point @ashiscs in the direction of this activity indicator.

**Comment by girishranganathan** [comment]
Hey guys, the `setTimeout` is not the right spot for a potential fix.

One thing we can try out is to change the &http.Client{} here: https://github.com/meshery/meshery/blob/aa9f143f7b1099b8f450a30e4ae82b0b87bb3937/helpers/grafana.go#L44
to
```
&http.Client{
    Timeout: 25 * time.Second,
}
```
and see if this helps with the issue. 


If not, we will have to go the pagination route using the `page` and `limit` query params described here, which I think is a better long term solution: 
https://grafana.com/docs/http_api/folder_dashboard_search/

The reason we dint do this earlier is that the Grafana SDK does not support pagination for this exact call. I don't think it does today too.
https://github.com/grafana-tools/sdk/blob/5b510d41beaa58c3008de999ffc718ece67d763c/rest-dashboard.go#L125

So, we might have to do our own thing here.

**Comment by leecalcote** [comment]
Thanks, @ashiscs. #335 partially fixes. We're in need of adding a waiting indicator, so that the user knows an operation is being performed.

**Comment by leecalcote** [comment]
@raghavaggarwal99 this area continues to provide a poor user experience. You'll notice that when a user initially connects to a Grafana instance, the Boards dropdown will not populate until the user navigates away from that section (or page entirely, I can't remember) and returns back to click the Boards dropdown. Only then, are they shown a list of Grafana board names. Will you look at this?

**Comment by leecalcote** [comment]
@Nikhil-Ladha @shivaylamba, this is still an issue. I wonder if you might have a look. The current behavior is that users can enter the Grafana API endpoint, Meshery will connect, but it takes either refreshing the page or navigating away and coming back in order for the dropdown lists to populate.

**Comment by leecalcote** [comment]
An update on the description of this bug - [![loading Grafana board](https://youtu.be/HEKBIujHwGg/0.jpg))](https://youtu.be/HEKBIujHwGg "loading Grafana board")
