### ISSUE TITLE
[Docs] Roadmap: add `system config` refactoring 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2731]
**Current State:**
mesheryctl RoadMap is missing upcoming changes to `system config`.

**Desired State:**
The `mesheryctl` roadmap should list:
- `system config` refactor for minikube for v0.6.0.
- `system config` refactor for GKE for v0.6.0.
- `system config` refactor for EKS for v0.7.0.
- `system config` refactor for AKS for v0.7.0.
- `system config` refactor for docker-compose for v0.8.0.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@hexxdump I neglected to highlight the importance of minikube on the call. Are there any refactoring considerations that we should include for this platform? // @kumarabd @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
I don't think we need to refactor it. We do not have any dependencies for minikube.

**Comment by leecalcote** [comment]
Gotcha. That makes sense: no refactoring. This is an opportune time to consider how to streamline this, if possible, though. Can we detect that Minikube is present? Can we execute the flatten and minify command on their behalf? Can we avoid the need to make users go get a Meshery token in the UI and come back to the CLI (have that kubeconfig manipulation logic in mesheryctl, too)? Users seem to get hung up on the `system config minikube -t …` command.

**Comment by navendu-pottekkat** [comment]
Yes, that is something that we should consider... And also, they need to properly network the adapters running on docker with minikube which might take a while... If we can also, do this with what you mentioned it would be great. I'm not sure if this is feasible though. @hexxdump ideas?
