### ISSUE TITLE
[mesheryctl] Updating Meshery `endpoint` automatically in the `current-context`

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2737]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Meshery can be deployed into different Kubernetes platforms. However, the endpoints in which Meshery is accessible can be changed. This would result in the user having to manually configure their `config.yaml` to use the new endpoint.

![Screenshot from 2021-04-22 10-00-27](https://user-images.githubusercontent.com/49474499/115656043-16cb4c80-a352-11eb-8347-9ac458004619.png)

#### Desired Behavior

Running `mesheryctl system start` and `mesheryctl system status` should identify and show the endpoint at which Meshery is deployed. 

`mesheryctl` should then change the `endpoint` for the user's `current-context` to accommodate this change.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by piyushsingariya** [comment]
I would like to give this a shot!

**Comment by navendu-pottekkat** [comment]
Of course! @piyushsingariya

**Comment by piyushsingariya** [comment]
@navendu-pottekkat can you explain this, I'm a bit confused about this

> `mesheryctl` should then change the `endpoint` for the user's `current-context` to accommodate this change.

**Comment by navendu-pottekkat** [comment]
The Meshery config file has a field for endpoint which by default is localhost:9081. When Meshery discovers the actual endpoint, it should also change this field in the Meshery config.

**Comment by piyushsingariya** [comment]
btw @navendu-pottekkat @leecalcote  we should add some new labels like `platform/kubernetes` and `platform/docker` to distinguish the specificity of the issue regarding the platform.

**Comment by piyushsingariya** [comment]
In k8s case right?
> When Meshery discovers the actual endpoint, it should also change this field in the Meshery config.
I mean we forcefully deploying meshery on the endpoint mentioned in the context in docker's case
plus can you explain/point to what is the actual endpoint in the case mentioned in the above screenshot? (So that I don't make any mistakes)

**Comment by leecalcote** [comment]
@kumarabd Will you point out the utility in MeshKit that can be used here?

**Comment by kumarabd** [comment]
@piyushsingariya this should help you discover meshery Kubernetes endpoint - https://github.com/meshery/meshkit/blob/master/utils/kubernetes/service.go#L26

**Comment by piyushsingariya** [comment]
Thanks!! @kumarabd

**Comment by pottekkat** [comment]
@piyushsingariya Related- https://github.com/meshery/meshery/pull/2761

**Comment by piyushsingariya** [comment]
I guess this is already being covered by @metonymic-smokey in #2761. right @metonymic-smokey ??

**Comment by metonymic-smokey** [comment]
@piyushsingariya I'm updating the endpoint in current context for `system start`.  This issue asks for `system status` too, the implementation is quite similar I think. 
Do you want me to do `system status` too?

**Comment by piyushsingariya** [comment]
@metonymic-smokey yeah, it would be better to include this with your current PR.
