### ISSUE TITLE
[Docs]Change platform casing for Kubernetes

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2749]
Casing for the platform parameter needs to be changed

**Current State:**
https://docs.meshery.io/installation/platforms/kubernetes
Platform: Kubernetes

**Desired State:**
Platform: kubernetes

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
@kumarabd Can I fix this along with #2747 ?

**Comment by leecalcote** [comment]
Does this need to be address within `mesheryctl` as well? This template is embedded in the code.

**Comment by kumarabd** [comment]
> @kumarabd Can I fix this along with #2747 ?
> Just the Kubernetes has to be replaced with kubernetes right?

Yes sure that sounds good
