### ISSUE TITLE
[Mesheryctl] Print meshery endpoint after deployment

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2752]
#### Description
Meshery endpoint information needs to be printed in the output log, where meshery is available after deployment.

#### Implementation
Use meshkit service discovery in case of Kubernetes deployment.

commands:
mesheryctl system start

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by metonymic-smokey** [comment]
@kumarabd could I give this a shot?

**Comment by kumarabd** [comment]
> @kumarabd could I give this a shot?

SURE
