### ISSUE TITLE
[mesheryctl] `perf` should not require a running Docker process

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2763]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl perf` requires require Docker to be running.

**Example**

```
$ mesheryctl perf
Docker is not running.
Start Docker now [y/n]? 
```

#### Desired Behavior
`mesheryctl perf` should not require Docker to be running.

- Meshery Version: v0.5.2
- Platform: Docker

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by adithyaakrishna** [comment]
@leecalcote I was looking into this issue, so had to confirm these, when mesheryctl perf is run, it performs this function

![image](https://user-images.githubusercontent.com/23498248/116528784-d8a5ce00-a8f9-11eb-9ea0-5ef62d5587b6.png)

Can I create a new function for removing this check?
![image](https://user-images.githubusercontent.com/23498248/116531951-55867700-a8fd-11eb-8e4e-ba2c955114b1.png)

**Comment by leecalcote** [comment]
Great research, @adithyaakrishna. In this case, the check can just be removed.

**Comment by leecalcote** [comment]
I meant to tag Joy and Naimot on this issue when I opened it just in time for She Code Africa.

**Comment by adithyaakrishna** [comment]
No No, I completely understand. @Ruth-ikegah had pinged me about this. The above stuff can help them finish the work soon :)

**Comment by Naimaoye** [comment]
can this be assigned to us already?
