### ISSUE TITLE
[mesheryctl] Global help: change "performance testing" to "performance management"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2766]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
The default help text in `mesheryctl` uses the phrase "performance testing". 

#### Desired Behavior

The project has graduated from this and should use the phrase "Performance Management" instead.

#### Screenshots/Logs
```
➜  ~ mesheryctl
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Available Commands:
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  pattern     Meshery Patterns Management
  perf        Performance Testing
  system      Meshery Lifecycle Management
  version     Version of mesheryctl
```

#### Environment

- Meshery Version: v0.5.2

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by adithyaakrishna** [comment]
Anyone willing to work on this, here's a bit of info to get you started. The perf command is located in `perf.go` inside `mesheryctl\internal\cli\root\perf`

**Comment by Nikhil-Ladha** [comment]
Sure @fallmor . Please go ahead with this. And if at all you face any issue, please feel free to join our slack workspace [slack.meshery.io](slack.meshery.io) and get your questions settled.
