### ISSUE TITLE
Docs: Identify version of each supported service mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#278]
**Enhancement Description**
Meshery docs has a [table listing its adapters](https://meshery.layer5.io/docs/adapters) and the version of each service mesh that it supports. This table has a column for service mesh version. This version field needs to be filled in like so:

| Istio | v.1.0 and above |
| Consul | v1.5 |
| Linkerd | v2.3 and above |

...and the rest.

**Comment by gunjanmimo** [comment]
sir, please check, is it done or  i should change something else

**Comment by leecalcote** [comment]
@gunjanmimo the changes you made in the related PR we’re just what we were looking for. Good stuff. We’re good to close this issue. 

Fixed by #283.
