### ISSUE TITLE
mesheryctl should pull lastest docker-compose

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#280]
**Description**
```vars.go``` in mesheryctl hardcodes a specific version of `docker-compose` to retrieve and install. Here is the line:

```
dockerComposeBinaryURL = "https://github.com/docker/compose/releases/download/1.24.1/docker-compose"
\```

**Expected Behavior**
The latest version of docker-compose should be downloaded, not a specific version coded into `mesheryctl`.

**Comment by girishranganathan** [comment]
@anandrkskd, lets use Go http.Get to make the call to find the latest version of docker compose and use that in the rest of the flow

**Comment by leecalcote** [comment]
Implemented.
