### ISSUE TITLE
[mesheryctl] mesheryctl panics when validating the latest release tag

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/meshery#2800]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

While executing many commands, mesheryctl uses the GitHub API for fetching the latest release tag and alerts the user if a new update is available. Some adapters also use this.

The GitHub API has a rate limit of 5000 requests per hour and the user may cross this. When this happens, mesheryctl panics on running any of the commands which validate the release first.
**This panic leaves the user unable to use many important functions for at least an hour.**
```
$ ./mesheryctl system help
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/pkg/utils.GetLatestStableReleaseTag(0x0, 0x0, 0x0, 0x0)
        /home/rudraksh/meshery-0.5.3/mesheryctl/pkg/utils/platform.go:179 +0x436
github.com/layer5io/meshery/mesheryctl/internal/cli/root.glob..func2(0x37c8c20, 0xc000314440, 0x1, 0x1)
        /home/rudraksh/meshery-0.5.3/mesheryctl/internal/cli/root/root.go:71 +0x34
github.com/spf13/cobra.(*Command).execute(0x37c8c20, 0xc000314410, 0x1, 0x1, 0x37c8c20, 0xc000314410)
        /home/rudraksh/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:836 +0x231
github.com/spf13/cobra.(*Command).ExecuteC(0x37c61a0, 0x2afd340, 0x3a26a18, 0x0)
        /home/rudraksh/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rudraksh/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
        /home/rudraksh/meshery-0.5.3/mesheryctl/internal/cli/root/root.go:85 +0x55
main.main()
        /home/rudraksh/meshery-0.5.3/mesheryctl/cmd/mesheryctl/main.go:22 +0x25
``` 

#### Desired Behavior

Check the status code in the GitHub API response to see if the request is unauthorized. If it is, handle it accordingly. 

---

#### Screenshots/Logs

GitHub API response headers when being rate limited:
```
HTTP/2 403
date: Sat, 01 May 2021 19:14:09 GMT
server: Varnish
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-security-policy: default-src 'none'; style-src 'unsafe-inline'
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
content-type: application/json; charset=utf-8
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 60
x-ratelimit-remaining: 0
x-ratelimit-reset: 1619896471
x-ratelimit-used: 60
content-length: 280
x-github-request-id: 9962:0A3F:1DC52F:2D93EB:608DA881
```

#### Environment

- Host OS: Linux x86_64
- Meshery Version: 0.5.3 - 0.5.5
- Platform [docker/kubernetes/gke/eks etc]:

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by pottekkat** [comment]
Thanks for opening up this issue. Could you toss in a fix for this if it is possible?

@meshery/mesheryctl-contributors FYI if someone likes to take it up

**Comment by DelusionalOptimist** [comment]
Thanks @navendu-pottekkat, this should be a small fix, I'll send a PR for this 😀.

**Comment by leecalcote** [comment]
Yay, @DelusionalOptimist! 🎈
