### ISSUE TITLE
[mesheryctl] Automatically updating meshconfig file

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2801]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl` is unable to parse old `meshconfig`(`.meshery/config.yaml`) files-

```
➜  ~ mesheryctl system context create k8s
Error: error processing config: 2 error(s) decoding:
* 'contexts[bob].token' expected type 'string', got unconvertible type 'map[string]interface {}'
* 'contexts[local].token' expected type 'string', got unconvertible type 'map[string]interface {}'
Usage:
  mesheryctl system context create <context-name> [flags]
```

#### Desired Behavior

This is because the `meshconfig` file the user has will have been created by an older version of `mesheryctl` and the user may be using a new version of `mesheryctl` in which the structure of the `meshconfig` may have been changed.

A graceful error handling is needed here that will backup the current meshconfig file and ask user if they want to let `mesheryctl` create a new meshconfig file which is of the latest format.

This handling is necessary as the structure of meshconfig file may be changed frequently and otherwise the users will need to manually delete their meshconfig files and run the commands again. 

---

#### Implementation

1. Check for config parsing errors using `PreRunE`
    - basically catching any errors when trying parse the meshconfig file.
1. Inform user of error. Prompt user to current meshconfig backed up and new meshconfig generated.
1. Move current config.yaml to config.bak

#### Mockups

```
➜  ~ mesheryctl system context create k8s
Looks like you are using an outdated config file. Do you want to generate a new config file [y/n] ?
```

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by fallmor** [comment]
hello i'am searching a new issue to work on. can i take this ?

**Comment by leecalcote** [comment]
@fallmor, yes, sounds great.
