### ISSUE TITLE
Permission denied while running installation script

### ISSUE THREAD

**Issue by mertgor** [layer5io/meshery#2804]
#### Description

Install script fails and returns permission denied
#### Expected Behavior

I expect it to install meshery to system Ubuntu 20.04 LTS 
#### Screenshots/Logs

![Screenshot from 2021-05-02 17-49-21](https://user-images.githubusercontent.com/74842488/116817384-c2547800-ab6e-11eb-94b9-5f931788d2b3.png)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

**Comment by leecalcote** [comment]
The permission message seems to be a red herring. // @hexxdump

**Comment by leecalcote** [comment]
@ramrodo the lack of published mesheryctl binaries in the recent releases causes this installation script to fail.

**Comment by hexxdump** [comment]
> red herring



> The permission message seems to be a red herring. // @hexxdump

I could change the meshery script to check the file size before trying to unzip it.

**Comment by ramrodo** [comment]
> @ramrodo the lack of published mesheryctl binaries in the recent releases causes this installation script to fail.

Ok, I'm still working on that fix. I'll submit a new PR today.
