### ISSUE TITLE
[mesheryctl] (child) List all Performance Profiles

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2825]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

See epic [perf commands for performance tests](https://github.com/layer5io/meshery/issues/2823) and the [design spec](https://docs.google.com/document/d/1znOqTofsXkcPTF1AXVVSHGEZa5kue6G8vGHM4nsc2tc/edit#) for more details.

#### Desired Behavior

As a `mesheryctl` user, I would like to list all my available performance profiles, so that I can select a profile to run or examine from the existing list of available profiles.

#### Implementation
A new subcommand `mesheryctl perf list` to list all the available performance profiles.

#### Acceptance Test
`mesheryctl perf list` will list all the available performance profiles similar to the GUI

#### Mockup

List available performance profiles-

```
❯ mesheryctl perf list

NAME                      RESULTS             LAST-RUN
consul_1618684476858      1                   April 18, 2021 12:04 AM
Linkerd_1618603056064     2                   April 8, 2021 6:23 PM
Soak-test                 8                   March 23, 2021 8:48 PM
```

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by piyushsingariya** [comment]
@navendu-pottekkat How do I get the number of `results` and `Last-Run`?

**Comment by navendu-pottekkat** [comment]
These results are exposed by the Meshery server API endpoints. So you should be able to get it from there... See https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=0
