### ISSUE TITLE
[mesheryctl] (child) View Performance Profile’s Configuration

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2827]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

See epic [perf commands for performance tests](https://github.com/layer5io/meshery/issues/2823) and the [design spec](https://docs.google.com/document/d/1znOqTofsXkcPTF1AXVVSHGEZa5kue6G8vGHM4nsc2tc/edit#) for more details.

#### Desired Behavior
As a `mesheryctl` user, I would like to view the configuration of a performance profile , so that I can decide which profile to use to run the test.

#### Implementation
A new subcommand `mesheryctl perf view <profile name>` which will show the current configuration of the given performance profile.

An optional flag `-o json` will be also available to format the output in json.

#### Acceptance Tests
`mesheryctl perf view <profile name>` should show the configuration of the given profile.

`mesheryctl perf view <profile name> -o json` should output the configuration of a given profile in json format.

#### Mockup

View test configuration of a profile-

```
❯ mesheryctl perf view soak-test

Name- soak-test
Endpoints- https://10.0.0.1/foo
Load generators- fortio
Test run duration- 30s
```

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by fallmor** [comment]
hello i want to work on this. Can I give a try ?

**Comment by leecalcote** [comment]
Yes, that’d be great, @fallmor ✔️

**Comment by fallmor** [comment]
hello @navendu-pottekkat  @leecalcote , is there an api exposed to get meshery perf test profile or configuration ?

**Comment by leecalcote** [comment]
@fallmor here's a spreadsheet containing a list of them - https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399
