### ISSUE TITLE
[CI] Re-enable Edge Release Workflow

### ISSUE THREAD

**Issue by ramrodo** [layer5io/meshery#2831]
#### Current Behavior

Due to the merge of these PRs:
- https://github.com/layer5io/meshery/pull/2806
- https://github.com/layer5io/meshery/pull/2770

the Edge Release Workflow was removed temporarily.

#### Desired Behavior

Have Edge version/release with the latest commits merged in master

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by leecalcote** [comment]
Thank you, @ramrodo. I _think_ that we'll be in a better place after this refactoring. Or I'll say that we will be if we eliminate the redundant builds we were experiencing in the past "on push". 

On this subject, I don't think that we should be running CodeQL as frequently as we are. It takes a long time and, perhaps, can be run less frequently.

**Comment by ramrodo** [comment]
> Thank you, @ramrodo. I _think_ that we'll be in a better place after this refactoring. Or I'll say that we will be if we eliminate the redundant builds we were experiencing in the past "on push".
> 
> On this subject, I don't think that we should be running CodeQL as frequently as we are. It takes a long time and, perhaps, can be run less frequently.

Ok. I'll create another issue to modify that CodeQL workflow and submit a PR for that then.

**Comment by ramrodo** [comment]
This is the issue to accomplish that: https://github.com/meshery/meshery/issues/2833
