### ISSUE TITLE
[meshery] dropdown item of "select your provider" in meshery landing page ui exceeding beyond 

### ISSUE THREAD

**Issue by samirparhi-dev** [layer5io/meshery#2834]
#### Description

Dropdown item of "select your provider" in meshery landing page ui exceeding beyond
See screenshot
#### Expected Behavior

The item should be well within the drop down area
#### Screenshots/Logs

<img width="427" alt="Screenshot 2021-05-05 at 12 08 28 AM" src="https://user-images.githubusercontent.com/59992800/117056189-a51fd500-ad39-11eb-9e12-40843e359a96.png">

#### Environment:
- Meshery Version: latest
- Kubernetes Version: 1.18
- Host OS: MAC OS X
- Browser: Chrome

#### To Reproduce
1.  start the server 
2.  access http://localhost:9081/provider on Chrome
3. Click on the dropdown

#### Suggested fix
option 1: introduce a scroll bar in the dropdown menu
option 2: Remove the horizonatal line in the dropdown

**Comment by leecalcote** [comment]
Thank you, @samirparhi-dev 👍 

To the contributor that addresses this issue: Option 2 under the suggested fixes is ideal.

**Comment by samirparhi-dev** [comment]
@NeelParihar : Absolutely !

**Comment by leecalcote** [comment]
Heads-up - I believe that @chinmaym07 has recently fixed this issue.

**Comment by NeelParihar** [comment]
Oh that's great. Thank you for informing!
