### ISSUE TITLE
[MeshSync] MeshSync data not being persisted to database

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2835]
#### Description
Meshery Operator is deployed with controllers running, however, Meshery UI shows Meshery Operator as not connected.

#### Expected Behavior
Meshery Operator should show as connected. Adapter chip should successfully ping. MeshSync data should persist to Meshery Database.

#### Screenshots/Logs

```
meshery_1               | time="2021-05-05T03:05:29Z" level=info msg="Incoming object: eac074af.layer5.io, kind: ConfigMap" app=meshery
meshery_1               | time="2021-05-05T03:05:29Z" level=error msg="Error while writing meshsync data.no such table: resource_object_meta" app=meshery code=test_code probable-cause=None severity=1 short-description=None suggested-remediation=None
```

#### Environment:
- Meshery Version: edge-latest (nearest stable is v0.5.10+)

**Comment by kumarabd** [comment]
@leecalcote Unable to get this state in any of the setups. Any specific step/configuration to be noted here?

**Comment by leecalcote** [comment]
Yes, orphan your instance of the Meshery Operator from the server, then
deploy a new Meshery server.

**Comment by kumarabd** [comment]
https://github.com/meshery/meshery/pull/2852
