### ISSUE TITLE
[MesheryUI] Highlight Header Icons when they are active for better User Experience 

### ISSUE THREAD

**Issue by NeelParihar** [layer5io/meshery#2838]
#### Current Behavior
The dashboard icon doesn't give a indication if user is on dashboard page or not, and it is not intuitive that user can click on it to go to the dashboard page

#### Desired Behavior
The dashboard icon should be highlighted in light blue colour when the user is on dashboard page.

#### Implementation
Apply a custom colour class of lightblue to the icon when user is on dashboard

#### Acceptance Tests
Dashboard icon should be highlighted in light blue colour when the user is on dashboard page.
Dashboard icon should not be highlighted in light blue colour when the user is not on dashboard page.

#### Screenshots/References
<img width="1280" alt="Screenshot 2021-05-05 at 8 27 17 PM" src="https://user-images.githubusercontent.com/51474217/117166818-58450880-ade4-11eb-8c1d-07728de5eda0.png">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@NeelParihar great write up. Can you expand this behavior to all of the nav bar icons?

@austinogiza can you provide the HEX code for the light blue color?

**Comment by NeelParihar** [comment]
Thank you @leecalcote. I think you are asking about the header menu right in the same line as of dashboard icon. I will try to do it simultaneously. Should i create new issues for that or just edit this one?
