### ISSUE TITLE
[Docs] Link broken for helm on kubernetes setup page

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#2839]
#### Description

The link `Using helm` in the screenshot below doesn't navigate to the correct subsection on the page.

#### Expected Behavior

The link should work properly, and navigate the user to the appropriate section.
The correct link is https://docs.meshery.io/installation/platforms/kubernetes#using-helm-charts. Only, an update
to the `id` of the tag is needed i.e, from `using-helm-charts` to `using-helm`

#### Screenshots/Logs

![Screenshot from 2021-05-05 21-42-39](https://user-images.githubusercontent.com/29438875/117174187-14a1cd00-adeb-11eb-811a-d1baaa024deb.png)

#### Steps to reproduce the behavior:
1. Go to https://docs.meshery.io/installation/platforms/kubernetes
2. Click on `using helm`.
3. See the error.

**Comment by Vi1234sh12** [comment]
hey @Nikhil-Ladha  I want work On this Issue , Please let me know

**Comment by Nikhil-Ladha** [comment]
Sure @Vi1234sh12 👍🏼
