### ISSUE TITLE
[Docs] Broken link: mesheryctl command reference

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2859]
**Current State:**
The link the mesheryctl command reference at the bottom of this page is broken - https://docs.meshery.io/guides/mesheryctl/configuring-autocompletion-for-mesheryctl

**Desired State:**
Should point to `/reference/mesheryctl`

<img width="769" alt="Screen Shot 2021-05-06 at 9 28 36 PM" src="https://user-images.githubusercontent.com/7570704/117389627-3fa32400-aeb2-11eb-88e9-f2f87bb43c50.png">

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Vi1234sh12** [comment]
hey @leecalcote  I want to work on this issue, please let me know

**Comment by leecalcote** [comment]
Sounds real good.
