### ISSUE TITLE
Changing notification color for completed process

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#287]
Currently, when an adapter has completed the installation the notification color is more like an "info" rather than a success. It should be changed to success notification.

**Comment by leecalcote** [comment]
@Nikhil-Ladha you captured this well.

**Comment by girishranganathan** [comment]
I will take look at it and get back to you.

**Comment by leecalcote** [comment]
@Nikhil-Ladha, I think we're good to close this issue given your use of blue and rephrasing of some of the messages. We still do desire to use a custom color scheme and avoid the standard colors.

**Comment by Nikhil-Ladha** [comment]
Ok sir

**Comment by leecalcote** [comment]
Let's close this one and open a new one when we're ready for custom colors.
