### ISSUE TITLE
[MesheryUI] Add tooltip which displays information for the load generators in performance profile section

### ISSUE THREAD

**Issue by NeelParihar** [layer5io/meshery#2874]
#### Current Behavior
In performance profile section the load generator options don't have any kind of information for user to understand what different load generators are capable of.

#### Desired Behavior
When user hovers on a particular option it should display a tooltip such that it shows information regarding that particular load generator.

 #### Implementation

Add tooltips for all the options with requried information text. 

#### Acceptance Tests
When users hovers on particular option it should display a tool tip with required information.

#### Screenshot/Reference
<img width="1150" alt="Screenshot 2021-05-08 at 2 06 02 AM" src="https://user-images.githubusercontent.com/51474217/117505669-0c3fc280-afa2-11eb-95b9-75da82db6713.png">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Thank you, @NeelParihar 👍

**Comment by DantrazTrev** [comment]
Can I work on this?

I have got an idea of something like this
![Screenshot from 2021-06-03 00-34-28](https://user-images.githubusercontent.com/43457420/120538086-aceb9b80-c403-11eb-8821-00ae1e740b02.jpg)

Or alternatively a help icon at the end of each radio button?

**Comment by leecalcote** [comment]
@DantrazTrev a help icon is a great suggestion. Perhaps, we can avoid three icons and consolidate to one just after the "Load Generator" section label, shoving all three descriptions and a hyperlink to the [Performance Management](https://docs.meshery.io/functionality/performance-management) section of the docs into there.

**Comment by leecalcote** [comment]
@DantrazTrev the lower than 100% opacity you have used in the background of the tooltip in this mockup is nice.

@Ayush-Khandelwal-007 @adithyaakrishna, perhaps, it's time to consider a standard method of displaying help to the user. Yes, I think it is time. @DantrazTrev, it would be good to get a proposal going in the Meshery UI design file in Figma.

**Comment by Ayush-Khandelwal-007** [comment]
Great Idea @DantrazTrev , we could just have an info button at the top of this dialog box which on click could give another dialog box regarding all the required data for a new user to make it easy for them to understand what all different fields are for.

Just having tooltip for the radio buttons for all 3 options could also be possible but may hinder the smooth experience for a user who is thorough with it.

**Comment by DantrazTrev** [comment]
> Great Idea @DantrazTrev , we could just have an info button at the top of this dialog box which on click could give another dialog box regarding all the required data for a new user to make it easy for them to understand what all different fields are for.
> 
> Just having tooltip for the radio buttons for all 3 options could also be possible but may hinder the smooth experience for a user who is thorough with it.

@Ayush-Khandelwal-007 I think both having a tooltip for each input section with tooltip and the info of the top of card would work? Also, we'll need a title for the cards then too

**Comment by DantrazTrev** [comment]
> @DantrazTrev the lower than 100% opacity you have used in the background of the tooltip in this mockup is nice.
> 
> @Ayush-Khandelwal-007 @adithyaakrishna, perhaps, it's time to consider a standard method of displaying help to the user. Yes, I think it is time. @DantrazTrev, it would be good to get a proposal going in the Meshery UI design file in Figma.

What about the figma proposal?  Sorry I didn't quite get that.

**Comment by leecalcote** [comment]
@DantrazTrev I sent you an invitation to the Figma design file for the Meshery project, called "Meshery UI". Let's get a mockup going for the proposed design that you have made above. The mockup should include consideration for my first suggestion regarding a help icon next to "Load Generator"

**Comment by DantrazTrev** [comment]
> @DantrazTrev I sent you an invitation to the Figma design file for the Meshery project, called "Meshery UI". Let's get a mockup going for the proposed design that you have made above. The mockup should include consideration for my first suggestion regarding a help icon next to "Load Generator"
Oh, I got a bit confused. I made a Draft PR (got a bit confused with the workflow) will just do that

**Comment by leecalcote** [comment]
No sweat. Your PR is pretty close to the mark and, overall, is quite good. There are couple things that we can clarify in the mockup:

- no purple for visited hyperlinks.
- potentially larger area tooltip for longer descriptions like these.
- potentially standard "tips" / "notes" area for all UIs.

**Comment by DantrazTrev** [comment]
> No sweat. Your PR is pretty close to the mark and, overall, is quite good. There are couple things that we can clarify in the mockup:
> 
> * no purple for visited hyperlinks.
> * potentially larger area tooltip for longer descriptions like these.
> * potentially standard "tips" / "notes" area for all UIs.

Sure I'll just work on that in a while. Just had a query about the figma mockup for the performance profile. Is that where we are headed towards and I need to add the tooltip mockup or does that need to be updated (cause it is quite different )
