### ISSUE TITLE
A litte issue in the Meshery docs

### ISSUE THREAD

**Issue by Jassi10000** [layer5io/meshery#2879]
#### Description

https://docs.meshery.io/reference/error-codes#meshery-adapter-library-library 
There are some headings in the docs  where the first letter of  <code>Linkerd</code> is not capitalised

#### Expected Behavior

![image](https://user-images.githubusercontent.com/64856348/117544406-ea484d80-b03e-11eb-942f-5009f5407a23.png)

![image](https://user-images.githubusercontent.com/64856348/117544474-398e7e00-b03f-11eb-9fb1-5b4e00dd1040.png)

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/64856348/117544329-93db0f00-b03e-11eb-80dd-b2d943485803.png)

![image](https://user-images.githubusercontent.com/64856348/117544358-b8cf8200-b03e-11eb-933b-77d44060066d.png)

#### Environment:
- Meshery Version: v0.5.0 
- Kubernetes Version: 
- Host OS: Windows
- Browser:  Chrome

 
#### To Reproduce
1. Go to 'https://docs.meshery.io/reference/error-codes#meshery-adapter-library-library '
2. Click on 'https://docs.meshery.io/reference/error-codes#meshery-adapter-for-linkerd'

**Comment by Jassi10000** [comment]
@leecalcote Can you please assign this to me

**Comment by Jassi10000** [comment]
@navendu-pottekkat  @leecalcote 

![image](https://user-images.githubusercontent.com/64856348/117565483-2cb96b00-b0cf-11eb-9e30-bbe1044aacb3.png)

Before I even changed the code , I saw this in the code 
Is this approach correct ? 

coz this CSS  property makes first letter of every word capital  , but here it's not working for all words

**Comment by leecalcote** [comment]
This is a prior attempt at solving the issue. It might be useful to iterate on this approach. CSS is one way to achieve the desired result.

**Comment by Jassi10000** [comment]
Actually I guess , due to issues faced in setting up my environment 
Give me some time , will be up with this

**Comment by Nikhil-Ladha** [comment]
The issue seems to be fixed now. Hence, closing this issue.
