### ISSUE TITLE
[Docs] GraphQL playground listed in docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2881]
**Current State:**
This statement is in the current API docs - https://docs.meshery.io/extensibility/api#graphql

<img width="741" alt="Screen Shot 2021-05-08 at 1 18 31 PM" src="https://user-images.githubusercontent.com/7570704/117549436-f8c34480-afff-11eb-997f-dd6c60ce6292.png">

**Desired State:**
If this playground only available in the Meshery Remote Provider, this statement needs to be removed.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by dhruv0000** [comment]
@leecalcote Meshery Playground is available for all the providers.
