### ISSUE TITLE
Add Octarine adapter to list of Meshery adapters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#289]
*Description*
Meshery's adapter for Octarine is in an alpha state - https://github.com/layer5io/meshery-octarine - and needs represented in the Meshery docs.

*Implemenation*
1. create a new adapter page
1. add to list here - https://meshery.layer5.io/docs/adapters

**Comment by ashiscs** [comment]
Resolved #289

**Comment by firstladymb** [comment]
Is there anything left to do for this? Looks completed!

**Comment by leecalcote** [comment]
@firstladymb you're right. Good call. This issue needs to be closed.
