### ISSUE TITLE
[UI] Overlapping chip with namespace input filed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2896]
#### Description

<img width="695" alt="Screen Shot 2021-05-11 at 9 08 03 AM" src="https://user-images.githubusercontent.com/7570704/117830037-e41dc100-b238-11eb-9760-c53f2c72746c.png">

#### Expected Behavior
Margins between cards should be consistent. Breakpoint should be reexamined. Font size should not change for just one component, but for all (if at all).

**Comment by srisatya1197** [comment]
@leecalcote Sir can I know more about expected behavior.

**Comment by Jassi10000** [comment]
Ya , would like to do some hands dirty on this issue

**Comment by srisatya1197** [comment]
@leecalcote @Jassi10000 completely fine.

**Comment by adithyaakrishna** [comment]
Hey @Jassi10000 
Any update on this?

**Comment by Jassi10000** [comment]
Hey buddy , I was not well some days back and even my development environment is not set properly , 
so was able to work on this , it would be nice that at present  any other member can solve this 
After I recover , I will resume back with work on future issues

**Comment by adithyaakrishna** [comment]
@srisatya1197 Would you like to work on this?

**Comment by srisatya1197** [comment]
@adithyaakrishna I presume it's assigned will try the other one.

**Comment by adithyaakrishna** [comment]
@srisatya1197 Okay sure 🚀
