### ISSUE TITLE
[Docs] Roadmap items missing bullet points

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2903]
**Current State:**
A couple of [roadmap](https://github.com/layer5io/meshery/blob/master/ROADMAP.md) entries are missing bullet points, but should have them.

**Screenshot**
<img width="567" alt="Screen Shot 2021-05-12 at 11 05 17 AM" src="https://user-images.githubusercontent.com/7570704/118007690-fb7cad00-b311-11eb-8335-cced041d9cca.png">

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by amino19** [comment]
Hey, I think, this issue has resolved..

**Comment by leecalcote** [comment]
@amino19 Thank you. You’re right.
