### ISSUE TITLE
[CI] Create Release Notes PR Workflow failing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2907]
#### Current Behavior
The [automated release notes workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-notes.yml) is failing at what seems to be [this step](https://github.com/layer5io/meshery/runs/2570815225?check_suite_focus=true#step:3:480).

Release notes from v0.5.2 and prior have been published, but v0.5.3 to 0.5.12 are missing.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by vineethvanga18** [comment]
@leecalcote I think this issue is fixed

**Comment by adithyaakrishna** [comment]
Thanks for this @vineethvanga18
