### ISSUE TITLE
[Docs] Overview: Broken markdown tables in overview page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2908]
**Current State:**
[Overview page](https://docs.meshery.io/overview) has broken markdown tables.

**Screenshot:**
<img width="1102" alt="Screen Shot 2021-05-12 at 9 34 23 PM" src="https://user-images.githubusercontent.com/7570704/118069471-e29fe600-b369-11eb-957d-e73928e93a5e.png">

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
This is a strange thing, VSCode shows it proper 👀 
![image](https://user-images.githubusercontent.com/23498248/118188214-ad74c000-b45d-11eb-9690-280d4a803a37.png)

**Comment by amino19** [comment]
Yes actually, it's shows table is properly configured, how this issue arrised! 🤔 
Can I take the charge & lookout over docs. If I can do something?

**Comment by amino19** [comment]
![table-fixed](https://user-images.githubusercontent.com/75872316/118396521-855bab80-b66d-11eb-9556-03c9bc8240d6.JPG)

@leecalcote Sir, it's fixed now & able to merge..
Pl verify! 😃
