### ISSUE TITLE
[mesheryctl] Kubernetes: `system stop` shows invalid endpoint

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2918]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Scenario: Meshery is stopped. Current-context is Kubernetes.

`system status` is showing an invalid endpoint to Meshery endpoint.

```
➜  ~ mesheryctl system status
NAME	READY	UP-TO-DATE	AVAILABLE	AGE
Meshery endpoint is http://localhost:9081
```

#### Desired Behavior

Keep the behavior the same between Docker and Kubernetes platform. Present the user with the same message:

```
Meshery is not running. Run `mesheryctl system start` to start Meshery.
```

- Host OS: macOS
- Meshery Version: v0.5.12
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by pottekkat** [comment]
@leecalcote This is not an issue with the endpoint. This is because of a bug in the preRunChecks. I was about to open an issue. We can close that now.

The endpoint issue is being addressed in this issue https://github.com/meshery/meshery/issues/2910

**Comment by pottekkat** [comment]
Opened issue- https://github.com/meshery/meshery/issues/2920
Fixing it
