### ISSUE TITLE
[mesheryctl] Grammar: Run-on sentence in `system stop` for Docker platform

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2919]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Scenario: Meshery is stopped. Current-context is Kubernetes.

```
➜  ~ mesheryctl system status
Meshery is not running, run `mesheryctl system start` to start Meshery
```

#### Desired Behavior

```
➜  ~ mesheryctl system status
Meshery is not running. Run `mesheryctl system start` to start Meshery.
```

Add two periods and capitalize "R"un.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by navendu-pottekkat** [comment]
@leecalcote currently, `mesheryctl system status` for Kubernetes platform does not show this error.

The platform must be docker. Will add the check in Kubernetes, as well as change the logs.
