### ISSUE TITLE
[Meshery UI] - The Meshery Provider UI Needs Some Changes - Button, Headings, Modal

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/meshery#2925]
#### Current Behavior
- There are two buttons, which should be made as a single one.

![image](https://user-images.githubusercontent.com/23498248/118175644-03da0280-b44e-11eb-9574-e254060cb4a4.png)

-  The Dividers needs to have it's color changed and add margins at the end along with Disabled text above it (Marked in Red Below)

![image](https://user-images.githubusercontent.com/23498248/118175824-3ab01880-b44e-11eb-8b89-7df47c235c76.png)

- The modal, shown in below image, the Provider text should be made bold, also the OK button needs to have a container (shown in blue)
![image](https://user-images.githubusercontent.com/23498248/118176226-c5911300-b44e-11eb-9e09-bd1dca26cbc4.png)

#### Desired Behavior
 - All of the above concerns to be addressed :)
 
#### Implementation
- All of the respective components are here, https://github.com/layer5io/meshery/blob/master/provider-ui/components/ProviderComponent.js

**Comment by adithyaakrishna** [comment]
@leecalcote I guess these are all the tasks or concerns to be addressed right? Do let me know if there are any changes or other stuff to be added

**Comment by leecalcote** [comment]
Perfect
