### ISSUE TITLE
[Docs] `mesheryctl system update` page missing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2936]
#### Current State
No page exists for this command in the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl).

#### Desired State
A docs page for this subcommand should be available.

#### Implementation
1. Create an entry for this subcommand in https://github.com/layer5io/meshery/tree/master/docs/_data/mesheryctlcommands/

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Blakelist7** [comment]
Hey! @leecalcote I want to work on this. Could you assign this to me?

**Comment by leecalcote** [comment]
Sounds great, @Blakelist7 👍

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha I guess we can close this issue as PR #2974 fixes this

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I guess we can close this issue as PR #2974 fixes this

Yes. Thank you @Blakelist7 .
