### ISSUE TITLE
[Docs] `mesheryctl system status` page missing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2938]
#### Current State
No page exists for this command in the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl).

#### Desired State
A docs page for this subcommand should be available.

#### Implementation
1. Create an entry for this subcommand in https://github.com/layer5io/meshery/tree/master/docs/_data/mesheryctlcommands/

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by umairnsr87** [comment]
I would love to take this issue..

**Comment by Ruth-ikegah** [comment]
sure @umairnsr87!

**Comment by leecalcote** [comment]
@umairnsr87 progress?

**Comment by umairnsr87** [comment]
Working on it....
