### ISSUE TITLE
[Docs] `mesheryctl system config` page missing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2940]
#### Current State
No page exists for this command in the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl).

#### Desired State
A docs page for this subcommand should be available.

#### Implementation
1. Create an entry for this subcommand in https://github.com/layer5io/meshery/tree/master/docs/_data/mesheryctlcommands/

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
@Blakelist7 Would you like to work on this? 👀

**Comment by Blakelist7** [comment]
Sure.
