### ISSUE TITLE
[Docs] `mesheryctl system restart` page missing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2943]
#### Current State
No page exists for this command in the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl).

#### Desired State
A docs page for this subcommand should be available.

#### Implementation
1. Create an entry for this subcommand in https://github.com/layer5io/meshery/tree/master/docs/_data/mesheryctlcommands/

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
@Anita-ihuman Can you please create a PR for this again?

**Comment by adithyaakrishna** [comment]
@leecalcote @navendu-pottekkat The PR linked to this Issue was Reverted in PR #3064

**Comment by Anita-ihuman** [comment]
I am perplexed. Am I meant to make a separate Pr for each issue, or there was something I missed?

**Comment by navendu-pottekkat** [comment]
I accidentally merged this PR before it was ready... And then we reverted those changes... Totally my bad.

You can work on the same branch as before or create a new branch with that branch and make a PR...
