### ISSUE TITLE
[mesheryctl] Add `-t` convenience flag as an alternative to `perf --token`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2948]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Users have to type the full name the `--token` flag as a mandatory parameter to `mesheryctl perf`.

#### Desired Behavior
Allow users to use `-t` as convenient shorthand for this flag.

#### Acceptance Tests
1. A token is still required. Users can use either -t or --token to supply a token.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by rajibmitra** [comment]
@leecalcote  hi Lee, I would like to work on this.

**Comment by leecalcote** [comment]
@rajibmitra excellent. 🙂
