### ISSUE TITLE
[mesheryctl] Add confirmation when channel is set

### ISSUE THREAD

**Issue by metonymic-smokey** [layer5io/meshery#2952]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
When running `meheryerctl channel set`, there is no user confirmation indicating the channel set.  

#### Desired Behavior
A confirmation message along the lines of `Set channel <edge/stable/edge-version/stable-version>` should be shown.

#### Screenshots/Logs
Current state:
![image](https://user-images.githubusercontent.com/48997495/118388272-149e9a00-b641-11eb-9a06-ae844fad712a.png)

#### Implementation
Use `log.Info` in  `setCmd` in`internal/cli/root/system/channel.go` to display the message.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by DARK-art108** [comment]
Can I work upon this fix?

**Comment by leecalcote** [comment]
Line 133 is all yours, @DARK-art108 👍

**Comment by DARK-art108** [comment]
yes thanks @leecalcote I am working upon it :)
