### ISSUE TITLE
[mesheryctl] `system update` does not update operator manifests for Docker platform

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2958]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system update` for Docker platform will only update the running containers and not the Meshery operator pods deployed on the Kubernetes cluster.

#### Desired Behavior

`mesheryctl system update` should also update the meshery-operator similar to how this command function for the Kubernetes platform.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
Sure @metonymic-smokey Sounds good!

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat in `update.go`, will the `skip-reset` flag apply the same way for docker as for kubernetes i.e. only restarting pods and not fetching manifests when the flag is used?

**Comment by navendu-pottekkat** [comment]
It should behave similarly @metonymic-smokey
