### ISSUE TITLE
[mesheryctl] `system context delete` does not handle deleting the `current-context` 

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2959]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system context delete <current-context name>` will delete the `current-context` leaving the `current-context` empty.

This will result in other commands failing.

#### Desired Behavior

Instead, `mesheryctl` could automatically set another context as the `current-context` or let the user decide which context to set from an interactive list.

This should also prevent the user from deleting the context if that is the only remaining context.

Please discuss the specifics on how this should be implemented below.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
This is the sequence of steps for such a case:
1. If user tries to delete current context, ask for confirmation(are they sure they want to delete it)?  
2.  If the user says no, abort the delete with a simple message.    
3. If the user says yes, display a list of contexts and ask them to pick one by typing the name.  
4. Continue asking till the user gives a valid context name. 
5. Delete the current context.    
6. Set the context given by the user as the current context.  

What do you think?  
@navendu-pottekkat @leecalcote

**Comment by navendu-pottekkat** [comment]
Can this be made interactive? We have to start somewhere with the interactivity and this might be a good place to try it out.

// @leecalcote

**Comment by metonymic-smokey** [comment]
https://github.com/manifoldco/promptui - This is a good library for the interactive select.  
It looks pretty straightforward to use in case we make context selection interactive.

**Comment by navendu-pottekkat** [comment]
Yes, that is a good package that we can use.

**Comment by leecalcote** [comment]
Does it facilitate the programmatic interaction and selection at the same time?

**Comment by leecalcote** [comment]
Are you suggesting this library, because it is the same one that we have used in the past or did you come upon this library independent that?

**Comment by navendu-pottekkat** [comment]
@leecalcote We can let the user skip the prompt through args and flags. This could be done by wrapping this package. This doable.

**Comment by leecalcote** [comment]
Alrighty.
