### ISSUE TITLE
[mesheryctl] Broken link (guides/mesheryctl/life-cycle-management) present at error logs of CTL Client

### ISSUE THREAD

**Issue by alphaX86** [layer5io/meshery#2969]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Whenever Meshery fails a given task, (eg., starting meshery etc) it shows up a link like "refer this link https://docs.meshery.io/guides/mesheryctl/#life-cycle-management" The link is actually broken and returns 404 error

#### Desired Behavior

The link must be replaced or the page must be brought up and fixed

- Host OS: Windows 10 ver 20H2, Ubuntu 20.04
- Meshery Version: stable (both from master and release)
- Platform: Docker

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
The last “/“ can be removed.

**Comment by alphaX86** [comment]
It's removed

**Comment by leecalcote** [comment]
@alphaX86, rather, I mean that a fix here can be to use this url: https://docs.meshery.io/guides/mesheryctl#life-cycle-management.

**Comment by alphaX86** [comment]
> @alphaX86, rather, I mean that a fix here can be to use this url: https://docs.meshery.io/guides/mesheryctl#life-cycle-management.

Hmm alright then
