### ISSUE TITLE
[Meshery] Namespace drop box to be responsive

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#2979]
#### Description
The Namespace dropdown currently lists all of the available namespaces in the cluster. When you have to add a new namespace, you will need to click on the `X` mark on the right and then type in values.

#### Expected Behaviour
The user should be enabled to type in the field when he clicks on it, instead of wanting to cross the `X` mark to type in (Current behaviour).

#### Screenshots/Logs
<img width="1769" alt="Screenshot 2021-05-19 at 11 23 28 AM" src="https://user-images.githubusercontent.com/10404724/118762927-a6eaac00-b894-11eb-903d-294c0ff3f81c.png">

#### Environment:
- Meshery Version: any
- Kubernetes Version: any
- Host OS: Any
- Browser: Chrome

**Comment by Ayush-Khandelwal-007** [comment]
I would like to work on this.

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007 sounds great. 👍

**Comment by leecalcote** [comment]
// @houshym FYI
