### ISSUE TITLE
[Docs] Releases: unhandled trailing forward slash in Jekyll configuration

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2991]
#### Current State

https://docs.meshery.io/project/releases/ leads to a 404.

#### Desired State
This is a Jekyll issue with trailing forward slashes as of Jekyll v4.0. Try https://docs.meshery.io/project/releases. Each page needs to be configured with a redirect to handle trailing forward slashes.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
// @samirparhi-dev

**Comment by leecalcote** [comment]
I _think_ all of these have been successfully addressed.

We have used the `redirect_from:` plugin to redirect from pages that end with a trailing slash to the same URL without trailing slash.

**Comment by adithyaakrishna** [comment]
I completely missed this issue 😶 
@leecalcote So does that mean this issue is fixed rn and can be closed? 👀

**Comment by leecalcote** [comment]
Yes, sir. Near as I can tell, we are good to close. I made a few updates earlier today on the last outstanding pages that I saw having this issue.
