### ISSUE TITLE
[Meshery UI - Draft] - Filter UI implementation 

### ISSUE THREAD

**Issue by Chadha93** [layer5io/meshery#3004]
#### Current Behavior
Changes not able to view locally even after configuring routes and building UI

#### Desired Behavior
discussion on a fix for the same

#### Implementation
Created routes pages for the filter UI and added entries in the navigator.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
@leecalcote @utkarsh-pro @Nikhil-Ladha  This is a draft pr.
@utkarsh-pro I have updated the files as you have suggested and have rebuild the Meshery UI but was unable to view my changes locally. Could you please guide me from my draft pr, what further changes needed to be done? (no issues while building the UI)
![Screenshot from 2021-05-23 00-19-20](https://user-images.githubusercontent.com/65453826/119238697-9de22f00-bb61-11eb-9ab7-645d18033009.png)

**Comment by Chadha93** [comment]
Log file:
[log.txt](https://github.com/layer5io/meshery/files/6527025/log.txt)

**Comment by leecalcote** [comment]
Nice work documenting you current progress and state of the challenge that you’re currently facing, @Chadha93. It’s nice to see this sort of diligence being exercised.

**Comment by Chadha93** [comment]
Thanks, @leecalcote I feel it will give a much more view of the issue and would be resolved accordingly.

**Comment by Nikhil-Ladha** [comment]
So, by not able to view you them, do you mean the link is not working or the item is not showing up on the Navigation Menu?

**Comment by Nikhil-Ladha** [comment]
The link is working and the page is rendered on navigating to `localhost:3000/configuration/filters`. But, the option will not be displayed in the Navigation Menu until you set `show: true`.

**Comment by Nikhil-Ladha** [comment]
Like after tweaking the values I was able to display the option without the check:
![Screenshot from 2021-05-23 13-48-57](https://user-images.githubusercontent.com/29438875/119253199-c0aa2d00-bbcd-11eb-9e29-c933ac9c82c9.png)

**Comment by Chadha93** [comment]
> The link is working and the page is rendered on navigating to `localhost:3000/configuration/filters`. But, the option will not be displayed in the Navigation Menu until you set `show: true`.
> And, I think that is so because the check is done at run time to check for `persist-meshery-pattern` and only then the option is enabled.
> Also, the check is only done for the `Patterns` id so even after that the `Filter` option will be available. Some updates need to be done there or at the declaration as well to correctly display the option.
> @utkarsh-pro might be able to highlight is better which approach should be taken.

It was giving me a `404 `page not found error when I tried using the URL. I haven't changed the `show value` for the filter because I logged in using` twitter` access and only `pattern` option was showing in the navigator

**Comment by Nikhil-Ladha** [comment]
Hmm....strange it works for me though.

**Comment by Chadha93** [comment]
> Hmm....strange it works for me though. Check if there's a typo in the path.

Yes it's working now with the URL but now showing in the navigator ( I have set the `show value true` )

**Comment by Nikhil-Ladha** [comment]
It should work without the show value as well, because ultimately it's a path, so that shouldn't matter.

**Comment by Chadha93** [comment]
@leecalcote @Nikhil-Ladha (Update) - Now showing in navigator also ( don't worry about the `Filtering` was just playing with it ). I Will now focus on the schema form
![Screenshot from 2021-05-24 19-46-08](https://user-images.githubusercontent.com/65453826/119361333-2b8c5e80-bcc9-11eb-9a2e-299f641ab172.png)
