### ISSUE TITLE
[Meshery] Input field for the config file works but looks disabled

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/meshery#3013]
#### Description
1.)In the orange box marked in the below screenshot, there is an input whose transparency is just very low. 
2.)The Input in green box marked in the below screenshot, the input is disabled presently.

#### Current Behaviour
1.)That input is just having low transparency and making a gap and making it asymmetrical that is not required.
2.)On hovering, neither the cursor in changed nor there is a change in the input field, so don't give a sense that file is to be uploaded.
#### Desired Behaviour
1.)That input could be removed without any change in functionality.
2.)It could be enabled or on hover the, cursor should become pointer so that the user know that file need to be uploaded here.

#### Screenshots/Logs
![Screenshot 2021-05-24 at 10 14 54 PM](https://user-images.githubusercontent.com/59086855/119382329-829d2e00-bcdf-11eb-82a9-3eea89616277.png)

####Environment:
- Meshery Version: any
- Kubernetes Version: any
- Host OS: Any
- Browser: Any

**Comment by adithyaakrishna** [comment]
@Ayush-Khandelwal-007 Would you be working on this? 👀

**Comment by Ayush-Khandelwal-007** [comment]
Sure! I'll work on this.

**Comment by leecalcote** [comment]
Quality write up in this issue description, @Ayush-Khandelwal-007 👍

**Comment by Ayush-Khandelwal-007** [comment]
Thank you @leecalcote
