### ISSUE TITLE
Collapsable Navigation Menu

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#304]
**Enhancement Description**
As a user, I sometimes prefer to collapse the lefthand side navigation menu to only show icons and sometime prefer to see the full menu with labels for each navigation menu item.

**Example**
![Untitled](https://user-images.githubusercontent.com/7570704/65795310-96217b80-e12f-11e9-81cd-ebe88650af52.gif)

**Implementation**
- [ ] A new icon will need to be added to denote this action.
- [ ] The icon used to collapse the menu should be placed in the lower, righthand side of the current navigation menu (see screenshot).
<img width="447" alt="Screen Shot 2019-09-27 at 1 30 49 PM" src="https://user-images.githubusercontent.com/7570704/65793667-f8787d00-e12b-11e9-8c3e-0d9a6268677f.png">

**Comment by mcastre** [comment]
I can help you with this!

**Comment by leecalcote** [comment]
@mcastre that would be just lovely. Yes, please. Here's a quick guide to [contributing](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md) (note the steps specific to the UI).

Be sure to see the [Meshery Contributors Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit) and join this Slack, so that you might get to know more of the community being this project - http://slack.meshery.io.

**Comment by mcastre** [comment]
Thanks @leecalcote! I'll get right on it!

**Comment by girishranganathan** [comment]
@mcastre assigning the issue so that no one else will accidentally work on the same. . . 🙂

**Comment by mcastre** [comment]
@leecalcote can we close this issue? Im not sure but Hacktoberfest isnt counting this PR as completed

**Comment by leecalcote** [comment]
@mcastre absolutely. Yes. Thanks for your good work here.
