### ISSUE TITLE
[mesheryctl] go lint check failure in `system context create`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3042]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
<img width="1244" alt="Screen Shot 2021-05-28 at 1 06 36 PM" src="https://user-images.githubusercontent.com/7570704/120024988-9bdefc80-bfb5-11eb-9ca3-394e6f9c0b89.png">

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
@leecalcote I've pushed [this commit](https://github.com/layer5io/meshery/pull/3001/commits/147ff9bd43406d3ca82f73972d2da642d5b0cb6e) to fix this in my current PR

This is passing the lint check so I think this should fix the issue when this PR is merged.

**Comment by metonymic-smokey** [comment]
Do you want me to link this issue to that PR?

**Comment by leecalcote** [comment]
Yes, ma'am. That would be great.

**Comment by piyushsingariya** [comment]
This is already covered in pr #2928

**Comment by metonymic-smokey** [comment]
@piyushsingariya thanks for the heads - up!
I had commented before this PR was merged.
