### ISSUE TITLE
[Docs]Error command in the Quick Start Guide

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/meshery#3049]
#### Current State

In the [Quick Start Guide](https://docs.meshery.io/installation/quick-start) under the Install Meshery section the command
`$ curl -L https://git.io/meshery | bash - `
gives an unexpected error as the platform (Docker, Kubernetes) is not defined.

#### Desired State

By running the single command in the Quick Start Guide under the Install Meshery section should download, install, and run Meshery.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment]
@leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Thank you, @sayantan1413

**Comment by leecalcote** [comment]
Ideally, the docs page (and other references in the docs) will replicate what's on meshery.io verbatim.

**Comment by sayantan1413** [comment]
> Ideally, the docs page (and other references in the docs) will replicate what's on meshery.io verbatim.

I didn't get this point :(

**Comment by leecalcote** [comment]
Copy what is on https://meshery.io/#getting-started

**Comment by sayantan1413** [comment]
Yeah I will copy two command one for docker and for kubernetes and replace that existing command which produces an error.

**Comment by leecalcote** [comment]
Good, good.
