### ISSUE TITLE
[Docs] Improve UI for REST/GraphQL API Docs

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery#3066]
[REST API Docs](https://docs.meshery.io/reference/rest-apis)
[GraphQL Docs](https://docs.meshery.io/reference/graphql-apis)

#### Desired State

Improve the UI/CSS for the Documentation pages.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
I would like to try this.

**Comment by leecalcote** [comment]
@piyushsingariya Will you double check that Anushka is not working on this already?

**Comment by Anushka-shukla** [comment]
> @piyushsingariya Will you double check that Anushka is not working on this already?

Yes, @leecalcote I'm on it.

**Comment by Chadha93** [comment]
Great

**Comment by leecalcote** [comment]
![Screen Shot 2021-05-31 at 11 19](https://user-images.githubusercontent.com/7570704/121515610-00855880-c9b3-11eb-898b-17486f3a818b.png)

**Comment by leecalcote** [comment]
![Screen Shot 2021-05-31 at 11 22](https://user-images.githubusercontent.com/7570704/121515639-07ac6680-c9b3-11eb-9cb6-cbe69cf28df5.png)

**Comment by leecalcote** [comment]
Hi @Anushka-shukla, checking on progress... are you still working on these?

**Comment by Anushka-shukla** [comment]
> Hi @Anushka-shukla, checking on progress... are you still working on these?

Yes.

**Comment by kaushambisharma** [comment]
I'd like to work on this.

**Comment by leecalcote** [comment]
Thank you, @kaushambisharma. 🙂
