### ISSUE TITLE
[meshery] Server return 500 for No results in a profile

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery#3068]
#### Description
While requesting results for a performance profile with zero tests, the server returns a 500 Internal Server Error
![image](https://user-images.githubusercontent.com/50979887/120093947-184f1800-c13b-11eb-8519-04b2666c73eb.png)

#### Expected Behavior
Should report with a simple error saying "No results for the given profile"

**Comment by kaushambisharma** [comment]
can I work on this issue?

**Comment by piyushsingariya** [comment]
@kaushambisharma This isn't an issue that needs to be worked on, It is more like a problem that needs attention. You should look out for some other issue :smile:
