### ISSUE TITLE
Add contribution instructions on how to bring local branches to HEAD on master branch.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#308]
**Issue Description**
Contributors who checkout a feature branch to from `master` regularly fall prey to errant code changes showing up in their subsequent pull requests based on other contributors' PRs being merged with other commits while the first developer is working on a local (now outdated) copy of master in their feature branch. Feature branches need to be brought up to speed (up to the latest commits in the master branch). This can be done by executing:

```
git checkout master
git pull
git checkout <YOUR LOCAL BRANCH>
git merge master
```
**Enhancement**
The CONTRIBUTING.md needs to be updated to describe this scenario and how to remediate it.

**Comment by leecalcote** [comment]
@ashiscs we'd do well to include instructions on syncing local forks with remote forks.

**Comment by ashiscs** [comment]
ok sir @leecalcote understood.
