### ISSUE TITLE
Kuma Adapter URL missing

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/meshery#3083]
#### Description
Adapter URL with port 10007 that is the URL for Kuma adapter is missing.

#### Screenshots/Logs
![Screenshot 2021-05-31 at 8 10 41 PM](https://user-images.githubusercontent.com/59086855/120227195-539a3580-c266-11eb-8731-a56f571cfde4.png)

#### Environment:
- Meshery Version: Latest 

#### To Reproduce
1. Go to Makefile
2. See error on the top

**Comment by debjani1413** [comment]
I would like to work on this issue, could you please guide me through it?

**Comment by debjani1413** [comment]
Hey, @Ayush-Khandelwal-007, I just need to add mesherylocal.layer5.io:10007 to the Makefile right??

**Comment by Ayush-Khandelwal-007** [comment]
@debjani1413  Here the constant contains all the URLs that are passed on when the server starts so these ports are listened for the Adapters when the sever is up. So you just need to add one more URL that have same base URL but the missing port, i.e., the port for Kuma adapter, further which is set default to 10007 in the adapter.

**Comment by debjani1413** [comment]
Okay great, will do that right away!
