### ISSUE TITLE
[MeshSync] Issues with KinD deployment

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3121]
@utkarsh-pro to update with details.

File an issue about MeshSync not working in your environment.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/3037#discussion_r642634489_

**Comment by leecalcote** [comment]
@kumarabd, as you dig into moving MeshKit's usage into Meshery Server for uses like kubeconfig and kube client handling, you should catch up with @utkarsh-pro on the details here.

**Comment by utkarsh-pro** [comment]
@leecalcote I, and @kumarabd went through this issue a while back and got it working on the KinD. The issue was not specific to either KinD or MeshSync rather was probably an issue with my environment.

Please re-open it if something more needs to be added here.
