### ISSUE TITLE
[Docs] - Missing Latest Meshery Release Notes - v0.5.16 & v0.5.17

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/meshery#3123]
#### Current State
[docs.meshery.io/project/releases](https://docs.meshery.io/project/releases) is missing the latest Meshery version release notes.

#### Desired State
Add release notes for v0.5.16 and v0.5.17

![image](https://user-images.githubusercontent.com/23498248/120496298-14412580-c3db-11eb-8f84-5a4bad84ac10.png)

Related to Issue #3017 

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
// @leecalcote @alphaX86

**Comment by umairnsr87** [comment]
@adithyaakrishna Can i work on this?

**Comment by adithyaakrishna** [comment]
@umairnsr87 Yes sure, please do refer this PR to know what exactly needs to be done, https://github.com/meshery/meshery/pull/2990

**Comment by umairnsr87** [comment]
@adithyaakrishna  I am unable to see the release notes of v0.5.15 too should I create them too?

**Comment by adithyaakrishna** [comment]
Yepp, please do go ahead and create that one, there's an upstream issue for that #3017

**Comment by umairnsr87** [comment]
> Yepp, please do go ahead and create that one, there's an upstream issue for that #3017
> Also please do comment once in the #3017 issue

Done @adithyaakrishna
