### ISSUE TITLE
[Docs] Favicon on docs.meshery.io should be of Meshery logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3125]
#### Current State
The favicon on docs.meshery. io is not of the Meshery logo currently.

#### Desired State
Use Meshery logo from https://layer5.io/brand

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by debjani1413** [comment]
I got 2 logo files in docs logo1.svg and logo.svg, which one to change?? also which logo to add?? can please help me by being a little more specific?

**Comment by hrishikeshnikam2000** [comment]
I would like to make my contribution starting from here.  

To be clear the logo required is the one which I am attaching below or is it a different one?

![meshery-logo-tag-light-text-side](https://user-images.githubusercontent.com/58680992/120653369-3c458d00-c49e-11eb-9a39-5c59daab04c3.png)

**Comment by adithyaakrishna** [comment]
@debjani1413 It's https://github.com/meshery/meshery/blob/master/docs/_includes/logo.svg
i.e **`logo.svg`**

**Comment by adithyaakrishna** [comment]
> I would like to make my contribution starting from here.
> 
> To be clear the logo required is the one which I am attaching below or is it a different one?
> 
> ![meshery-logo-tag-light-text-side](https://user-images.githubusercontent.com/58680992/120653369-3c458d00-c49e-11eb-9a39-5c59daab04c3.png)

Hey @hrishikeshnikam2000 
This issue is already taken and to answer your query, its not the one, we needed the Meshery Circle Logo without the text.
Also, feel free to have a look at other issues and find your suitable interest one. If you find it, do add a comment and I would be glad to assign it to you :)

**Comment by hrishikeshnikam2000** [comment]
okay I will look into other issues. thank you.

**Comment by leecalcote** [comment]
@debjani1413 @hrishikeshnikam2000 please first familiarize with the concept of a favicon. Reengaging if / when ready.
