### ISSUE TITLE
[UI] Logo area should be frozen in place

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3131]
#### Description
The Meshery Logo should not disappear when users scroll through the menu.

#### Screenshots/Logs
![Untitled](https://user-images.githubusercontent.com/7570704/120562259-ab05e600-c3cb-11eb-99e7-e3607006e402.gif)

#### Environment:
- Meshery Version: v0.5.17
- Browser: Safari

**Comment by sudo-NithishKarthik** [comment]
Can I take up this issue?

**Comment by dhruv0000** [comment]
sure.
