### ISSUE TITLE
[mesheryctl] bugs in `mesheryctl system channel set`

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/meshery#3143]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

* Panic when trying to set a channel without specifying version.
* Unable to set any version tag when specifying with `channelName-version`

#### Desired Behavior

* Setting channel without specifying any version should set it to "latest" by default
* Accept versions in the format `vX.X.X`

#### Screenshots/Logs

The first one:
```
$ mesheryctl system channel set stable
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.glob..func2(0x34cefc0, 0xc0003f4c00, 0x1, 0x1, 0x0, 0x0)
        /Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/channel.go:133 +0xa01
github.com/spf13/cobra.(*Command).execute(0x34cefc0, 0xc0003f4bc0, 0x1, 0x1, 0x34cefc0, 0xc0003f4bc0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x34c9fc0, 0x23b1e20, 0x369b340, 0x0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
        /Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:85 +0x56
main.main()
        /Users/runner/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:22 +0x20
```
The second:
```
$ mesheryctl system channel set stable-v0.5.17
Error: v0.5.17 is not a valid version tag
Usage:
  mesheryctl system channel set [stable|stable-version|edge|edge-version] [flags]

Flags:
  -h, --help   help for set

Global Flags:
      --config string     config file (default location is: /home/rudraksh/.meshery/config.yaml)
  -c, --context string    (optional) temporarily change the current context.
  -p, --platform string   platform to deploy Meshery to
  -v, --verbose           verbose output
  -y, --yes               (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Linux
- Meshery Server Version: stable-v0.5.18
- Meshery Client Version: stable-v0.5.18
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you for filing this, @DelusionalOptimist
