### ISSUE TITLE
[Bug] Not able to add API key in Grafana Marics Settings 

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/meshery#3150]
#### Description
User is not able to enter a API key in Grafana Settings. Instead `[object Object]` is shown.

#### Expected Behavior
User should be able to enter API key.

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/44001539/120934826-89836200-c71d-11eb-8ced-a0e692667975.png)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser: 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007 I wonder if you might knock this one out.

**Comment by Ayush-Khandelwal-007** [comment]
@leecalcote Okay! I'll take this bug down.
