### ISSUE TITLE
[Docs] Breakout Meshery Adapters contributing instructions into a separate page.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3151]
#### Current State
The https://docs.meshery.io/project/contributing page has general, server, and adapter instructions all in the same page. We are in the process of breaking out component sections into their own pages.

#### Desired State
Meshery Adapters should have their own page here - https://docs.meshery.io/project/contributing-adapters

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Annysah** [comment]
Hello Lee,
I would like to know if this issue is still open?

**Comment by leecalcote** [comment]
Hi @Annysah, thank you for asking. Actually, there's an open PR up for review on this now. Your review of the PR would be great.

**Comment by leecalcote** [comment]
Oh, no. I thought it was still open, but it has been merged already - https://github.com/meshery/meshery/pull/3152.

There are more open needs where this comes from, though. Like the need to separate out a page just for Meshery Server. Please don't hesitate to open an issue.
