### ISSUE TITLE
--yes flag fails to generate config file

### ISSUE THREAD

**Issue by s1ntaxe770r** [layer5io/meshery#3161]
#### Description

when running mesheryctl system start with the `--yes` flag a default config file is not generated.
 
#### Expected Behavior

A default config file. See screenshots below 
#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/53065463/121217029-5b1a9980-c879-11eb-8d3b-5b690dcdb5ec.png)

![image](https://user-images.githubusercontent.com/53065463/121217075-67065b80-c879-11eb-952b-21966990302c.png)

#### Environment:
- Meshery Version: 
- Kubernetes Version: v1.19.2
- Host OS:  Ubuntu 20.04(github action runner)
- Browser: 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by leecalcote** [comment]
@s1ntaxe770r will you recreate this in the form of a feature request? Will you use the mesheryctl issue template when you do?

**Comment by leecalcote** [comment]
From @navendu-pottekkat:

> From what I think you are trying to do, you can by default create a config file with Kubernetes platform when you first invoke start. system start has a -p flag which when used to set a platform, will change the platform inside the config file.
> Or, if you are using the bash script to install mesheryctl, you can directly pass in a platform to use
