### ISSUE TITLE
[UI] Only half of Meshery logo providing link to system dashboard

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3180]
#### Description
Only half of the Meshery logo is clickable to navigate users to the root page.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/121413063-eef86e00-c92a-11eb-94c7-c40fb9cccea1.mov

#### Environment:
- Meshery Version: v0.5.23
- Browser: Safari

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by DARK-art108** [comment]
Can I work upon this @leecalcote !

**Comment by Ayush-Khandelwal-007** [comment]
Here you go! @DARK-art108

**Comment by DARK-art108** [comment]
@Ayush-Khandelwal-007 @leecalcote is this behavior is only with safari or also with other browsers!

**Comment by sudo-NithishKarthik** [comment]
Hey @DARK-art108, i've been looking at this issue and i found that this is an unintentional side effect that got introduced while fixing #3144. Would you mind me fixing it?

**Comment by DARK-art108** [comment]
Yes, @sudo-NithishKarthik Please go ahead!
