### ISSUE TITLE
[Docs] Release notes missing in Docs 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3183]
#### Current State
Current release is v0.5.23. Docs only contain release notes up to v0.5.17.

#### Desired State
https://docs.meshery.io/project/releases should have entries for all release notes. Release notes are available here - https://github.com/layer5io/meshery/releases

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iambami** [comment]
Love to take this

**Comment by leecalcote** [comment]
@iambami fyi, if you add the issue # to the placeholder in the PR's description, it will autoclose the associated issue (this issue), saving us a step in the future. ✔️ 

Thanks for knocking this out.

**Comment by iambami** [comment]
Thank you Lee.
