### ISSUE TITLE
Opening browser does not work on Windows + WSL2

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#320]
**Description**
mesheryctl.exe on windows does not open the browser after all the services are up and running. We should detect Windows as the OS and use `start` or `execute` to open http://localhost:9081.

**Comment by girishranganathan** [comment]
@anandrkskd can you please knock this one out?

**Comment by anandrkskd** [comment]
Yes sure sir,

**Comment by leecalcote** [comment]
@nunix at your convenience, will you confirm that we’re ok to close this issue (that the issue has been fixed)?
