### ISSUE TITLE
[Docs] Update Performance usage example

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery#3214]
#### Current State
![image](https://user-images.githubusercontent.com/50979887/122206410-f685bd00-cebe-11eb-9a16-e38e04bc4445.png)

#### Desired State.
Update the pages https://docs.meshery.io/reference/mesheryctl and https://docs.meshery.io/reference/mesheryctl/perf with the latest changes in `mesheryctl perf` command.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NagaHarshita** [comment]
Can you please assign this issue to me?

**Comment by piyushsingariya** [comment]
Sure @NagaHarshita!
