### ISSUE TITLE
[mesheryctl] `system status` panics when executing while in-cluster deployments are restarting

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3244]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl system status` panics when executing while in-cluster deployments are restarting.

#### Desired Behavior
Whether Meshery Server's REST API is providing clean responses or not, mesheryctl should handle malformed / 500 responses from Meshery Server (/api/server/version responses).

#### Reproduction Steps
1. Run Meshery in-cluster
2. Execute `system restart`
3. While system is restarting, execute `system version`

#### Screenshots/Logs
```
➜  ~ mesheryctl system status
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.glob..func14(0x40febe0, 0x42cbee8, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/status.go:118 +0xcb8
github.com/spf13/cobra.(*Command).execute(0x40febe0, 0x42cbee8, 0x0, 0x0, 0x40febe0, 0x42cbee8)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x40fa0e0, 0x2fd0520, 0x42cbee8, 0x0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:85 +0x56
main.main()
	/Users/runner/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:22 +0x20
```

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.23
- Meshery Client Version: stable-v0.5.24
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
To repro: execute the `mesheryctl version` command as the Meshery Server pod is starting.

**Comment by metonymic-smokey** [comment]
> To repro: execute the `mesheryctl system status` command as the Meshery Server pod is starting.

@leecalcote I did not face this issue running `system status` when `start` was in progress:

![image](https://user-images.githubusercontent.com/48997495/122969434-44606080-d3aa-11eb-911f-d4e2ad492f75.png). 

Is there something I'm missing?
