### ISSUE TITLE
[mesheryctl] `system status` showing invalid endpoint when server is stopped

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3245]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
mesheryctl is showing an available endpoint for Meshery Server despite Meshery Server not being available.

#### Desired Behavior
Instead of "Meshery endpoint is", show user a message that says "Meshery is not running"

#### Screenshots/Logs
```
➜  ~ mesheryctl system status
NAME            	READY	STATUS 	RESTARTS	AGE
meshery-meshsync	1/1  	Running	4       	22m48s

Meshery endpoint is http://localhost:30416
```

#### Environment

- Meshery Server Version: stable-v0.5.24
- Meshery Client Version: stable-v0.5.24
- Platform:  Kubernetes
---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@anirudhjain75 An issue for warming up to mesheryctl
