### ISSUE TITLE
[CI] Move away from Netlify builds; Use Netlify for deploy previews only

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3250]
#### Current Behavior
The `layer5io/layer5` site uses GitHub Actions for building the site and publishes PR-specific deploy previews to Netlify. Using this approach, as a project, we don't have to worry about going over build minutes each month with Netlify.

#### Implementation
Mimic the `layer5` site build/deploy preview workflow - https://github.com/layer5io/layer5/blob/master/.github/workflows/preview-site.yml

#### Bonus:

Do not deploy previews to netlify, but to a local branch on the Meshery repo (or to another repo).

Join the Meshery CI WG meetings biweekly on Thursdays (https://meet.layer5.io) and/or join the Layer5 Slack (https://slack.layer5.io) for help. 

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by nehapithadiya** [comment]
@leecalcote I have started working on this. Discussed with @Nikhil-Ladha on this issue.
