### ISSUE TITLE
[Perf] Second Grafana board fails to save

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3258]
#### Description
When adding more than one Grafana board to the user's view, the following error is displayed:

<img width="523" alt="Screen Shot 2021-06-22 at 2 21 37 PM" src="https://user-images.githubusercontent.com/7570704/123000048-a8683200-d374-11eb-9136-6fce895174ad.png">

The second board is not displayed to the user. If the user refreshes the page, they will see the second board.

#### Environment:
- Meshery Version: v0.5.25
- Browser: Safari (any)

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by dhruv0000** [comment]
Fixed by #3263
