### ISSUE TITLE
Installation: Default to out of cluster config when config is not present

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#326]
**Description**
Meshery currently defaults to an in cluster configuration setting when it cannot locally discover a kubeconfig.

**Expected Behavior**
Meshery should be set to "in cluster config" only when this is determined to be true. Otherwise, Meshery should default to "out of cluster config".

**Screenshots**
![Screen Shot 2019-10-04 at 7 36 45 AM](https://user-images.githubusercontent.com/7570704/66208010-c90cc780-e679-11e9-88b1-a695c332ac29.png)

**To Reproduce**
1. Deploy Meshery on a host with no kubeconfig file present.

**Comment by girishranganathan** [comment]
@leecalcote, I have a fix for this in a branch. It will get fixed as part of the other pieces I am working on.

**Comment by girishranganathan** [comment]
This was fixed with a recent PR.
