### ISSUE TITLE
UI: Icons for service mesh operations

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#327]
**Enhancement Description**
In each of the service mesh adapter's management page, there are several categories of operations that may be performed against a given service mesh. Intuitive icons are needed for  each of the categories of operation:

- install / delete service mesh - provision or deprovision an entire service mesh.
- install / delete sample applications - onboard or offboard an application (a workload) to/from the service mesh.
- configure - apply a predefined (static) configuration to the service mesh.
- validate - run a set of checks to validate the service mesh's current configuration against a set of best practices.
- custom config - apply a custom configuration (user-defined) to the service mesh.

![Meshery](https://user-images.githubusercontent.com/31675149/66212395-d59a1b80-e68b-11e9-8025-3d12f88f3c68.png)

Meshery generally uses icons from font-awesome collection, but can use others.

**User Interface Redesign**
More broadly, the UI itself is in need of an overhaul. While the idea here is to design new “action” or “operation” icons, in fact, the entire user interaction is in need of an overhaul as what users are to do when they land on this page is not intuitively presented.

**Comment by mcastre** [comment]
Hey @leecalcote i can help you with this! Do you just want the icons or would you like them added to the UI as well?

**Comment by leecalcote** [comment]
@mcastre that would be just lovely. Yes, both. We're in need of identifying (or creating) representatives icons, and in turn, adding them to the UI.

We generally seek to pull from here:
- https://materialdesignicons.com 
- https://material-ui.com/components/material-icons
- https://fontawesome.com

Or just make a new one like this - [PR 292](https://github.com/layer5io/meshery/pull/292) - [performance.svg](https://github.com/layer5io/meshery/blob/c314eaafd75792e60ac1598fcd214ecda50a20d7/ui/static/img/performance.svg)
