### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by houshym** [layer5io/meshery#329]
https://meshery.layer5.io/docs/installation.md    does not works

**Comment by leecalcote** [comment]
@gunjanmimo @ashiscs could one of you have a look here?

**Comment by leecalcote** [comment]
@houshym thanks for opening this issue. Do you recall where you found the link to https://meshery.meshery.io/docs/installation.md? Links to this page should be pointing to https://meshery.meshery.io/docs/installation (without the .md). If there is a page that has the .md link listed, @ashiscs, we'll need to remove the .md.

**Comment by houshym** [comment]
i will try to find this page. But it was on minikube installation page and
in third step
