### ISSUE TITLE
a img is not loaded

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/meshery#330]
in the contribution section, an image is not loaded at [https://meshery.layer5.io/docs](https://meshery.layer5.io/docs)
@leecalcote is it an issue? 
![Screenshot (16)_LI](https://user-images.githubusercontent.com/46948185/66260062-32eeb380-e7d7-11e9-92f4-51ae77927021.jpg)

**Comment by leecalcote** [comment]
@gunjanmimo good catch. Yes, this is an issue. From what I can tell, this link wasn't intended to be an image, but simply a hyperlink. Yes, it needs fixed.

**Comment by gunjanmimo** [comment]
sir @leecalcote #336 I solved this problem
