### ISSUE TITLE
Istio installation - convert SMI and mTLS into checkbox options in the UI

### ISSUE THREAD

**Issue by antweiss** [layer5io/meshery#337]
**Enhancement Description**
Quoting @leecalcote : 
The ideal solution here is ... for an "enable SMI" to be a checkbox be presented as a choice (later to be enabled by default) when deploying Istio. The same goes for "enable mTLS" as a checkbox choice. 
This can be further developed into choosing additional Istio configurations like a 'minimal configuration' or others featured here for example:  https://github.com/istioinaction/book-source-code/tree/master/install

**Related Challenges**

As a meshery user when installing Istio I need to be able to choose Istio add-ons and options by checking a checkbox in the UI.

---
Brought on by the discussion in this PR: https://github.com/layer5io/meshery-istio/pull/27

**Comment by leecalcote** [comment]
Good deal. One of these options might be the exposure of Grafana and Prometheus service endpoints running in the control plane, so that each of these two services are automatically “discovered” and connected to by Meshery upon deployment of Istio.

**Comment by leecalcote** [comment]
Meshery v0.5.0 now allows users to switch on and off individual add-ons.

<img width="1808" alt="Screen Shot 2021-04-15 at 4 20 58 PM" src="https://user-images.githubusercontent.com/7570704/114939964-c199b300-9e06-11eb-885f-594cc56c65b4.png">

**Comment by leecalcote** [comment]
Thank you for this feedback, @antweiss 👍
