### ISSUE TITLE
Create modal to display performance test results

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#353]
*Current Behavior*
Performance results are show in the /results page and intermix both a line graph and metadata about the test. This text is hard to read and not well-structured. See screenshot. 

*Current Behavior Screenshot*
<img width="1340" alt="Current" src="https://user-images.githubusercontent.com/7570704/66600999-74cb8100-eb6c-11e9-8247-a27edf63dbd2.png">

*Enhancement Description*
This enhancement is to move the test and environment metadata into a modal that is displayed when the user clicks on the line chart. 

_Implementation_
The metadata should be clearly structured for easy of understanding.
 - [ ] show metadata in [a modal](https://material-ui.com/components/modal/).
 - [ ] the data to be displayed will be available in the context. Just like the rowData in here: https://github.com/layer5io/meshery/blob/82018c54539f3d79eb639109b7c7cf6f67e41b2b/ui/components/MesheryResults.js#L348
 - [ ] font size increased to be the same size as the text in the results table.
 - [ ] a tabular format for displaying metadata would work well (i.e. columns for the label and a columns for the values) like the cluster name, Kubernetes version, Installed Mesh & its version, etc.

_Mockup_
<img width="1644" alt="Mockup" src="https://user-images.githubusercontent.com/7570704/66681174-becd6900-ec37-11e9-8d56-15a5a0b86094.png">

*Dependency:*
- The row data does not currently have all available metadata to be displayed in the modal. #367  will need to be delivered in order to expose all metadata.

**Comment by Pika1998** [comment]
i would like to work on this

**Comment by leecalcote** [comment]
Excellent! Yes, please, @Pika1998. :)

**Comment by leecalcote** [comment]
@Pika1998 join this [Slack](http://slack.meshery.io) and we'll get you introduced to others in [the community](https://layer5.io/meshery/#community) and contributor resources you might need, like the [Meshery Newcomer Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit) (request access).

**Comment by leecalcote** [comment]
@Pika1998 just message in Slack when you dive in here, so that we can assist if needed. :)

**Comment by prafulla-codes** [comment]
Hey sorry I am finding it a bit hard to understand the code

**Comment by leecalcote** [comment]
@Pika1998 no problem. Join this Slack (http://slack.meshery.io) and a community member will help. // @Nikhil-Ladha
