### ISSUE TITLE
Displace read-only adapter field with an interactive adapter chip.

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#354]
**Enhancement Short Description**
Displace read-only adapter field with an interactive adapter chip.

**Current Behavior**
_Context:_
When Meshery connects to one of its adapters, users see those adapters represented as a chiclet in the Dashboard view (see screenshot). Users also see menu items representing each adapter in the navigation menu on the lefthand side. 

<img width="1353" alt="current" src="https://user-images.githubusercontent.com/7570704/66598622-059f5e00-eb67-11e9-90f7-84e8b95f5539.png">

**Enhancement Long Description**
When a user clicks on one of those menu items (on an adapter), they are navigated to that adapter's specific page or the management page the adapter URL is displayed as a read-only field (see "current" screenshot). 

This enhancement is to display the adapter as a [chip](https://material-ui.com/components/chips/) (the same as are on the Dashboard). When this chip is clicked, it should invoke the same connectivity test that is performed when an adapter chip is clicked on the Dashboard. See the _mockup_ below:

_Mockup_
<img width="1353" alt="enhanced" src="https://user-images.githubusercontent.com/7570704/66598652-13ed7a00-eb67-11e9-9195-e3e6c33d44f5.png">

**Comment by leecalcote** [comment]
@Nikhil-Ladha is a great resource here should you have questions @ashiscs
