### ISSUE TITLE
Switch to the new Docker Github action in Meshery-linkerd repo

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#356]
**Description**
Since last Monday (7th October 2019) the default Docker GitHub action stopped working because the repo was deleted. We have migrated to a different docker GitHub action in the Meshery repo.
We need to replace the entire Docker block in `Meshery-linkerd` repo's https://github.com/layer5io/meshery-linkerd/blob/master/.github/workflows/ci.yml file with the one from the `Meshery` repo (https://github.com/layer5io/meshery/blob/master/.github/workflows/ci.yml).

Here is the snippet from the Meshery repo which we want copied over:

https://github.com/layer5io/meshery/blob/82018c54539f3d79eb639109b7c7cf6f67e41b2b/.github/workflows/ci.yml#L139-L173

Here is the snippet which needs to be replaced:

https://github.com/layer5io/meshery-linkerd/blob/f14311abb52ecd9e97590531674e5f65084dde8d/.github/workflows/ci.yml#L106-L158

**Comment by GenericStudent** [comment]
Already resolved in commit [1588d704f95cfccedca157dc8e5930376c733e57](https://github.com/meshery/meshery-linkerd/commit/1588d704f95cfccedca157dc8e5930376c733e57?diff=unified)

**Comment by leecalcote** [comment]
@girishranganathan let's move this series of issues to their respective repos.
