### ISSUE TITLE
Switch to the new Docker Github action in Meshery-app-mesh repo

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#361]
**Description**
Since last Monday (7th October 2019) the default Docker GitHub action stopped working because the repo was deleted. We have migrated to a different docker GitHub action in the Meshery repo.
We need to replace the entire Docker block in `Meshery-app-mesh` repo's https://github.com/layer5io/meshery-app-mesh/blob/master/.github/workflows/ci.yml file with the one from the `Meshery` repo (https://github.com/layer5io/meshery/blob/master/.github/workflows/ci.yml).

Here is the snippet from the Meshery repo which we want copied over:

https://github.com/layer5io/meshery/blob/82018c54539f3d79eb639109b7c7cf6f67e41b2b/.github/workflows/ci.yml#L139-L173

Here is the snippet which needs to be replaced:

https://github.com/layer5io/meshery-app-mesh/blob/f678727891439da1000dd907d6470f86b36c4e41/.github/workflows/ci.yml#L106-L157

**Comment by leecalcote** [comment]
Closed by https://github.com/meshery/meshery-app-mesh/pull/13
