### ISSUE TITLE
Switch to the new Docker Github action in Meshery-maesh repo

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#362]
**Description**
Since last Monday (7th October 2019) the default Docker GitHub action stopped working because the repo was deleted. We have migrated to a different docker GitHub action in the Meshery repo.
We need to replace the entire Docker block in `Meshery-maesh` repo's https://github.com/layer5io/meshery-maesh/blob/master/.github/workflows/ci.yml file with the one from the `Meshery` repo (https://github.com/layer5io/meshery/blob/master/.github/workflows/ci.yml).

Here is the snippet from the Meshery repo which we want copied over:

https://github.com/layer5io/meshery/blob/82018c54539f3d79eb639109b7c7cf6f67e41b2b/.github/workflows/ci.yml#L139-L173

Here is the snippet which needs to be replaced:

https://github.com/layer5io/meshery-maesh/blob/aabf9be36ac63f34be500d24c956d8a640db2aea/.github/workflows/ci.yml#L106-L158

**Comment by leecalcote** [comment]
@ashiscs I think you are addressing this one. Will you ensure that your PR has a reference to this issue?

@girishranganathan to date, we've been opening adapter-specific issues within their respective repos.

**Comment by ashiscs** [comment]
https://github.com/meshery/meshery-maesh/pull/14
Fixed #362
