### ISSUE TITLE
UI: Line wrapping in mobile view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#366]
**Description**
When Meshery is viewed in a mobile-sized browser window, the global navigation menu, which normally sits in the upper lefthand corner (see desktop screenshot) is **sometimes** wrapped onto a new line under the page title (see mobile screenshot).

**Expected Behavior**
Global navigation should remain on the same line as the page title. See mockup.

**Screenshots**
_Desktop_
<img width="1016" alt="Screen Shot 2019-10-11 at 3 03 25 PM" src="https://user-images.githubusercontent.com/7570704/66681421-50d57180-ec38-11e9-9752-547b0592a876.png">

_Mobile_
<img width="454" alt="Screen Shot 2019-10-11 at 10 27 35 AM" src="https://user-images.githubusercontent.com/7570704/66681504-7febe300-ec38-11e9-9da1-e56e342f2089.png">

_Mockup_
<img width="501" alt="Screen Shot 2019-10-11 at 3 06 38 PM" src="https://user-images.githubusercontent.com/7570704/66681670-cf321380-ec38-11e9-8756-cdd58997cf28.png">

**Comment by leecalcote** [comment]
@mcastre will you validate that this is in fact a bug? I can't reproduce on my system while using either Safari or Chrome...

**Comment by mcastre** [comment]
Yes, it seems to be happening after <466px. The smallest screen size a user might have will be 320px. While we could account for cleaning up the UI on a screen thats 320px wide, we would be forced to sacrifice some of the elements, perhaps the 'Dashboard' text in the bar. I would think we can get away with fixing the nav bar between 400px and 600px. After 400, the rest of the UI starts to break.

**Comment by mcastre** [comment]
I can work on this bug since i figured out the fix for it already haha

**Comment by mcastre** [comment]
@girishranganathan i got a PR in for the fix. https://github.com/meshery/meshery/pull/370

**Comment by mcastre** [comment]
@leecalcote looks like the PR for this issue was merged!
