### ISSUE TITLE
Detect, identify and catalog meshes and their workloads

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#367]
**Current Behavior**
When a user runs a performance test, Meshery allows the user to self-identify the type and version of the service mesh that the perf test will run against.  

**Desired Behavior**
While most users will exercise diligence and accurately identify their service mesh, Meshery should not rely on the user to do so. Instead, Meshery needs to discover the service mesh and it's workloads by accurately identifing the type of service mesh, version number and all service endpoints running on the mesh so that selection of the endpoint can be made from the perf test form rather than making the user type in the address of the endpoint to be tested. 

**Enhancement Description**
Meshery should discover various details of it's connected environments. It should be able to scan the kubernetes environment and detect the installed mesh(es), their versions and possibly detect the other workloads that are deployed on the mesh and on the cluster.

**Implementation**
- [x] Define fingerprint to identify type and version of service mesh
- [ ] Ad-hoc invocation
- [x] Invocation after completion of perf test
- [ ] ...

**Functional Specification**
- Frequency of discovery
- Split of responsibility between Meshery and Meshery adapters. 
- URL of service mesh sync endpoint that Meshry will expose.

**Comment by leecalcote** [comment]
@girishranganathan using https://github.com/meshery/meshery/issues/390 as a template, will you create new issues for each of the supported meshes (in their repos) for implementation of ad-hoc connectivity test onClick of a service mesh chip?

**Comment by leecalcote** [comment]
@girishranganathan "Invocation after completion of perf test" is complete, correct? Is "Define fingerprint to identify type and version of service mesh" as well? Needs documented?

**Comment by girishranganathan** [comment]
Yes they are completed. Will add the details to the sync doc.

**Comment by leecalcote** [comment]
MeshSync v2 completed.
