### ISSUE TITLE
Switching meshery bash script to mesheryctl

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#373]
**Enhancement Description**
Today meshery bash script is used to communicate with meshery, which is going to be replaced by mesheryctl command line tool written in golang to perform the same. 

**Challenges**
1. Replacing meshery by mesheryctl.
2. Changes in meshery/docs according to mesheryctl
3. Changes in [meshery](layer5.io/meshery) according to mesheryctl

**Comment by leecalcote** [comment]
@anandrkskd Let's avoid leaving remnants of the downloaded archive by cleaning up (deleting) that archive after `mesheryctl` has been moved into place.

**Comment by anandrkskd** [comment]
Understood sir

**Comment by girishranganathan** [comment]
@leecalcote can we close this?

**Comment by leecalcote** [comment]
@girishranganathan, yes, good call. 

@anandrkskd, you did it!! We’re finally off of bash and onto go! 😀
