### ISSUE TITLE
Settings UI: Five small fixes to Cluster configuration.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#374]
**Description**
See screenshot for description of five requested changes.

**Screenshots**
![Screen Shot 2019-10-16 at 8 31 19 PM](https://user-images.githubusercontent.com/7570704/66975300-b6c05f80-f063-11e9-9d95-b578feb72ef6.png)

**Comment by leecalcote** [comment]
@Nikhil-Ladha quick check - do these make sense?

**Comment by Nikhil-Ladha** [comment]
Yes sir, i checked it. I got these issues. Even rectified four of them just left with one, which is the initial selection for context name when config is uploaded.

**Comment by leecalcote** [comment]
Very cool, @Nikhil-Ladha. 💪

**Comment by girishranganathan** [comment]
@Nikhil-Ladha great work. 
For the last one, you just need to trigger the event. Feel free to reach out to me if you have any questions.

**Comment by leecalcote** [comment]
Thanks for knocking these out, @Nikhil-Ladha
