### ISSUE TITLE
mesheryctl status on windows looks bad

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#378]
**Description**
`mesheryctl status` command output on linux or Mac seems to presented better. On windows it looks pretty bad. The formatting is off but a big factor.

**Expected Behavior**
`mesheryctl status` prints the status in a manner identical to that of on linux or Mac.

**Comment by girishranganathan** [comment]
@nunix can you please add a snapshot from your terminal?

**Comment by nunix** [comment]
![image](https://user-images.githubusercontent.com/905874/67239632-e4384f00-f44f-11e9-90cc-ee82e2f9a746.png)

here you have

**Comment by anandrkskd** [comment]
Got it! im on it will update!

**Comment by leecalcote** [comment]
Fixed by #460.
