### ISSUE TITLE
Meshery login keep redirecting back to the fallback page

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#379]
**Description**
After a successful social login, the user is directed to the fallback url: layer5.io/meshery. This goes on in a loop. The only way to log in to Meshery to start a fresh incognito session.

**Comment by raghavaggarwal99** [comment]
Hi @girishranganathan  can you describe what to do with it? I mean 
what should happen exactly?

**Comment by leecalcote** [comment]
@girishranganathan I think this is fixed already, right?

**Comment by leecalcote** [comment]
@girishranganathan @raghavaggarwal99 I believe this was fixed already. Will you confirm?

**Comment by kushthedude** [comment]
@leecalcote I can confirm this is fixed!
We can re-open it anytime if anyone ever experiences it again!

**Comment by leecalcote** [comment]
@kushthedude thank you for cleaning this up. You're right in that I don't think we've seen this issue since @kanishkarj's shifting of the project to JWT.
