### ISSUE TITLE
Watchtower fails on windows with windows containers

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#380]
**Description**
watchtower fails on windows with windows containers because it is unable to mount /var/run/docker.sock.

The issue happens mainly because in the `docker-compose.yml` file we are mounting the local docker socket inside the watchtower container. We need to figure out the right approach on windows with windows containers.

**Comment by leecalcote** [comment]
@nunix do you continue to face this issue?

**Comment by nunix** [comment]
no more with WSL2 docker daemon. It works fine, this should be ok to close
