### ISSUE TITLE
Page Title Caching Inaccurately

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#387]
**Description**
An issue with caching of the page title. The page title seems to go stale as you navigate from screen to screen.

**Reproduce**
1. Navigate from page to page and watch as the page title does not update.

**Relevant Items**
Related to issue #375.

**Comment by leecalcote** [comment]
@mcastre brainstorm briefly, if you would - what do you suspect is the root cause here?

**Comment by girishranganathan** [comment]
@leecalcote can you please test this again with the latest release?

**Comment by leecalcote** [comment]
@girishranganathan you bet. I did a `make build-ui; make run-local` on `master` at commit the latest current commit (https://github.com/meshery/meshery/commit/62ed80b62399083043a8d771984be0806107ac1d) and had these results:

1. When I opened http://localhost:9081, I saw "Dashboard" as the page title.
1. After navigating to "Management", I saw "Dashboard" as the page title (see screenshot 1).
1. I navigated to "Results" and saw the correct "View & Compare Results" title. Then, after navigating to "Performance" I continued to see "View & Compare Results title (see screenshot 2).

**Screenshot 1**
![Screen Shot 2019-10-28 at 9 41 21 PM](https://user-images.githubusercontent.com/7570704/67733372-2a4f5e80-f9cc-11e9-9d1d-9231c8227fa5.png)

**Screenshot 2**
![Screen Shot 2019-10-28 at 9 41 42 PM](https://user-images.githubusercontent.com/7570704/67733351-1d326f80-f9cc-11e9-8c5d-5e518a6f254d.png)

I tested in both Safari and Chrome. Both exhibited the same behavior.

**Comment by leecalcote** [comment]
@girishranganathan I think you recently fixed this issue. Is that right?

**Comment by girishranganathan** [comment]
Yes I think these were merged as part of the PR last week.

**Comment by leecalcote** [comment]
Close when ready.
