### ISSUE TITLE
Install: Allow ad-hoc connectivity test of Prometheus

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#390]
**Current Behavior**
Once a Meshery is connected to a Prometheus instance, the user is a shown a Prometheus chip (see screenshot) on the Settings and Dashboard pages.

**Screenshot**
<img width="210" alt="Screen Shot 2019-10-22 at 9 08 09 PM" src="https://user-images.githubusercontent.com/7570704/67350330-16a98100-f510-11e9-8c1e-3748754edbda.png">

**Desired Behavior**
In the same fashion that users are allowed to perform ad-hoc connectivity tests to the Kubernetes and service mesh chips, users should be allowed to perform ad-hoc connectivity tests to verify Meshery's current ability to interact with Prometheus (Meshery's ability to query Prometheus and retrieve metrics).

**Acceptance Criteria**
This enhancement is complete when:
- [ ] Users are able to invoke an ad-hoc connectivity test with Prometheus.
- [ ] Connectivity test retrieves Prometheus version for display in a tooltip when the user hovers the mouse over the chip.
- [ ] Connectivity tests display either a success message: "Prometheus successfully pinged!" or a failure message: "Could not connect to Prometheus."

---

**Future**
- [ ] Users should be able to invoke an ad-hoc connectivity test with *each* connected Prometheus instance.

**Comment by leecalcote** [comment]
Here's a short video describing this enhancement - https://youtu.be/VLlW_5c1MXk

**Comment by ashiscs** [comment]
@lee sir, i think this issue is already addressed and needs to be closed?

**Comment by leecalcote** [comment]
Spot on, @ashiscs
