### ISSUE TITLE
Install: Allow ad-hoc connectivity test of Grafana

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#391]
**Current Behavior**
Once a Meshery is connected to a Grafana instance, the user is a shown a Grafana chip (see screenshot) on the Settings and Dashboard pages.

**Screenshot**
<img width="229" alt="Screen Shot 2019-10-22 at 8 57 07 PM" src="https://user-images.githubusercontent.com/7570704/67349901-ddbcdc80-f50e-11e9-8360-e982a7c3e072.png">

**Desired Behavior**
In the same fashion that users are allowed to perform ad-hoc connectivity tests to the Kubernetes and service mesh chips, users should be allowed to perform ad-hoc connectivity tests to verify Meshery's current ability to interact with Grafana (Meshery's ability to query Grafana and retrieve boards, panels and metrics).

**Acceptance Criteria**
This enhancement is complete when:
- [ ] Users are able to invoke an ad-hoc connectivity test with Grafana.
- [ ] Connectivity test retrieves Grafana version for display in a tooltip when the user hovers the mouse over the chip.
- [ ] Connectivity tests display either a success message: "Grafana successfully pinged!" or a failure message: "Could not connect to Grafana."

---

**Future**
- [ ] Users should be able to invoke an ad-hoc connectivity test with *each* connected Grafana instance.

**Comment by leecalcote** [comment]
@raghavaggarwal99 once you're comfortable, an enhancement like this one might be an item to undertake.

**Comment by leecalcote** [comment]
Here's a short video describing this enhancement - https://youtu.be/VLlW_5c1MXk

**Comment by ashiscs** [comment]
@lee sir, i think this issue is already addressed and needs to be closed?

**Comment by leecalcote** [comment]
Good call, @ashiscs. Yes, you’re right.
