### ISSUE TITLE
Docs: Add WSL2 to platform compatibility table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#393]
**Issue Description**
Meshery is compatible with WSL2. This scenario and any additional environment considerations should be added to the [platform compatibility table](https://meshery.layer5.io/docs/installation).

**Comment by firstladymb** [comment]
This was resolved by https://github.com/meshery/meshery/pull/453. However, the link will not work until https://github.com/meshery/meshery/pull/454 is merged. We should be able to close this though :)
