### ISSUE TITLE
Update docs site footer with current social buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#394]
**Enhancement Description**
Update [the current docs footer](https://github.com/layer5io/meshery/blob/master/docs/_includes/footer.html) to use [the same social buttons](https://github.com/layer5io/layer5/blob/master/_includes/partials/hori-social.html) as those used on layer5.io as shown [in this screencast](https://youtu.be/FZ4Mi68CsGM).

**Comment by anusha5695** [comment]
Hi @leecalcote : Is this still up for grabs?

**Comment by leecalcote** [comment]
Hi @anusha5695, I missed your question earlier. Yes, help here would be very nice. @gunjanmimo has given this a try in PR #432, which is good. However, hasn't quite hit the mark yet in terms of the original ask to use [the same social buttons](https://github.com/layer5io/layer5/blob/master/_includes/partials/hori-social.html) as those used on layer5.io as shown [in this screencast](https://youtu.be/FZ4Mi68CsGM). 

You're help here would be much appreciated!

**Comment by schillingjerrid** [comment]
@leecalcote I can work on this if you want. Do we want the tooltips? They won't really work going below the buttons like they do on the layer5.io site but I can put them above the buttons.

**Comment by leecalcote** [comment]
@schillingjerrid yes, sir. Please.

**Comment by schillingjerrid** [comment]
@leecalcote Yes to the tooltips?

**Comment by leecalcote** [comment]
@schillingjerrid Yes, if the tooltips fit, it would be great to have them - whether they are below or above the buttons.

**Comment by schillingjerrid** [comment]
@leecalcote Sounds good to me.

**Comment by raghavaggarwal99** [comment]
Doesn't #527 solve this issue?

**Comment by schillingjerrid** [comment]
Hey guys, sorry I haven't been working on this recently. I have a branch with the changes made but I've been on holiday for the last few weeks and haven't finished testing it. @raghavaggarwal99 's branch looks good! I'll un-assign myself from the issue.

**Comment by leecalcote** [comment]
@schillingjerrid no problem. Thanks for signaling here. We're very pleased to get what time of yours that we can. :)
