### ISSUE TITLE
Docs: "Edit this page" hyperlink on docs is incorrectly linked

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#402]
**Description**
When users click on "Edit this page" in the Meshery Docs, they are directed to a 404 page on github.com.

**Expected Behavior**
Users should be directed to the specific markdown file in github that correlates to the page on which they clicked "Edit this page".

// @nunix

**Comment by leecalcote** [comment]
Should be a quick fix. @venilnoronha, if you're inclined, feel free to grab this one.

**Comment by firstladymb** [comment]
@leecalcote Mind if I take this one? It looks like we need to swap  with `/edit/master/` with `/blob/master/docs/` here: [https://github.com/meshery/meshery/blob/master/docs/_includes/editable.html](https://github.com/meshery/meshery/blob/master/docs/_includes/editable.html)

**Comment by leecalcote** [comment]
Hi @firstladymb. That would be lovely. Yes, please.

**Comment by firstladymb** [comment]
Yay! I'm loving all your documentation for contributions. Thanks so much!

**Comment by firstladymb** [comment]
Submitted the PR! 5 minutes to figure out how to fix the problem. 2 hours to figure out how to use Git and Github. This is why I need practice!

**Comment by leecalcote** [comment]
@firstladymb ha! Wow. Shazam, that was fast. :)

**Comment by leecalcote** [comment]
@firstladymb, thank you so much for jumping in! We'd love to have you engage in the community here. Please join this Slack (http://slack.meshery.io) and we'll get you better introduced and oriented to the projects.

An example area of help needed is within /docs. The Meshery docs site was just updated with a new Jekyll theme this past week (the one you're currently seeing). There are a [number of related fixes](https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) that are needed, if you interested (pretty please). ;)
