### ISSUE TITLE
Docs: "Releases" page is out of date.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#403]
**Current Behavior**
Users see invalid release numbers and corresponding descriptions of [releases in the docs](https://meshery.layer5.io/docs/installation/releases).

**Desired Behavior**
Release numbers and descriptions need to be copied from [releases in meshery repo](https://github.com/layer5io/meshery/releases) and pasted into the [Releases page here](https://github.com/layer5io/meshery/blob/master/docs/pages/installation/releases.md).

**Comment by schillingjerrid** [comment]
I'll take this issue.

**Comment by leecalcote** [comment]
Awesome. Thank you, @schillingjerrid!

**Comment by schillingjerrid** [comment]
I think it would make more sense top sort these in descending order chronologically, similar to the releases page on github.

What do you think? I'm not opposed to leaving it in ascending order. This is just my suggestion.

**Comment by leecalcote** [comment]
@schillingjerrid, descending order makes much sense to me. Conceptually, most visitors will be interested in details of the latest versions, and so, we'd do well to present those first. Good suggestion.
