### ISSUE TITLE
Add GitHub Issue Template for docs issues

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#408]
**Current Behavior**
There is no template for documentation issues - https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE

**Desired Behavior**
A docs template should exist, be assigned the [docs](https://github.com/layer5io/meshery/labels/docs) label and have these resources listed:

```
---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
```

**Comment by welenofsky** [comment]
I tried to attack this one in PR #420

**Comment by leecalcote** [comment]
So very much appreciated, @welenofsky. Quality work. 👍
