### ISSUE TITLE
Docs: docs/README.md update needed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#409]
**Description**
The /docs/README.md is outdated and needs to be update to reflect the Meshery project.

**Expected Behavior**
The README.md should have:
- [ ] a screenshot relevant to Meshery.
- [ ] a link to and description the Meshery documentation contribution instructions.
- [ ] an example of how to build the docs locally (and a link to Jekyll for reference).
- [ ] a link to the [Meshery Documentation](https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit) Google Doc.
---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by schillingjerrid** [comment]
I'll grab this one!

**Comment by schillingjerrid** [comment]
@leecalcote Would you like to see a screenshot of the docs for Meshery or of the Meshery dashboard itself?

**Comment by firstladymb** [comment]
@schillingjerrid I would use a screenshot of the docs site since it's the docs readme. It can always be changed!

**Comment by leecalcote** [comment]
@schillingjerrid thanks much for taking this issue on ( 👍 ) and for being considerate of the screenshot to include.

I concur with @firstladymb's suggestion that given that this README is documentation-specific, a screenshot of the docs site is most appropriate.

**Comment by schillingjerrid** [comment]
PR has been merged into master. Closing this issue.
