### ISSUE TITLE
Docs: Split each "platform" section into its own page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#419]
**Current Behavior**
Each "platform" section on the [Installation page](https://meshery.layer5.io/docs/installation) needs to be removed from the Installation page and have a new page dedicated to that respective platform created.

**Desired Behavior**
The "Quick Start" section is the last section on the page. Each of the "Platform" sections are moved to their own pages.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by schillingjerrid** [comment]
I'll work on this issue.

**Comment by leecalcote** [comment]
Excellent, @schillingjerrid. :) Thank you.

**Comment by leecalcote** [comment]
Very cool, @schillingjerrid. Nice work!

**Comment by leecalcote** [comment]
@schillingjerrid we'd love to have you engage in the community here. Please join this Slack (http://slack.meshery.io) and we'll get you better introduced and oriented to the projects.

**Comment by schillingjerrid** [comment]
Thank you for the invite.
