### ISSUE TITLE
Docs: Enhance the "Create Documentation Issue" hyperlink

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#422]
**Current Behavior:**
The current "Create Documentation Issue" in the [Meshery docs](https://meshery.layer5.io/docs) uses the [question.md GitHub issue template](https://github.com/layer5io/meshery/blob/master/.github/ISSUE_TEMPLATE/question.md). 

**Screenshot**
<img width="1240" alt="Screen Shot 2019-10-27 at 8 05 32 PM" src="https://user-images.githubusercontent.com/7570704/67645217-4df3a580-f8f5-11e9-8e6a-01062745a15c.png">

**Requested Behavior:**
The  "Create Documentation Issue" link should be updated to use the [documentation.md template](https://github.com/layer5io/meshery/blob/master/.github/ISSUE_TEMPLATE/documentation.md) and to assign the "docs" label. It should use this URL:

```
https://github.com/layer5io/meshery/issues/new?assignees=&labels=docs&template=documentation.md&title=Docs:
```

Please update the current hyperlink with the new one above.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by firstladymb** [comment]
I'll take this one!
