### ISSUE TITLE
Add capability to support: mesheryctl version

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#434]
**Desired Behavior**
We need the capability to print the version number when folks run `mesheryctl version`. 
The version number should match the version numbers available on GitHub.
We should be able to do this with `ldflags` from goreleaser while building.

```
    ldflags:
     - -s -w -X main.build={{.Version}}
```

For this to work:
- we should add a `var build string` to the main.go file (outside `func main`).
- add a cobra command to print the version number which should print the value from this variable.

**Comment by anandrkskd** [comment]
Okay understood the enhancement and I am on it.
Thank you @girishranganathan sir

**Comment by anandrkskd** [comment]
fixed with #497
