### ISSUE TITLE
mesheryctl: Include logic for handling errors in `start` and `stop`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#435]
**Description**
There are a number of unhandled errors in `mesheryctl` that should be handled in a graceful way. `mesheryctl` source code is here - https://github.com/layer5io/meshery/tree/master/mesheryctl

**Expected Behavior**
All errchecks should pass.

```
mesheryctl/cmd/start.go:40:12:	os.Mkdir(mesheryFolder, 0777)
mesheryctl/cmd/start.go:79:72:	exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Start()
mesheryctl/cmd/start.go:82:41:	exec.Command("xdg-open", url).Start()
mesheryctl/cmd/start.go:85:37:	exec.Command("open", url).Start()
mesheryctl/cmd/stop.go:33:12:	os.Mkdir(mesheryFolder, 0777)
```

**Reference**
https://github.com/layer5io/meshery/commit/e8b20ff18fc7a05b0e4818fbe5843a09c138e7d5/checks?check_suite_id=285379602

**Comment by supra08** [comment]
Hi @leecalcote , I would like to take up this issue.

**Comment by leecalcote** [comment]
@supra08, yes, please. That would be great.
