### ISSUE TITLE
Docs: Search is broken

### ISSUE THREAD

**Issue by firstladymb** [layer5io/meshery#438]
The search page is broken . 

Expected URL: https://meshery.layer5.io/docs/search/?q=test
Actual URL: https://layer5io.github.io/meshery/search/?q=test. 

I'm looking into it!

**Comment by leecalcote** [comment]
Yikes!

**Comment by firstladymb** [comment]
It works in my branch, so it seems to be something with the server configuration. It's a 301 redirect and it only appears to happen for `https://meshery.meshery.io/docs/search/`; bad URLs will load the 404. Maybe something to do with the recent site change?

![image](https://user-images.githubusercontent.com/26513119/67740452-7d7cdd80-f9db-11e9-9d3c-083ca0a1cce8.png)

**Comment by leecalcote** [comment]
@venilnoronha thoughts?

**Comment by girishranganathan** [comment]
@firstladymb we debugged this issue to NOT be associated with Jekyll or the theme used. It turned out to be a config issue elsewhere. We have taken care of this now.
Thanks a lot for your interest and time spent on this issue.
