### ISSUE TITLE
Setup project badges

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#44]
Using https://shields.io, let's add a few pertinent project badges to each of the Meshery repos. 

Crossplane is a good ([example project](https://github.com/crossplaneio/crossplane/blob/master/README.md
)).

**Comment by leecalcote** [comment]
@venkatasankarapu interested?

**Comment by leecalcote** [comment]
@venkatasankarapu Here's an example badge that would work well - ![Docker Pulls](https://img.shields.io/docker/pulls/meshery/meshery.svg)

If it's handy, here's the main gray color used in Meshery today - #647881.

**Comment by leecalcote** [comment]
@venkatasankarapu I popped two of these into the meshery repo. We'll want to get a few others and add all of them to each of the other meshery repos consistently (as appropriate).

@girishranganathan what do you think of this one? [![Go Report Card](https://goreportcard.com/badge/github.com/meshery/meshery)](https://goreportcard.com/report/github.com/meshery/meshery)

**Comment by girishranganathan** [comment]
Sure, will be a good start :)

**Comment by leecalcote** [comment]
@subhamkrai I'm not sure if @venkatasankarapu will have time to execute on this issue. If not, you might want to take a crack at it. Ultimately, we'll want to have the same set of project badges listed uniformly across each of the "meshery-...." repos.

**Comment by leecalcote** [comment]
@subhamkrai will you look at copying the project badges from the meshery repo to each of the meshery adapter repos?

**Comment by subhamkrai** [comment]
Sure @leecalcote

**Comment by leecalcote** [comment]
@subhamkrai following up on your last comment - yes, you're right, I'm looking for the combined set of project badges from meshery/meshery and from meshery/meshery to be proliferated across all meshery repos.

**Comment by leecalcote** [comment]
@subhamkrai to wrap up this issue, these [badges](https://github.com/meshery/meshery/commit/57f73ca6c96a49fec04a9ae253803657a93904b4#diff-04c6e90faac2675aa89e2176d2eec7d8R3-R10) need to be added to each of the [meshery repos](https://github.com/search?q=topic%3Ameshery+org%3Ameshery&type=Repositories)

**Comment by leecalcote** [comment]
@subhamkrai took care of each of these.
