### ISSUE TITLE
Ability to deploy Meshery on Istio

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#441]
**Current Behavior**
Meshery does have deployment artifacts to deploy Meshery and its ecosystem on Kubernetes. There is also a Istio yaml which contains virtual service and gateway definition.

**Expected Behaviour**
We need to ensure the deployment succeeds and works the expected way on Istio.

**Comment by girishranganathan** [comment]
We were able to test Meshery and its adapters on Istio. The change that came out of this session was the Gateway port change from 8080 to 80 to avoid adding more ports to the ingress gateway service.

**Comment by leecalcote** [comment]
@girishranganathan this was closed as a duplicate of #442, right?
