### ISSUE TITLE
Octarine: Expose adapter in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#447]
**Current Behavior**
The Meshery adapter for Octarine is now stable and included in the default Compose file.

**Desired Behavior**
The Octarine adapter now needs to be exposed in the Meshery UI.

**Comment by leecalcote** [comment]
// @thehh1974

**Comment by leecalcote** [comment]
I'll grab this one.

**Comment by thehh1974** [comment]
Thanks! I thought I had it all figured out on Friday, but somehow when I tested it the logo did not look right.

**Comment by leecalcote** [comment]
@thehh1974 Yeah, no... I bump my head on this same issue with some frequency. Here we are!

New v0.3.0 release publishing now:
<img width="1265" alt="Screen Shot 2019-11-10 at 5 18 29 PM" src="https://user-images.githubusercontent.com/7570704/68552598-409ee680-03de-11ea-87c9-6f7cf79932ac.png">

**Comment by thehh1974** [comment]
Awesome!

**Comment by leecalcote** [comment]
Fixed in #446
