### ISSUE TITLE
mesheryctl: Add support for `mesheryctl update` to upgrade mesheryctl itself

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#449]
**Current Behavior**
Currently `mesheryctl update` downloads new versions of the Meshery containers as described in the [Meshery Installation & Packaging](https://docs.google.com/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit#heading=h.hxpazjese5dc) document.

**Desired Behavior**
Ideally, `mesheryctl update` will also upgrade the binary itself (displacing itself with the latest version of the binary).

**Comment by anandrkskd** [comment]
I will be working on this issue.

**Comment by anandrkskd** [comment]
In the new updateCmd code I am facing a permission issue [My Working Branch](https://github.com/anandrkskd/meshery/tree/bug/anandrkskd/449)
**behaviour**

- update command detect the client os and arch the downloads the suitable latest mesheryctl zip for the system.
- downloaded file is stored in users **.meshery** directory in HOME of user,
- files are then unzipped to "/usr/local/bin/" dir.

**Comment by leecalcote** [comment]
@NupurThakur27 have a look at `gh` and how it provides provides this functionality. 

```
A new release of gh is available: 0.7.0 → v0.8.0
https://github.com/cli/cli/releases/tag/v0.8.0
```

https://github.com/cli/cli/blob/master/update/update.go

**Comment by nitishm** [comment]
@leecalcote want me to start working this?

**Comment by leecalcote** [comment]
@nitishm that'd be great, yes.

**Comment by KarenEfereyan** [comment]
@nitishm can I work with you? I really want to learn how this is done. It seems more than just a documentation issue. More like code involved.

**Comment by anirudhjain75** [comment]
Is this up for grabs ? @leecalcote

**Comment by anirudhjain75** [comment]
Regarding having mesheryctl show latest version as message / notification to user on invoking commands. gh makes uses of github release for cli repo and manages version using github api. You can try executing GET req on `https://api.github.com/repos/meshery/meshery/releases/latest`. This API results the latest release results of meshery repo. The issue with using the same approach as gh is that `mesheryctl` doesn't have its own repo which makes version management a bit tricky.

**Comment by anirudhjain75** [comment]
`mesheryctl` for now seems to be using the meshery version as it version tag. so things should be fine with making an implementation to check for updates similar to gh cli.

**Comment by anirudhjain75** [comment]
@leecalcote if the above is to be implemented. drop a message and I'll get it done right away :)
