### ISSUE TITLE
mesheryctl: Make `mesheryctl init` an internal function only; Do not expose `init` as a command line operation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#450]
**Current Behavior**
Users can directly invoke `mesheryctl init`. This command is intended for use by other mesheryctl commands, not for use by users.

See [Meshery Installation & Packaging](https://docs.google.com/a/layer5.io/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit?disco=AAAADSnE2DA) for more information.

**Desired Behavior**
Hide `init` from user invocation.

**Comment by jesuslerma** [comment]
Hi, Lee.

When we're going to call the `init` command by start and update?

**Comment by jesuslerma** [comment]
We can name that function to something like: `installPrereq` and move it to `vars.go`.

**Comment by leecalcote** [comment]
@jesuslerma spot on. Yes, your suggestion is ideal.

**Comment by leecalcote** [comment]
> When we're going to call the `init` command by start and update?

Given `init`'s current functionality, the most appropriate time to call it is upon finding that certain prerequisites are missing (namely `docker-compose` at the moment).

**Comment by leecalcote** [comment]
@jesuslerma @anandrkskd how did we make out on this issue?
