### ISSUE TITLE
Merge MeshConfigComponent.js and MeshOutClusterConfigComponent.js to remove duplicate code

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#461]
**Description**
MeshConfigComponent.js was replicated to create a new component MeshOutClusterConfigComponent.js to make the settings page work with the new UX for the page. Both the components now have a lot of duplicate code.

**Expected Behavior**
We should just probably update MeshConfigComponent.js in a way that it can be made to behave in different ways based on the different props given to it. 
GrafanaCustomChart component is an example. I am pretty sure we have a few more examples of such components.

**Comment by leecalcote** [comment]
Completed. ✔️
