### ISSUE TITLE
Docs: Convert list of network ports to a table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#469]
**Current State:**
Meshery's adapters and the network ports that they use are documented on the Architecture page - https://meshery.layer5.io/docs/architecture

**Desired State:**
Instead of a bulleted list, readers will be able to quickly digest a two column, tabular format of these same information.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by schillingjerrid** [comment]
I'll take this issue

**Comment by leecalcote** [comment]
Good! Thank you, @schillingjerrid!

**Comment by leecalcote** [comment]
Nice work! :)
