### ISSUE TITLE
Docs: Incorporate makefile commands from /docs/Makefile into /Makefile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#472]
**Current State:**
The Meshery [Makefile](https://github.com/layer5io/meshery/blob/master/Makefile) does not have a `make docs` command to build the documentation site.

**Desired State:**
Both the Meshery Makefile and the Docs Makefile have commands to build and run the site.

- [ ] The The Meshery [Makefile](https://github.com/layer5io/meshery/blob/master/Makefile) has a `make docs`.
- [ ] The Docs [Makefile](https://github.com/layer5io/meshery/blob/master/docs/Makefile) should remain as-is (for convenience of working on docs).

**Comment by raghavaggarwal99** [comment]
You can see the pull request #480
