### ISSUE TITLE
NSM: Improve usefulness of NSM successful deployment notification

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#474]
**Current Behavior**
The Meshery adapter for NSM is now stable and included in the default Compose file. When a user deploys NSM, they receive notification of successful deployment, however, the notification doesn't give any details of the deployment.

**Desired Behavior**
Successful deployment notification should include details like:
1. link to NSM administrative interface
1. list of available CNFs
1. version number of NSM
1. version number of dataplane forwarder and nsm manager

**Comment by raghavaggarwal99** [comment]
Hi @leecalcote can you explain the issue a little bit. Do you want just static text to be added when the adapter is pinged?
"Nsm is deployed and ....."
