### ISSUE TITLE
Update description for "Custom Config" adapter operation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#475]
**Current Behavior**
Meshery provides a "Custom Config" operation for all adapters wherein Meshery allows users to push custom configuration to each service mesh. The description of this operation is:

  "For the brave of hearts who want to speak YAML to your cluster directly".

**Desired Behavior**
The description of the "Custom Config" operation needs updated to be:

  "Customize the configuration of your service mesh."

**Screenshot**
<img width="1430" alt="Screen Shot 2019-11-12 at 2 25 54 PM" src="https://user-images.githubusercontent.com/7570704/68708020-7a93f800-0558-11ea-81d7-909fee5dbef0.png">

**Comment by leecalcote** [comment]
Hi @neilong31! Would you like to tackle this one as well? It would be much appreciated.

**Comment by neilong31** [comment]
@leecalcote Yeah I'd love too! I'll have a PR up by tomorrow night.

**Comment by leecalcote** [comment]
Awesome. 👍 Thank you, @neilong31!
