### ISSUE TITLE
[UI] Validate active user session prior to allowing operations to be invoked

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#488]
**Description**
Upon running a performance test, the following error is presented in the UI and seen in the logs. This happens because the user doesn't have an active session.
 
Meshery log:
```
meshery_1           | time="2019-11-12T17:27:03Z" level=error msg="error: unable to persist the load test results: error while sending results - Status code: 401, Body: unauthorized\n"
```
**Expected Behavior**
Meshery should verify that the user has an active session prior to allowing users to invoke operations in the UI, so that they don't get errors like this one.

**Screenshots**
<img width="672" alt="Screen Shot 2019-11-12 at 11 27 44 AM" src="https://user-images.githubusercontent.com/7570704/68694916-a9ea3b00-053f-11ea-942f-e4414a1f9879.png">

**Comment by ashiscs** [comment]
Sir @leecalcote , how can i approach this issue?

**Comment by leecalcote** [comment]
Completed.
