### ISSUE TITLE
Publish scoop app manifest to "scoop-bucket" repo

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#490]
**Desired Behavior**
We want the release process to publish a scoop app manifest so that Windows users can use [scoop](https://scoop.sh) to install `mesheryctl`.

We have created a new repository to host the scoop app: `scoop-bucket`

[Here](https://goreleaser.com/scoop/) is the goreleaser section which describes how to go about this.

**Comment by gunjanmimo** [comment]
@girishranganathan sir, I want to work on this issue
