### ISSUE TITLE
Update "help wanted" link in all READMEs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#492]
**Current Behavior**
Under the [Community section](https://github.com/layer5io/meshery#community) in each Meshery-related repository, the link used in this statement:

"_Not sure where to start?_ Grab an open issue with the help-wanted label."

only refers to issues with the Meshery repository.

**Desired Behavior**
The "help wanted" link should include issues across all Layer5 repositories. Each repository's README should use the following link for perusing "help wanted" issues:

```https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+```

**Comment by leecalcote** [comment]
@jesuslerma if you're inclined to grab this one, it may serve to familiarize you with the full extent of the Meshery project's code base (or at least repos), while enhancing the community contribution experience.

**Comment by jesuslerma** [comment]
Sure! Let me grab this one.

**Comment by jesuslerma** [comment]
Just to be sure, let me list the related projects:
- [ ] [xmeshery-istio](https://github.com/layer5io/meshery-istio)
- [ ] [meshery-adapter-template](https://github.com/layer5io/meshery-adapter-template)
- [ ] [meshery-nsx-sm](https://github.com/layer5io/meshery-nsx-sm)
- [ ] [meshery-nsm](https://github.com/layer5io/meshery-nsm)
- [ ] [gowrk2](https://github.com/layer5io/gowrk2)
- [ ] [meshery-kuma](https://github.com/layer5io/meshery-kuma)
- [ ] [meshery-consul](https://github.com/layer5io/meshery-consul)
- [ ] [meshery-app-mesh](https://github.com/layer5io/meshery-app-mesh)
- [ ] [meshery-linkerd](https://github.com/layer5io/meshery-linkerd)
- [ ] [meshery-cpx](https://github.com/layer5io/meshery-cpx)
- [ ] [meshery-octarine](https://github.com/layer5io/meshery-octarine)
- [ ] [meshery-maesh](https://github.com/layer5io/meshery-maesh)

After each of the three checkboxes have been marked, we can close this one, right?

**Comment by leecalcote** [comment]
@jesuslerma great question. @girishranganathan updated the list with a couple more. I think this is the whole set.

**Comment by leecalcote** [comment]
@jesuslerma we'll want to ensure that the "help wanted" link in the welcome guide is updated, too.

**Comment by jesuslerma** [comment]
Hi @leecalcote I'm working on this issue. I can see that some projects don't have a community section. I'm going to add it but I think that it would be great to have the next content:

```
Community
This project is community-built and welcomes collaboration! See the Layer5 Contributors Welcome Guide.
Not sure where to start? Grab an open issue with the help-wanted label.
```
Is there a *Layer5 Contributors Welcome Guide*? Or we should use the *Meshery Contributors Welcome Guide* on each one?
