### ISSUE TITLE
Decommission Meshery bash script

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#493]
**Current Behavior**
The recently displaced `meshery` bash script currently sits in this repo's root folder under the name "[meshery.old](https://github.com/layer5io/meshery/blob/master/meshery.old)". Now that `mesheryctl` has displaced this script. The time has come to delete this file.

**Desired Behavior**
`mesheryctl` should perform all of its current functions with accuracy, with an acceptable user experience and on each of the three supported OSes:

Linux
  - [x] (@anandrkskd)
  - [ ] (@jsedano)

MacOS
  - [x] (@leecalcote)
  - [ ] (@jsedeano)

Windows 
  - [x] (@nunix) 
  - [ ] (@jsedano)

(@jesuslerma, you may wish to jump in here as well)

After each of the three checkboxes have been marked, please delete the "meshery.old" file from this repo with a PR.

**Comment by jsedano** [comment]
Hey @leecalcote can I take this one? @jesuslerma will guide me around

**Comment by leecalcote** [comment]
That would be fantastic, @jsedano. Yes, please.

**Comment by nunix** [comment]
soo 😄 overall it's working great and only few small glitches remain (here is the list I found so far):
1. the `make` command in Mesheryctl directory outputs a "non-Windows" name at the end. An extra: `mv mesheryctl mesheryctl.exe` is needed

2. the `mesheryctl status` has just a `\n` in the timestamp line:
time="2019-11-13T21:24:44+01:00" level=info msg="Meshery containers status . . .\n"

everything else really worked as intended:
1. `mesheryctl status` now displays a nice looking table
![image](https://user-images.githubusercontent.com/905874/68801880-33435f80-065d-11ea-8753-2880d0fe9dc2.png)

2. the default browser opens on the correct page (no more login when connected already once ⭐️ )

3. start/stop/cleanup/status work as intended

great work team ⭐️

**Comment by leecalcote** [comment]
Here is a short overview of the `meshery` bash script and exercise to validate that the same functionality and user experience is upheld in `mesheryctl` as we finalize the removal of `meshery` bash script. https://youtu.be/LMJD3HpLb8k

**Comment by leecalcote** [comment]
@nunix excellent work. :) The two issues that you've uncovered are worthy of having GitHub issues opened in order to track a fix for them. Will you kindly open these two issues?

**Comment by nunix** [comment]
Hi @leecalcote 

here are the issues (I keep them here just for a centralised overview):
1. Mesheryctl `make` issue: #494
2. Mesheryctl `status` issue: #495

**Comment by leecalcote** [comment]
@nunix thank you. 👍

**Comment by anandrkskd** [comment]
mesheryctl should perform all of its current functions with accuracy, with an acceptable user experience on Linux system.

**Comment by leecalcote** [comment]
Given the tests complete here, I think we can call this issue safely completed.
