### ISSUE TITLE
[Windows] Mesheryctl make scripts does not have the extension

### ISSUE THREAD

**Issue by nunix** [layer5io/meshery#494]
**Description**
When building `mesheryctl` from source on Windows, the output binary is missing the ".exe".
Still, the binary is correctly build as a Windows one, and an additional `mv mesheryctl mesheryctl.exe` can be considered as the workaround

**Expected Behavior**
when running `make` in Mesheryctl directory, the output binary should be `mesheryctl.exe` when building the Windows binary.

**Screenshots**
Before the rename, Windows will not know how the binary should be opened:
![image](https://user-images.githubusercontent.com/905874/68953134-8e8e6280-07c1-11ea-85fb-020e568a1736.png)

After the rename, Mesheryctl runs fine:
![image](https://user-images.githubusercontent.com/905874/68953161-9fd76f00-07c1-11ea-907d-92ed70b117d7.png)

**Enviroment:**
 - OS: Windows 10
 - Browser: MS Edge Chromium
 - Device: laptop

---
[Optional] **To Reproduce**
1. Git clone meshery repo
2. Go to meshery/mesheryctl
3. Run `make`

[Optional] **Additional Context**
Any additional information can be provided if needed 😄

**Comment by anandrkskd** [comment]
fixed by #498
