### ISSUE TITLE
Change text on Service Mesh Settings page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#496]
Change this text to: "You are all set to manage service meshes".

<img width="1095" alt="Screen Shot 2019-11-15 at 5 55 04 PM" src="https://user-images.githubusercontent.com/7570704/68983576-3eb79780-07d1-11ea-9237-42b009371057.png">

**Comment by neilong31** [comment]
Hi @leecalcote ! I like to work on this please.

**Comment by leecalcote** [comment]
@neilong31 that would be fantastic. 👍  There are instructions for building Meshery and it’s UI components in the contributors.md file. There’s a guide for newcomers in there, too. Also, please jump into http://slack.meshery.io, so you can better connect with the community. It’ll be great to have you! 😀
