### ISSUE TITLE
Transition plan to Grafana from AO

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#5]
We need to investigate the possibility to do a few things with Grafana programatically:
- create a dashboard with charts
- list the charts in a dashboard
- for a chart, construct html code to embed the chart in a html page

**Comment by yogi4** [comment]
@girishranganathan Sorry it took me long to address this, and sorry about the confusion. 

For embedding charts , Grafana provides react controls 
Grafana 6.0 provides React Panels and integrations points 

http://docs.grafana.org/guides/whats-new-in-v6-0/#react-panels-query-editors
I'm in the process of creating a quick design for this.

**Comment by leecalcote** [comment]
@yogi4 nice. Is this an open source capability or “enterprise” version only?

- Lee

Sent from my mobile

________________________________

**Comment by yogi4** [comment]
@leecalcote This is opensource capability.

**Comment by girishranganathan** [comment]
@yogi4 good findings.

- The SDK is definitely a good find bcoz it covers several of their REST APIs. Hope it will provide a way to get the URL for a live chart which we can embed.

- Regarding the react stuff, I don't think this is the right thing we are looking for though. This is an excerpt from the link: 

  > Starting in v6.0 Panels and Data source plugins can be written in React using our published @grafana/ui sdk library.

  My understanding is that Grafana plugins are a way to extend Grafana itself. I am not sure if they will help borrow parts of Grafana into an external system.

**Comment by yogi4** [comment]
> * My understanding is that Grafana plugins are a way to extend Grafana itself. I am not sure if they will help borrow parts of Grafana into an external system.
@girishranganathan,  I was under the impression that  we would be running a grafana server to render these dashboards, and using react to render that html. 

However the other approaches would be sharing a snapshot of those dashboards or panels or using an image that was rendered ( we miss out on interactive panels). 

P.S: There is high chance that I potentially misunderstood the requirements. I will sync up with you tomorrow to make sure I didn't deviate much :).
