### ISSUE TITLE
Grafana: Improve error response when missing required API key

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#502]
**Current Behavior**
In the Settings-->Metrics screen... When trying to connect to a Grafana endpoint that requires and API key, if the API key is not provided or is incorrect, the following error is shown (see screenshot). This error is uninformative.

**Desired Behavior**
Give specific error message pointing to the actual problem (missing or invalid API key) and what the user should do to fix.

**Screenshot**
<img width="439" alt="Screen Shot 2019-11-16 at 8 39 58 PM" src="https://user-images.githubusercontent.com/7570704/69002272-9cbbac00-08b1-11ea-93e7-b2dfa3d15629.png">

**Comment by Nikhil-Ladha** [comment]
@leecalcote sir for this is there any particular format of an API key that we can check?

**Comment by leecalcote** [comment]
@Nikhil-Ladha good question. In this case, the user will have to provide an API key. Depending upon how they have deployed and configured their Grafana, the user may not have to provide an api key. For example, the Graham’s instance that deployed with Istio, does not require an API key in order to for Meshery to connect to it. But, some users configure their Graham’s deployment to require one, so when Meshery is attempting to connect, if it is unable to because the user didn’t enter a key into Meshery (in the Metrics screen), then e should detect that specific issue (error code) and tell the user something more useful than “there was an error”. 

I hope this helps. We can review on a call, if that helps.

**Comment by leecalcote** [comment]
@Nikhil-Ladha @girishranganathan I think we addressed this issue, but can't quite recall...

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha @girishranganathan I think we addressed this issue, but can't quite recall...

Indeed, yes sir😅
