### ISSUE TITLE
Add Meshery adapter for CPX to list of adapters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#506]
**Current State:**
The list of adapters is missing an entry for CPX.

The [CPX adapter](https://github.com/layer5io/meshery-cpx) should be listed as an alpha adapter with link to its the [adapter section of the Meshery documentation](https://meshery.layer5.io/docs/installation/adapters).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@dheerajng you might consider grabbing this one.

**Comment by dheerajng** [comment]
Created a [PR](https://github.com/layer5io/meshery/pull/517) for the same.

**Comment by leecalcote** [comment]
Nice work, @dheerajng!
