### ISSUE TITLE
Docs: New Meshery releases need posted to Releases docs page

### ISSUE THREAD

**Issue by l5io** [layer5io/meshery#509]
**Current State:**
The Releases page lists releases up to v0.2.4.

**Desired State:**
The Releases page should list all releases up to v0.3.2

Updating the Release page needs to be automated as part of the release process.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@schillingjerrid hopefully, we'll find a way to get these manual updates automated. This request is being tracked in #510.
