### ISSUE TITLE
Create Helm chart for Meshery

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#514]
**Current Behavior**
Meshery may be deployed using `mesheryctl`, or using `docker-compose` or using `kubectl`.  For users who use Helm, there is no chart for Meshery currently.

**Desired Behavior**
Capture in design consideration in [Design Doc].(https://docs.google.com/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit#heading=h.45f30knxz69z
1. Create a Helm chart for Meshery.
1. Create an entry in [Helm Hub](https://hub.helm.sh).

**Comment by Aisuko** [comment]
@gunjanmimo Thanks a lot.

**Comment by Aisuko** [comment]
Hey guys, Please kindly check the link below the https://github.com/Aisuko/meshery/tree/feat/meshery-chart/install

The project includes the draft charts that something needs to confirm already mark with # TODO in the code.  I believe it's not a good time to PR this. So, if you have any advice or questions feel chat with me. 
If you the draft contents approve by you guys I will finish `mesherylinkerd ` subchart and take a PR with this.

**Comment by Aisuko** [comment]
@leecalcote Hi Lee, If we want to add the Meshery chart to Helm Hub maybe we need to create a new GitHub project(https://github.com/helm/hub/blob/master/Repositories.md) please kindly check the document. We need a project URL that only includes the Helm chart.

**Comment by leecalcote** [comment]
@Aisuko, interesting. Sounds good. If that's what we need to do, I'll make it happen pronto. 

I see some remotely-hosted repositories that point to a publicly available `index.yaml`, which points to charts located in the projects main repo. Flagger is an example - https://flagger.app/index.yaml. I'm not opposed to creating a separate repo, but am trying to make sense of when one is truly necessary / beneficial. Alternatively to creating a separate repo, would we instead publish a public `index.yaml` and point back to the main repo (meshery/meshery)? We could host this file in a long-lived `gh-pages` branch in the meshery/meshery repo. (e.g. https://github.com/weaveworks/flagger/tree/gh-pages/)

**Comment by Aisuko** [comment]
I know what's your mean. But as Meshery project grows up there may support many service mesh. You can think of lots of adapter for them. Just like `meshery-nsm` etc. Every project needs its own chart. If every project we need to open a new branch for the chart may complex for maintaining.

**Comment by Aisuko** [comment]
We can follow the example https://helm.sh/docs/topics/chart_repository/#github-pages-example do this.

**Comment by Aisuko** [comment]
As we discussed, We can follow the Flagger chart https://flagger.app/index.yaml.  as our chart repo.  And share the URL to Helm.hub. @leecalcote

**Comment by Aisuko** [comment]
@gunjanmimo Hi, gunjanmimo. As I and Lee discussed, `Meshery-nsm` may not have itself chart. The adapter just provides value to Meshery.

**Comment by leecalcote** [comment]
Pull request for Helm Hub entry - https://github.com/helm/hub/pull/249

**Comment by leecalcote** [comment]
Done! 😄
