### ISSUE TITLE
Docs: Animate and colorize footer buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#519]
**Current State:**
The buttons in [footer.html](https://github.com/layer5io/meshery/blob/master/docs/_includes/footer.html) of the Meshery documentation are not colorized or animated, but remain static when users hover over them.

<img width="351" alt="Screen Shot 2019-12-14 at 11 41 41 AM" src="https://user-images.githubusercontent.com/7570704/70852474-639e3980-1e67-11ea-97ef-ed188db4c264.png">

Related issue - https://github.com/layer5io/layer5/issues/255

**Desired State:**
Buttons in the documentation footer should behave like those used on layer5.io.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by raghavaggarwal99** [comment]
Hi @ashiscs are you having trouble with this issue? I was looking at it and was thinking I could take it.
