### ISSUE TITLE
Docs: Platform Support for KinD

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#526]
**Current State:**
Meshery is compatible with WSL2 and with KinD, however, in order for Meshery to be able to communicate with KinD additional environment setup is necessary.

**Desired State:**
1. KinD listed as a supported platform.
1. Additional networking configuration documented.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Jekyll schmeckle. Nothing will stop Darth Nunix from taking up this gauntlet.

**Comment by sachincool** [comment]
I was just thinking why kinD is not present in docs XD
WB K3s? k3d?

**Comment by Aisuko** [comment]
👌 I will try to take this.
