### ISSUE TITLE
Hide the readonly field with the adapter url if there is only one adapter for a type

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#529]
**Current Behavior**
Each connected adapter has its own page in Meshery. In these pages there is a read-only field which shows the adapter URL.

**Desired Behavior**
Even though the read-only field with the adapter URL is helpful, we do not want to show it when there is only one adapter of the given type

**Comment by raghavaggarwal99** [comment]
hi @Nikhil-Ladha is this solved?

**Comment by Nikhil-Ladha** [comment]
> hi @Nikhil-Ladha is this solved?

Yes @raghavaggarwal99 it is

**Comment by ashiscs** [comment]
@leecalcote sir, I think this issue is already fixed and needs to be closed!
