### ISSUE TITLE
Docs: Add entry for CPX adapter in Meshery Docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#539]
**Current State:**
The CPX adapter is not currently listed.

**Desired State:**
The CPX adapter should have an entry in the list of adapters and should now be a "beta" adapter.

See https://meshery.layer5.io/docs/installation/adapters

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by schillingjerrid** [comment]
The CPX adapter is already in the docs. I updated it with some new information but this issue can be closed.

**Comment by leecalcote** [comment]
Very good. Thank you, @schillingjerrid
