### ISSUE TITLE
Docs: Broken link to Service Mesh Performance page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#545]
**Current State:**
The [toc.yml](https://github.com/layer5io/meshery/blob/master/docs/_data/toc.yml) seems to have a broken link to the "service mesh performance" page. Broken link: https://meshery.layer5.io/docs/performance

![Screen Shot 2019-12-30 at 10 49 08 PM](https://user-images.githubusercontent.com/7570704/71610449-b6117280-2b56-11ea-899c-b4fb7a06e34a.png)

**Comment by subhamkrai** [comment]
@leecalcote actually I was just looking to these issues and about start can you assign me?

**Comment by ashiscs** [comment]
Sure @subhamkrai you can take this issue!

**Comment by subhamkrai** [comment]
@ashiscs thanks

**Comment by leecalcote** [comment]
Fixed by #548
