### ISSUE TITLE
Docs: Broken link to Supported Platforms page

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/meshery#550]
**Current State:** 
The [https://github.com/layer5io/meshery/blob/master/docs/_data/toc.yml](toc.yml) seems to have a broken link to the "platforms" page.

[(https://meshery.layer5.io/docs/platforms
![Screenshot from 2020-01-03 21-41-20](https://user-images.githubusercontent.com/34444611/71734630-5d9de600-2e72-11ea-8167-00e4a090faf8.png)
](https://meshery.layer5.io/docs/platforms)

**Comment by gunjanmimo** [comment]
@subhamkrai may i take this issue ?
what is expected change ?

**Comment by subhamkrai** [comment]
> @subhamkrai may i take this issue ?
@leecalcote already done with this issues but there are lot more issues you can look on

**Comment by leecalcote** [comment]
Fixed
