### ISSUE TITLE
Docs: meshery installation page not working properly

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/meshery#551]
**Current State:**
Page [https://layer5io.github.io/meshery/installation](https://layer5io.github.io/meshery/installation) is having some problems.

![Screenshot from 2020-01-03 21-49-07](https://user-images.githubusercontent.com/34444611/71734856-e7e64a00-2e72-11ea-93bf-7c837ca0e2bd.png)

**Comment by leecalcote** [comment]
Ignore PR #552. That PR is to fix #550, not this issue.

**Comment by leecalcote** [comment]
@subhamkrai, thanks for filing this. Will you post the steps to reproduce this issue?

**Comment by leecalcote** [comment]
@subhamkrai I think this bug is no longer an issue. Will you verify?

**Comment by subhamkrai** [comment]
Sure I'm on it

**Comment by subhamkrai** [comment]
@leecalcote you are right...we are ready to close these issue
