### ISSUE TITLE
UI: Service Mesh icon color too light to be visible

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#561]
**Description**
The service mesh icons were recently lightened to beautify the navigation menu (which is great), but has had the unintended consequence of washing them out in other UI views.

**Expected Behavior**
Meshery should display icons in context of the background color. We should either have two sets of icons (white w/transparency and full color) or we should manipulate the icon SVG values to suite the background on which they are displayed.

**Screenshots**
<img width="991" alt="Screen Shot 2020-01-05 at 11 42 17 AM" src="https://user-images.githubusercontent.com/7570704/71783749-ed49ae80-2fb0-11ea-9a18-e137b17dd5e0.png">

<img width="871" alt="Screen Shot 2020-01-05 at 11 42 02 AM" src="https://user-images.githubusercontent.com/7570704/71783750-f175cc00-2fb0-11ea-86bc-6b9bc78a838e.png">

<img width="209" alt="Screen Shot 2020-01-05 at 11 41 38 AM" src="https://user-images.githubusercontent.com/7570704/71783758-f76bad00-2fb0-11ea-9d87-fe4e872d3495.png">

<img width="893" alt="Screen Shot 2020-01-05 at 11 41 50 AM" src="https://user-images.githubusercontent.com/7570704/71783766-166a3f00-2fb1-11ea-9822-f8d9a96dc3b7.png">

**Comment by gunjanmimo** [comment]
sir what is the exact file for this issue?

**Comment by leecalcote** [comment]
I'm tagging @raghavaggarwal99 as he can chime in here as well.

**Comment by raghavaggarwal99** [comment]
Hi @gunjanmimo i think it's done, sorry dude.
