### ISSUE TITLE
[UI] meshery page needs to be more responsive

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/meshery#567]
**Description**
As we  squish meshery page to 50% of the screen it's not responsive but if we squish it further then its responsive.
![Screenshot from 2020-01-06 08-55-42](https://user-images.githubusercontent.com/34444611/71794840-4bd26380-3069-11ea-95f8-371f371be205.png)
![Screenshot from 2020-01-06 09-05-19](https://user-images.githubusercontent.com/34444611/71794842-4e34bd80-3069-11ea-9523-42e5a6e9adc3.png)

**Comment by gunjanmimo** [comment]
@subhamkrai what is the exact file for this issue?

**Comment by subhamkrai** [comment]
@Nikhil-Ladha is the right person to ask for

**Comment by Nikhil-Ladha** [comment]
> @subhamkrai what is the exact file for this issue?

I guess it is `MesheryAdapterPlayComponent.js` file.

**Comment by leecalcote** [comment]
@subhamkrai @gunjanmimo this issue rears its ugly head particularly nastily during demonstrations of Meshery on lower resolution projectors. It would great if we could set a new breakpoint.

![Untitled](https://user-images.githubusercontent.com/7570704/74498160-4a385e80-4ea5-11ea-99c7-ec138ba527ff.gif)

**Comment by leecalcote** [comment]
@mcastre may even want to take a crack at this.

**Comment by leecalcote** [comment]
@dhruv0000, perhaps, you could take a crack at this?
