### ISSUE TITLE
Docs: Remove hidden, red anchor

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#575]
**Current State:**
Currently, the Meshery docs will autogenerate an in-page anchor for each heading (e.g. ```<h1>, <h2>```) element on the page, so that users might easily deep link to content. This link is shown as a black chain-looking icon on the lefthand side of the headings.

There is a second, errant anchor that is generated and mostly hidden from view. It is a red paragraph symbol (see screenshot) that need to be removed through reconfiguration of anchor.js library that the Meshery docs is using.

**Screenshot**

<img width="1059" alt="Screen Shot 2020-01-08 at 10 04 34 PM" src="https://user-images.githubusercontent.com/7570704/72037349-6a03b380-3263-11ea-915a-df46fc263154.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@schillingjerrid this one is a pain in the rump. Fortunately, it seems to be right up your alley.

**Comment by schillingjerrid** [comment]
Hey @leecalcote , it looks like this is related to the permalinks.html include. It looks like some of this functionality was added in the past few months. Do we want to remove the permalinks file and its references? It looks like anchor.js is doing permalinking as well so maybe not necessary to include the permalinks file that is creating the red paragraph symbols.

**Comment by leecalcote** [comment]
Oh, interesting, @schillingjerrid. Yes, anchor.js library is more robust than the script in permalinks.html. Good diagnosis and suggestion to remove. 👍

**Comment by schillingjerrid** [comment]
If so I have created a [PR for this issue](https://github.com/layer5io/meshery/pull/586).
