### ISSUE TITLE
Performance: Sorting of "service meshes" list based on adapters present

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#587]
**Current Behavior**
When users visit the Performance test page, they are presented an alphabetically sorted list of service meshes with which they may associate to their test.

**Desired Behavior**
The list of entries in the “Service Mesh” drop-down needs to be a bit more intelligent in that it should rearrange the ordering of the list based on which adapters the user is running. For example, if the user only has the Istio adapter loaded, Istio should be listed first and there should be a small, horizontal line separating service meshes that have adapters loaded and those that don’t.

**Mockup**
<img width="424" alt="Untitled" src="https://user-images.githubusercontent.com/7570704/72267227-4fc03180-35e5-11ea-8159-015fac248771.png">

**Comment by kanishkarj** [comment]
I could work on this with some help.

**Comment by leecalcote** [comment]
@kanishkarj excellent. 👍

**Comment by kanishkarj** [comment]
Please checkout PR #701 .
