### ISSUE TITLE
Preference: Sending of Anonymous Usage Statistics

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#599]
**Current Behavior**
Meshery sends anonymous usage statistics to provide insight and feedback on Meshery's functionality and influence Meshery's roadmap. 

**Desired Behavior**
1. Whether an instance of Meshery sends of anonymous usage statistics should be a user's choice (behavior controlled via user preference).
1. Sending of anonymous usage statistics should be enabled by default.

**Implementation**
1. See `AnonymousUsageStats` in models/preferences.go.
1. Users should be able to control this setting by navigating to their user avatar and clicking the "Preferences" menu item.

---
**Additional context**
[Meshery Performance Management](https://docs.google.com/document/d/1VEvh4qprHbbI3CjeOf9zU9bRhpmhBAVEaPhIO2XDDlc/edit)

**Comment by leecalcote** [comment]
This feature has been implemented, however, a bug needs to be raised, because user selections are not reflected accurately after the user navigates away and comes back to the Preferences screen.

**Comment by Nikhil-Ladha** [comment]
I thought of that when you left the review on the PR and thought of talking about that in the call. Anyways, I will see that.
But just to make it better there is a PR made by @girishranganathan sir for the 404 error on opening that page, so if you can merge that pr then i will go ahead with the work.

**Comment by leecalcote** [comment]
@Nikhil-Ladha oh, very good! @girishranganathan's PR was merged a little bit ago and now the 404 issue is gone. 😄 

There is a new issue, however, --> #676

**Comment by leecalcote** [comment]
Good work here! Closing issue. Feature has been delivered. 👍
