### ISSUE TITLE
Add flag in mesheryctl version 

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#602]
**Current Behavior**
currently mehseryctl doesn't take any flag as argument for version command 

**Desired Behavior**
Adding a version flag. eg: **mesheryctl -v** will reproduce the output of mehseryctl version and will be an alternate to version keywork/argument.

**Comment by anirudhjain75** [comment]
Hey @anandrkskd , Let me know if this is still up for picks :)

**Comment by leecalcote** [comment]
@anirudhjain75 this is an interesting issue. It’s half completed by #626. The other half remains unworked on. The remaining half is interesting as it potentially spans server.go in meshery to goreleaser to GitHub actions workflow (not sure that a change in github workflow is needed, but possible).

**Comment by leecalcote** [comment]
We might be able to close this issue in lieu of #603. The server-side implementation still needs completed, which I think is the purpose of #603.
