### ISSUE TITLE
[mesheryctl] Add meshery server in mesheryctl version 

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#603]
**Current Behavior**
Currently `mesheryctl system version` only _accurately_ displays GitSHA and mesheryctl client version information. The server information shown is inaccurate.

**Prologue**
Meshery will provide a hierarchy of context-specific `version` commands, going from root (`mesheryctl`) to subcommand (`mesheryctl mesh`) to a specific type of that subcommand  (`mesh --type istio --version`).

**Desired Behavior**
Enhance `mesheryctl system version` to use the Meshery REST API provided by #963.

**Acceptance Tests**
1. `mesheryctl system version` should also include Meshery server's version (release tag) and Git SHA (commit ID).
1.  `mesheryctl --version` should reports this same information(_future_: and eventually information for versions of all types of objects under lifecycle management).

**Related**
- meshery server build - #962
- meshery server api - #963

**Comment by leecalcote** [comment]
This issue is related to https://github.com/meshery/meshery/issues/765 - "[mesheryctl] GitSHA in `mesheryctl version` should specify client vs server"
