### ISSUE TITLE
Login required to use?

### ISSUE THREAD

**Issue by coip** [layer5io/meshery#607]
**How can we help?**
I might be missing something here, as I admittedly have very little context.

I see you require using a social login to address this concern of yours:
> Why do I need to authenticate my social account to use Meshery?
> Create your account - avoid having to reconfigure Meshery each time you deploy it. When you use a social account to authenticate to Meshery, your environment configuration persists from session to session.
> ...

Why not support some sort of ~`.config` file?
Is this not intended to be supported?

-----
and (almost ironically) just below is seen:
> Why use Meshery?
> Meshery is an open source, vendor neutral projects that facilitates testing across meshes.

But unless I sign into a Github, Google, Twitter, or LinkedIn account, it doesnt seem like I can do really anything.

Seems quite vendor gnostic.

**Comment by coip** [comment]
I dont mind reconfiguring. I might even like to version control my config?

**Comment by kushthedude** [comment]
Hi @coip , You can use our local provider if you are not willing to authenticate using your social accounts. Local Provider gives all the features in parallel with the Meshery-Social-Auth Provider except the use of JWT as it is required to maintain our social auth.
Please let us know if you have any more questions/doubts!

**Comment by coip** [comment]
hi @kushthedude !

Thanks for getting back to me regarding this.

If/when I revisit, requalify using meshery, do you have any supplementary info on how to use this local provider feature?

Docs, PRs, Issues, Impl, etc. would be appreciable :) 

Cheers!
e

**Comment by kushthedude** [comment]
Hi @coip , we are working on improving our documentation. For what it is worth, I am listing some core differences b/t Cloud & Local Provider. 

**Meshery Cloud**
<li>Persistent sessions</li> 
  <li>Save environment setup and adaper configuration</li>
                     <li>Retrieve performance test results</li>
                     <li>Free use</li>
<br>

**Local Provider**
<li>Ephemeral sessions</li>
  <li>Environment setup not saved</li>
 <li>No performance test result history</li>
 <li>Free use</li>

**Comment by coip** [comment]
Thanks for the context & provenance!

**Comment by coip** [comment]
https://github.com/meshery/meshery/issues/743

**Comment by coip** [comment]
https://github.com/meshery/meshery/commit/dfe3203172d4fdac38ec452fdcaca9c217c102c7
