### ISSUE TITLE
Do we need to make a new repo to handle all the helm chart ?

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/meshery#608]
As @Aisuko has completed helm chart for Meshery Istio and Linkerd, and in further we will need helm chart for NSM adapter. So, to handle all these helm charts from the same repo should we make a another repo?

**Comment by Aisuko** [comment]
@gunjanmimo Thanks for your quick activate, the chart just a draft I development for the discussion. As   I said that the chart needs to review. And please kindly check the doc https://docs.google.com/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit?ts=5e2222b8#heading=h.wyjfw2mc7wze

**Comment by Aisuko** [comment]
As we discussed, we will follow the project https://github.com/weaveworks/flagger/tree/gh-pages/ to design our Meshery chart. Please kindly check https://github.com/meshery/meshery/issues/514#issuecomment-579079936 below.   @gunjanmimo  please feel free to close this issue.
