### ISSUE TITLE
Docs: Release page update for v0.3.8

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#610]
Update Releases docs page with Meshery v0.3.8 details.

**Comment by ashiscs** [comment]
@leecalcote sir, it is already addressed!!

**Comment by gunjanmimo** [comment]
@leecalcote sir, it is already added if I am not wrong.

**Comment by leecalcote** [comment]
Oops. I mean v0.3.8

**Comment by gunjanmimo** [comment]
ok sir, i will add the description

**Comment by leecalcote** [comment]
@ashiscs knocked this one out real quick in #609.
