### ISSUE TITLE
Docs: Make landing page buttons responsive

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#614]
**Current State:**
The three buttons on the landing page of [Meshery Docs](https://meshery.layer5.io/docs) are not responsive. See screenshot.

**Desired State:**
These buttons should rearrange (stack vertically and not have the words in their labels linewrapped, but scale with the size of the screen)

**Screenshot**
<img width="494" alt="Screen Shot 2020-01-21 at 4 59 39 AM" src="https://user-images.githubusercontent.com/7570704/72799546-1736de00-3c0b-11ea-8011-3c1d06fb8522.png">

**Comment by leecalcote** [comment]
@schillingjerrid the sweet marriage of your talents are requested here kind sir.

**Comment by anirudhjain75** [comment]
Hey @leecalcote @schillingjerrid Let me know if this is still available for picks :)

**Comment by leecalcote** [comment]
@anirudhjain75 yes, please do grab it. 👍 

@schillingjerrid does an amazing job. I don’t know that he’s available to pick this one up, though.

**Comment by leecalcote** [comment]
Fixed by #649

**Comment by schillingjerrid** [comment]
Thanks guys! Sorry I wasn't able to get to this one.
