### ISSUE TITLE
Docs: Add docs page for NSM overview

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#619]
**Current State:**
The Meshery Docs has a placeholder for a description of NSM and the Meshery adapter's functionality for NSM - https://meshery.layer5.io/docs/adapters/nsm

**Desired State:**
Ideally, this page gives a short overview about NSM as a project, how Meshery integrates, and what functionality is provided by the integration.

**NSM + Meshery Resources:**
- https://calcotestudios.com/talks/decks/slides-nsmcon-kubecon-na-2019-adopting-network-service-mesh-with-meshery.html
- https://drive.google.com/open?id=1oH_yYELjTbuO69oUAZwaRxgc-W9rab7NEY10T39hEhw

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@ivanayov this issue is right up your alley. :)

**Comment by leecalcote** [comment]
@Vineet-Sharma29, we ended up adding documentation to the NSM adapter page, but still need to list the talk, slide, and video above in the Overview page of the docs. You might toss this one in while you're in there making changes.

**Comment by Vineet-Sharma29** [comment]
Would work on this

**Comment by Vineet-Sharma29** [comment]
@leecalcote Overview page of docs has deck and video of NSM adapter in meshery presentation section. So do I need to add them in some other section of overview page?

**Comment by KarenEfereyan** [comment]
@leecalcote should I take this up?

**Comment by leecalcote** [comment]
@KarenEfereyan The only outstanding item here is to list the ServiceMeshCon talk provided under the **NSM + Meshery Resources:** section above. Are you available to finish off this week?

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan The only outstanding item here is to list the ServiceMeshCon talk provided under the **NSM + Meshery Resources:** section above. Are you available to finish off this week?

@leecalcote I'll try my absolute best to get it sorted this week. Sorry for the delay!!

**Comment by KarenEfereyan** [comment]
@leecalcote i'm onto this right now. This [link](https://docs.google.com/presentation/d/1oH_yYELjTbuO69oUAZwaRxgc-W9rab7NEY10T39hEhw/edit#slide=id.g5ae9aabf3f_0_0) seems to have really small information. Is this all that is available?

**Comment by KarenEfereyan** [comment]
@lee I found that the nsm docs page does exist at this [link](https://meshery.layer5.io/docs/service-meshes/adapters/nsm/nsm)
What do I do about it. The contents of that file are the same as the resources you provided above. What do I do?

**Comment by PluckyPrecious** [comment]
Hey @KarenEfereyan apologies for the delay in response, do you mind taking another go at  the issue? Here’s the correct  [nsm doc](https://meshery.layer5.io/docs/service-meshes/adapters/nsm) which is same as the one Lee wrote.

**Comment by leecalcote** [comment]
Completed.
