### ISSUE TITLE
mesheryctl: Improve `logs` message when Meshery is not running

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#625]
**Current Behavior**
When Meshery is stopped and a user runs `mesheryctl logs`, the receive this output:

```
➜  ~ mesheryctl logs 
Starting Meshery logging...
Attaching to 
```
or this output:

```
➜  ~ mesheryctl logs
Starting Meshery logging...
exit status 1
```

**Desired Behavior**
Instead of `Starting Meshery logging...`, the user will ideally see a message stating: `Meshery is stopped.` If this is difficult, then the following will suffice as an improvement:

```
➜  ~ mesheryctl logs
Starting Meshery logging...
No logs. Meshery is stopped.
```

**Comment by leecalcote** [comment]
@anirudhjain75 what do you think? Would you like to take this one?

**Comment by anirudhjain75** [comment]
Not at the moment, I have little experience with mesheryctl as of now.

**Comment by mayankshah1607** [comment]
@leecalcote @anirudhjain75 I could give this  a try if its not a problem :)

**Comment by anirudhjain75** [comment]
sure have at it @mayankshah1607
