### ISSUE TITLE
mesheryctl: New `completion` command to generate autocompletions script for the specified shell (bash or zsh)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#636]
**Current Behavior**
CLI users enjoy and benefit from less typing when they have enabled autocompletion for a command line interface. `mesheryctl` does not currently provide a `completion` command from which the full set of `mesheryctl` commands may be sourced for the user's specific type of shell (bash or zsh). 

**Desired Behavior**
[Leveraging Cobra's generator](https://github.com/spf13/cobra/blob/master/bash_completions.md), create a new `completion` command is created with the following parameters and flags:

1. 
```
mesheryctl completion SHELL - Generates autocompletion script for the specified shell (bash or zsh)
```

2. 
```
meshery completion --help

Generate autocompletion script for Meshery for the specified shell (bash or zsh).

This command can generate shell autocompletions. e.g.

    $ mesheryctl completion bash

Can be sourced as such

    $ source <(mesheryctl completion bash)

Usage:
  mesheryctl completion SHELL [flags]

Flags:
  -h, --help   help for completion
```

3. Provide detailed instructions to users by updating the Meshery docs. Use `kubectl`'s docs as an example - https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

**Comment by mayankshah1607** [comment]
@leecalcote I could take up this one if that's okay

**Comment by leecalcote** [comment]
This one has your name all over it, @mayankshah1607. ;)

**Comment by kushthedude** [comment]
This is the enhancement you are talking about @nitishm, right?

**Comment by nitishm** [comment]
Yessir

**Comment by leecalcote** [comment]
Hi @WLun001, we would love to have your help here. Given your experience with autocomplete (and fish shell) will you consider taking on this issue?

**Comment by WLun001** [comment]
@leecalcote I can try out sometimes probably this week or next week

**Comment by leecalcote** [comment]
@WLun001, that would be fantastic. 😄
