### ISSUE TITLE
create a easy install script which will run docker-compose & get a short url from something like git.io

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#64]
- Create a simple install experience for downloading and running Meshery locally. Use Istio as an example - https://istio.io/docs/setup/kubernetes/download/
- Create a beautified git.io short link - https://gist.github.com/dikiaap/01f5e2ba3c738012aef0a8f524a6e207

**Comment by leecalcote** [comment]
Hi @venkatasankarapu, would you like to take this on? You can use the Istio's use of git.io as an example - https://istio.io/docs/setup/kubernetes/download/

**Comment by leecalcote** [comment]
We expect users to bring their own cluster, but to optionally bring their own service mesh and optionally bring their own application. Meshery will provide either of the two of the latter (mesh and sample app), if they don't provide these.

**Comment by girishranganathan** [comment]
Super basic steps:
- wget https://github.com/meshery/meshery/blob/master/docker-compose.yaml
- docker-compose up -d

**Comment by girishranganathan** [comment]
@leecalcote, we have an initial version of the script [here](https://raw.githubusercontent.com/meshery/meshery/master/meshery-cli.sh).
I created a git.io short URL and got this https://git.io/fjTxV
Do you want to create a meshery.io short url? so that we can have a slicker install command?

**Comment by girishranganathan** [comment]
We now have an easy install script and a git.io url: https://git.io/meshery
