### ISSUE TITLE
The issues management needs more automation

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#640]
**Current Behavior**
A brief description of what the problem is. (e.g. I need to be able to...)

Some issues that we do not manage. We need to close or give feedback to the issue's author.

**Desired Behavior**
A brief description of the enhancement.

Our issue management needs more automation. And I believe issues that over 30 days need to be label as stale and will be closed after 14 days. (We can config for our project situation.)

Please follow the link https://probot.github.io/apps/stale/ add the stale robot to the project.

---
**Resources**
Helpful tools and reference information.

**Alternatives / Additional Context**
A brief description of any alternative solutions or features you've considered or other context that might be helpful.

**Comment by gunjanmimo** [comment]
@Aisuko I think I can solve this issue.

**Comment by leecalcote** [comment]
@gunjanmimo good deal. There's a PR on this issue available for review - #639
