### ISSUE TITLE
Add `vet` to existing CI Workflow

### ISSUE THREAD

**Issue by mayankshah1607** [layer5io/meshery#645]
**Current Behavior**
As of now, the current workflow allows code that contains suspicious or poorly written constructs.

**Desired Behavior**
The CI workflow must examine each PR for bad constructs using [vet](https://golang.org/cmd/vet/)
Example of a suspicious construct : 
```go
if <expr> {
   return true
}
return false
```
This can be better written as : 
```go
return <expr>
```
[vet](https://golang.org/cmd/vet/) ensures that the codebase is neat and developers follow good practices. ;)

---
**Resources**
Helpful tools and reference information - https://golang.org/cmd/vet/

**Comment by leecalcote** [comment]
Sounds good

**Comment by leecalcote** [comment]
On a related note, `vet` was recently enabled on the `meshery-istio` adapter. There are a few issues that @gunjanmimo and @ashiscs might be looking into.

**Comment by mayankshah1607** [comment]
@gunjanmimo @ashiscs Please feel free to drop in your suggestions

**Comment by gunjanmimo** [comment]
I am also trying to solve git action errors?

**Comment by ashiscs** [comment]
Yes, this should be implemented!!
