### ISSUE TITLE
Meshery: Improve error message for failed duplicative operation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#647]
**Current Behavior**
When a user tries to deploy the same application twice or when a user tries to deploy the same type of service mesh to a namespace that already contains an instance of that type of service mesh, the error shown back to the user is:

<img width="973" alt="Screen Shot 2020-02-01 at 7 45 51 PM" src="https://user-images.githubusercontent.com/7570704/73601704-c89f1300-452b-11ea-9760-f37b63c0733d.png">

**Desired Behavior**
The error shown to the user should state:

"Unable to deploy this resource. A resource of the same name already exists. Try deploying again in a different namespace."

**Comment by avhvr** [comment]
@leecalcote I'd like to work on this issue.

**Comment by leecalcote** [comment]
@avhvr, excellent. Yes, that would be fantastic. This one is medium-sized, so to speak. Which is to say that for a first-time contributor, you'll have a mouthful. :) @girishranganathan and others will help you through it, though. 👍 Let's do it!

**Comment by KarenEfereyan** [comment]
@leecalcote who is currently working on this

**Comment by Nikhil-Ladha** [comment]
@leecalcote I don't think a very big fix is needed for this. And, we can add the `good-first-issue` label to it. As we only need to update the error message.

**Comment by leecalcote** [comment]
These issues have been addressed in MeshKit.
