### ISSUE TITLE
create docs site for Meshery

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#65]

**Comment by girishranganathan** [comment]
We have decided to host the docs on meshery.meshery.io

**Comment by girishranganathan** [comment]
MkDocs is a good candidate

**Comment by girishranganathan** [comment]
Have the src for docs in meshery-saas folder called "docs" and possibly host the contents on GitHub Pages.
Have a redirect to GH pages from Meshery SaaS possibly. . .

**Comment by leecalcote** [comment]
Documentation for setting up GH Pages with MkDocs - https://www.mkdocs.org/user-guide/deploying-your-docs/

Material theme for MkDocs - https://squidfunk.github.io/mkdocs-material

**Comment by leecalcote** [comment]
@girishranganathan in consideration of @yogi4 taking this on, will you recap our conversations with him and point him in our chosen direction?

**Comment by yogi4** [comment]
@girishranganathan my day is pretty wide open tomorrow , let me know your availability and . I will take this on.

**Comment by girishranganathan** [comment]
Cool, I am available at 11:30 AM Eastern. Let's have a slack call.
Ty,
G

**Comment by yogi4** [comment]
sure Girish. 11:30AM EST works for me . let's have a slack call.

**Comment by leecalcote** [comment]
@yogi4 good to close?

**Comment by girishranganathan** [comment]
We have the framework in place.
