### ISSUE TITLE
[mesheryctl] Update `start` to support multi-platform setup for meshery

### ISSUE THREAD

**Issue by mayankshah1607** [layer5io/meshery#665]
**Current Behavior**
As of now, we can start meshery using either `mesheryctl` or manually deploy to [various platforms](https://meshery.layer5.io/docs/installation/platforms) manually. 

**Desired Behavior**
The goal of this proposal is to enhance user experience by allowing the users to deploy meshery on various platforms via a new set of flags for the `start` command. Some examples:
```bash
# deploy locally using docker-compose
$ mesheryctl start --docker

# establish connection to a cluster via local kubeconfig file and deploy to the k8s cluster
$ mesheryctl start --k8s

# deploy multiple replicas of various meshery components on a k8s cluster
$ mesheryctl start --ha
```
---
**Resources**
Refer [design doc](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

cc @leecalcote

**Comment by leecalcote** [comment]
Good, good, @mayankshah1607. We'll want to consider a structure that will support these forthcoming operations:

- Meshery lifecycle management (start, stop, status, update, cleanup, version)
- service mesh lifecycle management (deploy, delete, status, version)
- performance test (run)

It could be the case that multiple of these are facilitated under the same command, e.g., `mesheryctl start -p kubernetes -sm linkerd`, however, better yet, they are likely split out. Brainstorming:

`mesheryctl start -p docker` -- having a `-p` for "platform" facilitates the ability to deploy to a platform and to optionally add an `--ha` flag after.
`mesheryctl deploy -p <cluster-name:context-name> -sm <service-mesh-name> -f <service-mesh-configuration-file>
`mesheryctl test -name <name-of-test> -f <filename-of-test-config>`

**Comment by antweiss** [comment]
I like the idea fo splitting this out to separate subcommands.

**Comment by leecalcote** [comment]
@thakursaurabh1998 the considerations above need to be incorporated into the mesheryctl design spec.

**Comment by thakursaurabh1998** [comment]
Noted @leecalcote

**Comment by leecalcote** [comment]
Mostly addressed in https://github.com/meshery/meshery/pull/1084

**Comment by leecalcote** [comment]
`mesheryctl system context` brings in a `config.yaml` that lists multiple Meshery deployments with individual contexts each of which have a "platform" attribute. @mayankshah1607, you'll be so proud of the Meshery v0.5.0 release, which has support for the functionality requested here. 😄
