### ISSUE TITLE
Investigate displaying Fortio data in grafana as well

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#67]
- Consider how Grafana can facilitate comparison of multiple test results in same charts.
- possible steps
  - create an endpoint in Meshery which will serve JSON data for the chosen graphs and/or individual fortio result
  - configure Grafana programmatically to treat the new endpoint as a datasource
  - programmatically create a panel with the data for the selected charts
  - embed that panel in Meshery

**Comment by leecalcote** [comment]
A non-issue considering Meshery's move to billboardjs?

**Comment by leecalcote** [comment]
@girishranganathan A non-issue considering Meshery's move to billboardjs?

**Comment by girishranganathan** [comment]
We are now using billboardjs. Closing this for now.
