### ISSUE TITLE
UI: Provide anchor on each Settings tab for deep-linking

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#670]
**Current Behavior**
A user visiting the /settings page in Meshery may want to land within one of the Settings tabs (Environment, Service Meshes, Metrics). 

As an example, currently, if a user navigates to http://meshery/settings#service-meshes, the "Service Meshes" tab is not open.

**Desired Behavior**
Named anchor (<a>) tags should be added to each Settings screen tab, like so:

- `<a name="environment"> </a>`
- `<a name="service-meshes"> </a>`
- `<a name="metrics"> </a>`

**Reference**
```
<button class="MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary Mui-selected MuiTab-labelIcon MuiTab-fullWidth" tabindex="0" type="button" role="tab" aria-selected="true" title="Connect Meshery Adapters">
```
**Screenshot**
<img width="946" alt="Screen Shot 2020-02-12 at 10 40 32 PM" src="https://user-images.githubusercontent.com/7570704/74402050-bef99300-4de8-11ea-9438-769f8dbadb8f.png">

**Comment by snitin315** [comment]
@leecalcote Can I take this up?

**Comment by leecalcote** [comment]
@snitin315 please, sir, yes. This "small" enhancement will have no "small" impact on user confusion when trying to nav the app.

**Comment by aayushdutt** [comment]
@snitin315 Are you still working on this? Can I take this?

**Comment by snitin315** [comment]
Feel free to work on it.

**Comment by leecalcote** [comment]
@aayushdutt an example use case should have been noted in the description. Here's one:

**Current behavior:**
- A user doesn't have an Istio adapter configured.
- They click on "Istio" in the navigation bar.
- They see a "Configure Settings" button instead of actions to take with the adapter.
- They click on "Configure Settings" and are dropped off at /settings, which shows them the Environment tab (wrong tab).

We want to change that last step's behavior.

**Comment by aayushdutt** [comment]
Got it @leecalcote 
I went through #671 and it looks like the description you gave above. I'll be working on the same next.
However, I guess the current behaviour when Istio adapter is not configured is that it does nothing when clicked on "Istio" on the navbar.

**Comment by leecalcote** [comment]
@aayushdutt, good point. I was just noticing this same behavior. I suppose what I described is only true for the first two bullets. It would be an improvement if we were to implement the two last bullets with the new anchor included.

**Comment by aayushdutt** [comment]
@leecalcote That would be great.

What do you think about -
* We put a label next to "Istio" in the navigation bar which says `Not Configured` (probably with a similar styling of labels as that on GitHub)
* When it's clicked, it directly redirects to `/settings` page to configure it.

![image](https://user-images.githubusercontent.com/25280541/80564832-8f801d00-8a0c-11ea-8342-a70d0e4787f9.png)
