### ISSUE TITLE
[UI] Missing Adapter: Navigate user to Settings page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#671]
**Current Behavior**
When an adapter of a certain type is not connected, that type of service mesh is still listed in the sidebar nav (that's fine), but when the user clicks on that menu item, they are not shown anything or navigated anywhere.

**Example:**
![Untitled](https://user-images.githubusercontent.com/7570704/74402258-50690500-4de9-11ea-9a19-4dd8e89c2242.gif)

**Desired Behavior**
1. Show the user a page stating that an adapter for this type of service mesh is not connected.
1. Prompt them to connect an adapter with a "Configure Adapter" button.
1. Navigate them to /settings#service-meshes when the "Configure Adapter" button is clicked. (relates to #670)

**Comment by leecalcote** [comment]
@Nikhil-Ladha given your familiarity with this area, this might be simple for you to tackle.

**Comment by Nikhil-Ladha** [comment]
Work mode on!

**Comment by leecalcote** [comment]
#670 is related to this issue.

**Comment by Nikhil-Ladha** [comment]
> #670 is related to this issue.

Yeah, I saw that and was just going to mention the same ;)

**Comment by aayushdutt** [comment]
@Nikhil-Ladha Are you still working on this? Can I take this up?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Are you still working on this? Can I take this up?

Actually, I was but since you started to work on the other. I was waiting for your PR. But if you want you can take this up. No issues 👍🏼.
