### ISSUE TITLE
[UI] User Preference selections not remembered

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#676]
**Description**
User selections are not reflected accurately after the user navigates away and comes back to the Preferences screen.

**Expected Behavior**
Users should see their previous selections when returning to the Preferences screen.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/7570704/74507381-d9536f80-4ec1-11ea-8873-d976530b432d.gif)

**Related**
This issue is related to #599

**Comment by leecalcote** [comment]
While these changes are being made here, could we also shorten the page name from "userpreferences" to "preferences"?

**Comment by kushthedude** [comment]
I am looking into the following. @leecalcote Can you assign me to this or my comment will be sufficient to indicate other contributors that I am working on it?

**Comment by leecalcote** [comment]
@kushthedude thanks for considering jumping in here! @Nikhil-Ladha is this an inflight issue for you (one that you're currently working on)?

**Comment by Nikhil-Ladha** [comment]
Well, I was. But I didn't have good progress till now. So if @kushthedude is willing to take up the issue. Thumbs up!

**Comment by kushthedude** [comment]
Great!

**Comment by kushthedude** [comment]
I looked at the implementation of User-Preferences Component. It is Frontend centric implemented, whatever be the value sent to the API the component is just sending the value to API regardless of considering what is the value previously stored. Hence after every reload, the preferences are reset to false as described in the component constructor hook.

**Comment by Nikhil-Ladha** [comment]
> I looked at the implementation of User-Preferences Component. It is Frontend centric implemented, whatever be the value sent to the API the component is just sending the value to API regardless of considering what is the value previously stored. Hence after every reload, the preferences are reset to false as described in the component constructor hook.

Yeah, that's why we need to store the value in backend and then use them again at reload.

**Comment by kushthedude** [comment]
Thats correct.

**Comment by leecalcote** [comment]
@kushthedude as you look into this issue, will you have a look-see at PR #627 as well? The unfinished portion of that PR is related to the issue described here.

**Comment by nveenjain** [comment]
@kushthedude , are you working on this issue? Me, @shivaylamba  and @leecalcote  had a discussion on this issue about few days ago, and a fix was recommended during that discussion. If you're not working on it, I would like to take up this issue.
