### ISSUE TITLE
Incorporation of adapters into project pipeline.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#69]
Define a set of tests for an adapter build to pass for incorporation into the overall project build.

Should this simply be the return of a message from each service method?

**Comment by kushthedude** [comment]
@leecalcote Do we have to test each adapter build in this ?

**Comment by leecalcote** [comment]
The early thought here was to validate adapter functionality with integration testing. The work that @ksatchit, @uditgaurav, and @naturalett are looking into may be valuable here.
