### ISSUE TITLE
App doesn't start when the server provider is not selected

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#690]
**Description**

The app doesn't start when the service provider from server is not selected
**Expected Behavior**

There should be a definite instruction to set up with the app once server and UI have been built up.

**Enviroment:**
 - OS: MacOS Mojave
 - Browser: Safari

---
[Optional] **To Reproduce**
Steps to reproduce the behaviour:

1. Start the server and make UI.
2. Go to localhost:3000
3. See error

[Optional] **Additional Context**

Page keeps loading continuosly and refreshes itself.

**Comment by leecalcote** [comment]
@girishranganathan will you clarify the make / build instructions?

**Comment by kushthedude** [comment]
Also when running `make run-local`, the ui also runs without specifically
running `make ui-build` .

**Comment by Nikhil-Ladha** [comment]
@leecalcote and @kushthedude  I faced a similar issue when I was working on my local but ignored it.

**Comment by kushthedude** [comment]
> @girishranganathan will you clarify the make / build instructions?

@leecalcote I will make changes to docs from what can I get from the new behaviour of build. Still if there is anything wrong in the same @girishranganathan may suggest changes to the same.

**Comment by nveenjain** [comment]
@leecalcote @kushthedude , can this issue be closed in favor of #697 ?

**Comment by kushthedude** [comment]
> @leecalcote @kushthedude , can this issue be closed in favor of #697 ?

#697 was more of a workaround. 
I will make the PR with the fix for this soon.

**Comment by leecalcote** [comment]
Given some of our recent changes, is this still an issue?
