### ISSUE TITLE
wrong default config file location in `meshery -h`

### ISSUE THREAD

**Issue by antweiss** [layer5io/meshery#691]
**Description**
When running `mesheryctl -h` the following is displayed:
`Flags:
      --config string   config file (default location is: $HOME/.meshery/config.yaml)
`
While in fact the default compose file is $HOME/.meshery/meshery.yaml

**Expected Behavior**
Correct file name/path should be shown

Actually we should be using existing var `dockerComposeFile` specified in vars.go.

**Enviroment:**
 - OS: MacOS

**Comment by leecalcote** [comment]
Good call, @antweiss. 👍
