### ISSUE TITLE
Support alternative kubeconfig locations

### ISSUE THREAD

**Issue by antweiss** [layer5io/meshery#693]
**Current Behavior**
When running `mesheryctl start` (based on docker-compose) with the default ~/.meshery/meshery.yaml -  current user's $HOME/.kube is mounted into the meshery container:
```
 volumes:
      - $HOME/.kube:/home/appuser/.kube:ro
```
That means that if the current context comes from an env variable $KUBECONFIG setting - it gets ignored.
Moreover - loading the kubeconfig through the UI afterwards might not work if a pem file it requires resides in the same directory.

**Desired Behavior**

Meshery should respect the $KUBECONFIG env variable. Or at least allow specifying an alternative KUBECONFIG on cli. Meshery should then mount the base directory for the KUBECONFIG file and set the env variable inside the container accordingly.

**Challenges**

Currently the mount is statically defined in meshery.yaml. The described feature would require to edit it dynamically in some way. Docker-compose format isn't flexible enough.

**Comment by antweiss** [comment]
![ezgif-3-9401373d2d2a](https://user-images.githubusercontent.com/3274734/74831501-04a0e900-531e-11ea-8f40-0c1a5cb4039d.gif)

**Comment by leecalcote** [comment]
@clementkng would you like to take this one?
