### ISSUE TITLE
[Performance] Feature: vegeta might be a good fit for load generation

### ISSUE THREAD

**Issue by sachincool** [layer5io/meshery#694]
**Current Behavior**
Currently, we have [wrk2](https://github.com/giltene/wrk2) and [fortio](https://github.com/fortio/fortio) as HTTP load generators.

**Desired Behavior**
Load generators like Vegeta support distributed load testing. Supporting this scenario in context of microservices and service meshes supporting those services makes a lot of sense.

---
**Resources**
- [Vegeta github](https://github.com/tsenart/vegeta)
- [Vegeta getting started](https://medium.com/@jamesstradling/https-medium-com-jamesstradling-load-testing-apis-with-go-and-vegeta-1105523e4b1a)

**Alternatives / Additional Context**
* It has a lot of customizations which can aid people's use of a service mesh.
* [Additional links](https://github.com/tsenart/vegeta#usage-library)

**Comment by kushthedude** [comment]
I personally suggest using Vegeta, It will definitely be much useful in the long run for Meshery.

**Comment by leecalcote** [comment]
Great suggestion. We’ve considered this before. This is a welcomed feature.

**Comment by kushthedude** [comment]
@sachincool Are you planning to work on it? Or can I give it a shot?

**Comment by sachincool** [comment]
I just suggested the Feature, you are free to work on it :D

**Comment by leecalcote** [comment]
@sachincool an update: we're focusing our attention first on Envoy's Nighthawk in collaboration with @mum4k.

**Comment by Aisuko** [comment]
keep active
