### ISSUE TITLE
Set-Up Netlify Deployment

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#695]
It would be great if we could have Netlify Deployment for UI Related PRs.

**Comment by kushthedude** [comment]
@leecalcote I have written a raw configuration file for now, should I push it and see how it works ?

**Comment by leecalcote** [comment]
@kushthedude sounds real good, yes.

**Comment by leecalcote** [comment]
@kushthedude, progress - you should have an invitation to join the Layer5 Netlify team now.

**Comment by ashiscs** [comment]
@leecalcote sir, this issue is already addressed and needs to be closed!!

**Comment by kushthedude** [comment]
Who told you it has been done ?

**Comment by kushthedude** [comment]
There is still of a hosted cloud provider to have a netlify.

**Comment by ashiscs** [comment]
Ok got it.
On the site, in the footer section i saw something "deploys by netlify" so i thought the task is completed, but my fault here..
