### ISSUE TITLE
Set up ESLint rules and Lint checker tests

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#696]
Set up ESLint and Linting tests in CI for quality of code.

**Comment by kushthedude** [comment]
@leecalcote How does it sounds ?

**Comment by leecalcote** [comment]
@kushthedude sounds good. For go, there are few checks enabled in the CI workflow today in [ci.yml](https://github.com/meshery/meshery/blob/master/.github/workflows/ci.yml), like https://revive.run. Have a look at ci.yml, if you would, perhaps, we can start improving here by uncommenting a few of the other checks that we're not running today (security and so on).

**Comment by leecalcote** [comment]
Nice work, @kushthedude. Do we need documentation with respect to our use of ESLint? I'm not sure that we do, but if so, a doc in [this folder](https://drive.google.com/drive/u/0/folders/1g8anBCT9UrTe3FRA6eKpo59k46yCvZct) or a note in the [contributing](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md) guide are appropriate locations.

**Comment by kushthedude** [comment]
Yes @leecalcote , we need a document to specify that before pushing the
commit you should run ESlint on local so that your tests do not fail.
In the near future I will try to add pre-commit hook which will
automatically run the eslint on the local when the contributor adds a
commit.

**Comment by leecalcote** [comment]
Awesome. 🥇
