### ISSUE TITLE
[Install]: Meshery Helm Chart Error: "cannot set --generate-name and also specify a name"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#700]
**Description**
Helm installs produce an error. Executing the following commands to install Meshery via `helm`:

```
➜  ~ kubectl create namespace meshery
namespace/meshery created
➜  ~ helm install -g meshery --namespace meshery install/kubernetes/helm/meshery
Error: cannot set --generate-name and also specify a name
```
produces the above error.

**Expected Behavior**
A `meshery` namespace is created and Meshery deployment and services created.

**Enviroment:**
 - Docker Desktop v2.2.0.3
 - Kubernetes v1.15.5
 - Helm v3.0.3

**Comment by Aisuko** [comment]
Hi @leecalcote 

I used to hit the issue. In fact, I'm not sure too many details. But, I have been changed the document's scripts.

```
helm install meshery --namespace meshery install/kubernetes/helm/meshery
```

**Comment by Aisuko** [comment]
Under my understanding, I change the command

```
helm install repo-name/mychart --generate-name
```
to 
```
helm install release-name repo-name/mychart
```

So, we manually define  the release name.

**Comment by leecalcote** [comment]
@Aisuko will you take another look here?

**Comment by Aisuko** [comment]
> @Aisuko will you take another look here?

We can close this issue, as you can see our document all have been remove the `--generate-name` parameter this parameter may not useful for the chart

**Comment by leecalcote** [comment]
Sounds real good. Thank you, @Aisuko
