### ISSUE TITLE
[UI]: Update default Meshery logo with Citrix logo on meshery-cpx adapter chip

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#703]
**Description**
See screenshot. The default Meshery logo should be replaced with a Citrix logo for the meshery-cpx UI adapter chip. The [colored Citrix logo svg](https://github.com/layer5io/meshery/blob/master/ui/static/img/citrix.svg).

**Screenshots**
<img width="1164" alt="Screen Shot 2020-02-25 at 11 23 57 PM" src="https://user-images.githubusercontent.com/7570704/75314657-03902000-5826-11ea-9efa-ffcc2af01dfb.png">

**Comment by subhamkrai** [comment]
hey @leecalcote I might be wrong but the path of the image seems right here [dashboard](uhttps://github.com/layer5io/meshery/blob/master/ui/components/DashboardComponent.js#L382)

**Comment by leecalcote** [comment]
@subhamkrai you're right. That is the same file reference. This is bit of a head scratcher. I wonder if the SVG itself is having problems when the UI is being built. I'll upload a reformatted copy of the SVG and see if this has an affect.

**Comment by leecalcote** [comment]
@subhamkrai I believe the that [case statement](https://github.com/layer5io/meshery/blob/master/ui/components/DashboardComponent.js#L381-L382) needs updated to be "cpx", not "citrix" in order to fix this issue.
