### ISSUE TITLE
[MeshSync]: Adapter Scans for Linkerd, Octarine, NSM, Consul

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#704]
**Current Behavior**
The /performance page scans the environment to detect the presence and details of deployed service meshes. Currently, this functionality is partially provided for Istio (just for Istio's presence and version #). 

**Desired Behavior**
Meshery should scan the environment for all known types of service meshes and their details.

**Implementation**
Using [istio-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/istio-scan.go) as an example, create scans for each of the other types of Meshery-supported service meshes.

**Future:** each scan needs to be enhanced to gather service mesh-specific configuration details.

**Comment by kushthedude** [comment]
I will take a look at it!

**Comment by leecalcote** [comment]
Nice. Yes, this is much needed.

**Comment by leecalcote** [comment]
@kushthedude ping @nveenjain and @leecalcote on Slack about this issue - "MeshSync".

**Comment by kushthedude** [comment]
@leecalcote Where are the other scan helpers added?

**Comment by nveenjain** [comment]
@kushthedude , we alreay support Istio,Linkerd,Consul and Network Service Mesh.
Octarine and cpx are pending as of now.

**Comment by kushthedude** [comment]
Clearly there is more work pending in this issue which means the
corresponding PR didn't fixes the issue then why did this issue was closed?
Also I don't see the scanners for NSM.

**Comment by nveenjain** [comment]
@kushthedude , NSM is scanned currently :- 
https://github.com/meshery/meshery/blob/master/helpers/kubernetes-scan.go#L30

Yes, there are scanners for CPX and octarine, that need to be added...

**Comment by leecalcote** [comment]
> Clearly there is more work pending in this issue which means the corresponding PR didn't fixes the issue then why did this issue was closed? Also I don't see the scanners for NSM.
> […](#)

@kushthedude good question - this is more an incidental closure through use of keywords in PR with "fixes", "closes", and so on. Here's a related issue that we can either deduplicate or can use to track scanning / syncing of Citrix Service Mesh separately - https://github.com/meshery/meshery/issues/745

**Comment by nveenjain** [comment]
This issue was fixed in #752, the pending work should be tracked by #745
