### ISSUE TITLE
[mesheryctl] Update description of Meshery in `mesheryctl help`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#711]
**Current Behavior**
`mesheryctl` prints information on Meshery and `mesheryctl` commands. The description used for Meshery: "Meshery is a a multi-service mesh performance benchmark and playground tool" needs to be updated.

**Desired Behavior**
Replace old description with new one - "Meshery is the multi-service mesh management plane, providing lifecycle, performance, and configuration management of service meshes."

**Comment by ashiscs** [comment]
@leecalcote sir, there doesn't exists a file named mesheryctl help?
