### ISSUE TITLE
[mesheryctl] Update `perf` flag default settings

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#718]
**Current Behavior**
The Meshery UI and `mesheryctl perf` command are two client interface to Meshery's performance test capability (/api/load-test, /api/load-test-smps). Ideally, the Meshery load test API will provide defaults for various load testing behavior. Until such time, we'll want to mimic the behavior by keeping client defaults aligned.

**Desired Behavior**
`mesheryctl perf`'s defaults should be the same as those found in Meshery's /performance UI.

- --duration should be 30s
- --parallel-requests should be 0
- --qps should be 0 _(zero means that the load generator will attempt as many as it can)_

---
**Resources**
- [Meshery CLI Commands & Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#)

**Comment by leecalcote** [comment]
@chandresh-pancholi i think we’re ok to close this issue. Is that right?

**Comment by chandresh-pancholi** [comment]
Yes.
