### ISSUE TITLE
[mesheryctl] Generate cluster access for Minikube clusters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#722]
**Current Behavior**
Users running Meshery against a Kubernetes cluster in minikube need to execute the CLI statement [documented here](https://meshery.layer5.io/docs/installation/minikube#2-generate-):

```
kubectl config view --minify --flatten > config_minikube.yaml
```

**Desired Behavior**
Enable users to  use `mesheryctl`  to generate the appropriate kubeconfig file for Meshery to access the Kubernetes cluster inside of the Minikube VM.

**Implementation**
1. Create a `config` command for `mesheryctl` so that users may generate the config necessary for Minikube and other platforms.

```
mesheryctl system config generate -p <platform-name>
```

2. Document the `config` command in the [Meshery CLI Reference](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#).

---
**Resources**
Related issue: https://github.com/layer5io/meshery/issues/146

**Comment by ranjithkumar007** [comment]
@leecalcote , I would like to have a go at this.

**Comment by PluckyPrecious** [comment]
Knock Knock! @nveenjain @ranjithkumar007  checking in for situation report.😃

**Comment by ranjithkumar007** [comment]
Didn't get enough time.. Please feel free to take it up.

**Comment by leecalcote** [comment]
Capturing some additional thoughts from conversation with @vijcheru:

The idea of this issue being that the step of requiring a user of Meshery and Minikube to export a flattened minikube config can be made to feel a little more native via a `mesheryctl` command that essentially invokes the same minikube export ... command.

As a **first step**, `mesheryctl` could export the file to the user’s `~/.meshery folder`. That’s enough to make a new release of mesheryctl.

As a **second step**, mesheryctl can accept a global flag: `mesheryctl --mesheryctlconfig = <location of a yaml file>`, which is a configuration file for mesheryctl to use. Upon invoking `mesheryctl system config generate -p minikube`, after exporting the minikube config, that same command could be updated to include logic that updates the `mesheryctlconfig.yaml` file to point to the newly exported minikube config.

As a **third step**, when Meshery UI loads, it should look to the `mesheryctlconfig.yaml` and use whatever kubeconfig file is being pointed to, not simply assume that the desired kubeconfig file is in the user’s `~/.kube/config` location. 

As a **fourth step**, mesheryctl system start should invoke a short discovery of the users’ environment to see if there is more than one kubeconfig present, or if minikube is running and if it sees minikube running, it should invoke the procedure included in the `system config generate -p minikube` function automatically.

Some of what I just said is a little rough, but the gist here is that we want to try to delight users. We want Meshery to be the most broadly used and easy-to-use (yet powerful) service mesh management tool. To make it so, we’ll have to pull out all the stops, so to speak, and have to make some assumptions about what most users would want. We’ll have to make healthy assumptions about Meshery’s default behavior (while allowing users to customize those defaults with things like `mesheryctlconfig.yaml`)

// @anirudhjain75

**Comment by anirudhjain75** [comment]
Is this because minikube uses key path instead of keys in yaml that we have to do the above command. If that's the case, I think someone was already working on giving meshery ability to read and work with minikube without any extra steps.

**Comment by leecalcote** [comment]
@clementkng @anirudhjain75 treating this issue as an epic, let's create other issues (using the issue/child label) to track these four steps.

**Comment by subhamkrai** [comment]
@leecalcote is this taken?

**Comment by leecalcote** [comment]
All, this functionality was actually implemented some time ago, but never documented. The PR above cleans up the command a little and documents it.
