### ISSUE TITLE
Running `mesheryctl` should show usage information

### ISSUE THREAD

**Issue by peterj** [layer5io/meshery#723]
**Description**
Running `mesheryctl` without any arguments outputs empty lines

**Expected Behavior**
Running `mesheryctl` without arguments should show usage information (just like `mesheryctl -h` does)

**Enviroment:**
 - OS: macos
 - Browser: n/a
 - Version: 

Client Version: 0.3.10
Server Version: 0.3.10
GitSHA:07ca1f461b0c7a2bd3f4b943b56257a7f332ce89

**Comment by leecalcote** [comment]
Great call,  @peterj 👍

**Comment by leecalcote** [comment]
@subhamkrai thanks for grabbing this one. Is this something that you might demo on today’s call?

**Comment by leecalcote** [comment]
Thank you, @ashis

**Comment by ashiscs** [comment]
@leecalcote sir, should i close this issue??

**Comment by leecalcote** [comment]
Please, yes, @ashiscs. I think we're good to go here.
<img width="781" alt="Screen Shot 2020-03-24 at 2 58 47 PM" src="https://user-images.githubusercontent.com/7570704/77471290-014ac280-6de0-11ea-82a3-79e10249129e.png">
