### ISSUE TITLE
Unable to run perf test against Linkerd installed on Docker for Mac

### ISSUE THREAD

**Issue by peterj** [layer5io/meshery#724]
**Description**
I am unable to run a simple perf test against Linkerd installed on Docker for Mac. I have installed Linkerd through Meshery as well as the Emojivoto sample app. Both installations seem fine (i.e. I can access the app etc.)

If I try to run a perf test against http://localhost (either through the UI or CLI), I get the following error: 

```
$ mesheryctl perf --mesh linkerd --url http://localhost


Test name used :  GqGyFM1n
data: {"status":"info","message":"Initiating load test . . . "}

data: {"status":"error","message":"error: unable to perform load test"}


Test Completed Successfully!

``` 

**Expected Behavior**
Load test should run, I should get the results.

**Enviroment:**
 - OS: Mac
 - Browser: n/a
 - Version: 

```
$ mesheryctl -v
Client Version: 0.3.10
Server Version: 0.3.10
GitSHA:07ca1f461b0c7a2bd3f4b943b56257a7f332ce89
```
---

**Comment by peterj** [comment]
Note that I tried both `fortio` and `wrk2` with the same results.

**Comment by leecalcote** [comment]
@peterj one deceiving aspect to this test might have to do with Docker Desktop networking and that the network that Meshery is deployed on (`meshery_default` is bridge-based networking). Are you able to run a successful performance test using the IP address of your host's NIC (e.g. the IP address from `ifconfig en0` or `ifconfig en1`)?

**Comment by kanishkarj** [comment]
@leecalcote Could we verify that by doing a performance test on any generic website? like https://github.com/, would that give more insight into this issue?

**Comment by peterj** [comment]
Good point! Will try that and update/close the ticket.

**Comment by peterj** [comment]
Yep, that's what it was! I'll close this issue as it looks like #725 is tracking the doc updates.

**Comment by leecalcote** [comment]
B-e-a-u-tiful. 👍 I snagged on this more than once.
