### ISSUE TITLE
Docs: Example usage of `mesheryctl perf`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#725]
**Current State:**
The Meshery docs are missing example usage of `mesheryctl perf`. 

**Desired State:**
Considering the deceiving user experience of being able to reach a given endpoint (service) from a user's local machine, but Meshery (running on a bridge network) not being able to reach that same endpoint (when referenced as `localhost` or some other unreachable name/network), the [`mesheryctl` user guide](https://meshery.layer5.io/docs/guides/mesheryctl) should contain example uses.

**Related Issues:**
- #724 

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by ashiscs** [comment]
@leecalcote sir, this issue is already addressed and needs to be closed

**Comment by leecalcote** [comment]
Good call, @ashis. You’re right.
