### ISSUE TITLE
Default perf test values mismatch between dashboard and CLI

### ISSUE THREAD

**Issue by peterj** [layer5io/meshery#726]
**Description**
The default perf test duration in the dashboard is `30s`, while in the `mesherycli` is set to 10 seconds. Similarly for QPS - 0 in the UI and 1 in the CLI,  and the concurrent requests (0 vs 1). Also, the flag name in the CLI is `parallel-requests`, while in the UI it's called `Concurrent requests` - it would be nice to be consistent.

**Expected Behavior**
Consistent values/naming between the UI and CLI.

**Comment by leecalcote** [comment]
Items like this are important. @peterj will you have a quick look at #718 and determine whether we might close #718 as duplicative of the issue being correct here?
