### ISSUE TITLE
[MeshSync] Can't delete a mesh or application if the namespace doesn't match

### ISSUE THREAD

**Issue by peterj** [layer5io/meshery#731]
**Description**
When installing a service mesh or sample application, you can type in a namespace. However, when you want to remove either of those you need to make sure to remember the exact namespace stuff was originally deployed in. Not sure if this is by design, but it would be nice if Meshery could remember the namespace a mesh/app was installed in and know how to delete it later

**Comment by leecalcote** [comment]
Good highlight, @peterj. No, behavior is more by lack of bandwidth to implement. Very much so this is needed. 👍

**Comment by leecalcote** [comment]
@chandresh-pancholi  thanks for grabbing this one. Is this something that we might to talk through on today’s call?

**Comment by chandresh-pancholi** [comment]
@leecalcote let's discuss it today.

**Comment by leecalcote** [comment]
Recent enhancements in MeshSync make this issue more ready to address. // @nveenjain

**Comment by nveenjain** [comment]
Yes, let's we can modify the UI to show the namespaces. It might help the users and they can select the namespace they want to apply an specific operation on.

**Comment by chandresh-pancholi** [comment]
@nveenjain Isn't better to remember it at the time of the creation and let not user worry about it?

**Comment by nveenjain** [comment]
Yes, @chandresh-pancholi , but what if there are multiple installations of a single service mesh in different namespaces, we can show the user a list of namespaces, where the service mesh currently is existing.
If there is only one instance of service mesh, we can by default show that one only.
