### ISSUE TITLE
Move "deployment_yamls" folder under "install" folder

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#738]
**Description**
A small chore is needed to be done in order to consolidate top-level folders. [deployment_yamls](https://github.com/layer5io/meshery/tree/master/deployment_yamls) can be moved under the [install](https://github.com/layer5io/meshery/tree/master/install) folder. 

**Implementation**
1. Move folder/files.
1. The Meshery Kubernetes deployment instructions will need to be updated with this new location.

**Comment by leecalcote** [comment]
@nunix does the [docker app package](https://github.com/layer5io/meshery/tree/master/mesheryapp.dockerapp) need to be top-level or can this, too, be relocated under the "install" folder?

**Comment by nunix** [comment]
Hi all, sorry just seeing this now, and yes no problem having it moved
