### ISSUE TITLE
Move "mesheryapp.dockerapp" folder under "install" folder

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#742]
**Description**
A small chore is needed to be done in order to consolidate top-level folders. [docker app package](https://github.com/layer5io/meshery/tree/master/mesheryapp.dockerapp) can be moved under the [install](https://github.com/layer5io/meshery/tree/master/install) folder. 

**Implementation**
1. Move folder/files.
1. The Meshery Docker App deployment instructions will need to be updated with this new location.

**Comment by leecalcote** [comment]
@chandresh-pancholi Would you like to take this one?

**Comment by ashiscs** [comment]
@leecalcote sir, but there is no instructions for Meshery Docker App deployment.

**Comment by chandresh-pancholi** [comment]
@leecalcote I will look at it.

**Comment by nunix** [comment]
nope, I will write them in the coming days 😅

**Comment by leecalcote** [comment]
Done. ✔️
