### ISSUE TITLE
[Readme] Include a screenshot of Meshery's service mesh configuration best practices

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#744]
**Current State:**
Meshery's ability to check a service mesh's configuration against best practice uses is under-represented. 

**Desired State:**
Incorporate the screenshot below into the 

- [ ] Meshery repo readme.md.
- [ ] the [overview.md](https://github.com/layer5io/meshery/blob/master/docs/pages/overview.md) in Meshery docs

**Screenshot**
<img width="1582" alt="service-mesh-configuration-best-practices" src="https://user-images.githubusercontent.com/7570704/77011431-da9d0f80-6939-11ea-8662-b54f3bb485db.png">

**Comment by leecalcote** [comment]
@nidhinmahesh Would you like to address this one?

**Comment by nidhinmahesh** [comment]
Yes. 👍

**Comment by leecalcote** [comment]
@nidhinmahesh see https://github.com/meshery/meshery.io/pull/130 as an example.
