### ISSUE TITLE
[MeshSync] Support discovery of Citrix Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#745]
**Current Behavior**
The /performance page scans the environment to detect the presence and details of deployed service meshes. Currently, this functionality is partially provided for Istio (just for Istio's presence and version #). 

**Desired Behavior**
Meshery should scan the environment for all known types of service meshes and their details, including Citrix CPX.

**Implementation**
Using [kubernetes-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/kubernetes-scan.go) and [istio-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/istio-scan.go) an example, create scans for each of the other types of Meshery-supported service meshes.

**Future:** each scan needs to be enhanced to gather service mesh-specific configuration details.

**Comment by nveenjain** [comment]
@leecalcote, I guess we would only need to populate [kubernetes-scan.go](https://github.com/layer5io/meshery/blob/master/helpers/kubernetes-scan.go#L16)'s meshesMeta variable,  with citrix and Octarine mesh images... Everything will work fine without any breaking changes

**Comment by leecalcote** [comment]
@nveenjain sounds right to me. 👍
