### ISSUE TITLE
[mesheryctl] Neither -v or --version returns the CLI version number

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#764]
**Description**
  -v, --version are global flags that should return the version of mesheryctl. Neither flag returns this information, however, `mesheryctl version` does.

**Expected Behavior**
Either flag should return the same information as does `mesheryctl version`

**Comment by ashiscs** [comment]
But sir @leecalcote according to this pr https://github.com/meshery/meshery/pull/653
mesheryctl -v has output verbatim that of /mesheryctl version.

**Comment by gunjanmimo** [comment]
@leecalcote  sir, should we use -v for version checking which is global used for verbose mode?

**Comment by gunjanmimo** [comment]
@leecalcote sir, I have doubt that do we need to replace `mesheryctl version` by `mesheryctl --version`?

**Comment by leecalcote** [comment]
@gunjanmimo we could, but supporting all three methods is simple enough and makes it convenient for users who may not recall precisely which command to use.

**Comment by leecalcote** [comment]
In the future, it may be the case the the `-v` is reserved for verbose mode.

**Comment by gunjanmimo** [comment]
ok, sir, I will add both --version and -v option. This will be helpful

**Comment by ashiscs** [comment]
But sir @leecalcote i guess -v is already supported as the pr landed by anirudhjain shows
https://github.com/meshery/meshery/pull/653

**Comment by leecalcote** [comment]
@ashiscs Oh, I missed that. The output was hidden in my terminal buffer. In this case, the update that we need here is to remove the help output (see below) and simply display the version info.

```
~ mesheryctl -v


Client Version: 0.3.11
Server Version: 0.3.11
GitSHA:2f20e18af829df593b94a670fa70c62d80a5344e

Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Available Commands:
  cleanup     Clean up Meshery
  help        Help about any command
  logs        Print logs
  pref        Performance testing and benchmarking
  start       Start Meshery
  status      Check Meshery status
  stop        Stop Meshery
  update      Pull new Meshery images from Docker Hub.
  version     Version of mesheryctl

Flags:
      --config string   config file (default location is: $HOME/.meshery/config.yaml)
  -h, --help            help for mesheryctl
  -t, --toggle          Help message for toggle
  -v, --version         Version of mesheryctl

Use "mesheryctl [command] --help" for more information about a command.
```
