### ISSUE TITLE
[mesheryctl] GitSHA in `mesheryctl version` should specify client vs server

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#765]
**Current Behavior**
`mesheryctl version` returns:
```
Client Version: 0.3.11
Server Version: 0.3.11
GitSHA:2f20e18af829df593b94a670fa70c62d80a5344e
```
**Desired Behavior**
The GitSHA in this response should be identified as being related to the client (as opposed to the server). Its indistinguishable currently.

**Comment by gunjanmimo** [comment]
@leecalcote sir, is this issue open, I will like to work?

**Comment by ashiscs** [comment]
And sir @leecalcote in this issue do we need to replace the value printed by GitSHA similar to value printed by client version??

**Comment by leecalcote** [comment]
@ashiscs to improve the client version experience, we can reformat the `mesheryctl version` output like so:

```
Client Version: 0.3.11      GitSHA: 2f20e18af829df593b94a670fa70c62d80a5344e
Server Version: 0.3.11
```

**Comment by leecalcote** [comment]
@gunjanmimo yes, please. Please see Issue #603 for an understanding of the fact that the `Server Version` is a placeholder for functionality that has yet to be delivered.

**Comment by ashiscs** [comment]
Got it sir @leecalcote

**Comment by leecalcote** [comment]
@gunjanmimo reference - https://github.com/spf13/cobra/blob/master/command_test.go
