### ISSUE TITLE
Include Meshery in SMI's ecosystem

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#768]
**Current Behavior**
https://github.com/servicemeshinterface/smi-spec dose not list Meshery

**Desired Behavior**
The SMI Spec readme should include "Meshery: the service mesh management plane (meshery.io)"

**Comment by nveenjain** [comment]
Done @leecalcote , This issue can be closed!

**Comment by leecalcote** [comment]
Thank you, sir. 👍
