### ISSUE TITLE
[MeshSync] Expose functionalities to scan prometheus and grafana

### ISSUE THREAD

**Issue by nveenjain** [layer5io/meshery#770]
**Current Behavior**

When we want to know what Prometheus or grafana instances are deployed in the cluster, we have to let user enter the URL or prometheus/grafana manually in meshery dashboard. This is little inconvenient and can be automated.

**Desired Behavior**

Currently we've implemented ScanPromGrafana functionality in https://github.com/layer5io/meshery/blob/master/helpers/kubernetes-scan.go#L83 
This functionality isn't exposed by the Rest API that meshery supports. It would be very useful if this functionality is exposed by the API. 

---
**Resources**

1. Add Request handler in [this file](https://github.com/layer5io/meshery/blob/master/handlers/prometheus_handlers.go) and send the result of  ScanPromGrafana in response.
2. Expose the endpoint in [this file](https://github.com/layer5io/meshery/blob/master/router/server.go)

**Alternatives / Additional Context**

If any help is required, feel free to comment. I'll be happy to help!

**Comment by leecalcote** [comment]
Closing this as @vijcheru previously knocked it out. 💪
