### ISSUE TITLE
Meshery Provider UI is messed up

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#771]
**Description**

Meshery Provider UI is messed up
**Expected Behavior**

After running `make run-local` , provider UI dont show options as expected.

**Comment by kushthedude** [comment]
<img width="933" alt="Screenshot 2020-03-27 at 4 18 04 PM" src="https://user-images.githubusercontent.com/44091822/77748695-c72f2a00-7046-11ea-9d6a-3b71957277ef.png">
I dont know why GitHub wont let me upload the ss in the issue description itself.
cc: @leecalcote I dont think this is expected behaviour or am I missing something?

**Comment by kushthedude** [comment]
@Nikhil-Ladha When you made the PR for provider-UI description, was the Provider-UI working as expected ?

**Comment by Nikhil-Ladha** [comment]
Yes. And moreover, I think you don't have the latest changes as I have made the "provider" in the line "Please choose a provider to continue" clickable and opening a modal on clicking.

**Comment by kushthedude** [comment]
I pulled up latest changes from the master just now and this is the result.

**Comment by Nikhil-Ladha** [comment]
That's interesting because it was showing correctly on my system. If @leecalcote sir could also check it once, then we can go ahead with it.

**Comment by kushthedude** [comment]
Try it once again and let me know.

**Comment by leecalcote** [comment]
Gents,

Here's a few screenshots of the latest release running on my local machine:

<img width="1105" alt="Screen Shot 2020-03-27 at 1 46 28 PM" src="https://user-images.githubusercontent.com/7570704/77789682-7c56e780-7031-11ea-935c-4f1d1d3998f1.png">
<img width="1105" alt="Screen Shot 2020-03-27 at 1 46 36 PM" src="https://user-images.githubusercontent.com/7570704/77789687-7fea6e80-7031-11ea-8d42-6cd4631fa7cd.png">
<img width="1105" alt="Screen Shot 2020-03-27 at 1 46 43 PM" src="https://user-images.githubusercontent.com/7570704/77789690-80830500-7031-11ea-9990-b4c7aeaf4813.png">

**Comment by Nikhil-Ladha** [comment]
Thanks @lee sir!. There is an outstanding PR from me which completes the work.

**Comment by kushthedude** [comment]
I will see if it is issue on my local. Its quite weird indeed.

**Comment by leecalcote** [comment]
@kushthedude sounds good. Folks occasionally miss the `make build-ui` step before running `make run-local`, which might be something to look at.

**Comment by kushthedude** [comment]
That was strange, After removing the node-modules and reinstalling them fixed this up. 
Thanks for the help @leecalcote @Nikhil-Ladha

**Comment by leecalcote** [comment]
Weird. Sure, you bet, @kushthedude.
