### ISSUE TITLE
[UI] Display discovered Prometheus and Grafana instances

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#772]
**Current Behavior**
Based on #770, Meshery is cognizant of whether Prometheus and Grafana instances are deploying in the currently connected Kubernetes cluster.

However, Meshery does not automatically expose the Prometheus or Grafana instances in the UI. 

**Desired Behavior**
If only one instances of Prometheus or Grafana or one of both is available, set these as the active Prometheus and Grafana connections. User can change these connections in the /settings screen. Users can see these connections in the Dashboard screen. Users can also click to perform an ad-hoc "ping" (connectivity test) between Meshery and the Prom and Graf instances.

**Example**
Ideally, this field is pre-populated with the Grafana endpoint.

<img width="1122" alt="Screen Shot 2020-03-27 at 10 57 00 PM" src="https://user-images.githubusercontent.com/7570704/78047209-b67bfe00-733d-11ea-8a43-52bf6bae107c.png">

---
**Future**
- support more a than one connection to Prometheus
- support more than one connection to Grafana

**Comment by leecalcote** [comment]
@shivaylamba are you up to the task here

**Comment by kalradev** [comment]
Hey, can I take this up?

**Comment by PluckyPrecious** [comment]
> Hey, can I take this up?

@leecalcote @kushthedude
