### ISSUE TITLE
[mesheryctl]: Fail to upgrade mesheryctl to the latest version

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#775]
**Description**

On upgrading mesheryctl using curl command, upgradation is done only upto version 0.3.9. Inspite of the fact that higher versions are available for upgrade.

**Expected Behavior**

On upgrading mesheryctl, latest version of mesheryctl should be downloaded.

**Comment by leecalcote** [comment]
Thank you, @Nikhil-Ladha. 

@nupur-thakur would you like to have a look here?

**Comment by nupur-thakur** [comment]
Yes Sure @leecalcote Sir.

**Comment by leecalcote** [comment]
@nupur-thakur as inspiration - this project's approach is somewhat novel and very well done - https://shipyard.run/apply

@anandrkskd did you and @nupur-thakur put together a design to solve this? If so, will you guys update the [Meshery Installation & Packaging](https://docs.google.com/document/d/1inncJ56SKEzIMIUikzj3XdCWF4d0xdtzOcq6J4GQYz0/edit#) design spec?

**Comment by kushthedude** [comment]
I have been struggling with this since hours, blaming my machine for not upgrading the version.

**Comment by kushthedude** [comment]
Not only with curl command, `mesheryctl update` also don't go above 0.3.9

**Comment by leecalcote** [comment]
@kushthedude oh, right. You're comment highlights that we need to organize and clarify the various sets of CLI commands that `mesheryctl` will have. This particular command currently performs the task of updating the meshery containers only. Arguably, it should also take care of the task of updating `mesheryctl`. Whether it should or not / the approach that it takes should be dependent upon which manner of installation the user choose for mesheryctl (bash, brew, .... scoop), though.
