### ISSUE TITLE
Results pagination showing different result count per page

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#80]
**Describe the bug**
Meshery -> Results -> The table is showing paginated results from Dynamo. The issue is that due to the way Dynamo scans + filters work, the number of records returned is inconsistent.

**To Reproduce**
1. Go to 'Results'
2. Not all pages will have the same result count

**Expected behavior**
The pagination works consistently.

**Comment by girishranganathan** [comment]
@leecalcote, I think this is a good time to start moving away from Dynamo. . . I will gradually start migration to RDS. Will leverage pgsql + JSON for flexibility.

**Comment by leecalcote** [comment]
@girishranganathan SGTM
