### ISSUE TITLE
[Workflow] Star count for Slack notifier

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#800]
**Description**
The GitHub Action workflow to notify the #buzz channel in Slack is broken after a recent enhancement to include the total count of stars in the notification.

**Screenshots**
<img width="994" alt="Screen Shot 2020-04-05 at 9 57 09 PM" src="https://user-images.githubusercontent.com/7570704/78519351-b4c09900-7788-11ea-87d6-a64f3019d056.png">

**Comment by leecalcote** [comment]
@subhamkrai any ideas to the approach for this fix?

**Comment by subhamkrai** [comment]
> @subhamkrai any ideas to the approach for this fix?

Not definite solutions but can try one more thing...if you have something I'll happy to that.

**Comment by leecalcote** [comment]
@subhamkrai I haven't look. I'm pinging because its currently broken and so no notifications are coming through. It would be good to revert the change while a fix is pending.

**Comment by kushthedude** [comment]
@subhamkrai  I don't see Action notifier to include the star count, which should have been included after #834.

**Comment by subhamkrai** [comment]
> @subhamkrai I don't see Action notifier to include the star count, which should have been included after #834.

@kushthedude seems little weird why it didn't work. Are you able to find any loophole?
