### ISSUE TITLE
Docs: Adding "Updating with Scoop" section to mesheryctl quick start guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#811]
**Current State:**
Instructions for installing `mesheryctl` with Scoop are available.

**Desired State:**
Akin to other installers, Scoop instructions for how to upgrade `mesheryctl` should be available as well.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@nupur-thakur interested here by chance?

**Comment by nupur-thakur** [comment]
Yes Sure, I'll look into it, Sir.
