### ISSUE TITLE
Go Compile error with Grafana_helper.go

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#817]
When compiling current code with latest grafana_helper. There is error
` c.GetActualOrg undefined (type *sdk.Client has no field or method GetActualOrg) ` on line 61,129 at grafana_helper.go 

Fix this error 

Reference :
https://github.com/grafana-tools/sdk/blob/f0431e44c1c35b20751dc4c210a00b4c0d09d1d5/rest-org.go#L76
See here and update the code.

**Comment by kushthedude** [comment]
cc: @Aisuko @leecalcote

**Comment by leecalcote** [comment]
@kushthedude good catch. We'll want to track this dependency opened by @Aisuko - https://github.com/grafana-tools/sdk/issues/81
