### ISSUE TITLE
Addition of Spell Test in CI

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#827]
Addition Go-SpellTest in the current CI-Workflow.

___

### Resources -:
https://github.com/client9/misspell
https://github.com/client9/misspell#gometalinter

**Comment by kushthedude** [comment]
@leecalcote How does it sounds?

**Comment by nveenjain** [comment]
+1 for the spell test! While misspell is great,  I do have a suggestion:- Can we use https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell, it also has support for almost all programming languages and some common computer science terms and is extensible (just need to add a file in repo). We can also propose our own terms to https://github.com/streetsidesoftware/cspell-dicts

**Comment by kushthedude** [comment]
> https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell

Its npm engine, How will you support go with it? Also, Eslint has spell check plugin.

**Comment by nveenjain** [comment]
@kushthedude , it installs using npm, but it supports every major language that we are using in the project (go, javascript, html,css)

https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#features

It also has extension for VSCode, and can be easily integrated with the CI pipeline.

**Comment by kushthedude** [comment]
No, thats what not I am getting.
To use in GitHub Actions you will first install node and then npm and then grab the dependency with the npm engine. 
Cool, If this is what we need to do at place of a single line of go get _____.

**Comment by nveenjain** [comment]
I'm suggesting this for entire codebase(JS,go based code, CSS files,etc) not for only go based code. (for the complete file, not only comments, cspell, as I see, checks only for comments). We already install node and can install this globally... 
https://github.com/meshery/meshery/blob/master/.github/workflows/ci.yml#L122

**Comment by leecalcote** [comment]
Stale issue? Please reopen at your leisure.
