### ISSUE TITLE
Trigger PR specific CI jobs

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#849]
**Current Behavior**

Currently, we are triggering all CI jobs irrespective of PR type. As discussed in the CI W/G, we need to trigger CI jobs that are related to PR which will reduce the CI Build Time as well as will be easy to manage.

**Desired Behavior**

Preferred Area->Jobs Relation -:

- Documentation -> Only run netlify
- Server -> Run Go-Vet/Sec/Tests/ErrCheck/Error-Test/Static-Check/Revive-Lint + Server Build Check
- Mesheryctl -> Run Go-Vet/Sec/Tests/ErrCheck/Error-Test/Static-Check/Revive-Lint + Mesheryctl build & releae 
- UI -> Run Tests+Lint+Build

**Way to move forward**

We are planning to incorporate conditional logic on the basis of PR Labels to let us know in what area does the PR include changes after then we will decide on the basis of the label to trigger the CI Jobs.

---
**Alternatives / Additional Context**

See https://github.com/layer5io/meshery/pull/832#pullrequestreview-392472434

**Comment by kushthedude** [comment]
/cc @leecalcote @naturalett 
Please let me know if there are any more changes required in CI Workflows.

**Comment by leecalcote** [comment]
Ready for Labeler action.

**Comment by leecalcote** [comment]
Ready to reinstitute the Labeler action.

**Comment by leecalcote** [comment]
`labeler.yml` config and `pr-labeler.yml` workflow reinstated

**Comment by leecalcote** [comment]
Another step taken here. 

```
   paths-ignore:
      - 'docs/**'      
```

This has been added to ci.yml and build and release.yml
