### ISSUE TITLE
Move mesheryctl cleanup -> mesheryctl reset

### ISSUE THREAD

**Issue by anandrkskd** [layer5io/meshery#855]
**Current Behavior**
mesheryctl cleanup is the command to remove old meshery.yml file with default one.

**Desired Behavior**
A renaming of  `mesheryctl cleanup` to `mesheryctl reset` as the name of the command.
so that `mesheryctl reset` should be  the command to remove current meshery.yml file with default meshery.yml.

**Comment by gunjanmimo** [comment]
@anandrkskd I am taking this issue
