### ISSUE TITLE
[UI] TypeError: null is not an object (evaluating 'tableState.announceText.split')

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#868]
**Description**

When I access to routers `/results` and will get the error

**Expected Behavior**

 The UI work well
**Screenshots**

![Screen Shot 2020-04-20 at 11 28 13 AM](https://user-images.githubusercontent.com/8053949/79711298-0bd27c00-82fa-11ea-97c7-20439fd35e3c.png)

![Screen Shot 2020-04-20 at 11 25 57 AM](https://user-images.githubusercontent.com/8053949/79711170-b5fdd400-82f9-11ea-949c-1547cb2408f1.png)

**Environment:**
 - OS: [e.g. Ubuntu]
    * MacOS
 - Browser: [e.g. Chrome, Safari]
   * Safari
 - Version: [e.g. 22]
   * Version 13.0.2 (15608.2.30.1.1)
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**The Meshery was used by me is the version which includes the PR  #856, please to reproduce the behavior with the branch which includes the PR**

**Comment by kushthedude** [comment]
Looking at it

**Comment by kushthedude** [comment]
@Aisuko This behaviour is still present in meshery, there is no connection of this behaviour & changes you made in PR #856 . It is most probably the pre-fetching of results which are not even present. Also, this behaviour only occurs when there are no test results present in the meshery.
Let me know if anything I mentioned above is not correct.

**Comment by leecalcote** [comment]
@nveenjain and I experience this issue when results are present as well. @Nikhil-Ladha help!

**Comment by Aisuko** [comment]
Thanks 👍
