### ISSUE TITLE
Docs: Footer Formatting

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#870]
**Current State:**

The docs footer is off-center both horizontally and vertically.

<img width="1573" alt="Screen Shot 2020-04-20 at 8 15 04 AM" src="https://user-images.githubusercontent.com/7570704/79755694-24816880-82df-11ea-82ce-84e1176dbe0a.png">
**Desired State:**
<img width="1573" alt="Screen Shot 2020-04-20 at 8 15 04 AM" src="https://user-images.githubusercontent.com/7570704/79755878-690d0400-82df-11ea-9c9d-b7afb4befff9.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by rubenlorenzo** [comment]
Hello @leecalcote, I am looking to solve it.

**Comment by ashiscs** [comment]
GO ahead @rubenlorenzo

**Comment by leecalcote** [comment]
Hi @rubenlorenzo, that would be fantastic. Yes, please. I welcome you to join the community Slack as well - http://slack.meshery.io. It would be nice to have you join.
