### ISSUE TITLE
[Meshery] Add the Service Meshes drop-down list show the meshes adapters name 

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#875]
**Current Behavior**

 I'm developing Meshery at the localhost and when I want to add the adapter at my local. And the debug console while getting the error message below. 

```
ERRO[1325] unable to unmarshal user: invalid character 'u' looking for beginning of value 
DEBU[1325] meshLocationURL: mesherylocal.layer5.io:10000 
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"\u001b[31mERRO\u001b[0m[1325] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host\" \r\n"}}
ERRO[1325] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host" 
```

Should we transfer the domain name to localhost If we notice that Meshery did not deploy to Kubernetes cluster

**Desired Behavior**

Meshery can work well with no Kubernetes cluster situation
---
**Resources**

* Steps to reproduce
  * Pulling the latest meshery code 
  * Run `make run-ui-dev`
  * Debug with `meshery` and keeping start server at the default port

**Alternatives / Additional Context**

![Screen Shot 2020-04-21 at 3 24 07 PM](https://user-images.githubusercontent.com/8053949/79838139-233a6380-83e5-11ea-9dd7-257e66d9855d.png)

**Comment by leecalcote** [comment]
@Aisuko, an item to check - 

- Do you have mesherylocal.meshery.io entered into your /etc/hosts file pointing to your loopback interface (127.0.0.1)?

**Comment by Aisuko** [comment]
> @Aisuko, an item to check -
> 
> * Do you have mesherylocal.meshery.io entered into your /etc/hosts file pointing to your loopback interface (127.0.0.1)?

Maybe we can add these contents to the document

**Comment by leecalcote** [comment]
Certainly, yes. I'm not sure how well highlighted it is now (how well the docs flow) - https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#running-meshery-from-ide. What do you think? Update at-will.

**Comment by Aisuko** [comment]
Oh, I saw the document right now and doing well.
