### ISSUE TITLE
Ability to restart mesheryctl

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#878]
**Current Behavior**

We provide `mesheryctl start/stop`, but there can be an instance when someone changes the config file or make some code changes. He/she would want to restart the mesheryctl, but for now, we have first stop and then start which when carried out for long may seem frustrating & if there would be a restart command for the mesheryctl, it would have eased the pain.

**Alternatives / Additional Context**

It happened with me 5 times today when I change some YAML & had to manually start/stop mesheryctl and at that point, I thought how much better would it have been if we provided restart command too.
It is indeed a proposal which may invite a variety of opinion from the community.

**Comment by kushthedude** [comment]
cc: @leecalcote

**Comment by thakursaurabh1998** [comment]
@kushthedude I don't think the code change point is valid if someone is using the `mesheryctl` cli, code change makes sense when development is going on.

**Comment by kushthedude** [comment]
> @kushthedude I don't think the code change point is valid if someone is using the `mesheryctl` cli, code change makes sense when development is going on.

It is still a proposal, also my main point was when someone makes changes in `kube config`, `Adapter URLs`, `Configuration YAMLs`. I would have to go all back to stop & restart, and think a restart subcommand would have done all this.

**Comment by thakursaurabh1998** [comment]
I definitely support the idea of a reset command, kudos to you 👏🏼.  I was just pointing out where the reset command would really be helpful. :)

**Comment by leecalcote** [comment]
@kushthedude great suggestion. Makes sense. 👍

**Comment by leecalcote** [comment]
Re-reading this proposed enhancement, I'll make note of `mesheryctl cleanup` (in case folks in this thread aren't already aware of this command), which grabs a pristine copy of meshery.yaml (docker-compose.yaml) from GitHub and resets the local config file. At this point, I think both @kushthedude and @thakursaurabh1998 are aware of this command given the notion that `cleanup` will ideally be renamed `reset`.

@thakursaurabh1998, there is need for some forethought and planning to go into the structure of mesheryctl commands when considering all of the forthcoming functionality to be exposed through it. Let's chat on this topic in one of our upcoming meetings.

**Comment by nitishm** [comment]
Maybe take the istioctl approach with an "experimental" set of commands ? Just a suggestion. May be out of context.

**Comment by leecalcote** [comment]
Quick update: 

- as of v03.15, `cleanup` has been displaced by `reset`
- as of v0.4.0, the command structure will be `mesheryctl system restart`

**Comment by leecalcote** [comment]
@ tharun208 will you give this a review?
