### ISSUE TITLE
Docs: Project, Releases, Security Vulnerability navigation links broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#879]
**Current State:**
The Project, Releases, Security Vulnerability pages need to be updated to respond to /project/releases, /project/security-vulnerability.

**Desired State:**
- The [project page](https://meshery.layer5.io/docs/project) needs an iterator added to it to display links to all pages under this category similar to the [guides page index](https://meshery.layer5.io/docs/guides).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@gunjanmimo @ashiscs @manishdangi98 would one of you like to take this one on?

**Comment by manishdangi98** [comment]
@leecalcote sure

**Comment by leecalcote** [comment]
Thank you, @manishdangi98. 👍
