### ISSUE TITLE
Localise Go Tests performed by CI

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#893]
All the Go Tests performed by GitHub Actions have not been localised, which means user can't test all these checks like fmt, lint, vet etc on it's local.

I propose to localise all these tests to improve the UX for Meshery Server!

Opinions/Comments Welcome.

**Comment by gunjanmimo** [comment]
this repo could be helpful https://github.com/nektos/act

**Comment by kushthedude** [comment]
I was thinking to go by traditional way. But this seems interesting to me,
I will check it out.

**Comment by kushthedude** [comment]
I checkout act, it is a great tool but it has limited amount of support. Considering the vast platform support which Meshery offers using act will only limit users.

**Comment by dhruv0000** [comment]
Can I work on this @kushthedude ?

**Comment by kushthedude** [comment]
Sure, go ahead @dhruv0000
