### ISSUE TITLE
[Docs] Kubernetes endpoint not reachable using minikube with "docker" driver

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#894]
**Current State:**
If installed minikube using driver as docker i.e, `minikube start --driver=docker`. Then the container of minikube is created on a separate network in docker having a different subnet. Whereas the meshery container has a separate subnet. That's being the reason meshery is not able to ping the kubernetes server on uploading the kube-config file to meshery.

**Desired State:**
Meshery should be able to communicate with kubernetes server automatically, even in such situation. It should check that and configure the address accordingly. But, this can be done using docker bridge and add the meshery container to minikube using `docker network connect bridge meshery_meshery_1` .  Here `bridge` is the network name of minikube.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Pictorial description of the issue - https://docs.google.com/drawings/d/1t40B6sn7RVH3z0ZVOvFD4wxv8YXemyq5JlHugy9_x7A/edit

![Meshery Issue #984](https://user-images.githubusercontent.com/7570704/80429869-b0345f80-88b2-11ea-9d8d-1c215e61470f.png)

**Comment by kumarabd** [comment]
@leecalcote  I did do a workaround on this issue. Basically had used a localhost entry of `minikubeCA` to point to host's ip address. Then I put that in the kubeconfig so that it resolves to the host rather than localhost. I used `minikubeCA` because minikube has a set of dns that is signed with the CA cert, and this was one of them.

**Comment by leecalcote** [comment]
@nitishvu does this make sense? Are you available to assist in documenting this?

**Comment by Nikhil-Ladha** [comment]
> @nitishvu does this make sense? Are you available to assist in documenting this?

@leecalcote I think this has already been documented. Not sure why the issue is still open.
