### ISSUE TITLE
Adapters not discoverable after introduction of JWT

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#899]
**Description**

Adapters not discoverable after the introduction of JWT

**Expected Behavior**

Adapters should discoverable as have been working before of JWT

**Screenshots**

<img width="1229" alt="Screenshot 2020-04-27 at 12 20 23 AM" src="https://user-images.githubusercontent.com/44091822/80316761-40c06080-881d-11ea-90a0-689b73d15507.png">

**Logs**

```sh
INFO[0222] retrieved user: {kushthedude   https://avatars0.githubusercontent.com/u/44091822?v=4}
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.layer5.io: no such host"
```

---

[Optional] **Additional Context**

Use command `make run-local` and see the error.

**Comment by nveenjain** [comment]
@kushthedude , just one thing to check, have you configured `/etc/hosts` file so that `mesherylocal.meshery.io` points to localhost?

**Comment by kushthedude** [comment]
@nveenjain This is the file, I think it is already pointing to localhost.
<img width="591" alt="Screenshot 2020-04-27 at 3 07 09 AM" src="https://user-images.githubusercontent.com/44091822/80320482-437a8000-8834-11ea-8065-a2382b77e46d.png">

**Comment by nveenjain** [comment]
Can you try opening `mesherylocal.meshery.io:9081` and see if it is working(opening up the meshery adapter page, authentication might not work as JWTs are maybe domain specific and work currently only for localhost)...

If it doesn't work, restarting the system might help...

**Comment by kushthedude** [comment]
No, mesherylocal.meshery.io:9081 it is not working.
Neither the restart.

**Comment by nveenjain** [comment]
@kushthedude sorry, I just missed the error hosts file, I guess your entry should be

`127.0.0.1	mesherylocal.meshery.io`

**Comment by nveenjain** [comment]
try switching the IP and hostname, and it should work... 
A system reboot maybe required...

**Comment by kushthedude** [comment]
Trying it right away!

**Comment by kushthedude** [comment]
Two things:
- Token is not received while using URL `mesherlocal.meshery.io:9081`.
- Adapters are still not discoverable, with same error log.

**Comment by nveenjain** [comment]
Yes, tokens doesn't work in URL  `mesherlocal.meshery.io:9081`. This is something that was notified in slack #meshery channel a few days back... Opening an issue and assigning Kanishkar would be a nice idea...
Regarding error logs, can you please again paste the error logs, i assume host must be reachable, and maybe adapters can't be pinged...

**Comment by kushthedude** [comment]
> Yes, tokens doesn't work in URL `mesherlocal.meshery.io:9081`. This is something that was notified in slack #meshery channel a few days back... Opening an issue and assigning Kanishkar would be a nice idea...
> Regarding error logs, can you please again paste the error logs, i assume host must be reachable, and maybe adapters can't be pinged...

Same logs
```sh
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
ERRO[0222] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mesherylocal.meshery.io: no such host"
```

**Comment by nveenjain** [comment]
I wonder why this is happening, `mesherylocal.meshery.io` should be able to connect... 
Can you try running `host mesherylocal.meshery.io` in your terminal...

**Comment by kushthedude** [comment]
`Host mesherylocal.meshery.io:9081 not found: 3(NXDOMAIN)`

**Comment by nveenjain** [comment]
Ideal output should be (if hosts file is properly applied)

```bash
host mesherylocal.meshery.io
mesherylocal.meshery.io has address 127.0.0.1
Host mesherylocal.meshery.io not found: 3(NXDOMAIN)
```

Can you confirm that /etc/hosts has correct config and restart system once again??

**Comment by nveenjain** [comment]
A workaround would be to replace all `mesherylocal.meshery.io` with `127.0.0.1` or localhost
at https://github.com/meshery/meshery/blob/master/Makefile#L1

**Comment by kushthedude** [comment]
<img width="499" alt="Screenshot 2020-04-27 at 4 22 08 AM" src="https://user-images.githubusercontent.com/44091822/80321899-acff8c00-883e-11ea-91b9-69b24188427b.png">

mesherylocal.meshery.io:9081 is pointing me to provider UI. I don't think there should be an error in config.
I don't know why `host mesherylocal.meshery.io` is showing this output.

**Comment by kushthedude** [comment]
Also one more thing to note, my `etc/hosts` was not configured before JWT but I was quite well able to use meshery . Also this redirection of host is not mentioned in any readME, would it be worth to document this ?

**Comment by kushthedude** [comment]
> A workaround would be to replace all `mesherylocal.meshery.io` with `127.0.0.1` or localhost
> at https://github.com/meshery/meshery/blob/master/Makefile#L1

Workaround is also not working throwing the same error logs!
```shERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10000: connect: connection refused"
ERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10001: connect: connection refused"
ERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10002: connect: connection refused"
ERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10003: connect: connection refused"
ERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10004: connect: connection refused"
ERRO[0023] Error creating a mesh client.: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:10008: connect: connection refused"
```

**Comment by nveenjain** [comment]
>  Also this redirection of host is not mentioned in any readME, would it be worth to document this ?

Actually, it is mentioned in [Contributing.md](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#running-meshery-from-ide) but yeah it should be made more visible...

**Comment by nveenjain** [comment]
> Workaround is also not working throwing the same error logs!

These errors are expected... Maybe adapters are not running in your system? maybe cloning any adapter and runnign them would work...

**Comment by kushthedude** [comment]
> > Workaround is also not working throwing the same error logs!
> 
> These errors are expected... Maybe adapters are not running in your system? maybe cloning any adapter and runnign them would work...

That is why I opened the issue, BTW all this is after #892 gets merged as I am using #892 as my base currently.

**Comment by nveenjain** [comment]
ohhh, i'll checkout the PR too... I thought this was on master branch...

**Comment by nveenjain** [comment]
It is working on that PR too @kushthedude. also `host mesherylocal.meshery.io` should emit
```
mesherylocal.meshery.io has address 127.0.0.1
Host mesherylocal.meshery.io not found: 3(NXDOMAIN)
```
I guess we need to debug that...

**Comment by kushthedude** [comment]
We do need a debugging call then I presume. @leecalcote @kanishkarj

**Comment by kushthedude** [comment]
Thanks to @nveenjain I was able to fix the issue on my local!
