### ISSUE TITLE
[CI] Add the cache action to the CI

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery#902]
**Current Behavior**

Every time needs to redownload the dependencies for building.

**Desired Behavior**

The action allows caching dependencies and builds outputs to improve workflow execution time.

---
**Resources**

**Alternatives / Additional Context**

**Comment by leecalcote** [comment]
Adding to today's CI Working Group meeting agenda.

**Comment by Aisuko** [comment]
Fixed by #972
