### ISSUE TITLE
UI:  Populate 'Test Name' in Performance page for unnamed tests

### ISSUE THREAD

**Issue by aayushdutt** [layer5io/meshery#907]
**Current Behavior**
When a test without a name is run, it is assigned a name automatically on the server. Currently, there is no way to view which name is assigned to the test.
![image](https://user-images.githubusercontent.com/25280541/80430428-36c95b00-890c-11ea-8a56-71cdc89075b9.png)

**Desired Behavior**
It will be better if the 'Test Name' field gets populated automatically after the test results are fetched.
![image](https://user-images.githubusercontent.com/25280541/80430438-3d57d280-890c-11ea-92eb-50ec2296f73b.png)

---
**Resources**

**Alternatives / Additional Context**

**Comment by leecalcote** [comment]
Thank you, @aayushdutt. Great description and articulation of a behavior improvement that would signal to the user what test name they should refer to in the /results page when referencing their results in the future.
