### ISSUE TITLE
UI: TypeError: Cannot assign to read only property 'query' of object '#<Object>'

### ISSUE THREAD

**Issue by aayushdutt** [layer5io/meshery#909]
**Description**
When I go to `/management` I get this error
![image](https://user-images.githubusercontent.com/25280541/80431296-afc9b200-890e-11ea-9757-79f1ac55da73.png)

**Expected Behavior**
Management page should open without any errors.

**Environment:**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 80
 - Device: laptop
---
[Optional] **To Reproduce**
Steps to reproduce the behaviour:
1. Start dev server: `make run-ui-dev`
2. Go to `/management`
3. See error

[Optional] **Additional Context**
The error only appears in UI dev server (localhost:3000) and not on localhost:9081

**Comment by nveenjain** [comment]
This line can be removed!
