### ISSUE TITLE
Convert the `no-used-var` & `no-undef` rule to error

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#910]
**Description**

We have recently set up ES-Lint rules for our client-side code. Due to poor code quality & to begin with, we had to use these rules as optional so that error does not occur. But, this is one of the most occurring error in our codebase of the client-side.

**Expected Behavior**

Remove all `unused-var` & `no-undef` variables to accommodate to extend the ES-Lint rules.

** Work on Local**

To check this error on local:-

https://github.com/layer5io/meshery/blob/3f21f32ab9008d9a2410221f08fcb0a79ccbcf9e/ui/.eslintrc.js#L50
https://github.com/layer5io/meshery/blob/3f21f32ab9008d9a2410221f08fcb0a79ccbcf9e/ui/.eslintrc.js#L42
Change the `warn` & `off` to `error` respectively and then run `npm test` to see all the places where we have this bug.

**Additional Context**

This will require a lot of files to change. New contributors & old contributors are encouraged to pick-up a file or a component so that the progress can be subsequently increased.

**Comment by kushthedude** [comment]
@aayushdutt Would you like to take care of remaining errors ?

**Comment by aayushdutt** [comment]
@kushthedude  I'd love to. Not my highest priority at the moment though.
