### ISSUE TITLE
mesheryctl: Build & Release process failing

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#915]

**Comment by leecalcote** [comment]
Thanks for working on this, @kushthedude

**Comment by kushthedude** [comment]
> Thanks for working on this, @kushthedude

This is getting quite ugly, https://github.com/meshery/meshery/pull/914 I fix one issue another pops up, all due to zero CGO support of goreleaser.

**Comment by nveenjain** [comment]
This issue is most likely due to https://github.com/vmihailenco/taskq/issues/55. We need to update taskq package that is using `zstd` package(not compatible with all OS architectures)

**Comment by kushthedude** [comment]
This is the issue in goreleaser, as cgo is not supported where as gozstd
needs explicit flag to have cgo enabled to solve this issue.

**Comment by kushthedude** [comment]
I am looking for workarounds but atlast if nothing goes well, we could make
a fork and update the code as per our need. Also, grafand sdk was causing a
lot of issues but I fixed them here too.
But I hope we won't get to this state to have a fork and customize at our
will.

**Comment by nveenjain** [comment]
@kushthedude , I think upgrading `taskq` would work for this issue... If you're trying some other workaround, I might also give a shot at this and this way any of the approach that works can be used in project... 
Thoughts?

**Comment by kushthedude** [comment]
Are we even using taskq ?

**Comment by nveenjain** [comment]
It is taskq

**Comment by kushthedude** [comment]
> It is taskq

Have pushed a commit to update, let's see if it do the miracle !
