### ISSUE TITLE
Get access to kubernetes

### ISSUE THREAD

**Issue by jeusdi** [layer5io/meshery#919]
I've just installed meshery using:

    curl -L https://git.io/meshery | bash -

So, meshery is up and running.

I can reach my kubernetes from console:

```
$ kubectl cluster-info
Kubernetes master is running at https://localhost:6443
CoreDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://localhost:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
```
When I get access to meshery web interface:

> Kubernetes
> Not connected to Kubernetes.

Any ideas?

**Comment by kushthedude** [comment]
Hello @jeusdi , 
Can you try uploading the Kube-config manually?
- Go to `localhost:9081/settings`
- You will see an option to manually upload your Kube configuration
- Once you do it, you will be successfully able to connect to Kubernetes.

Please let me know if you have more doubts regarding the same.

**Comment by leecalcote** [comment]
Manually loading kubeconfig will do the trick. 👍 

There is a bug here, though. I've seen this behavior across my systems. Meshery should be automatically grabbing the kubeconfig (`~/.kube/config`) file from the user's home folder, but seems to no longer be doing this.

**Comment by kushthedude** [comment]
This but is only with mesheryctl, I have opened the issue I think.

**Comment by kushthedude** [comment]
I think we are good to close this, @jeusdi Please reach out if you have any questions/doubt.
Thanks!

**Comment by leecalcote** [comment]
@jeusdi we would love to hear any feedback you might have or just have you in our service mesh community. Please join here and say "hi". 😄 - http://slack.meshery.io

**Comment by leecalcote** [comment]
Issue #921 is related and essentially describes the same issue of the user's kubeconfig not being auto-discovered. When Meshery is deployed outside of the cluster, unless the user does not have a valid kubeconfig (with certificates directly included in the file), Meshery should auto-ingest the user's `$HOME/.kube/config` and attempt connection to the `current-context`. 

A behavior change occurred within the last month or so, causing this auto-discovery to not work in some (all?) environments. This auto-discovery functionality is important in terms of Meshery delighting users.

// @nitishm
