### ISSUE TITLE
Set up pre-commit hooks for client-side code

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#924]
Set-Up pre-commit hooks for ES-Lint.

**Comment by leecalcote** [comment]
Note: It'd be good if all current ES-Lint issues are addressed prior to instituting pre-commit hooks.

**Comment by kushthedude** [comment]
> Note: It'd be good if all current ES-Lint issues are addressed prior to instituting pre-commit hooks.

Only one issue is remaining to restore two of the major rules #910 .
