### ISSUE TITLE
Docs: Outdent "Project" section in site navigation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#928]
**Current State:**
Project section of docs navigation is indented too far.

<img width="252" alt="Screen Shot 2020-04-28 at 6 11 38 PM" src="https://user-images.githubusercontent.com/7570704/80546683-ef7ab300-897b-11ea-8f25-7473cf422028.png">

**Desired State:**
Should be shifted left (outdented).

**Comment by Vineet-Sharma29** [comment]
@leecalcote  Shall I close this issue since it has a merge PR?

**Comment by leecalcote** [comment]
@Vineet-Sharma29 normally, yes, but in this case PR #927 didn't fix this issue. The issue still persists.

**Comment by leecalcote** [comment]
Fixed by #1030

**Comment by leecalcote** [comment]
Thanks, @Vineet-Sharma29 !
