### ISSUE TITLE
Docs: Upgrade Jekyll site to Ruby 2.7.0

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#929]
**Current Behavior**
This site runs on Ruby 2.6.5.

**Desired Behavior**
Ruby 2.7.0 is available as a stable release. Ideally, this Jekyll site and the other Jekyll-based project sites are upgraded to use 2.7.0.

**Related Issues**
- meshery.io: https://github.com/layer5io/meshery.io/issues/170
- layer5.io: https://github.com/layer5io/layer5/issues/393

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Nikhil-Ladha** [comment]
@leecalcote , Won't the title be "Upgrade Jekyll site to Ruby 2.7.0" ?

**Comment by leecalcote** [comment]
@Nikhil-Ladha yes, you're right. I'm updating the title now...

**Comment by rubenlorenzo** [comment]
@Nikhil-Ladha @leecalcote, Why is it commented Gemfile? If, it is this for the upgrade ruby and other things.

**Comment by leecalcote** [comment]
Fixed by #1030

**Comment by leecalcote** [comment]
@rubenlorenzo good question... I can't say that I'm sure why Ruby version was commented out. It must have been defaulting to whatever GitHub Pages currently supports / defaults to.

**Comment by leecalcote** [comment]
Thanks, @rubenlorenzo !
