### ISSUE TITLE
Docs: Publish additional Meshery Architecture slides

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#934]
**Current State:**
The [Architecture page](https://meshery.layer5.io/docs/architecture) only has one diagram. There are multiple diagrams of Meshery's architecture depending upon your vantage point.

**Desired State:**
- Each of the architecture diagrams in the Meshery Architecture deck (slides 3 through 5 of the [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g845a92c6ce_0_441)) should be displayed.
- Diagrams should be published as an SVG.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by manishdangi98** [comment]
@leecalcote please assign me

**Comment by ashiscs** [comment]
@manishdangi98 feel free to self assign and knock the issue !!

**Comment by leecalcote** [comment]
Thank you, gents. 👍

**Comment by leecalcote** [comment]
Completed. ✔️
