### ISSUE TITLE
Performance for one query

### ISSUE THREAD

**Issue by prateeksahu** [layer5io/meshery#94]
A selection of 1 request per second, 1 concurrent request and time of 1s does not execute just one but defaults to 2 queries.

This is seen on Istio adapter. Not tested on Linkerd.

Behavior should be just one query for the experiment.

**Comment by leecalcote** [comment]
@nveenjain would you like to consider this in context of the SMI Conformance effort?

**Comment by nveenjain** [comment]
@leecalcote this would be modification in load generator, right?

**Comment by leecalcote** [comment]
@nveenjain potentially, unless you're able to provide a configuration to the load generator that restricts the generated load to a single request.

**Comment by leecalcote** [comment]
If this requires changes in the load generator, let's set this aside. I assume that we will like to have the same capability to facilitate some of the conformance tests.

**Comment by kushthedude** [comment]
Not stale
