### ISSUE TITLE
Helper module

### ISSUE THREAD

**Issue by kanishkarj** [layer5io/meshery#942]
**Current Behavior**

Meshery server and mesheryctl have a lot of helper functions which they use. Currently they are defined right next to where they are being used. Also, there might be helper functions/objects that both need to share and currently we might be replicating it in both the places. 

**Desired Behavior**

It would be helpful to have a separate go module called helper which defines all these common functions/structs.

---
**Resources**

Examples:
- SafeClose() a very important function is currently defined in both the projects.
- A couple of functions in mesheryctl/cmd/var.go 

**Alternatives / Additional Context**

**Comment by kanishkarj** [comment]
@leecalcote @nveenjain More comments? also the right tags for this issue?

**Comment by leecalcote** [comment]
@kanishkarj in context of `mesheryctl`, literally having a `helper.go` file makes much sense to me. In the larger code base of Meshery server, I can see the need for this to be a separate module, considering there are potentially a number of functions to centralize and share (perhaps).

Are you thinking this would be a shared package between mesheryctl and Meshery server or thinking of keeping their helper functions segregated?

**Comment by kanishkarj** [comment]
I was suggesting for a shared package, but there not much to share then your suggestion sounds good!
