### ISSUE TITLE
Mention about ES-Lint in contributing.md

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#943]
**Current State:**

We have recently introduced ES-Lint in our client-side code with few new make commands. 
Currently, those commands are not mentioned in contributing.md which results in failure of CI.

**Desired State:**

Mention about ES-Lint & make file commands in the UI Section of contributing.md, so that new contributors may get acquanted easily.

---

**Contributor Resources**
- Make Commands to mention:-
    - https://github.com/layer5io/meshery/blob/7e00fcb6ef2aed18d47e3f971f814512b8d2d13a/Makefile#L89
    - https://github.com/layer5io/meshery/blob/7e00fcb6ef2aed18d47e3f971f814512b8d2d13a/Makefile#L93
- [File to update](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@ishita-kumar as you venture into Meshery UI contributions, will you review this issue and confirm if it has already been addressed? If not, will you consider undertaking it?

**Comment by tory-brown** [comment]
is this still open? if i take it up, what am i expected to do?

**Comment by PluckyPrecious** [comment]
> is this still open? if i take it up, what am i expected to do?

@leecalcote @kushthedude

**Comment by kushthedude** [comment]
Fixed in https://github.com/meshery/meshery/commit/e9cb7ef8bcea5b012c8be8df3e62902158d384a8

**Comment by kushthedude** [comment]
@tory-brown You may take look at https://github.com/meshery/meshery/issues/1449
