### ISSUE TITLE
[Meshery] Versioning of Meshery Server

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#963]
**Current Behavior**
`mesheryctl --version` only returns the client version number, and a stubbed-out version number for meshery server. When meshery server is built, the release tag (as entered into GitHub releases) is not included as an artifact in the meshery server Docker image.

**Desired Behavior**
- expose the properties.yaml content a new REST endpoint: `/api/server/version`

**Related**
- mesheryctl - #603
- meshery server build - #962

**Comment by kushthedude** [comment]
I will be looking into it!

**Comment by leecalcote** [comment]
Closing given functionality provided in #1202
