### ISSUE TITLE
[UI] Results: Props not retained after sorting/searching

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#970]
**Description**

Results: Props not retained after sorting/searching
**Expected Behavior**

Table Props should be retained irrespective of any action performed on table.

**Comment by Vineet-Sharma29** [comment]
Would like to work on it. Can you tell which files to look at?

**Comment by kushthedude** [comment]
You would want to take look at components/MesheryResults .

**Comment by Nikhil-Ladha** [comment]
I just checked the table in the Results page, everything seems fine to me. Can you confirm the issue once @kushthedude ?

**Comment by kushthedude** [comment]
Already confirmed, can you share a GIF if its working fine on your local?

**Comment by Nikhil-Ladha** [comment]
![results_page](https://user-images.githubusercontent.com/29438875/89121724-054dc600-d4df-11ea-98ef-869e8ad84dca.gif)
This is what you were saying about, right?

**Comment by kushthedude** [comment]
Try to modify table props, show/hide columns and then try sorting or any
tabular function

**Comment by Nikhil-Ladha** [comment]
Tried with that too, if you could share the issue what you are facing that would be more helpful here.

**Comment by kushthedude** [comment]
@Nikhil-Ladha the bug was in the dependency & was fixed when we made a jump of 7 major versions in dependabot over here https://github.com/meshery/meshery/pull/1167 .

Thanks for bringing in to notice, I guess this can be closed 👍 !

**Comment by kushthedude** [comment]
One of the advantages of keeping dependencies in check 😄

**Comment by Nikhil-Ladha** [comment]
Woof! Nice 👍😆
