### ISSUE TITLE
[UI]: Conversion of cards into paper

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#973]
**Description**

Currently, cards are of an irregular size which makes UI look ugly.
**Expected Behavior**

Convert cards into paper
**Screenshots**

<img width="892" alt="Screenshot 2020-05-06 at 7 07 25 PM" src="https://user-images.githubusercontent.com/44091822/81184759-6a704900-8fce-11ea-85c8-c12a4a30dd79.png">

**Comment by kushthedude** [comment]
cc: @leecalcote @nveenjain 
Opinions?

**Comment by Nikhil-Ladha** [comment]
How will paper be different than a card. Means, if the issues is with size we can fix the size for all of them. Other than that, is there any difference?

**Comment by kushthedude** [comment]
> How will paper be different than a card. Means, if the issues is with size we can fix the size for all of them. Other than that, is there any difference?

I was thinking of stacking them horizontally, also the paper is quite more responsiveness as in cards there are issues of overflow. But we can wrap the cards with horizontal grids to replicate a similar sort of design.

**Comment by Nikhil-Ladha** [comment]
> > How will paper be different than a card. Means, if the issues is with size we can fix the size for all of them. Other than that, is there any difference?
> 
> I was thinking of stacking them horizontally, also the paper is quite more responsiveness as in cards there are issues of overflow. But we can wrap the cards with horizontal grids to replicate a similar sort of design.

But if we stack them all horizontally them in case for some of the adapters it will look conjusted. Because different adapters have different set of functionalities. That's the reason, I was saying so.

**Comment by kishore007k** [comment]
As far as I understand we have to convert the cards into paper component and stack them right below each other. Correct me if I'm wrong. And Is this website built using the React and Material UI?. If so I can do this.

**Comment by kushthedude** [comment]
> As far as I understand we have to convert the cards into paper component and stack them right below each other. Correct me if I'm wrong. And Is this website built using the React and Material UI?. If so I can do this.

Yes, you are half right, but this is not a website rather a UI dashboard. Also, we need to have further discussion on if this UI makeover is required & further use-cases.

**Comment by leecalcote** [comment]
I think @utkarsh-pro may have made recent improvements in this area.

**Comment by leecalcote** [comment]
@dhruv0000 how does this line up with your recent efforts?
