### ISSUE TITLE
Results: Comparision of two results is not working

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#977]
**Description**

https://github.com/layer5io/meshery/issues/958#issuecomment-623664832

**Expected Behavior**

Comparision should work fine.

---
[Optional] **To Reproduce**
- Still ambiguous

**Comment by kushthedude** [comment]
@leecalcote Got the issue fix is on the way!

**Comment by leecalcote** [comment]
Sweet. 😄
