### ISSUE TITLE
Setup Editor Configuration for js file

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#982]
**Current Behavior**

We don't have editorconfig file which may result in a different view of files in different editors.

**Desired Behavior**

Add a `.editorconfig` file in client-side code for consistency in IDEs.

---
**Resources**

[Editor-Config](https://editorconfig.org)
[File to be added](https://github.com/fossasia/open-event-frontend/blob/development/.editorconfig)

**Alternatives / Additional Context**

You just need to copy & add the file which I have shown below as our rules are very similar.

**Comment by tsingh2k15** [comment]
@kushthedude I can take this up

**Comment by kushthedude** [comment]
Yes Please!

**Comment by kushthedude** [comment]
Fixed in #1020
