### ISSUE TITLE
Grafana setup in docs,mesheryctl,UI

### ISSUE THREAD

**Issue by nitishvu** [layer5io/meshery#984]
**Current Behavior**

I don't find any  instructions related to Grafana setup

**Desired Behavior**

step1: Adding Grafana setup instructions  in Guides
https://meshery.layer5.io/docs/guides
step2: Mention this guide in the metrics configuration/Grafana setting  page
step3: option in mesheryctl (grafana start) that automatically configures grafan with meshery

---
**Resources**

manual steps:

1)``` mesheryctl start``` 
      All  meshery containers are in ```meshery_default```  network.
2) Run Grafana container
     ```docker run -d -p 3000:3000 --name grafana grafana/grafana:6.5.0```
3)Login to ```localhost:3000``` and generate API key
4)Attach Grafana container to ```meshery_default``` network.
 ```docker network connect  meshery_default grafana```
5)get Grafana container IP address which belongs to ```meshery_default``` subnet
```docker inspect --format '{{(index .NetworkSettings.Networks "meshery_default").IPAddress}}' grafana```
6) use  the IP address generated in step5 in meshery UI.

**Alternatives / Additional Context**

**Comment by leecalcote** [comment]
@nitishvu this is a good call out. This example shows how to bring in a separate Grafana instance and connect to it. A PR to the docs on this would be great. 

In addition, a PR to include a description of the fact that the Meshery adapter for Istio includes an instance of Grafana and so too does the Meshery adapter for Linkerd.

@vijcheru we've yet to expose the MeshSync discovery that you've done. This is one of the uses of that endpoint. Will you point it out to @nitishvu?

@shivaylamba, we're in need of tying the above together - considerations of auto-discovered and manually added Grafana instances; @nveenjain, we need support for multiple instances of Grafana (perhaps, via a new `environment` logical object).
