### ISSUE TITLE
Tests: Add Cypress Tests for UI Visual Regression Testing

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#987]
**Current Behavior**

We don't have any tests for UI nor Server.

**Desired Behavior**

Initiate testing for UI

---
**Resources**

https://www.cypress.io/

**Alternatives / Additional Context**

- Alternatives are mocha.js or selenium but I dont need to tell how slow and powerless they are. 
- If anyone has another alternative, please feel free to comment else there is no next.js test suite as with ember or vue.js. So let's move ahead with cypress and bring testing✌️

**Comment by leecalcote** [comment]
We're good to go in terms of tossing this into `meshery-tmp` immediately. We'll want to identify how to exclude cypress libraries from the release artifacts.

**Comment by leecalcote** [comment]
Completed. ✔️
