### ISSUE TITLE
[Docs] Search is broken in documentation site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#991]
**Current State:**
When a search is performed in the documentation site, an extra `/docs` is added to the url, breaking the search functionality for the docs site.

<img width="1150" alt="Screen Shot 2020-05-12 at 5 37 08 AM" src="https://user-images.githubusercontent.com/7570704/81674380-aeba7980-9412-11ea-8d93-1431c5bb5025.png">

**Comment by nitishvu** [comment]
below entries present in _config.yml
removed site.baseurl in below line main.js

var searchPage = "{{ site.url }}{{ site.baseurl }}/search/?q=" + query;

baseurl: "/docs" 
url: "https://meshery.layer5.io/docs"
