### ISSUE TITLE
[Docs] Add v0.3.16 to Releases page in docs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#994]
**Current State:**
The [releases page](https://meshery.layer5.io/docs/project/releases) is missing a description of the v0.3.16 release.

**Desired State:**
Details of the this release should be posted. Details can be found [here](https://github.com/layer5io/meshery/releases).

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Vineet-Sharma29** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
Yes, please, @Vineet-Sharma29. 👍

**Comment by Vineet-Sharma29** [comment]
@leecalcote , v0.3.16 details aren't available at https://github.com/meshery/meshery/releases/

**Comment by leecalcote** [comment]
@Vineet-Sharma29 Oh, you're right. I'm a release ahead of myself here. I'll close out this issue...
