### ISSUE TITLE
[Docs] Add Open Source 101 at Home to Meshery Presentations section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#995]
**Current Behavior**
A talk on Meshery was given at Open Source 101 at Home - "Solving the Service Mesh Adopter’s Dilemma"

**Desired Behavior**

This talk should be added to https://meshery.layer5.io/docs/overview#meshery-presentations

- Deck - https://calcotestudios.com/talks/decks/slides-open-source-101-at-home-solving-the-service-mesh-adopters-dilemma.html
- Event - https://opensource101.com/sessions/solving-the-service-mesh-adopters-dilemma/
---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Vineet-Sharma29** [comment]
Would work on this.
