### ISSUE TITLE
Kiali Dashboard does not show Jaeger

### ISSUE THREAD

**Issue by sb1975** [layer5io/meshery#998]
How to configure the Kiali dashboard so it shows Jaeger as well.
Presently Kiali shows this error - 
Could not fetch Jaeger info. Turning off Jaeger integration.
Jaeger URL is not set in Kiali configuration

**Comment by nitishm** [comment]
What version of Istio are you running? Is Jaeger external to istio-system? I have seen some issues with the Kiali config getting Jaeger, Prometheus and grafana urls misconfigured. 

Could you also share the Kiali logs when you see the error message on the dashboard.

**Comment by sb1975** [comment]
The latest version 1.5.4.
Sorry, my setup was removed, have to rebuilt and test.
Also I see some other useful links to troubleshoot probably - https://discuss.istio.io/t/jaeger-url-not-valid-in-kiali-configuration/5307
I will get back if I can get more details on it.

**Comment by nitishm** [comment]
I had a similar issue albeit it was for external prometheus/grafana/jaeger
https://github.com/kiali/kiali/issues/2538
